// packages/vue/src/viewer/components/Extrusion3DOverlay.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import { computed } from 'vue';

import type { Extrusion3DData, Extrusion3dCss } from '../composables/visual-3d';

/**
 * Extrusion3DOverlay: Vue port of React's `Extrusion3DOverlay.tsx`.
 *
 * Renders the CSS 3D extrusion side faces (top/bottom/left/right panels) of a
 * shape with `a:sp3d` extrusion depth, using the framework-agnostic panel data
 * from shared `build3DExtrusionData`. Each panel is a plain `<div>` positioned
 * in 3D space around the shape's bounding box to form the sides of the
 * extrusion volume; an optional material gradient overlays the front face.
 *
 * This is purely visual (`pointer-events: none`, `aria-hidden`): no
 * interactivity on the panels. The wrapper establishes its own
 * `transform-style: preserve-3d` + `perspective` context, so it can be dropped
 * straight into the shape box without extra container wiring.
 */
const props = defineProps<{
	/** Extrusion data computed by shared `build3DExtrusionData`. */
	data: Extrusion3DData;
}>();

/**
 * Convert a framework-neutral `Extrusion3dCss` map to a Vue `CSSProperties`.
 *
 * The shared builder returns raw numbers for length values (`width`, `height`,
 * `left`, `top`, `inset`) relying on React's automatic `px` suffixing. Vue's
 * `:style` binding does NOT append units to numbers, so coerce every numeric
 * value to a `px` string here (unitless properties never appear in this data).
 */
function toCss(style: Extrusion3dCss): CSSProperties {
	const out: Record<string, string> = {};
	for (const [key, value] of Object.entries(style)) {
		out[key] = typeof value === 'number' ? `${value}px` : value;
	}
	return out as CSSProperties;
}

const wrapperStyle = computed<CSSProperties>(() => toCss(props.data.wrapperStyle));

const panels = computed(() =>
	props.data.panels.map((panel) => ({ side: panel.side, style: toCss(panel.style) })),
);

const materialOverlayStyle = computed<CSSProperties | null>(() => {
	if (!props.data.materialOverlay) {
		return null;
	}
	return {
		position: 'absolute',
		inset: 0,
		backgroundImage: props.data.materialOverlay,
		pointerEvents: 'none',
		borderRadius: 'inherit',
		transform: props.data.frontFaceStyle.transform as string | undefined,
		transformStyle: 'preserve-3d',
		backfaceVisibility: 'hidden',
		mixBlendMode: 'normal',
	};
});
</script>

<template>
	<div
		v-if="data.hasExtrusion && data.panels.length > 0"
		class="pptx-vue-extrusion-3d-wrapper"
		:style="wrapperStyle"
		aria-hidden="true"
	>
		<div
			v-for="panel in panels"
			:key="panel.side"
			class="pptx-vue-extrusion-3d-panel"
			:class="`pptx-vue-extrusion-3d-panel--${panel.side}`"
			:style="panel.style"
		/>
		<div
			v-if="materialOverlayStyle"
			class="pptx-vue-extrusion-3d-material-overlay"
			:style="materialOverlayStyle"
		/>
	</div>
</template>

// packages/react/src/viewer/components/elements/Extrusion3DOverlay.tsx
/**
 * Extrusion3DOverlay — renders CSS 3D extrusion side faces for shapes
 * with `a:sp3d` extrusion depth.
 *
 * This component creates the side panels (top, bottom, left, right) of a
 * 3D-extruded shape using CSS 3D transforms (`transform-style: preserve-3d`,
 * `perspective`, `rotateX/Y`). Each panel is a plain `<div>` positioned in
 * 3D space around the shape's bounding box to form the sides of the extrusion.
 *
 * The front face of the shape (the original content) gets a `translateZ`
 * offset applied through inline styles so it sits at the front of the
 * extrusion volume.
 *
 * A material overlay gradient is rendered on the front face to simulate
 * specular highlights and environment reflections based on the material preset.
 *
 * This is purely visual — no interactivity on the panels.
 */
import React from "react";

import type {
  Extrusion3DData,
  ExtrusionPanel,
} from "../../utils/shape-visual-3d";

interface Extrusion3DOverlayProps {
  /** Extrusion data computed by `build3DExtrusionData`. */
  data: Extrusion3DData;
}

/**
 * Renders the 3D extrusion side panels as absolutely-positioned divs
 * within a `preserve-3d` container. This component should be rendered
 * as a sibling or wrapper alongside the shape's main content.
 */
export const Extrusion3DOverlay: React.FC<Extrusion3DOverlayProps> = React.memo(
  function Extrusion3DOverlayInner({ data }) {
    if (!data.hasExtrusion || data.panels.length === 0) {
      return null;
    }

    return (
      <div
        className="extrusion-3d-wrapper"
        style={data.wrapperStyle}
        aria-hidden="true"
      >
        {data.panels.map((panel: ExtrusionPanel) => (
          <div
            key={panel.side}
            className={`extrusion-3d-panel extrusion-3d-panel--${panel.side}`}
            style={panel.style}
          />
        ))}
        {data.materialOverlay && (
          <div
            className="extrusion-3d-material-overlay"
            style={{
              position: "absolute",
              inset: 0,
              backgroundImage: data.materialOverlay,
              pointerEvents: "none",
              borderRadius: "inherit",
              transform: data.frontFaceStyle.transform,
              transformStyle: "preserve-3d",
              backfaceVisibility: "hidden",
              mixBlendMode: "normal",
            }}
          />
        )}
      </div>
    );
  },
);
