// packages/vue/src/viewer/components/ShareDialog.vue
<script setup lang="ts">
import type { CollaborationConfig } from 'pptx-viewer-shared';
import {
	buildActiveSessionUsers,
	buildCollaborationShareUrl,
	buildCreateCollaborationConfig,
	buildJoinCollaborationConfig,
	resolveTransportForServerUrl,
} from 'pptx-viewer-shared';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import type { UseCollaborationResult } from '../composables/useCollaboration';
import ModalDialog from './ModalDialog.vue';

/**
 * ShareDialog - Vue port of the React `ShareDialog`.
 *
 * Configures and starts a real-time collaboration session (room id, display
 * name, server URL), or stops an active one. Field defaults are supplied by
 * the host application via the `defaults` prop. When `active` is `true` the
 * form is replaced by the active-session view: status, a copyable share link,
 * room/server details, and the connected-users list built by shared's
 * `buildActiveSessionUsers` from `collab`'s live presence state.
 */
const props = defineProps<{
	/** Whether the dialog is visible. */
	open: boolean;
	/** Prefilled values for the form fields. */
	defaults?: { roomId?: string; userName?: string; serverUrl?: string };
	/** Whether a collaboration session is currently active. */
	active?: boolean;
	/** Live collaboration session state (status/count/remote users). */
	collab?: UseCollaborationResult;
	/** The config the active session was started with; null while stopped. */
	activeCollaboration?: CollaborationConfig | null;
}>();

const emit = defineEmits<{
	/** Fired with the assembled config when the user starts sharing. */
	start: [config: CollaborationConfig];
	/** Fired when the user stops an active session. */
	stop: [];
	/** Fired when the dialog is dismissed. */
	close: [];
}>();

const { t } = useI18n();

const roomId = ref('');
const userName = ref('');
const serverUrl = ref('');
const mode = ref<'create' | 'join'>('create');
const invitation = ref('');

function resetFromDefaults(): void {
	roomId.value = props.defaults?.roomId ?? '';
	userName.value = props.defaults?.userName ?? '';
	serverUrl.value = props.defaults?.serverUrl ?? '';
}

// Re-seed the form from defaults whenever the dialog (re)opens.
watch(
	() => props.open,
	(open) => {
		if (open) {
			resetFromDefaults();
		}
	},
	{ immediate: true },
);

// A blank server URL is valid: it selects serverless peer-to-peer (webrtc).
const pendingConfig = computed(() =>
	mode.value === 'join'
		? buildJoinCollaborationConfig({
				invitation: invitation.value,
				userName: userName.value,
				serverUrl: serverUrl.value,
			})
		: buildCreateCollaborationConfig({
				roomId: roomId.value,
				userName: userName.value,
				serverUrl: serverUrl.value,
			}),
);
const canStart = computed(() => pendingConfig.value !== null);

// True when the current server field selects serverless peer-to-peer mode.
const isPeerToPeer = computed(() => resolveTransportForServerUrl(serverUrl.value) === 'webrtc');

// ── Active-session view ──────────────────────────────────────────────────

const status = computed(() => props.collab?.status.value ?? 'disconnected');
const connectedCount = computed(() => props.collab?.connectedCount.value ?? 0);
const activeIsPeerToPeer = computed(
	() => resolveTransportForServerUrl(props.activeCollaboration?.serverUrl ?? '') === 'webrtc',
);
const activeShareUrl = computed(() => {
	if (!props.activeCollaboration || typeof window === 'undefined') {
		return '';
	}
	return buildCollaborationShareUrl(props.activeCollaboration, {
		origin: window.location.origin,
		pathname: window.location.pathname,
	});
});
const sessionUsers = computed(() => {
	if (!props.collab || !props.activeCollaboration) {
		return [];
	}
	return buildActiveSessionUsers({
		localUserName: props.activeCollaboration.userName,
		localUserColor: props.activeCollaboration.userColor,
		remoteUsers: props.collab.remotePresences.value.map((peer) => ({
			clientId: peer.clientId,
			userName: peer.userName,
			userColor: peer.color,
			activeSlideIndex: peer.activeSlide,
		})),
	});
});

const copied = ref(false);
function onCopyLink(): void {
	if (!activeShareUrl.value || typeof navigator === 'undefined' || !navigator.clipboard) {
		return;
	}
	void navigator.clipboard.writeText(activeShareUrl.value).then(() => {
		copied.value = true;
		window.setTimeout(() => {
			copied.value = false;
		}, 2000);
		return undefined;
	});
}

function handleStart(): void {
	if (pendingConfig.value) {
		emit('start', pendingConfig.value);
	}
}

function handleStop(): void {
	emit('stop');
}
</script>

<template>
	<ModalDialog
		:open="open"
		:title="active ? t('pptx.share.collaborationActive') : t('pptx.toolbar.share')"
		@close="emit('close')"
	>
		<div v-if="active" class="pptx-vue-share-active flex flex-col gap-4">
			<!-- Status -->
			<div class="flex items-center gap-2">
				<span
					class="inline-block h-2 w-2 rounded-full"
					:class="{
						'bg-green-400': status === 'connected',
						'bg-yellow-400': status === 'connecting',
						'bg-red-400': status !== 'connected' && status !== 'connecting',
					}"
				/>
				<span class="text-[13px] font-medium capitalize text-foreground">{{ status }}</span>
				<span class="ml-auto text-[12px] text-muted-foreground">
					{{ t('pptx.collaboration.userCount', { count: connectedCount }) }}
				</span>
			</div>

			<!-- Share URL -->
			<div v-if="activeShareUrl" class="pptx-vue-share-field flex flex-col gap-1.5">
				<label class="text-[12px] font-medium text-foreground">{{
					t('pptx.share.shareLink')
				}}</label>
				<div class="flex items-center gap-2">
					<div
						class="flex-1 select-all truncate rounded border border-border bg-background px-3 py-1.5 font-mono text-[11px] text-foreground"
					>
						{{ activeShareUrl }}
					</div>
					<button
						type="button"
						class="shrink-0 rounded border border-border bg-muted px-2.5 py-1.5 text-[12px] text-foreground transition-colors hover:bg-accent"
						:title="t('pptx.share.copyLink')"
						@click="onCopyLink"
					>
						{{ copied ? t('pptx.share.copied') : t('pptx.share.copyUrl') }}
					</button>
				</div>
				<p class="text-[11px] text-muted-foreground">{{ t('pptx.share.shareHint') }}</p>
			</div>

			<!-- Session details -->
			<div
				v-if="activeCollaboration"
				class="flex items-center gap-3 text-[11px] text-muted-foreground"
			>
				<span>
					{{ t('pptx.share.room') }}
					<code class="font-mono text-foreground">{{ activeCollaboration.roomId }}</code>
				</span>
				<span>
					{{ t('pptx.share.server') }}
					<code class="font-mono text-foreground">
						{{
							activeIsPeerToPeer ? t('pptx.share.p2pServerValue') : activeCollaboration.serverUrl
						}}
					</code>
				</span>
			</div>
			<p
				v-else-if="isPeerToPeer"
				class="pptx-vue-share-server-value text-[12px] text-muted-foreground"
			>
				{{ t('pptx.share.p2pServerValue') }}
			</p>

			<!-- Connected users -->
			<div v-if="sessionUsers.length > 0" class="pptx-vue-share-field flex flex-col gap-1.5">
				<label class="text-[12px] font-medium text-foreground">{{
					t('pptx.share.connectedUsers')
				}}</label>
				<div
					class="max-h-[140px] divide-y divide-border overflow-y-auto rounded border border-border bg-background"
				>
					<div
						v-for="user in sessionUsers"
						:key="user.id"
						class="flex items-center gap-2 px-3 py-2"
					>
						<div
							class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[9px] font-semibold text-white"
							:style="{ backgroundColor: user.color }"
						>
							<img
								v-if="user.avatarUrl"
								:src="user.avatarUrl"
								alt=""
								class="h-full w-full rounded-full object-cover"
							/>
							<template v-else>{{ user.initials }}</template>
						</div>
						<span class="truncate text-[12px] text-foreground">{{ user.name }}</span>
						<span class="ml-auto text-[10px] text-muted-foreground">
							{{
								user.isLocal ? t('pptx.share.you') : t('pptx.notes.slideN', { n: user.slideNumber })
							}}
						</span>
					</div>
				</div>
			</div>

			<button
				type="button"
				class="pptx-vue-share-stop w-full rounded border border-red-500/30 bg-red-500/10 px-3 py-2 text-[12px] font-medium text-red-400 transition-colors hover:bg-red-500/20"
				@click="handleStop"
			>
				{{ t('pptx.share.stopSharing') }}
			</button>
		</div>

		<div v-else class="pptx-vue-share-form flex flex-col gap-4">
			<div class="grid grid-cols-2 gap-1 rounded-lg bg-muted p-1" role="tablist">
				<button
					v-for="candidate in ['create', 'join'] as const"
					:key="candidate"
					type="button"
					role="tab"
					:aria-selected="mode === candidate"
					class="rounded-md px-3 py-1.5 text-[12px] font-medium transition-colors"
					:class="
						mode === candidate ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground'
					"
					@click="mode = candidate"
				>
					{{ t(candidate === 'create' ? 'pptx.share.createSession' : 'pptx.share.joinSession') }}
				</button>
			</div>
			<p class="pptx-vue-share-desc text-[13px] leading-relaxed text-muted-foreground">
				{{ t(mode === 'join' ? 'pptx.share.joinDescription' : 'pptx.share.formDescription') }}
			</p>

			<div v-if="mode === 'join'" class="pptx-vue-share-field flex flex-col gap-1.5">
				<label for="pptx-vue-share-invitation" class="text-[12px] font-medium text-foreground">
					{{ t('pptx.share.invitationLabel') }}
				</label>
				<input
					id="pptx-vue-share-invitation"
					v-model="invitation"
					type="text"
					class="pptx-vue-share-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					:placeholder="t('pptx.share.invitationPlaceholder')"
				/>
				<p class="text-[11px] text-muted-foreground">{{ t('pptx.share.invitationHint') }}</p>
			</div>

			<div v-else class="pptx-vue-share-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-share-room"
					class="pptx-vue-share-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.share.roomId') }}
				</label>
				<input
					id="pptx-vue-share-room"
					v-model="roomId"
					type="text"
					class="pptx-vue-share-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					:placeholder="t('pptx.share.roomIdPlaceholder')"
				/>
			</div>

			<div class="pptx-vue-share-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-share-name"
					class="pptx-vue-share-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.share.yourName') }}
				</label>
				<input
					id="pptx-vue-share-name"
					v-model="userName"
					type="text"
					class="pptx-vue-share-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					:placeholder="t('pptx.share.yourNamePlaceholder')"
				/>
			</div>

			<div class="pptx-vue-share-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-share-server"
					class="pptx-vue-share-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.share.serverUrl') }}
				</label>
				<input
					id="pptx-vue-share-server"
					v-model="serverUrl"
					type="text"
					class="pptx-vue-share-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					:placeholder="t('pptx.share.serverPlaceholder')"
				/>
				<p v-if="isPeerToPeer" class="pptx-vue-share-p2p-hint text-[11px] text-muted-foreground">
					{{ t('pptx.share.p2pHint') }}
				</p>
			</div>
		</div>

		<template #footer>
			<button
				type="button"
				class="pptx-vue-share-btn rounded bg-muted px-3 py-1.5 text-[12px] text-foreground transition-colors hover:bg-accent"
				@click="emit('close')"
			>
				{{ active ? t('pptx.share.close') : t('pptx.share.cancel') }}
			</button>
			<button
				v-if="!active"
				type="button"
				class="pptx-vue-share-btn pptx-vue-share-btn-primary rounded bg-primary px-3 py-1.5 text-[12px] text-white transition-colors hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-40"
				:disabled="!canStart"
				@click="handleStart"
			>
				{{ t(mode === 'join' ? 'pptx.share.joinSession' : 'pptx.share.startSharing') }}
			</button>
		</template>
	</ModalDialog>
</template>

// packages/svelte/src/viewer/collab/components/ShareDialog.svelte
<script lang="ts">
	/**
	 * ShareDialog: configure and start a real-time collaboration session (room
	 * id, display name, server URL), or stop an active one. Svelte port of the
	 * Vue `ShareDialog.vue`; form/config logic lives in `share-helpers.ts`. The
	 * active view (status, share link, connected-users list) mirrors React's
	 * `ShareDialogActiveView.tsx`, built on shared's `buildActiveSessionUsers`.
	 */
	import { buildActiveSessionUsers, buildCollaborationShareUrl, resolveTransportForServerUrl } from 'pptx-viewer-shared';

	import { useTranslator } from '../../../i18n/context';
	import ModalDialog from './ModalDialog.svelte';
	import type { ShareDialogProps } from './props';
	import {
		buildJoinConfig,
		buildShareConfig,
		canJoinShare,
		canStartShare,
		isPeerToPeerShare,
		seedShareFields,
	} from './share-helpers';

	const {
		open,
		defaults,
		active,
		status,
		connectedCount,
		remotePresences,
		activeCollaboration,
		onstart,
		onstop,
		onclose,
	}: ShareDialogProps = $props();

	const t = useTranslator();

	let roomId = $state('');
	let userName = $state('');
	let serverUrl = $state('');
	let mode = $state<'create' | 'join'>('create');
	let invitation = $state('');

	// Re-seed the form from defaults whenever the dialog (re)opens.
	$effect(() => {
		if (open) {
			const seeded = seedShareFields(defaults);
			roomId = seeded.roomId;
			userName = seeded.userName;
			serverUrl = seeded.serverUrl;
		}
	});

	const canStart = $derived(canStartShare({ roomId, userName, serverUrl }));
	const canJoin = $derived(canJoinShare({ invitation, userName, serverUrl }));
	const isPeerToPeer = $derived(isPeerToPeerShare(serverUrl));
	const isJoinMode = $derived(mode === 'join');

	function setMode(targetMode: 'create' | 'join'): void {
		mode = targetMode;
	}

	function setInvitation(value: string): void {
		invitation = value;
	}

	function handleStart(): void {
		const config =
			mode === 'join'
				? buildJoinConfig({ invitation, userName, serverUrl })
				: buildShareConfig({ roomId, userName, serverUrl });
		if (config) {
			onstart(config);
		}
	}

	// ── Active-session view ──────────────────────────────────────────────────

	const activeIsPeerToPeer = $derived(
		resolveTransportForServerUrl(activeCollaboration?.serverUrl ?? '') === 'webrtc',
	);
	const activeShareUrl = $derived(
		activeCollaboration && typeof window !== 'undefined'
			? buildCollaborationShareUrl(activeCollaboration, {
					origin: window.location.origin,
					pathname: window.location.pathname,
				})
			: '',
	);
	const sessionUsers = $derived(
		activeCollaboration
			? buildActiveSessionUsers({
					localUserName: activeCollaboration.userName,
					localUserColor: activeCollaboration.userColor,
					remoteUsers: remotePresences,
				})
			: [],
	);

	let copied = $state(false);
	function onCopyLink(): void {
		if (!activeShareUrl || typeof navigator === 'undefined' || !navigator.clipboard) {
			return;
		}
		void navigator.clipboard.writeText(activeShareUrl).then(() => {
			copied = true;
			window.setTimeout(() => {
				copied = false;
			}, 2000);
			return undefined;
		});
	}
</script>

<ModalDialog
	{open}
	title={active ? t('pptx.share.collaborationActive') : t('pptx.toolbar.share')}
	{onclose}
>
	{#if active}
		<div class="pptx-svelte-share-active">
			<!-- Status -->
			<div class="pptx-svelte-share-status-row">
				<span
					class="pptx-svelte-share-status-dot"
					class:is-connected={status === 'connected'}
					class:is-connecting={status === 'connecting'}
				></span>
				<span class="pptx-svelte-share-status-text">{status}</span>
				<span class="pptx-svelte-share-count">
					{t('pptx.collaboration.userCount', { count: connectedCount })}
				</span>
			</div>

			<!-- Share URL -->
			{#if activeShareUrl}
				<div class="pptx-svelte-share-field">
					<label for="pptx-svelte-share-link">{t('pptx.share.shareLink')}</label>
					<div class="pptx-svelte-share-link-row">
						<div id="pptx-svelte-share-link" class="pptx-svelte-share-link-value">{activeShareUrl}</div>
						<button
							type="button"
							class="pptx-svelte-share-btn"
							title={t('pptx.share.copyLink')}
							onclick={onCopyLink}
						>
							{copied ? t('pptx.share.copied') : t('pptx.share.copyUrl')}
						</button>
					</div>
					<p class="pptx-svelte-share-p2p-hint">{t('pptx.share.shareHint')}</p>
				</div>
			{/if}

			<!-- Session details -->
			{#if activeCollaboration}
				<div class="pptx-svelte-share-details-row">
					<span>
						{t('pptx.share.room')}
						<code>{activeCollaboration.roomId}</code>
					</span>
					<span>
						{t('pptx.share.server')}
						<code>{activeIsPeerToPeer ? t('pptx.share.p2pServerValue') : activeCollaboration.serverUrl}</code>
					</span>
				</div>
			{:else if isPeerToPeer}
				<p class="pptx-svelte-share-server-value">{t('pptx.share.p2pServerValue')}</p>
			{/if}

			<!-- Connected users -->
			{#if sessionUsers.length > 0}
				<div class="pptx-svelte-share-field">
					<label for="pptx-svelte-share-users">{t('pptx.share.connectedUsers')}</label>
					<div id="pptx-svelte-share-users" class="pptx-svelte-share-users">
						{#each sessionUsers as user (user.id)}
							<div class="pptx-svelte-share-user">
								<span class="pptx-svelte-share-user-avatar" style={`background-color: ${user.color}`}>
									{#if user.avatarUrl}
										<img src={user.avatarUrl} alt="" />
									{:else}
										{user.initials}
									{/if}
								</span>
								<span class="pptx-svelte-share-user-name">{user.name}</span>
								<span class="pptx-svelte-share-user-tag">
									{user.isLocal ? t('pptx.share.you') : t('pptx.notes.slideN', { n: user.slideNumber ?? 1 })}
								</span>
							</div>
						{/each}
					</div>
				</div>
			{/if}

			<button type="button" class="pptx-svelte-share-stop" onclick={onstop}>
				{t('pptx.share.stopSharing')}
			</button>
		</div>
	{:else}
		<div class="pptx-svelte-share-form">
			<div class="pptx-svelte-share-tabs" role="tablist">
				<button type="button" role="tab" aria-selected={mode === 'create'} onclick={() => setMode('create')}>
					{t('pptx.share.createSession')}
				</button>
				<button type="button" role="tab" aria-selected={mode === 'join'} onclick={() => setMode('join')}>
					{t('pptx.share.joinSession')}
				</button>
			</div>
			<p class="pptx-svelte-share-desc">
				{t(isJoinMode ? 'pptx.share.joinDescription' : 'pptx.share.formDescription')}
			</p>
			{#if isJoinMode}
			<div class="pptx-svelte-share-field">
				<label for="pptx-svelte-share-invitation">{t('pptx.share.invitationLabel')}</label>
				<input
					id="pptx-svelte-share-invitation"
					type="text"
					value={invitation}
					oninput={(event: Event) => setInvitation((event.target as HTMLInputElement).value)}
					placeholder={t('pptx.share.invitationPlaceholder')}
				/>
				<p class="pptx-svelte-share-p2p-hint">{t('pptx.share.invitationHint')}</p>
			</div>
			{:else}
			<div class="pptx-svelte-share-field">
				<label for="pptx-svelte-share-room">{t('pptx.share.roomId')}</label>
				<input
					id="pptx-svelte-share-room"
					type="text"
					bind:value={roomId}
					placeholder={t('pptx.share.roomIdPlaceholder')}
				/>
			</div>
			{/if}
			<div class="pptx-svelte-share-field">
				<label for="pptx-svelte-share-name">{t('pptx.share.yourName')}</label>
				<input
					id="pptx-svelte-share-name"
					type="text"
					bind:value={userName}
					placeholder={t('pptx.share.yourNamePlaceholder')}
				/>
			</div>
			<div class="pptx-svelte-share-field">
				<label for="pptx-svelte-share-server">{t('pptx.share.serverUrl')}</label>
				<input
					id="pptx-svelte-share-server"
					type="text"
					bind:value={serverUrl}
					placeholder={t('pptx.share.serverPlaceholder')}
				/>
				{#if isPeerToPeer}
					<p class="pptx-svelte-share-p2p-hint">{t('pptx.share.p2pHint')}</p>
				{/if}
			</div>
		</div>
	{/if}
	{#snippet footer()}
			<button type="button" class="pptx-svelte-share-btn" onclick={onclose}>
				{active ? t('pptx.share.close') : t('pptx.share.cancel')}
			</button>
			{#if !active}
				<button
					type="button"
					class="pptx-svelte-share-btn pptx-svelte-share-btn-primary"
					disabled={isJoinMode ? !canJoin : !canStart}
					onclick={handleStart}
				>
					{t(isJoinMode ? 'pptx.share.joinSession' : 'pptx.share.startSharing')}
				</button>
			{/if}
	{/snippet}
</ModalDialog>

<style>
	.pptx-svelte-share-active,
	.pptx-svelte-share-form {
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	.pptx-svelte-share-desc {
		margin: 0;
		font-size: 13px;
		line-height: 1.5;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-share-server-value,
	.pptx-svelte-share-p2p-hint {
		margin: 0;
		font-size: 12px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-share-field {
		display: flex;
		flex-direction: column;
		gap: 6px;
	}

	.pptx-svelte-share-tabs {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 4px;
		padding: 4px;
		border-radius: 8px;
		background: var(--pptx-muted, #1f2937);
	}

	.pptx-svelte-share-tabs button {
		border: 0;
		border-radius: 6px;
		background: transparent;
		color: var(--pptx-muted-foreground, #94a3b8);
		padding: 6px 10px;
		font: 500 12px/1.2 inherit;
		cursor: pointer;
	}

	.pptx-svelte-share-tabs button[aria-selected='true'] {
		background: var(--pptx-background, #11111b);
		color: var(--pptx-foreground, #e2e8f0);
	}

	.pptx-svelte-share-field label {
		font-size: 12px;
		font-weight: 500;
		color: var(--pptx-foreground, #e2e8f0);
	}

	.pptx-svelte-share-field input {
		width: 100%;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-background, #11111b);
		color: var(--pptx-foreground, #e2e8f0);
		padding: 6px 10px;
		font: inherit;
		font-size: 13px;
	}

	.pptx-svelte-share-field input:focus {
		outline: 1px solid var(--pptx-primary, #6366f1);
		outline-offset: -1px;
	}

	.pptx-svelte-share-status-row {
		display: flex;
		align-items: center;
		gap: 8px;
	}

	.pptx-svelte-share-status-dot {
		width: 8px;
		height: 8px;
		border-radius: 9999px;
		background: #f87171;
	}

	.pptx-svelte-share-status-dot.is-connected {
		background: #4ade80;
	}

	.pptx-svelte-share-status-dot.is-connecting {
		background: #facc15;
	}

	.pptx-svelte-share-status-text {
		font-size: 13px;
		font-weight: 500;
		text-transform: capitalize;
		color: var(--pptx-foreground, #e2e8f0);
	}

	.pptx-svelte-share-count {
		margin-left: auto;
		font-size: 12px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-share-link-row {
		display: flex;
		align-items: center;
		gap: 8px;
	}

	.pptx-svelte-share-link-value {
		flex: 1;
		overflow: hidden;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-background, #11111b);
		padding: 6px 10px;
		color: var(--pptx-foreground, #e2e8f0);
		font-family: monospace;
		font-size: 11px;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.pptx-svelte-share-details-row {
		display: flex;
		align-items: center;
		gap: 12px;
		font-size: 11px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-share-details-row code {
		color: var(--pptx-foreground, #e2e8f0);
		font-family: monospace;
	}

	.pptx-svelte-share-users {
		max-height: 140px;
		overflow-y: auto;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-background, #11111b);
	}

	.pptx-svelte-share-user {
		display: flex;
		align-items: center;
		gap: 8px;
		border-bottom: 1px solid var(--pptx-border, #33334d);
		padding: 6px 10px;
	}

	.pptx-svelte-share-user:last-child {
		border-bottom: 0;
	}

	.pptx-svelte-share-user-avatar {
		display: inline-flex;
		flex-shrink: 0;
		align-items: center;
		justify-content: center;
		width: 22px;
		height: 22px;
		border-radius: 9999px;
		overflow: hidden;
		color: #ffffff;
		font-size: 9px;
		font-weight: 600;
	}

	.pptx-svelte-share-user-avatar img {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.pptx-svelte-share-user-name {
		overflow: hidden;
		font-size: 12px;
		color: var(--pptx-foreground, #e2e8f0);
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.pptx-svelte-share-user-tag {
		margin-left: auto;
		font-size: 10px;
		color: var(--pptx-muted-foreground, #94a3b8);
		white-space: nowrap;
	}

	.pptx-svelte-share-stop {
		width: 100%;
		border: 1px solid rgba(239, 68, 68, 0.3);
		border-radius: var(--pptx-radius, 6px);
		background: rgba(239, 68, 68, 0.1);
		color: #f87171;
		padding: 8px 12px;
		font: 500 12px/1 system-ui, sans-serif;
		cursor: pointer;
	}

	.pptx-svelte-share-stop:hover {
		background: rgba(239, 68, 68, 0.2);
	}

	.pptx-svelte-share-btn {
		border: none;
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-muted, #1f2937);
		color: var(--pptx-foreground, #f3f4f6);
		padding: 6px 16px;
		font-size: 12px;
		font-family: inherit;
		cursor: pointer;
	}

	.pptx-svelte-share-btn:hover {
		background: var(--pptx-accent, #33334d);
	}

	.pptx-svelte-share-btn-primary {
		background: var(--pptx-primary, #6366f1);
		color: #fff;
	}

	.pptx-svelte-share-btn-primary:hover {
		background: var(--pptx-primary, #6366f1);
		opacity: 0.9;
	}

	.pptx-svelte-share-btn-primary:disabled {
		cursor: not-allowed;
		opacity: 0.4;
	}
</style>
