// packages/svelte/src/viewer/components/ribbon/file/AccountPage.svelte
<script lang="ts">
	/**
	 * AccountPage: File > Account's real content (replacing the old generic
	 * stub shared with Options). Four sections: a local-only display profile
	 * (persisted via `pptx-viewer-shared`'s `saveViewerProfile`), a
	 * storage/privacy panel backed by the IndexedDB autosave/recovery store,
	 * app info, and a disabled-by-default sign-in hook point for hosts that
	 * want to wire a real auth flow (`accountAuth`).
	 */
	import { onMount } from 'svelte';
	import {
		AVATAR_COLOR_SWATCHES,
		clearAllLocalViewerData,
		DEFAULT_VIEWER_PROFILE,
		formatBackstageSize,
		getLocalStorageUsageSummary,
		readStoredViewerPrefs,
		resolveProfileInitial,
		saveViewerProfile,
	} from 'pptx-viewer-shared';
	import type { AccountAuthConfig, LocalStorageUsageSummary, ViewerProfile } from 'pptx-viewer-shared';
	import { useTranslator } from '../../../../i18n/context';

	const { accountAuth }: { accountAuth?: AccountAuthConfig } = $props();
	const t = useTranslator();

	// This global is injected at build time from this package's own
	// `package.json` version (see `vite.config.ts`); the `typeof` guard keeps
	// it safe to reference under Vitest, which doesn't define it.
	const appVersion =
		typeof __PPTX_SVELTE_VIEWER_VERSION__ === 'string' ? __PPTX_SVELTE_VIEWER_VERSION__ : 'dev';

	let profile = $state<ViewerProfile>(readStoredViewerPrefs().profile ?? { ...DEFAULT_VIEWER_PROFILE });
	let usage = $state<LocalStorageUsageSummary | undefined>(undefined);
	let cleared = $state(false);

	async function refreshUsage(): Promise<void> {
		usage = await getLocalStorageUsageSummary();
	}
	onMount(() => {
		void refreshUsage();
	});

	function commitProfile(next: ViewerProfile): void {
		profile = next;
		saveViewerProfile(next);
	}

	function onNameInput(event: Event): void {
		const value = (event.currentTarget as HTMLInputElement).value;
		commitProfile({ ...profile, displayName: value });
	}

	function onPickColor(color: string): void {
		commitProfile({ ...profile, avatarColor: color });
	}

	async function onClearData(): Promise<void> {
		if (!window.confirm(t('pptx.account.storage.clearConfirm'))) {
			return;
		}
		await clearAllLocalViewerData();
		cleared = true;
		profile = { ...DEFAULT_VIEWER_PROFILE };
		await refreshUsage();
	}
</script>

<div class="pptx-svelte-account">
	<section class="card">
		<h2>{t('pptx.account.profile.title')}</h2>
		<div class="profile-row">
			<span class="avatar" style={`background:${profile.avatarColor}`}>{resolveProfileInitial(profile)}</span>
			<label class="name-field">
				<span>{t('pptx.account.profile.nameLabel')}</span>
				<input
					type="text"
					value={profile.displayName}
					placeholder={t('pptx.account.profile.namePlaceholder')}
					oninput={onNameInput}
				/>
			</label>
		</div>
		<span class="swatches-label">{t('pptx.account.profile.avatarColorLabel')}</span>
		<div class="swatch-row" role="group" aria-label={t('pptx.account.profile.avatarColorLabel')}>
			{#each AVATAR_COLOR_SWATCHES as color (color)}
				<button
					type="button"
					class:active={color === profile.avatarColor}
					style={`background:${color}`}
					aria-label={color}
					aria-pressed={color === profile.avatarColor}
					onclick={() => onPickColor(color)}
				></button>
			{/each}
		</div>
	</section>

	<section class="card">
		<h2>{t('pptx.account.storage.title')}</h2>
		{#if usage}
			<p>
				{usage.presentationCount > 0
					? t('pptx.account.storage.usage', {
							count: usage.presentationCount,
							size: formatBackstageSize(usage.totalBytes),
						})
					: t('pptx.account.storage.usageEmpty')}
			</p>
		{/if}
		<button type="button" class="secondary" onclick={() => void onClearData()}>
			{t('pptx.account.storage.clear')}
		</button>
		{#if cleared}<p class="notice">{t('pptx.account.storage.clearedNotice')}</p>{/if}
		<p class="muted">{t('pptx.account.storage.privacyBlurb')}</p>
	</section>

	<section class="card">
		<h2>{t('pptx.account.about.title')}</h2>
		<p>pptx-svelte-viewer</p>
		<p class="muted">{t('pptx.account.about.version', { version: appVersion })}</p>
	</section>

	{#if accountAuth?.enabled}
		<section class="card">
			<h2>{t('pptx.account.signIn.title')}</h2>
			{#if accountAuth.signedInUser}
				<p>{t('pptx.account.signIn.signedInAs', { name: accountAuth.signedInUser.name })}</p>
			{:else}
				<p>{t('pptx.account.signIn.description')}</p>
				<button type="button" class="primary" onclick={() => accountAuth?.onSignIn()}>
					{t('pptx.account.signIn.button')}
				</button>
			{/if}
		</section>
	{/if}
</div>

<style>
	.pptx-svelte-account {
		display: flex;
		max-width: 760px;
		flex-direction: column;
		gap: 20px;
		margin-top: 32px;
	}

	.card {
		padding: 24px 28px;
		border: 1px solid var(--pptx-border, #ddd);
		background: var(--pptx-card, #fff);
		color: var(--pptx-card-foreground, #242424);
	}

	h2 {
		margin: 0 0 16px;
		font-size: 15px;
	}

	p {
		margin: 0 0 12px;
		line-height: 1.6;
	}

	.muted {
		color: var(--pptx-muted-foreground, #666);
		font-size: 12px;
	}

	.notice {
		color: var(--pptx-primary, #c43e1c);
		font-size: 12px;
	}

	.profile-row {
		display: flex;
		align-items: center;
		gap: 16px;
		margin-bottom: 16px;
	}

	.avatar {
		display: grid;
		width: 48px;
		height: 48px;
		flex: none;
		place-items: center;
		border-radius: 50%;
		color: #fff;
		font-size: 18px;
		font-weight: 600;
	}

	.name-field {
		display: flex;
		flex: 1;
		flex-direction: column;
		gap: 4px;
		font-size: 12px;
		color: var(--pptx-muted-foreground, #666);
	}

	.name-field input {
		height: 36px;
		padding: 0 12px;
		border: 1px solid var(--pptx-input, #888);
		background: var(--pptx-card, #fff);
		color: var(--pptx-card-foreground, #242424);
		font-size: 13px;
	}

	.name-field input:focus {
		border-color: var(--pptx-ring, #c43e1c);
		outline: none;
	}

	.swatches-label {
		display: block;
		margin-bottom: 8px;
		font-size: 12px;
		color: var(--pptx-muted-foreground, #666);
	}

	.swatch-row {
		display: flex;
		gap: 8px;
	}

	.swatch-row button {
		width: 24px;
		height: 24px;
		border: 2px solid transparent;
		border-radius: 50%;
		cursor: pointer;
	}

	.swatch-row button.active {
		border-color: var(--pptx-foreground, #242424);
	}

	.secondary,
	.primary {
		padding: 8px 16px;
		border: 1px solid var(--pptx-border, #ddd);
		background: var(--pptx-secondary, #f5eee9);
		color: inherit;
		font-size: 12px;
	}

	.primary {
		border: 0;
		background: var(--pptx-primary, #c43e1c);
		color: var(--pptx-primary-foreground, #fff);
		font-weight: 600;
	}
</style>

// packages/vue/src/viewer/components/ribbon/AccountPage.vue
<script setup lang="ts">
/**
 * AccountPage - File ▸ Account.
 *
 * Replaces the old static "PowerPoint Viewer" stub in `FileSection.vue` with
 * real, local-first content: a profile editor, a storage/privacy panel backed
 * by the shared autosave store, app/version info, and a disabled-by-default
 * sign-in hook point (`accountAuth`, injected from `PowerPointViewer.vue` via
 * `AccountAuthKey` so it doesn't need threading through `RibbonProps`).
 */
import {
	AVATAR_COLOR_SWATCHES,
	clearAllLocalViewerData,
	DEFAULT_VIEWER_PROFILE,
	formatBackstageSize,
	getLocalStorageUsageSummary,
	readStoredViewerPrefs,
	resolveProfileInitial,
	saveViewerProfile,
} from 'pptx-viewer-shared';
import type { ViewerProfile } from 'pptx-viewer-shared';
import { onMounted, reactive, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { PPTX_VUE_VIEWER_VERSION } from '../../../version';
import { useAccountAuth } from '../../composables/account-auth';

const { t } = useI18n();

const accountAuth = useAccountAuth();

// ── Profile ───────────────────────────────────────────────────────────
const profile = reactive<ViewerProfile>({
	...DEFAULT_VIEWER_PROFILE,
	...readStoredViewerPrefs().profile,
});

function commitProfile(): void {
	saveViewerProfile({ ...profile });
}

function onNameInput(event: Event): void {
	profile.displayName = (event.target as HTMLInputElement).value;
	commitProfile();
}

function selectAvatarColor(color: string): void {
	profile.avatarColor = color;
	commitProfile();
}

// ── Storage & Privacy ─────────────────────────────────────────────────
const presentationCount = ref(0);
const totalBytes = ref(0);
const cleared = ref(false);

async function refreshUsage(): Promise<void> {
	const summary = await getLocalStorageUsageSummary();
	presentationCount.value = summary.presentationCount;
	totalBytes.value = summary.totalBytes;
}

async function clearLocalData(): Promise<void> {
	if (!window.confirm(t('pptx.account.storage.clearConfirm'))) {
		return;
	}
	await clearAllLocalViewerData();
	cleared.value = true;
	await refreshUsage();
}

onMounted(() => void refreshUsage());
</script>

<template>
	<div class="pptx-vue-account mt-8 flex max-w-[760px] flex-col gap-6">
		<!-- Profile -->
		<section class="pptx-vue-account-section border border-border bg-card p-6 text-card-foreground">
			<h2 class="text-base font-semibold">{{ t('pptx.account.profile.title') }}</h2>
			<div class="mt-4 flex items-center gap-4">
				<div
					class="grid size-14 shrink-0 place-items-center rounded-full text-xl font-semibold text-white"
					:style="{ background: profile.avatarColor }"
				>
					{{ resolveProfileInitial(profile) }}
				</div>
				<div class="min-w-0 flex-1">
					<label class="block text-xs font-medium text-muted-foreground">
						{{ t('pptx.account.profile.nameLabel') }}
					</label>
					<input
						:value="profile.displayName"
						type="text"
						:placeholder="t('pptx.account.profile.namePlaceholder')"
						class="mt-1 h-9 w-full max-w-[320px] border border-input bg-background px-3 text-sm outline-none focus:border-ring"
						@input="onNameInput"
					/>
				</div>
			</div>
			<div class="mt-4">
				<span class="block text-xs font-medium text-muted-foreground">
					{{ t('pptx.account.profile.avatarColorLabel') }}
				</span>
				<div class="mt-2 flex gap-2">
					<button
						v-for="color in AVATAR_COLOR_SWATCHES"
						:key="color"
						type="button"
						class="size-7 rounded-full border-2 transition-transform hover:scale-110"
						:class="profile.avatarColor === color ? 'border-foreground' : 'border-transparent'"
						:style="{ background: color }"
						:aria-pressed="profile.avatarColor === color"
						:aria-label="color"
						@click="selectAvatarColor(color)"
					/>
				</div>
			</div>
		</section>

		<!-- Storage & Privacy -->
		<section class="pptx-vue-account-section border border-border bg-card p-6 text-card-foreground">
			<h2 class="text-base font-semibold">{{ t('pptx.account.storage.title') }}</h2>
			<p class="mt-2 text-sm text-muted-foreground">
				{{
					presentationCount === 0
						? t('pptx.account.storage.usageEmpty')
						: t('pptx.account.storage.usage', {
								count: presentationCount,
								size: formatBackstageSize(totalBytes),
							})
				}}
			</p>
			<p class="mt-3 text-xs leading-5 text-muted-foreground">
				{{ t('pptx.account.storage.privacyBlurb') }}
			</p>
			<button
				type="button"
				class="mt-4 border border-destructive/40 px-4 py-2 text-xs font-semibold text-destructive hover:bg-destructive/10"
				@click="clearLocalData"
			>
				{{ t('pptx.account.storage.clear') }}
			</button>
			<p v-if="cleared" class="mt-2 text-xs text-muted-foreground" role="status">
				{{ t('pptx.account.storage.clearedNotice') }}
			</p>
		</section>

		<!-- About -->
		<section class="pptx-vue-account-section border border-border bg-card p-6 text-card-foreground">
			<h2 class="text-base font-semibold">{{ t('pptx.account.about.title') }}</h2>
			<p class="mt-2 text-sm text-muted-foreground">
				pptx-vue-viewer<template v-if="PPTX_VUE_VIEWER_VERSION">
					&middot; {{ t('pptx.account.about.version', { version: PPTX_VUE_VIEWER_VERSION }) }}
				</template>
			</p>
		</section>

		<!-- Sign-in (disabled by default) -->
		<section
			v-if="accountAuth?.enabled"
			class="pptx-vue-account-section border border-border bg-card p-6 text-card-foreground"
		>
			<template v-if="accountAuth.signedInUser">
				<h2 class="text-base font-semibold">{{ t('pptx.account.signIn.title') }}</h2>
				<p class="mt-2 text-sm text-muted-foreground">
					{{ t('pptx.account.signIn.signedInAs', { name: accountAuth.signedInUser.name }) }}
				</p>
			</template>
			<template v-else>
				<h2 class="text-base font-semibold">{{ t('pptx.account.signIn.title') }}</h2>
				<p class="mt-2 text-sm text-muted-foreground">
					{{ t('pptx.account.signIn.description') }}
				</p>
				<button
					type="button"
					class="mt-4 bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-90"
					@click="accountAuth.onSignIn"
				>
					{{ t('pptx.account.signIn.button') }}
				</button>
			</template>
		</section>
	</div>
</template>
