// packages/react/src/viewer/components/toolbar/ModeSwitcher.tsx
import React from 'react';

import { PresentDropdown } from './PresentDropdown';
import type { ToolbarProps } from './toolbar-types';

export type ModeSwitcherProps = Pick<
	ToolbarProps,
	| 'mode'
	| 'onSetMode'
	| 'onCloseMasterView'
	| 'onToggleSlideSorter'
	| 'onEnterPresenterView'
	| 'onEnterRehearsalMode'
	| 'onOpenSetUpSlideShow'
	| 'onOpenBroadcastDialog'
	| 'onToggleSubtitles'
	| 'showSubtitles'
>;

export function ModeSwitcher({
	mode,
	onSetMode,
	onCloseMasterView,
	onEnterPresenterView,
	onEnterRehearsalMode,
	onOpenSetUpSlideShow,
	onOpenBroadcastDialog,
	onToggleSubtitles,
	showSubtitles,
}: ModeSwitcherProps): React.ReactElement {
	if (mode === 'master') {
		return (
			<div className='inline-flex items-center gap-1.5'>
				<span className='inline-flex items-center px-2 py-0.5 rounded-sm bg-amber-600/90 text-[10px] text-amber-50'>
					Master View
				</span>
				<button
					type='button'
					onClick={onCloseMasterView}
					className='px-2 py-0.5 rounded-sm hover:bg-accent text-[10px] text-foreground transition-colors'
					title='Close master view'
				>
					Close
				</button>
			</div>
		);
	}

	// Present dropdown only; view mode buttons moved to status bar
	return (
		<PresentDropdown
			isActive={mode === 'present'}
			onPresent={() => onSetMode('present')}
			onPresenterView={onEnterPresenterView}
			onRehearse={onEnterRehearsalMode}
			onSetUpSlideShow={onOpenSetUpSlideShow}
			onBroadcast={onOpenBroadcastDialog}
			onToggleSubtitles={onToggleSubtitles}
			showSubtitles={showSubtitles}
		/>
	);
}

// packages/vue/src/viewer/components/ribbon/ModeSwitcher.vue
<script setup lang="ts">
/**
 * ModeSwitcher — the Vue 3 port of React's `ModeSwitcher` from
 * `toolbar/ModeSwitcher.tsx`. In master mode it renders the "Master View" badge
 * + Close button; otherwise it delegates to `PresentDropdown` (view-mode buttons
 * live in the status bar). A faithful, mechanical port for visual + behavioral
 * parity: class strings are copied verbatim, callbacks arrive as function props.
 */
import PresentDropdown from './PresentDropdown.vue';
import type { ViewerMode } from './ribbon-types';

interface Props {
	mode: ViewerMode;
	onSetMode: (mode: ViewerMode) => void;
	onCloseMasterView: () => void;
	onEnterPresenterView?: () => void;
	onEnterRehearsalMode?: () => void;
	onOpenSetUpSlideShow?: () => void;
	onOpenBroadcastDialog?: () => void;
	onToggleSubtitles?: () => void;
	showSubtitles?: boolean;
}

const props = defineProps<Props>();
</script>

<template>
	<div v-if="props.mode === 'master'" class="inline-flex items-center gap-1.5">
		<span
			class="inline-flex items-center px-2 py-0.5 rounded-sm bg-amber-600/90 text-[10px] text-amber-50"
		>
			Master View
		</span>
		<button
			type="button"
			class="px-2 py-0.5 rounded-sm hover:bg-accent text-[10px] text-foreground transition-colors"
			title="Close master view"
			@click="props.onCloseMasterView()"
		>
			Close
		</button>
	</div>
	<!-- Present dropdown only — view mode buttons moved to status bar -->
	<PresentDropdown
		v-else
		:is-active="props.mode === 'present'"
		:on-present="() => props.onSetMode('present')"
		:on-presenter-view="props.onEnterPresenterView"
		:on-rehearse="props.onEnterRehearsalMode"
		:on-set-up-slide-show="props.onOpenSetUpSlideShow"
		:on-broadcast="props.onOpenBroadcastDialog"
		:on-toggle-subtitles="props.onToggleSubtitles"
		:show-subtitles="props.showSubtitles"
	/>
</template>
