// packages/react/src/viewer/components/toolbar/OverflowMenu.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { LuEllipsis } from 'react-icons/lu';

import { cn } from '../../utils';
import { ic, OV } from './toolbar-constants';
import type { ToolbarProps } from './toolbar-types';

type OverflowKeys =
	| 'onExportPng'
	| 'onExportPdf'
	| 'onExportVideo'
	| 'onExportGif'
	| 'onSaveAsPptx'
	| 'onSaveAsPpsx'
	| 'onSaveAsPptm'
	| 'onSaveAsPpt'
	| 'onPrint'
	| 'onCopySlideAsImage'
	| 'onRunAccessibilityCheck'
	| 'onToggleShortcuts'
	| 'onToggleVersionHistory'
	| 'onOpenDocumentProperties'
	| 'onOpenPasswordProtection'
	| 'onOpenFontEmbedding'
	| 'onOpenDigitalSignatures'
	| 'hasMacros'
	| 'isOverflowMenuOpen'
	| 'onSetOverflowMenuOpen';

export type OverflowMenuProps = Pick<ToolbarProps, OverflowKeys>;

export function OverflowMenu(p: OverflowMenuProps): React.ReactElement {
	const { t } = useTranslation();
	const ovAct = (k: string) => {
		p.onSetOverflowMenuOpen(false);
		(
			({
				png: p.onExportPng,
				pdf: p.onExportPdf,
				video: p.onExportVideo,
				gif: p.onExportGif,
				pptx: p.onSaveAsPptx,
				ppsx: p.onSaveAsPpsx,
				pptm: p.onSaveAsPptm,
				ppt: p.onSaveAsPpt,
				print: p.onPrint,
				copyImg: p.onCopySlideAsImage,
				a11y: p.onRunAccessibilityCheck,
				shortcuts: p.onToggleShortcuts,
				versionHistory: p.onToggleVersionHistory,
				documentProperties: p.onOpenDocumentProperties,
				passwordProtection: p.onOpenPasswordProtection,
				fontEmbedding: p.onOpenFontEmbedding,
				digitalSignatures: p.onOpenDigitalSignatures,
			}) as Record<string, (() => void) | undefined>
		)[k]?.();
	};

	return (
		<div className='relative'>
			<button
				type='button'
				onClick={() => p.onSetOverflowMenuOpen(!p.isOverflowMenuOpen)}
				className={cn(
					'p-1.5 rounded transition-colors',
					p.isOverflowMenuOpen ? 'bg-primary/80 text-white' : 'bg-muted hover:bg-accent',
				)}
				title={t('pptx.ribbon.moreActions')}
				aria-label={t('pptx.ribbon.moreActions')}
			>
				<LuEllipsis className={ic} />
			</button>
			{p.isOverflowMenuOpen && (
				<>
					<button
						type='button'
						className='fixed inset-0 z-40'
						aria-label={t('pptx.overflow.closeMenu')}
						onClick={() => p.onSetOverflowMenuOpen(false)}
					/>
					<div className='absolute right-0 top-full mt-1 z-50 w-44 rounded-lg border border-border bg-popover backdrop-blur-lg shadow-2xl py-1'>
						{OV.filter((o) => o.k !== 'pptm' || p.hasMacros).map((o) =>
							o.k.startsWith('---') ? (
								<div key={o.k} className='my-1 border-t border-border/60' />
							) : (
								<button
									key={o.k}
									type='button'
									onClick={() => ovAct(o.k)}
									className='flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-muted transition-colors'
								>
									{o.i}
									{t(o.labelKey)}
								</button>
							),
						)}
					</div>
				</>
			)}
		</div>
	);
}

// packages/vue/src/viewer/components/ribbon/OverflowMenu.vue
<script setup lang="ts">
/**
 * OverflowMenu: the Vue 3 port of React's `toolbar/OverflowMenu.tsx`. Renders
 * the "More actions" ellipsis button and its popover, driven by the OV table.
 * A faithful, mechanical port for visual + behavioral parity: class strings are
 * copied verbatim, open state stays prop-driven (`isOverflowMenuOpen` /
 * `onSetOverflowMenuOpen`) exactly as React, and each OV key maps to its handler.
 */
import { Ellipsis } from 'lucide-vue-next';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import { ic, ics, OV } from './ribbon-constants';
import type { RibbonProps } from './ribbon-types';

interface Props extends RibbonProps {}

const props = defineProps<Props>();
const { t } = useI18n();

function ovAct(k: string): void {
	props.onSetOverflowMenuOpen(false);
	const handlers: Record<string, (() => void) | undefined> = {
		png: props.onExportPng,
		pdf: props.onExportPdf,
		video: props.onExportVideo,
		gif: props.onExportGif,
		pptx: props.onSaveAsPptx,
		ppsx: props.onSaveAsPpsx,
		pptm: props.onSaveAsPptm,
		ppt: props.onSaveAsPpt,
		print: props.onPrint,
		copyImg: props.onCopySlideAsImage,
		a11y: props.onRunAccessibilityCheck,
		shortcuts: props.onToggleShortcuts,
		versionHistory: props.onToggleVersionHistory,
		documentProperties: props.onOpenDocumentProperties,
		passwordProtection: props.onOpenPasswordProtection,
		fontEmbedding: props.onOpenFontEmbedding,
		digitalSignatures: props.onOpenDigitalSignatures,
	};
	handlers[k]?.();
}
</script>

<template>
	<div class="relative">
		<button
			type="button"
			:class="
				cn(
					'p-1.5 rounded transition-colors',
					props.isOverflowMenuOpen ? 'bg-primary/80 text-white' : 'bg-muted hover:bg-accent',
				)
			"
			:title="t('pptx.ribbon.moreActions')"
			:aria-label="t('pptx.ribbon.moreActions')"
			@click="props.onSetOverflowMenuOpen(!props.isOverflowMenuOpen)"
		>
			<Ellipsis :class="ic" />
		</button>
		<template v-if="props.isOverflowMenuOpen">
			<button
				type="button"
				class="fixed inset-0 z-40"
				:aria-label="t('pptx.overflow.closeMenu')"
				@click="props.onSetOverflowMenuOpen(false)"
			/>
			<div
				class="absolute right-0 top-full mt-1 z-50 w-44 rounded-lg border border-border bg-popover backdrop-blur-lg shadow-2xl py-1"
			>
				<template v-for="o in OV.filter((o) => o.k !== 'pptm' || props.hasMacros)" :key="o.k">
					<div v-if="o.k.startsWith('---')" class="my-1 border-t border-border/60" />
					<button
						v-else
						type="button"
						class="flex items-center gap-2 w-full px-3 py-1.5 text-xs text-foreground hover:bg-muted transition-colors"
						@click="ovAct(o.k)"
					>
						<component :is="o.icon" v-if="o.icon" :class="ics + ' text-muted-foreground'" />
						{{ t(o.labelKey) }}
					</button>
				</template>
			</div>
		</template>
	</div>
</template>
