// packages/react/src/viewer/components/toolbar/RecordSection.tsx
import { RECORD_COMMAND_GROUPS } from 'pptx-viewer-shared';
import React from 'react';
import { useTranslation } from 'react-i18next';

import { WebRibbonCommand, WebRibbonGroup } from './WebRibbonControls';

interface RecordSectionProps {
	onRecordFromBeginning: () => void;
	onRecordFromCurrent: () => void;
}
export function RecordSection(props: RecordSectionProps): React.ReactElement {
	const { t } = useTranslation();
	const actions: Record<string, (() => void) | undefined> = {
		'record.record.fromBeginning': props.onRecordFromBeginning,
		'record.record.fromCurrent': props.onRecordFromCurrent,
	};
	return (
		<>
			{RECORD_COMMAND_GROUPS.map((group) => (
				<WebRibbonGroup key={group.id} label={t(group.labelKey)} groupId={group.id}>
					{group.commands.map((command) => (
						<WebRibbonCommand
							key={command.id}
							controlId={command.id}
							label={t(command.labelKey)}
							icon={command.icon}
							disabled={command.unsupported}
							compact
							onCommand={actions[command.id]}
						/>
					))}
				</WebRibbonGroup>
			))}
		</>
	);
}

// packages/vue/src/viewer/components/ribbon/RecordSection.vue
<script setup lang="ts">
import { RECORD_COMMAND_GROUPS } from 'pptx-viewer-shared';
import { useI18n } from 'vue-i18n';

const props = defineProps<{ onRecordFromBeginning: () => void; onRecordFromCurrent: () => void }>();
const { t } = useI18n();
function request(id: string): void {
	if (id === 'record.record.fromBeginning') {
		props.onRecordFromBeginning();
	} else if (id === 'record.record.fromCurrent') {
		props.onRecordFromCurrent();
	}
}
</script>
<template>
	<pptx-ui-ribbon-group
		v-for="group in RECORD_COMMAND_GROUPS"
		:key="group.id"
		:label="t(group.labelKey)"
		:data-ribbon-group="group.id"
	>
		<pptx-ui-ribbon-command
			v-for="command in group.commands"
			:key="command.id"
			:label="t(command.labelKey)"
			:icon="command.icon"
			:disabled="command.unsupported || undefined"
			:data-ribbon-control="command.id"
			compact
			@command-request="request(command.id)"
		></pptx-ui-ribbon-command>
	</pptx-ui-ribbon-group>
</template>
