// packages/react/src/viewer/components/toolbar/ViewSection.tsx
import type { PptxUiRibbonViewElement, RibbonViewRequestEvent } from 'pptx-viewer-shared';
import React, { useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';

export interface ViewSectionProps {
	canEdit: boolean;
	editTemplateMode: boolean;
	onSetEditTemplateMode: (mode: boolean) => void;
	spellCheckEnabled: boolean;
	onSetSpellCheckEnabled: (enabled: boolean) => void;
	showGrid: boolean;
	showRulers: boolean;
	showGuides: boolean;
	snapToGrid: boolean;
	snapToShape: boolean;
	onSetShowGrid: (enabled: boolean) => void;
	onSetShowRulers: (enabled: boolean) => void;
	onSetShowGuides: (enabled: boolean) => void;
	onSetSnapToGrid: (enabled: boolean) => void;
	onSetSnapToShape: (enabled: boolean) => void;
	onAddGuide: (axis: 'h' | 'v') => void;
	onEnterMasterView: () => void;
	isSelectionPaneOpen?: boolean;
	onToggleSelectionPane?: () => void;
	eyedropperActive?: boolean;
	onToggleEyedropper?: () => void;
	onToggleSlideSorter?: () => void;
	/**
	 * View > Normal: leave whichever alternate view (slide sorter, reading,
	 * outline, master) is open and return to the ordinary editing canvas.
	 */
	onGoToNormalView?: () => void;
	/** Enter PowerPoint's Reading View (full window, not the fullscreen show). */
	onOpenReadingView?: () => void;
	/** Enter PowerPoint's Outline view: the deck as editable indented text. */
	onOpenOutlineView?: () => void;
	onZoomToFit?: () => void;
}

export function ViewSection(p: ViewSectionProps): React.ReactElement {
	const { t } = useTranslation();
	const ref = useRef<PptxUiRibbonViewElement>(null);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		host.state = {
			editable: p.canEdit,
			showRulers: p.showRulers,
			showGrid: p.showGrid,
			showGuides: p.showGuides,
			snapToGrid: p.snapToGrid,
			snapToShape: p.snapToShape,
			templateEditing: p.editTemplateMode,
			selectionPaneOpen: p.isSelectionPaneOpen,
			eyedropperActive: p.eyedropperActive,
			translate: t,
		};
	}, [p, t]);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		const request = (event: Event) => {
			const intent = (event as RibbonViewRequestEvent).detail;
			if (intent.kind === 'guide') {
				p.onAddGuide(intent.axis);
			} else if (intent.kind === 'option') {
				const setters = {
					showRulers: p.onSetShowRulers,
					showGrid: p.onSetShowGrid,
					showGuides: p.onSetShowGuides,
					snapToGrid: p.onSetSnapToGrid,
					snapToShape: p.onSetSnapToShape,
					templateEditing: p.onSetEditTemplateMode,
				};
				setters[intent.value](intent.enabled);
			} else {
				const commands = {
					normal: p.onGoToNormalView,
					slideSorter: p.onToggleSlideSorter,
					outline: p.onOpenOutlineView,
					readingView: p.onOpenReadingView,
					slideMaster: p.onEnterMasterView,
					selectionPane: p.onToggleSelectionPane,
					eyedropper: p.onToggleEyedropper,
					zoomToFit: p.onZoomToFit,
				};
				commands[intent.value]?.();
			}
		};
		host.addEventListener('view-request', request);
		return () => host.removeEventListener('view-request', request);
	}, [p]);
	return <pptx-ui-ribbon-view ref={ref} />;
}

// packages/vue/src/viewer/components/ribbon/ViewSection.vue
<script setup lang="ts">
/**
 * ViewSection: thin adapter for the shared `pptx-ui-ribbon-view`. The shared
 * element owns the groups, icons, labels and pressed/disabled state; this
 * component supplies viewer options and routes typed intents to the native
 * handlers. Guides toggles guide visibility only; Snap to shape is its own flag.
 */
import type { RibbonViewRequestEvent } from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

interface Props {
	canEdit: boolean;
	editTemplateMode: boolean;
	onSetEditTemplateMode: (mode: boolean) => void;
	spellCheckEnabled: boolean;
	onSetSpellCheckEnabled: (enabled: boolean) => void;
	showGrid: boolean;
	showRulers: boolean;
	/** Guide-overlay visibility only; the guides themselves stay in the model. */
	showGuides: boolean;
	snapToGrid: boolean;
	snapToShape: boolean;
	onSetShowGrid: (enabled: boolean) => void;
	onSetShowRulers: (enabled: boolean) => void;
	onSetShowGuides: (enabled: boolean) => void;
	onSetSnapToGrid: (enabled: boolean) => void;
	onSetSnapToShape: (enabled: boolean) => void;
	onAddGuide: (axis: 'h' | 'v') => void;
	onEnterMasterView: () => void;
	isSelectionPaneOpen?: boolean;
	onToggleSelectionPane?: () => void;
	eyedropperActive?: boolean;
	onToggleEyedropper?: () => void;
	onToggleSlideSorter?: () => void;
	onGoToNormalView?: () => void;
	onOpenReadingView?: () => void;
	/** Enter PowerPoint's Outline view: the deck as editable indented text. */
	onOpenOutlineView?: () => void;
	onZoomToFit?: () => void;
}

const props = defineProps<Props>();
const { t } = useI18n();
const state = computed(() => ({
	editable: props.canEdit,
	showRulers: props.showRulers,
	showGrid: props.showGrid,
	showGuides: props.showGuides,
	snapToGrid: props.snapToGrid,
	snapToShape: props.snapToShape,
	templateEditing: props.editTemplateMode,
	selectionPaneOpen: props.isSelectionPaneOpen,
	eyedropperActive: props.eyedropperActive,
	selectionPaneAvailable: Boolean(props.onToggleSelectionPane),
	eyedropperAvailable: Boolean(props.onToggleEyedropper),
	translate: t,
}));

function request(event: RibbonViewRequestEvent): void {
	const intent = event.detail;
	if (intent.kind === 'guide') {
		props.onAddGuide(intent.axis);
	} else if (intent.kind === 'option') {
		const setters = {
			showRulers: props.onSetShowRulers,
			showGrid: props.onSetShowGrid,
			showGuides: props.onSetShowGuides,
			snapToGrid: props.onSetSnapToGrid,
			snapToShape: props.onSetSnapToShape,
			templateEditing: props.onSetEditTemplateMode,
		};
		setters[intent.value](intent.enabled);
	} else {
		const commands = {
			normal: props.onGoToNormalView,
			slideSorter: props.onToggleSlideSorter,
			outline: props.onOpenOutlineView,
			readingView: props.onOpenReadingView,
			slideMaster: props.onEnterMasterView,
			selectionPane: props.onToggleSelectionPane,
			eyedropper: props.onToggleEyedropper,
			zoomToFit: props.onZoomToFit,
		};
		commands[intent.value]?.();
	}
}
</script>

<template>
	<pptx-ui-ribbon-view :state.prop="state" @view-request="request" />
</template>
