// packages/vue/src/viewer/components/ribbon/ClipboardGroup.vue
<script setup lang="ts">
/**
 * ClipboardGroup: the Home tab's Clipboard group (Paste, Cut, Copy, Format
 * Painter) with the brief copied / cut feedback flash. Split out of
 * `HomeSection.vue` to keep that file short.
 */
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import { gB, gL, grp, ic } from './ribbon-constants';
import type { ElementClipboardPayload } from './ribbon-types';
import RibbonIcon from './RibbonIcon';

interface Props {
	canEdit: boolean;
	/** Cut and Copy act on the selection, so with nothing selected they are disabled. */
	hasSelection: boolean;
	clipboardPayload: ElementClipboardPayload | null;
	formatPainterActive?: boolean;
	canActivateFormatPainter?: boolean;
	onCopy: () => void;
	onCut: () => void;
	onPaste: () => void;
	onToggleFormatPainter?: () => void;
}

const props = defineProps<Props>();
const { t } = useI18n();

const copiedFeedback = ref(false);
const cutFeedback = ref(false);

function handleCut(): void {
	props.onCut();
	cutFeedback.value = true;
	setTimeout(() => {
		cutFeedback.value = false;
	}, 600);
}

function handleCopy(): void {
	props.onCopy();
	copiedFeedback.value = true;
	setTimeout(() => {
		copiedFeedback.value = false;
	}, 600);
}
</script>

<template>
	<div class="flex flex-col items-center gap-0.5" data-ribbon-group="home.clipboard">
		<div :class="grp">
			<button
				type="button"
				data-ribbon-control="home.clipboard.paste"
				:disabled="!props.clipboardPayload || !props.canEdit"
				:class="gB"
				:title="t('pptx.arrange.paste')"
				@click="props.onPaste()"
			>
				<RibbonIcon name="home.clipboard.paste" :class="ic" />
			</button>
			<button
				type="button"
				data-ribbon-control="home.clipboard.cut"
				:disabled="!props.canEdit || !hasSelection"
				:class="cn(gB, cutFeedback && 'bg-green-600/20 text-green-400')"
				:title="t('pptx.arrange.cut')"
				@click="handleCut()"
			>
				<RibbonIcon name="home.clipboard.cut" :class="ic" />
			</button>
			<button
				type="button"
				data-ribbon-control="home.clipboard.copy"
				:disabled="!hasSelection"
				:class="cn(gB, copiedFeedback && 'bg-green-600/20 text-green-400')"
				:title="t('pptx.arrange.copy')"
				@click="handleCopy()"
			>
				<RibbonIcon name="home.clipboard.copy" :class="ic" />
			</button>
			<button
				v-if="props.onToggleFormatPainter"
				type="button"
				:disabled="
					!props.canEdit || (props.canActivateFormatPainter === false && !props.formatPainterActive)
				"
				data-testid="format-painter-toggle"
				data-ribbon-control="home.clipboard.formatPainter"
				:data-active="props.formatPainterActive ? 'true' : 'false'"
				:class="
					cn(gL, props.formatPainterActive ? 'bg-amber-600 hover:bg-amber-500 text-amber-50' : '')
				"
				:title="t('pptx.arrange.formatPainter')"
				@click="props.onToggleFormatPainter()"
			>
				<RibbonIcon name="home.clipboard.formatPainter" :class="ic" />
			</button>
		</div>
		<span class="text-[9px] text-muted-foreground leading-none">{{
			t('pptx.ribbon.clipboard')
		}}</span>
	</div>
</template>

// packages/react/src/viewer/components/toolbar/ClipboardGroup.tsx
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuClipboardPaste, LuCopy, LuPaintbrush, LuScissors } from 'react-icons/lu';

import { cn } from '../../utils';
import { controlAttr, groupAttr } from './PowerPointRibbonControls';
import { gB, gL, grp, ic } from './toolbar-constants';

export interface ClipboardGroupProps {
	canEdit: boolean;
	/** Cut and Copy act on the selection, so they need one. */
	hasSelection: boolean;
	canPaste: boolean;
	formatPainterActive?: boolean;
	canActivateFormatPainter?: boolean;
	onCopy: () => void;
	onCut: () => void;
	onPaste: () => void;
	onToggleFormatPainter?: () => void;
}

/** Home > Clipboard: Paste, Cut, Copy and Format Painter. */
export function ClipboardGroup(p: ClipboardGroupProps): React.ReactElement {
	const { t } = useTranslation();
	const [copiedFeedback, setCopiedFeedback] = useState(false);
	const [cutFeedback, setCutFeedback] = useState(false);
	return (
		<div className='flex flex-col items-center gap-0.5' {...groupAttr('home.clipboard')}>
			<div className={grp}>
				<button
					type='button'
					onClick={p.onPaste}
					disabled={!p.canPaste || !p.canEdit}
					className={gB}
					title={t('pptx.arrange.paste')}
					{...controlAttr('home.clipboard.paste')}
				>
					<LuClipboardPaste className={ic} />
				</button>
				<button
					type='button'
					onClick={() => {
						p.onCut();
						setCutFeedback(true);
						setTimeout(() => setCutFeedback(false), 600);
					}}
					disabled={!p.canEdit || !p.hasSelection}
					className={cn(gB, cutFeedback && 'bg-green-600/20 text-green-400')}
					title={t('pptx.arrange.cut')}
					{...controlAttr('home.clipboard.cut')}
				>
					<LuScissors className={ic} />
				</button>
				<button
					type='button'
					onClick={() => {
						p.onCopy();
						setCopiedFeedback(true);
						setTimeout(() => setCopiedFeedback(false), 600);
					}}
					disabled={!p.hasSelection}
					className={cn(gB, copiedFeedback && 'bg-green-600/20 text-green-400')}
					title={t('pptx.arrange.copy')}
					{...controlAttr('home.clipboard.copy')}
				>
					<LuCopy className={ic} />
				</button>
				{p.onToggleFormatPainter && (
					<button
						type='button'
						onClick={p.onToggleFormatPainter}
						disabled={
							!p.canEdit || (p.canActivateFormatPainter === false && !p.formatPainterActive)
						}
						data-testid='format-painter-toggle'
						data-active={p.formatPainterActive ? 'true' : 'false'}
						className={cn(
							gL,
							p.formatPainterActive ? 'bg-amber-600 hover:bg-amber-500 text-amber-50' : '',
						)}
						title={t('pptx.arrange.formatPainter')}
						{...controlAttr('home.clipboard.formatPainter')}
					>
						<LuPaintbrush className={ic} />
					</button>
				)}
			</div>
			<span className='text-[9px] text-muted-foreground leading-none'>
				{t('pptx.ribbon.clipboard')}
			</span>
		</div>
	);
}
