// packages/vue/src/viewer/components/ribbon/FileSection.vue
<script setup lang="ts">
import { ArrowLeft } from 'lucide-vue-next';
import {
	BACKSTAGE_NAV,
	BACKSTAGE_TEMPLATES,
	formatBackstageDate,
	formatBackstageSize,
	listBackstageRecentFiles,
	type BackstagePage,
	type BackstageRecentFile,
} from 'pptx-viewer-shared';
import { computed, onMounted, ref } from 'vue';

import { backstageIcon } from './file-section-icons';
import type { FileSectionProps } from './file-section-types';

const props = defineProps<FileSectionProps>();
const page = ref<BackstagePage>('home');
const query = ref('');
const recent = ref<BackstageRecentFile[]>([]);
onMounted(() => void listBackstageRecentFiles().then((items) => (recent.value = items)));
const visibleRecent = computed(() => {
	const q = query.value.trim().toLowerCase();
	return q
		? recent.value.filter((file) => `${file.name} ${file.location}`.toLowerCase().includes(q))
		: recent.value;
});
const title = computed(() => BACKSTAGE_NAV.find((item) => item.id === page.value)?.label ?? 'Home');
const run = (action?: () => void) => {
	action?.();
	if (action) props.onClose();
};
const actions = computed(() => {
	if (page.value === 'info')
		return [
			[
				'Protect Presentation',
				'Control what changes people can make.',
				'🔒',
				props.onOpenPasswordProtection,
			],
			[
				'Inspect Presentation',
				'Review properties and hidden content.',
				'ⓘ',
				props.onOpenDocumentProperties,
			],
			['Embed Fonts', 'Keep typography consistent across devices.', 'T', props.onOpenFontEmbedding],
			[
				'Digital Signatures',
				'View and manage attached signatures.',
				'✓',
				props.onOpenDigitalSignatures,
			],
		] as const;
	if (page.value === 'saveAs')
		return [
			['PowerPoint Presentation', 'Save an editable .pptx copy.', 'P', props.onSaveAsPptx],
			['PowerPoint Show', 'Save a .ppsx slide show.', '▶', props.onSaveAsPpsx],
			...(props.hasMacros
				? [
						[
							'Macro-Enabled Presentation',
							'Preserve VBA in a .pptm file.',
							'M',
							props.onSaveAsPptm,
						] as const,
					]
				: []),
			['Package for Sharing', 'Bundle the deck and linked assets.', '□', props.onPackageForSharing],
		] as const;
	if (page.value === 'export')
		return [
			['Create PDF', 'Publish one page per slide.', 'PDF', props.onExportPdf],
			['Export current slide', 'Create a high-quality PNG image.', 'PNG', props.onExportPng],
			['Create a Video', 'Export timings and animations as WebM.', '▶', props.onExportVideo],
			['Create an Animated GIF', 'Make a compact looping preview.', 'GIF', props.onExportGif],
			['Copy as Image', 'Copy the current slide to the clipboard.', '▣', props.onCopySlideAsImage],
		] as const;
	if (page.value === 'print')
		return [
			[
				'Print Presentation',
				'Choose layout and output settings in the browser print dialog.',
				'▧',
				props.onPrint,
			],
		] as const;
	if (page.value === 'share')
		return [
			['Share with People', 'Invite collaborators to work together.', '◇', props.onOpenShareDialog],
			[
				'Package for Sharing',
				'Download a self-contained offline package.',
				'□',
				props.onPackageForSharing,
			],
		] as const;
	return [];
});
function selectPage(id: BackstagePage): void {
	if (id === 'close') return props.onClose();
	if (id === 'save') return run(props.onSaveAsPptx);
	if (id === 'options' && props.onOpenSettings) return run(props.onOpenSettings);
	page.value = id;
}
</script>

<template>
	<div
		class="fixed inset-0 z-[200] flex bg-background font-[Aptos,Segoe_UI,sans-serif] text-foreground"
		role="dialog"
		aria-modal="true"
		aria-label="File"
	>
		<aside class="flex w-[148px] shrink-0 flex-col border-r border-border bg-secondary">
			<button
				type="button"
				aria-label="Back to presentation"
				class="grid min-h-12 place-items-center border-b border-border text-xl hover:bg-accent"
				@click="props.onClose()"
			>
				<ArrowLeft :size="18" aria-hidden="true" />
			</button>
			<nav class="flex min-h-0 flex-1 flex-col py-2">
				<button
					v-for="item in BACKSTAGE_NAV.filter((entry) => !entry.group)"
					:key="item.id"
					type="button"
					:class="[
						'flex min-h-10 items-center gap-3 border-l-2 px-4 text-left text-[12px]',
						page === item.id
							? 'border-primary bg-card text-primary'
							: 'border-transparent hover:bg-accent',
					]"
					@click="selectPage(item.id)"
				>
					<component :is="backstageIcon(item.id)" :size="17" aria-hidden="true" />
					{{ item.label }}
				</button>
				<div class="flex-1" />
				<button
					v-for="item in BACKSTAGE_NAV.filter((entry) => entry.group)"
					:key="item.id"
					type="button"
					:class="[
						'flex min-h-10 items-center gap-3 border-l-2 px-4 text-left text-[12px]',
						page === item.id
							? 'border-primary bg-card text-primary'
							: 'border-transparent hover:bg-accent',
					]"
					@click="selectPage(item.id)"
				>
					<component :is="backstageIcon(item.id)" :size="17" aria-hidden="true" />
					{{ item.label }}
				</button>
			</nav>
		</aside>
		<main class="min-w-0 flex-1 overflow-y-auto px-[clamp(32px,4vw,72px)] py-5">
			<h1 class="text-[24px] font-semibold">{{ page === 'home' ? 'Good evening' : title }}</h1>
			<template v-if="page === 'home' || page === 'new'">
				<h2 class="mt-7 text-[17px] font-semibold">New</h2>
				<div class="mt-5 grid grid-cols-[repeat(auto-fill,minmax(150px,1fr))] gap-6">
					<button
						v-for="template in BACKSTAGE_TEMPLATES"
						:key="template.id"
						type="button"
						class="text-left"
						@click="run(() => props.onCreatePresentation(template.id))"
					>
						<span
							class="block aspect-[16/9] border border-border shadow-sm transition hover:-translate-y-0.5 hover:border-primary hover:shadow-lg"
							:style="{ background: template.preview }"
						/><strong class="mt-2 block truncate text-[12px] font-medium">{{
							template.name
						}}</strong
						><span class="block truncate text-[10px] text-muted-foreground">{{
							template.description
						}}</span>
					</button>
				</div>
			</template>
			<template v-if="page === 'home' || page === 'open'">
				<input
					v-model="query"
					class="mt-8 h-10 w-full max-w-[540px] border border-input bg-card px-4 text-[13px] text-card-foreground outline-none focus:border-ring"
					placeholder="Search recent presentations"
				/>
				<button
					v-if="page === 'open'"
					type="button"
					class="mt-4 bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-90"
					@click="run(props.onOpenFile)"
				>
					Browse this device
				</button>
				<h2 class="mt-6 text-[16px] font-semibold">Recent</h2>
				<div class="mt-5 border-t border-border">
					<div
						class="grid grid-cols-[1fr_120px_90px] px-3 py-2 text-[11px] font-semibold text-muted-foreground"
					>
						<span>Name</span><span>Date modified</span><span>Size</span>
					</div>
					<button
						v-for="file in visibleRecent"
						:key="file.key"
						type="button"
						class="grid w-full grid-cols-[1fr_120px_90px] items-center border-t border-border px-3 py-3 text-left hover:bg-accent"
						@click="run(() => props.onOpenRecentFile?.(file.key))"
					>
						<span class="flex min-w-0 items-center gap-3"
							><span
								class="grid size-8 shrink-0 place-items-center bg-primary font-bold text-primary-foreground"
								>P</span
							><span class="min-w-0"
								><strong class="block truncate text-[13px] font-normal">{{ file.name }}</strong
								><small class="block truncate text-[11px] text-muted-foreground">{{
									file.location
								}}</small></span
							></span
						><span class="text-[11px] text-muted-foreground">{{
							formatBackstageDate(file.timestamp)
						}}</span
						><span class="text-[11px] text-muted-foreground">{{
							formatBackstageSize(file.size)
						}}</span>
					</button>
					<div
						v-if="visibleRecent.length === 0"
						class="border-t border-border px-3 py-10 text-center text-sm text-muted-foreground"
					>
						No recent presentations yet.
					</div>
				</div>
			</template>
			<div v-if="actions.length" class="mt-8 grid max-w-[900px] grid-cols-2 gap-5">
				<button
					v-for="action in actions"
					:key="action[0]"
					type="button"
					class="flex min-h-28 items-start gap-4 border border-border bg-card p-5 text-left text-card-foreground transition hover:border-primary hover:shadow-md"
					@click="run(action[3])"
				>
					<span class="grid size-10 shrink-0 place-items-center bg-accent text-primary">{{
						action[2]
					}}</span
					><span
						><strong class="block text-[15px]">{{ action[0] }}</strong
						><span class="mt-1 block text-[12px] leading-5 text-muted-foreground">{{
							action[1]
						}}</span></span
					>
				</button>
			</div>
			<div
				v-if="page === 'account' || page === 'options'"
				class="mt-8 max-w-[760px] border border-border bg-card p-7 text-card-foreground"
			>
				<div
					class="grid size-14 place-items-center rounded-full bg-primary text-xl font-semibold text-primary-foreground"
				>
					{{ page === 'options' ? '⚙' : 'P' }}
				</div>
				<h2 class="mt-4 text-lg font-semibold">
					{{ page === 'options' ? 'PowerPoint Options' : 'PowerPoint Viewer' }}
				</h2>
				<p class="mt-2 text-sm leading-6 text-muted-foreground">
					{{
						page === 'options'
							? 'Configure autosave, proofing, grid, rulers, language, theme, and keyboard shortcuts.'
							: 'Your presentations and recovery history stay in your browser unless you explicitly share or download them.'
					}}
				</p>
				<button
					v-if="page === 'options'"
					type="button"
					class="mt-6 bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-90"
					@click="run(props.onOpenSettings)"
				>
					Open Options
				</button>
			</div>
			<p class="mt-12 text-[11px] text-muted-foreground">
				{{ props.fileName || 'Untitled Presentation.pptx' }} · Saved to this browser
			</p>
		</main>
	</div>
</template>

// packages/react/src/viewer/components/toolbar/FileSection.tsx
import { BACKSTAGE_NAV, listBackstageRecentFiles } from 'pptx-viewer-shared';
import type { BackstagePage, BackstageRecentFile } from 'pptx-viewer-shared';
import React, { useEffect, useMemo, useState } from 'react';
import {
	LuArrowLeft,
	LuBox,
	LuCopy,
	LuDownload,
	LuFileImage,
	LuFileText,
	LuFolderOpen,
	LuInfo,
	LuLock,
	LuPackage,
	LuPlay,
	LuPrinter,
	LuSearch,
	LuSettings,
	LuShare2,
	LuShieldAlert,
	LuType,
	LuVideo,
} from 'react-icons/lu';

import { BackstageNavIcon } from './file-backstage-icons';
import {
	BackstageAction as Action,
	BackstageNewGallery,
	BackstageRecentList,
} from './file-backstage-parts';
import type { FileSectionProps } from './file-backstage-parts';

export function FileSection(p: FileSectionProps): React.ReactElement {
	const [page, setPage] = useState<BackstagePage>('home');
	const [query, setQuery] = useState('');
	const [recent, setRecent] = useState<BackstageRecentFile[]>([]);
	useEffect(() => {
		void listBackstageRecentFiles().then(setRecent);
	}, []);
	const visibleRecent = useMemo(() => {
		const q = query.trim().toLowerCase();
		return q
			? recent.filter((file) => `${file.name} ${file.location}`.toLowerCase().includes(q))
			: recent;
	}, [query, recent]);

	const run = (action?: () => void) => {
		action?.();
		if (action) {
			p.onClose();
		}
	};
	const title = BACKSTAGE_NAV.find((item) => item.id === page)?.label ?? 'Home';
	return (
		<div
			className='fixed inset-0 z-[200] flex bg-background font-[Aptos,Segoe_UI,sans-serif] text-foreground'
			role='dialog'
			aria-modal='true'
			aria-label='File'
		>
			<aside className='flex w-[148px] shrink-0 flex-col border-r border-border bg-secondary'>
				<button
					type='button'
					aria-label='Back to presentation'
					onClick={p.onClose}
					className='grid h-47px min-h-[48px] place-items-center border-b border-border text-xl hover:bg-accent'
				>
					<LuArrowLeft />
				</button>
				<nav className='flex min-h-0 flex-1 flex-col py-2'>
					{BACKSTAGE_NAV.filter((item) => !item.group).map((item) => (
						<button
							key={item.id}
							type='button'
							onClick={() =>
								item.id === 'close'
									? p.onClose()
									: item.id === 'save'
										? run(p.onSaveAsPptx)
										: setPage(item.id)
							}
							className={`flex min-h-10 items-center gap-3 border-l-2 px-4 text-left text-[12px] ${page === item.id ? 'border-primary bg-card text-primary' : 'border-transparent hover:bg-accent'}`}
						>
							<BackstageNavIcon page={item.id} />
							{item.label}
						</button>
					))}
					<div className='flex-1' />
					{BACKSTAGE_NAV.filter((item) => item.group).map((item) => (
						<button
							key={item.id}
							type='button'
							onClick={() =>
								item.id === 'options' && p.onOpenSettings ? run(p.onOpenSettings) : setPage(item.id)
							}
							className={`flex min-h-10 items-center gap-3 border-l-2 px-4 text-left text-[12px] ${page === item.id ? 'border-primary bg-card text-primary' : 'border-transparent hover:bg-accent'}`}
						>
							<BackstageNavIcon page={item.id} />
							{item.label}
						</button>
					))}
				</nav>
			</aside>
			<main className='min-w-0 flex-1 overflow-y-auto bg-background px-[clamp(32px,4vw,72px)] py-5'>
				<h1 className='text-[24px] font-semibold'>{page === 'home' ? 'Good evening' : title}</h1>
				{(page === 'home' || page === 'new') && (
					<BackstageNewGallery
						onCreate={(templateId) => run(() => p.onCreatePresentation(templateId))}
					/>
				)}
				{(page === 'home' || page === 'open') && (
					<>
						<div className='mt-8 flex max-w-[540px] items-center border border-input bg-card px-3 focus-within:border-ring'>
							<LuSearch className='text-muted-foreground' />
							<input
								value={query}
								onChange={(event) => setQuery(event.target.value)}
								placeholder='Search recent presentations'
								className='h-10 min-w-0 flex-1 bg-transparent px-3 text-[13px] outline-none'
							/>
						</div>
						{page === 'open' && (
							<button
								type='button'
								className='mt-4 inline-flex items-center gap-2 bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-90'
								onClick={() => run(p.onOpenFile)}
							>
								<LuFolderOpen /> Browse this device
							</button>
						)}
						<h2 className='mt-6 text-[16px] font-semibold'>Recent</h2>
						<BackstageRecentList
							files={visibleRecent}
							onOpen={(key) => run(() => p.onOpenRecentFile?.(key))}
						/>
					</>
				)}
				{page === 'info' && (
					<div className='mt-8 grid max-w-[900px] grid-cols-2 gap-5'>
						<Action
							icon={<LuLock />}
							title='Protect Presentation'
							body='Control what changes people can make to this presentation.'
							onClick={() => run(p.onOpenPasswordProtection)}
						/>
						<Action
							icon={<LuInfo />}
							title='Inspect Presentation'
							body='Review document properties, accessibility, and hidden content.'
							onClick={() => run(p.onOpenDocumentProperties)}
						/>
						<Action
							icon={<LuType />}
							title='Embed Fonts'
							body='Keep typography consistent when the file moves between devices.'
							onClick={() => run(p.onOpenFontEmbedding)}
						/>
						<Action
							icon={<LuShieldAlert />}
							title='Digital Signatures'
							body='View and manage signatures attached to this presentation.'
							onClick={() => run(p.onOpenDigitalSignatures)}
						/>
					</div>
				)}
				{page === 'saveAs' && (
					<div className='mt-8 grid max-w-[900px] grid-cols-2 gap-5'>
						<Action
							icon={<LuDownload />}
							title='PowerPoint Presentation'
							body='Save an editable .pptx copy.'
							onClick={() => run(p.onSaveAsPptx)}
						/>
						<Action
							icon={<LuPlay />}
							title='PowerPoint Show'
							body='Save a .ppsx file that opens directly in slide show.'
							onClick={() => run(p.onSaveAsPpsx)}
						/>
						{p.hasMacros && (
							<Action
								icon={<LuFileText />}
								title='Macro-Enabled Presentation'
								body='Preserve VBA content in a .pptm file.'
								onClick={() => run(p.onSaveAsPptm)}
							/>
						)}
						<Action
							icon={<LuPackage />}
							title='Package for Sharing'
							body='Bundle the presentation and linked assets.'
							onClick={() => run(p.onPackageForSharing)}
						/>
					</div>
				)}
				{page === 'export' && (
					<div className='mt-8 grid max-w-[900px] grid-cols-2 gap-5'>
						<Action
							icon={<LuFileText />}
							title='Create PDF'
							body='Publish a portable document with one page per slide.'
							onClick={() => run(p.onExportPdf)}
						/>
						<Action
							icon={<LuFileImage />}
							title='Export current slide'
							body='Create a high-quality PNG image.'
							onClick={() => run(p.onExportPng)}
						/>
						<Action
							icon={<LuVideo />}
							title='Create a Video'
							body='Export slide timings and animations as WebM.'
							onClick={() => run(p.onExportVideo)}
						/>
						<Action
							icon={<LuBox />}
							title='Create an Animated GIF'
							body='Make a compact looping preview.'
							onClick={() => run(p.onExportGif)}
						/>
						<Action
							icon={<LuCopy />}
							title='Copy as Image'
							body='Copy the current slide to the clipboard.'
							onClick={() => run(p.onCopySlideAsImage)}
						/>
					</div>
				)}
				{page === 'print' && (
					<div className='mt-8 max-w-[700px]'>
						<Action
							icon={<LuPrinter />}
							title='Print Presentation'
							body='Choose a printer, layout, copies, and output settings in your browser print dialog.'
							onClick={() => run(p.onPrint)}
						/>
					</div>
				)}
				{page === 'share' && (
					<div className='mt-8 grid max-w-[900px] grid-cols-2 gap-5'>
						<Action
							icon={<LuShare2 />}
							title='Share with People'
							body='Invite collaborators and work on the presentation together.'
							onClick={() => run(p.onOpenShareDialog)}
						/>
						<Action
							icon={<LuPackage />}
							title='Package for Sharing'
							body='Download a self-contained package for offline sharing.'
							onClick={() => run(p.onPackageForSharing)}
						/>
					</div>
				)}
				{page === 'account' && (
					<div className='mt-8 max-w-[700px] border border-border bg-card p-7 text-card-foreground'>
						<div className='flex items-center gap-4'>
							<span className='grid size-14 place-items-center rounded-full bg-primary text-xl font-semibold text-primary-foreground'>
								P
							</span>
							<div>
								<h2 className='text-lg font-semibold'>PowerPoint Viewer</h2>
								<p className='text-sm text-muted-foreground'>Local-first presentation editing</p>
							</div>
						</div>
						<p className='mt-6 text-sm leading-6 text-muted-foreground'>
							Your presentations and recovery history stay in your browser unless you explicitly
							share or download them.
						</p>
					</div>
				)}
				{page === 'options' && (
					<div className='mt-8 max-w-[760px] border border-border bg-card p-7 text-card-foreground'>
						<LuSettings className='text-3xl text-primary' />
						<h2 className='mt-4 text-lg font-semibold'>PowerPoint Options</h2>
						<p className='mt-2 text-sm text-muted-foreground'>
							Configure autosave, proofing, grid, rulers, language, theme, and keyboard shortcuts.
						</p>
						<button
							type='button'
							className='mt-6 bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-90'
							onClick={() => run(p.onOpenSettings)}
						>
							Open Options
						</button>
					</div>
				)}
				<p className='mt-12 text-[11px] text-muted-foreground'>
					{p.fileName || 'Untitled Presentation.pptx'} · Saved to this browser
				</p>
			</main>
		</div>
	);
}
