// packages/vue/src/viewer/components/inspector/BookmarkTriggerRow.vue
<script setup lang="ts">
import type { PptxElement, PptxElementAnimation } from 'pptx-viewer-core';
import {
	bookmarkTriggerPatch,
	listMediaBookmarkOptions,
	selectedBookmarkOptionValue,
} from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * The "On bookmark" trigger's bookmark picker: every (media element, bookmark)
 * pair on the slide, from shared's `listMediaBookmarkOptions`.
 */
const props = defineProps<{
	animation: PptxElementAnimation;
	elements: readonly PptxElement[];
}>();
const emit = defineEmits<{
	patch: [patch: Partial<PptxElementAnimation>];
}>();
const { t } = useI18n();

const options = computed(() => listMediaBookmarkOptions(props.elements));

function onChange(event: Event): void {
	const target = event.target as HTMLSelectElement | null;
	emit('patch', bookmarkTriggerPatch(target?.value ?? ''));
}
</script>

<template>
	<label
		>{{ t('pptx.animation.trigger.bookmarkLabel') }}
		<pptx-ui-select
			data-pptx-animation-bookmark-picker
			:aria-label="t('pptx.animation.trigger.bookmarkLabel')"
			:value="selectedBookmarkOptionValue(animation)"
			:disabled="options.length === 0 || undefined"
			@change="onChange"
		>
			<option value="">
				{{
					t(
						options.length === 0
							? 'pptx.animation.trigger.noBookmarks'
							: 'pptx.animation.trigger.selectBookmark',
					)
				}}
			</option>
			<option v-for="option in options" :key="option.value" :value="option.value">
				{{ option.label }}
			</option>
		</pptx-ui-select>
	</label>
</template>

// packages/react/src/viewer/components/inspector/BookmarkTriggerRow.tsx
import type { PptxElement, PptxElementAnimation } from 'pptx-viewer-core';
import { listMediaBookmarkOptions, selectedBookmarkOptionValue } from 'pptx-viewer-shared';
import React from 'react';
import { useTranslation } from 'react-i18next';

import { WebSelect } from '../WebControls';
import { SELECT_CLS } from './animation-panel-constants';

export interface BookmarkTriggerRowProps {
	/** The slide's elements, searched for media bookmarks. */
	elements: readonly PptxElement[];
	/** The selected element's animation entry. */
	animation: PptxElementAnimation | undefined;
	canEdit: boolean;
	style?: React.CSSProperties;
	/** Receives the chosen option value (see `setTriggerBookmark`). */
	onChange: (optionValue: string) => void;
}

/**
 * The "On bookmark" trigger's bookmark picker: every (media element, bookmark)
 * pair on the slide, from shared's `listMediaBookmarkOptions`.
 */
export function BookmarkTriggerRow({
	elements,
	animation,
	canEdit,
	style,
	onChange,
}: BookmarkTriggerRowProps): React.ReactElement {
	const { t } = useTranslation();
	const options = listMediaBookmarkOptions(elements);
	return (
		<label className='flex flex-col gap-1'>
			<span className='text-muted-foreground text-[11px]'>
				{t('pptx.animation.trigger.bookmarkLabel')}
			</span>
			<WebSelect
				aria-label={t('pptx.animation.trigger.bookmarkLabel')}
				data-pptx-animation-bookmark-picker
				value={selectedBookmarkOptionValue(animation)}
				onChange={(event) => onChange(event.target.value)}
				disabled={!canEdit || options.length === 0}
				className={SELECT_CLS}
				style={style}
			>
				<option value=''>
					{t(
						options.length === 0
							? 'pptx.animation.trigger.noBookmarks'
							: 'pptx.animation.trigger.selectBookmark',
					)}
				</option>
				{options.map((option) => (
					<option key={option.value} value={option.value}>
						{option.label}
					</option>
				))}
			</WebSelect>
		</label>
	);
}
