// packages/vue/src/viewer/components/inspector/ChartErrorBarOptions.vue
<script setup lang="ts">
import type { PptxChartErrBars, PptxChartSeries, PptxChartType } from 'pptx-viewer-core';
import {
	ERROR_BAR_SUPPORTED_TYPES,
	ERROR_BAR_TYPE_OPTIONS,
	ERROR_BAR_VALTYPE_OPTIONS,
	ERROR_BAR_VALUE_TYPES,
} from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * ChartErrorBarOptions: per-series error bars (value type, direction, amount).
 * Mirrors React's `ChartErrorBarOptions`. Emits `setErrorBars(index, bars)`
 * where `null` removes the error bars.
 */
const props = defineProps<{
	chartType: PptxChartType;
	series: readonly PptxChartSeries[];
}>();

const emit = defineEmits<{
	setErrorBars: [index: number, errBars: PptxChartErrBars | null];
}>();

const { t } = useI18n();

const visible = computed(
	() => ERROR_BAR_SUPPORTED_TYPES.has(props.chartType) && props.series.length > 0,
);

function firstBars(s: PptxChartSeries): PptxChartErrBars | undefined {
	return s.errBars?.[0];
}

function showValue(bars: PptxChartErrBars | undefined): boolean {
	return Boolean(bars && ERROR_BAR_VALUE_TYPES.has(bars.valType));
}

function onValType(event: Event, index: number, bars: PptxChartErrBars | undefined): void {
	const value = (event.target as HTMLSelectElement).value;
	if (!value) {
		emit('setErrorBars', index, null);
		return;
	}
	emit('setErrorBars', index, {
		direction: bars?.direction ?? 'y',
		barType: bars?.barType ?? 'both',
		valType: value as PptxChartErrBars['valType'],
		val: bars?.val,
	});
}

function onBarType(event: Event, index: number, bars: PptxChartErrBars): void {
	emit('setErrorBars', index, {
		...bars,
		barType: (event.target as HTMLSelectElement).value as PptxChartErrBars['barType'],
	});
}

function onAmount(event: Event, index: number, bars: PptxChartErrBars): void {
	const raw = (event.target as HTMLInputElement).value;
	const num = raw === '' ? undefined : Number.parseFloat(raw);
	if (raw !== '' && !Number.isFinite(num)) {
		return;
	}
	emit('setErrorBars', index, { ...bars, val: num });
}
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.errorBars') }}
		</div>
		<div class="space-y-2">
			<div v-for="(s, i) in props.series" :key="`${s.name}-${i}`" class="space-y-1">
				<div class="flex items-center gap-2 text-[11px]">
					<span class="flex-1 truncate" :title="s.name">{{ s.name }}</span>
					<select
						class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
						data-testid="chart-error-bar-valtype"
						:value="firstBars(s)?.valType ?? ''"
						@change="onValType($event, i, firstBars(s))"
					>
						<option v-for="opt in ERROR_BAR_VALTYPE_OPTIONS" :key="opt.value" :value="opt.value">
							{{ t(opt.labelKey) }}
						</option>
					</select>
				</div>

				<div v-if="firstBars(s)" class="flex items-center gap-2 ml-2">
					<select
						class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
						data-testid="chart-error-bar-type"
						:value="firstBars(s)!.barType"
						@change="onBarType($event, i, firstBars(s)!)"
					>
						<option v-for="opt in ERROR_BAR_TYPE_OPTIONS" :key="opt.value" :value="opt.value">
							{{ t(opt.labelKey) }}
						</option>
					</select>
					<input
						v-if="showValue(firstBars(s))"
						type="number"
						data-testid="chart-error-bar-amount"
						class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
						:value="firstBars(s)!.val ?? ''"
						:placeholder="t('pptx.chart.errorBarAmount')"
						@input="onAmount($event, i, firstBars(s)!)"
					/>
				</div>
			</div>
		</div>
	</div>
</template>

// packages/react/src/viewer/components/inspector/ChartErrorBarOptions.tsx
import type { PptxChartErrBars, PptxChartSeries, PptxChartType } from 'pptx-viewer-core';
import { useTranslation } from 'react-i18next';

import { WebSelect } from '../WebControls';
import {
	CARD,
	ERROR_BAR_SUPPORTED_TYPES,
	ERROR_BAR_TYPE_OPTIONS,
	ERROR_BAR_VALTYPE_OPTIONS,
	ERROR_BAR_VALUE_TYPES,
	HEADING,
	INPUT,
} from './chart-panel-constants';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------
export interface ChartErrorBarOptionsProps {
	chartType: PptxChartType;
	series: PptxChartSeries[];
	canEdit: boolean;
	onSetErrorBars: (seriesIndex: number, errBars: PptxChartErrBars | null) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export function ChartErrorBarOptions({
	chartType,
	series,
	canEdit,
	onSetErrorBars,
}: ChartErrorBarOptionsProps) {
	const { t } = useTranslation();

	if (!ERROR_BAR_SUPPORTED_TYPES.has(chartType) || series.length === 0) {
		return null;
	}

	return (
		<div className={CARD}>
			<div className={HEADING}>{t('pptx.chart.errorBars')}</div>
			<div className='space-y-2'>
				{series.map((s, i) => {
					const bars = s.errBars?.[0];
					const valType = bars?.valType ?? '';
					const showValue = ERROR_BAR_VALUE_TYPES.has(valType);
					return (
						<div key={`${s.name}-${i}`} className='space-y-1'>
							<div className='flex items-center gap-2 text-[11px]'>
								<span className='flex-1 truncate' title={s.name}>
									{s.name}
								</span>
								<WebSelect
									disabled={!canEdit}
									className={INPUT}
									value={valType}
									onChange={(e) => {
										const value = e.target.value;
										if (!value) {
											onSetErrorBars(i, null);
											return;
										}
										onSetErrorBars(i, {
											direction: bars?.direction ?? 'y',
											barType: bars?.barType ?? 'both',
											valType: value as PptxChartErrBars['valType'],
											val: bars?.val,
										});
									}}
								>
									{ERROR_BAR_VALTYPE_OPTIONS.map((opt) => (
										<option key={opt.value} value={opt.value}>
											{t(opt.labelKey)}
										</option>
									))}
								</WebSelect>
							</div>

							{bars && (
								<div className='flex items-center gap-2 ml-2'>
									<WebSelect
										disabled={!canEdit}
										className={INPUT}
										value={bars.barType}
										onChange={(e) =>
											onSetErrorBars(i, {
												...bars,
												barType: e.target.value as PptxChartErrBars['barType'],
											})
										}
									>
										{ERROR_BAR_TYPE_OPTIONS.map((opt) => (
											<option key={opt.value} value={opt.value}>
												{t(opt.labelKey)}
											</option>
										))}
									</WebSelect>
									{showValue && (
										<input
											type='number'
											disabled={!canEdit}
											className={INPUT}
											value={bars.val ?? ''}
											placeholder={t('pptx.chart.errorBarAmount')}
											onChange={(e) => {
												const raw = e.target.value;
												const num = raw === '' ? undefined : Number.parseFloat(raw);
												if (raw !== '' && !Number.isFinite(num)) {
													return;
												}
												onSetErrorBars(i, { ...bars, val: num });
											}}
										/>
									)}
								</div>
							)}
						</div>
					);
				})}
			</div>
		</div>
	);
}
