// packages/angular/src/viewer/chart-axis-options.component.ts
/**
 * chart-axis-options.component.ts: Per-axis scale + label formatting controls.
 *
 * Selector: `pptx-chart-axis-options`
 *
 * Mirrors React's `ChartAxisOptions.tsx`: for each axis present on the chart it
 * exposes min/max/major-unit/minor-unit (scaled axes only), display units, axis
 * title text, number format, tick-label position, and major/minor gridline
 * visibility. Edits route through the headless `setChartAxis` core op (via the
 * `setAxis` immutable wrapper) and emit a new `ChartPptxElement`.
 *
 * @module angular-viewer/chart-axis-options
 */

import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type {
	ChartAxisEdit,
	ChartPptxElement,
	PptxChartAxisFormatting,
	PptxChartAxisType,
} from 'pptx-viewer-core';

import type { ChartTickLabelPosition } from '../internal/shared';
import { DISPLAY_UNITS_OPTIONS, TICK_LABEL_POSITION_OPTIONS } from '../internal/shared';
import { setAxis } from './chart-advanced-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { boolFromEvent, numFromEvent, selectValue, stringFromEvent } from './chart-event-helpers';

/** Axis kinds the inspector exposes, with their label key and whether they scale. */
interface AxisRow {
	type: PptxChartAxisType;
	labelKey: string;
	hasScale: boolean;
	axis: PptxChartAxisFormatting;
}

const AXIS_DEFS: ReadonlyArray<{ type: PptxChartAxisType; labelKey: string; hasScale: boolean }> = [
	{ type: 'valAx', labelKey: 'pptx.chart.valueAxis', hasScale: true },
	{ type: 'dateAx', labelKey: 'pptx.chart.dateAxis', hasScale: true },
	{ type: 'catAx', labelKey: 'pptx.chart.categoryAxis', hasScale: false },
];

/** Numeric scale fields, paired with their label key, rendered for scaled axes. */
const SCALE_FIELDS: ReadonlyArray<{
	key: 'min' | 'max' | 'majorUnit' | 'minorUnit';
	labelKey: string;
}> = [
	{ key: 'min', labelKey: 'pptx.chart.min' },
	{ key: 'max', labelKey: 'pptx.chart.max' },
	{ key: 'majorUnit', labelKey: 'pptx.chart.majorUnit' },
	{ key: 'minorUnit', labelKey: 'pptx.chart.minorUnit' },
];

@Component({
	selector: 'pptx-chart-axis-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (rows().length > 0) {
			<section class="pptx-chart-card" [attr.aria-label]="'pptx.chart.axes' | translate">
				<h4 class="pptx-chart-card__heading">{{ 'pptx.chart.axes' | translate }}</h4>
				@for (row of rows(); track row.type) {
					<div class="pptx-chart-card__group">
						<div class="pptx-chart-card__subhead">{{ row.labelKey | translate }}</div>
						<div class="pptx-chart-card__group pptx-chart-card__group--indent">
							@if (row.hasScale) {
								@for (field of scaleFields; track field.key) {
									<label class="pptx-chart-card__row">
										<span class="pptx-chart-card__label">{{ field.labelKey | translate }}</span>
										<input
											type="number"
											class="pptx-chart-card__input"
											[placeholder]="'pptx.chart.auto' | translate"
											[disabled]="!canEdit()"
											[value]="numValue(row.axis, field.key)"
											(change)="onScaleField(row.type, field.key, $event)"
										/>
									</label>
								}
								<label class="pptx-chart-card__row">
									<span class="pptx-chart-card__label">{{
										'pptx.chart.displayUnits' | translate
									}}</span>
									<select
										[attr.aria-label]="'pptx.chart.displayUnits' | translate"
										class="pptx-chart-card__input"
										[disabled]="!canEdit()"
										[value]="row.axis.displayUnits ?? ''"
										(change)="onDisplayUnits(row.type, $event)"
									>
										@for (opt of displayUnitOptions; track opt.value) {
											<option [value]="opt.value">{{ opt.labelKey | translate }}</option>
										}
									</select>
								</label>
							}

							<label class="pptx-chart-card__row">
								<span class="pptx-chart-card__label">{{ 'pptx.chart.axisTitle' | translate }}</span>
								<input
									type="text"
									class="pptx-chart-card__input"
									[placeholder]="'pptx.chart.axisTitlePlaceholder' | translate"
									[disabled]="!canEdit()"
									[value]="row.axis.titleText ?? ''"
									(change)="onTitleText(row.type, $event)"
								/>
							</label>

							<label class="pptx-chart-card__row">
								<span class="pptx-chart-card__label">{{
									'pptx.chart.numberFormat' | translate
								}}</span>
								<input
									type="text"
									class="pptx-chart-card__input"
									placeholder="General"
									[disabled]="!canEdit()"
									[value]="row.axis.numFmt?.formatCode ?? ''"
									(change)="onNumberFormat(row.type, $event)"
								/>
							</label>

							<label class="pptx-chart-card__row">
								<span class="pptx-chart-card__label">{{
									'pptx.chart.tickLabels' | translate
								}}</span>
								<select
									[attr.aria-label]="'pptx.chart.tickLabels' | translate"
									class="pptx-chart-card__input"
									[disabled]="!canEdit()"
									[value]="row.axis.tickLblPos ?? 'nextTo'"
									(change)="onTickPosition(row.type, $event)"
								>
									@for (opt of tickPositionOptions; track opt.value) {
										<option [value]="opt.value">{{ opt.labelKey | translate }}</option>
									}
								</select>
							</label>

							<label class="pptx-chart-card__check">
								<input
									type="checkbox"
									[disabled]="!canEdit()"
									[checked]="row.axis.majorGridlines ?? false"
									(change)="onGridlines(row.type, 'major', $event)"
								/>
								<span>{{ 'pptx.chart.majorGridlines' | translate }}</span>
							</label>
							<label class="pptx-chart-card__check">
								<input
									type="checkbox"
									[disabled]="!canEdit()"
									[checked]="row.axis.minorGridlines ?? false"
									(change)="onGridlines(row.type, 'minor', $event)"
								/>
								<span>{{ 'pptx.chart.minorGridlines' | translate }}</span>
							</label>
						</div>
					</div>
				}
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartAxisOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	protected readonly scaleFields = SCALE_FIELDS;
	protected readonly displayUnitOptions = DISPLAY_UNITS_OPTIONS;
	protected readonly tickPositionOptions = TICK_LABEL_POSITION_OPTIONS;

	/** Only the axes that actually exist on the chart (pie charts have none). */
	protected readonly rows = computed<AxisRow[]>(() => {
		const axes = this.element().chartData?.axes ?? [];
		const result: AxisRow[] = [];
		for (const def of AXIS_DEFS) {
			const axis = axes.find((a) => a.axisType === def.type);
			if (axis) {
				result.push({ ...def, axis });
			}
		}
		return result;
	});

	protected numValue(
		axis: PptxChartAxisFormatting,
		key: 'min' | 'max' | 'majorUnit' | 'minorUnit',
	): string {
		const value = axis[key];
		return value === undefined ? '' : String(value);
	}

	protected onScaleField(
		axisType: PptxChartAxisType,
		key: 'min' | 'max' | 'majorUnit' | 'minorUnit',
		event: Event,
	): void {
		const num = numFromEvent(event);
		if (num === undefined) {
			return;
		}
		this.emit(axisType, { [key]: num });
	}

	protected onDisplayUnits(axisType: PptxChartAxisType, event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.emit(axisType, {
			displayUnits: (value || null) as ChartAxisEdit['displayUnits'],
		});
	}

	protected onTitleText(axisType: PptxChartAxisType, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.emit(axisType, { title: value });
	}

	protected onNumberFormat(axisType: PptxChartAxisType, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.emit(axisType, { numberFormat: value });
	}

	protected onTickPosition(axisType: PptxChartAxisType, event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.emit(axisType, { tickLabelPosition: value as ChartTickLabelPosition });
	}

	protected onGridlines(axisType: PptxChartAxisType, which: 'major' | 'minor', event: Event): void {
		const checked = boolFromEvent(event);
		this.emit(
			axisType,
			which === 'major' ? { majorGridlines: checked } : { minorGridlines: checked },
		);
	}

	private emit(axisType: PptxChartAxisType, edit: ChartAxisEdit): void {
		this.elementChange.emit(setAxis(this.element(), axisType, edit));
	}
}

// packages/react/src/viewer/components/inspector/ChartAxisOptions.tsx
import type { PptxChartAxisFormatting } from 'pptx-viewer-core';
import { useTranslation } from 'react-i18next';

import {
	CARD,
	DISPLAY_UNITS_OPTIONS,
	HEADING,
	INPUT,
	TICK_LABEL_POSITION_OPTIONS,
} from './chart-panel-constants';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------
export interface ChartAxisOptionsProps {
	axes: PptxChartAxisFormatting[] | undefined;
	canEdit: boolean;
	onUpdateAxis: (
		axisType: PptxChartAxisFormatting['axisType'],
		patch: Partial<PptxChartAxisFormatting>,
	) => void;
}

/** Axis kinds the inspector exposes, with their label keys and whether they carry a numeric scale. */
const AXIS_ROWS: ReadonlyArray<{
	type: PptxChartAxisFormatting['axisType'];
	labelKey: string;
	hasScale: boolean;
}> = [
	{ type: 'valAx', labelKey: 'pptx.chart.valueAxis', hasScale: true },
	{ type: 'dateAx', labelKey: 'pptx.chart.dateAxis', hasScale: true },
	{ type: 'catAx', labelKey: 'pptx.chart.categoryAxis', hasScale: false },
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export function ChartAxisOptions({ axes, canEdit, onUpdateAxis }: ChartAxisOptionsProps) {
	const { t } = useTranslation();

	// Only render axes that actually exist on the chart (e.g. pie charts have none).
	const rows = AXIS_ROWS.map((row) => ({
		...row,
		axis: axes?.find((a) => a.axisType === row.type),
	})).filter((row): row is typeof row & { axis: PptxChartAxisFormatting } => Boolean(row.axis));

	if (rows.length === 0) {
		return null;
	}

	const numberField = (
		axisType: PptxChartAxisFormatting['axisType'],
		labelKey: string,
		value: number | undefined,
		key: 'min' | 'max' | 'majorUnit' | 'minorUnit',
	) => (
		<label className='flex items-center gap-2 text-[11px]'>
			<span className='w-16 text-muted-foreground shrink-0'>{t(labelKey)}</span>
			<input
				type='number'
				disabled={!canEdit}
				className={INPUT}
				value={value ?? ''}
				placeholder={t('pptx.chart.auto')}
				onChange={(e) => {
					const raw = e.target.value;
					if (raw === '') {
						onUpdateAxis(axisType, { [key]: undefined });
						return;
					}
					const num = Number.parseFloat(raw);
					if (Number.isFinite(num)) {
						onUpdateAxis(axisType, { [key]: num });
					}
				}}
			/>
		</label>
	);

	return (
		<div className={CARD}>
			<div className={HEADING}>{t('pptx.chart.axes')}</div>
			{rows.map(({ type, labelKey, hasScale, axis }) => (
				<div key={type} className='space-y-1.5'>
					<div className='text-[11px] font-medium'>{t(labelKey)}</div>

					{hasScale && (
						<div className='space-y-1.5 ml-2'>
							{numberField(type, 'pptx.chart.min', axis.min, 'min')}
							{numberField(type, 'pptx.chart.max', axis.max, 'max')}
							{numberField(type, 'pptx.chart.majorUnit', axis.majorUnit, 'majorUnit')}
							{numberField(type, 'pptx.chart.minorUnit', axis.minorUnit, 'minorUnit')}

							{/* Display units */}
							<label className='flex items-center gap-2 text-[11px]'>
								<span className='w-16 text-muted-foreground shrink-0'>
									{t('pptx.chart.displayUnits')}
								</span>
								<select
									disabled={!canEdit}
									className={INPUT}
									value={axis.displayUnits ?? ''}
									onChange={(e) =>
										onUpdateAxis(type, {
											displayUnits: (e.target.value ||
												undefined) as PptxChartAxisFormatting['displayUnits'],
										})
									}
								>
									{DISPLAY_UNITS_OPTIONS.map((opt) => (
										<option key={opt.value} value={opt.value}>
											{t(opt.labelKey)}
										</option>
									))}
								</select>
							</label>
						</div>
					)}

					<div className='space-y-1.5 ml-2'>
						{/* Axis title */}
						<label className='flex items-center gap-2 text-[11px]'>
							<span className='w-16 text-muted-foreground shrink-0'>
								{t('pptx.chart.axisTitle')}
							</span>
							<input
								type='text'
								disabled={!canEdit}
								className={INPUT}
								value={axis.titleText ?? ''}
								placeholder={t('pptx.chart.axisTitlePlaceholder')}
								onChange={(e) => onUpdateAxis(type, { titleText: e.target.value })}
							/>
						</label>

						{/* Number format */}
						<label className='flex items-center gap-2 text-[11px]'>
							<span className='w-16 text-muted-foreground shrink-0'>
								{t('pptx.chart.numberFormat')}
							</span>
							<input
								type='text'
								disabled={!canEdit}
								className={INPUT}
								value={axis.numFmt?.formatCode ?? ''}
								placeholder='General'
								onChange={(e) =>
									onUpdateAxis(type, {
										numFmt: e.target.value
											? { formatCode: e.target.value, sourceLinked: false }
											: undefined,
									})
								}
							/>
						</label>

						{/* Tick label position */}
						<label className='flex items-center gap-2 text-[11px]'>
							<span className='w-16 text-muted-foreground shrink-0'>
								{t('pptx.chart.tickLabels')}
							</span>
							<select
								disabled={!canEdit}
								className={INPUT}
								value={axis.tickLblPos ?? 'nextTo'}
								onChange={(e) =>
									onUpdateAxis(type, {
										tickLblPos: e.target.value as PptxChartAxisFormatting['tickLblPos'],
									})
								}
							>
								{TICK_LABEL_POSITION_OPTIONS.map((opt) => (
									<option key={opt.value} value={opt.value}>
										{t(opt.labelKey)}
									</option>
								))}
							</select>
						</label>

						{/* Gridlines */}
						<label className='flex items-center gap-2 cursor-pointer'>
							<input
								type='checkbox'
								disabled={!canEdit}
								checked={axis.majorGridlines ?? false}
								onChange={(e) => onUpdateAxis(type, { majorGridlines: e.target.checked })}
								className='accent-primary'
							/>
							<span className='text-[11px]'>{t('pptx.chart.majorGridlines')}</span>
						</label>
						<label className='flex items-center gap-2 cursor-pointer'>
							<input
								type='checkbox'
								disabled={!canEdit}
								checked={axis.minorGridlines ?? false}
								onChange={(e) => onUpdateAxis(type, { minorGridlines: e.target.checked })}
								className='accent-primary'
							/>
							<span className='text-[11px]'>{t('pptx.chart.minorGridlines')}</span>
						</label>
					</div>
				</div>
			))}
		</div>
	);
}
