// packages/vue/src/viewer/components/inspector/ColorChangeSection.vue
<script setup lang="ts">
import type { PptxElement, PptxImageEffects } from 'pptx-viewer-core';
import { normalizeHexColor } from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { DEFAULT_CLR_CHANGE, mergeEffectsPatch } from '../../composables/useImageEditing';
import DebouncedColorInput from './DebouncedColorInput.vue';

/**
 * ColorChangeSection: recolour (chroma-key) toggle with from/to colour pickers
 * and a "make target transparent" option, mapping to `imageEffects.clrChange`
 * (`a:clrChange`). Emits the FULL merged `imageEffects` sub-object per change.
 */
const props = defineProps<{
	fx: PptxImageEffects | undefined;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxElement>];
}>();

const { t } = useI18n();

const cc = computed(() => props.fx?.clrChange);
const clrFrom = computed<string>(() =>
	normalizeHexColor(cc.value?.clrFrom, DEFAULT_CLR_CHANGE.clrFrom),
);
const clrTo = computed<string>(() => normalizeHexColor(cc.value?.clrTo, DEFAULT_CLR_CHANGE.clrTo));
const toTransparent = computed<boolean>(() => Boolean(cc.value?.clrToTransparent));

function commit(patch: Partial<PptxImageEffects>): void {
	emit('update', mergeEffectsPatch(props.fx, patch));
}

function onToggle(event: Event): void {
	const on = (event.target as HTMLInputElement).checked;
	commit({ clrChange: on ? { ...DEFAULT_CLR_CHANGE } : undefined });
}

function onFrom(hex: string): void {
	commit({
		clrChange: { clrFrom: hex, clrTo: clrTo.value, clrToTransparent: toTransparent.value },
	});
}

function onTo(hex: string): void {
	commit({
		clrChange: { clrFrom: clrFrom.value, clrTo: hex, clrToTransparent: toTransparent.value },
	});
}

function onTransparent(event: Event): void {
	commit({
		clrChange: {
			clrFrom: clrFrom.value,
			clrTo: clrTo.value,
			clrToTransparent: (event.target as HTMLInputElement).checked,
		},
	});
}
</script>

<template>
	<div class="pptx-vue-color-change flex flex-col gap-1 text-[11px]">
		<label class="flex items-center justify-between gap-2">
			<span class="font-semibold text-muted-foreground">{{ t('pptx.image.colorChange') }}</span>
			<input type="checkbox" :checked="Boolean(cc)" @change="onToggle" />
		</label>

		<div v-if="cc" class="grid grid-cols-2 gap-1.5">
			<label class="flex items-center gap-2">
				<span class="text-muted-foreground">{{ t('pptx.image.colorChangeFrom') }}</span>
				<DebouncedColorInput
					:value="clrFrom"
					:aria-label="t('pptx.image.recolourFromAria')"
					@commit="onFrom"
				/>
			</label>
			<label class="flex items-center gap-2">
				<span class="text-muted-foreground">{{ t('pptx.image.colorChangeTo') }}</span>
				<DebouncedColorInput
					:value="clrTo"
					:disabled="toTransparent"
					:aria-label="t('pptx.image.recolourToAria')"
					@commit="onTo"
				/>
			</label>
			<label class="col-span-2 flex items-center justify-between gap-2">
				<span class="text-muted-foreground">{{ t('pptx.image.colorChangeTransparent') }}</span>
				<input type="checkbox" :checked="toTransparent" @change="onTransparent" />
			</label>
		</div>
	</div>
</template>

// packages/react/src/viewer/components/inspector/ColorChangeSection.tsx
import React from "react";
import { useTranslation } from "react-i18next";

import { normalizeHexColor } from "../../utils";
import { DebouncedColorInput } from "./DebouncedColorInput";
import type { EffectSectionProps } from "./image-properties-types";

// ---------------------------------------------------------------------------
// Colour change toggle + from/to controls
// ---------------------------------------------------------------------------

export function ColorChangeSection({
  fx,
  canEdit,
  updateEffects,
}: EffectSectionProps): React.ReactElement {
  const { t } = useTranslation();
  const cc = fx?.clrChange;
  return (
    <div className="space-y-1 text-[11px]">
      <label className="flex items-center justify-between gap-2">
        <span className="text-muted-foreground">
          {t("pptx.image.colorChange")}
        </span>
        <input
          type="checkbox"
          disabled={!canEdit}
          checked={Boolean(cc)}
          onChange={(e) =>
            updateEffects({
              clrChange: e.target.checked
                ? {
                    clrFrom: "#ffffff",
                    clrTo: "#000000",
                    clrToTransparent: false,
                  }
                : undefined,
            })
          }
        />
      </label>
      {cc && (
        <div className="grid grid-cols-2 gap-1.5">
          <label className="flex items-center gap-2">
            <span className="text-muted-foreground">
              {t("pptx.image.colorChangeFrom")}
            </span>
            <DebouncedColorInput
              disabled={!canEdit}
              value={normalizeHexColor(cc.clrFrom, "#ffffff")}
              className="h-6 w-8 rounded border border-border bg-transparent cursor-pointer"
              onCommit={(hex) =>
                updateEffects({
                  clrChange: {
                    ...cc,
                    clrFrom: hex,
                    clrTo: cc.clrTo ?? "#000000",
                  },
                })
              }
            />
          </label>
          <label className="flex items-center gap-2">
            <span className="text-muted-foreground">
              {t("pptx.image.colorChangeTo")}
            </span>
            <DebouncedColorInput
              disabled={!canEdit || Boolean(cc.clrToTransparent)}
              value={normalizeHexColor(cc.clrTo, "#000000")}
              className="h-6 w-8 rounded border border-border bg-transparent cursor-pointer"
              onCommit={(hex) =>
                updateEffects({
                  clrChange: {
                    ...cc,
                    clrFrom: cc.clrFrom ?? "#ffffff",
                    clrTo: hex,
                  },
                })
              }
            />
          </label>
          <label className="flex items-center justify-between gap-2 col-span-2">
            <span className="text-muted-foreground">
              {t("pptx.image.colorChangeTransparent")}
            </span>
            <input
              type="checkbox"
              disabled={!canEdit}
              checked={Boolean(cc.clrToTransparent)}
              onChange={(e) =>
                updateEffects({
                  clrChange: {
                    clrFrom: cc.clrFrom ?? "#ffffff",
                    clrTo: cc.clrTo ?? "#000000",
                    clrToTransparent: e.target.checked,
                  },
                })
              }
            />
          </label>
        </div>
      )}
    </div>
  );
}
