// packages/svelte/src/viewer/components/inspector/MotionPathRow.svelte
<script lang="ts">
	/**
	 * MotionPathRow: the animation panel's motion-path row (Svelte port of
	 * React's `inspector/MotionPathRow.tsx`). Pick a catalogue path, clear it, or
	 * see that the applied path was hand-dragged.
	 *
	 * WHY the extra "Custom Path" option: dragging the end handle on the canvas
	 * produces geometry that matches no catalogue entry any more. Without this
	 * option the select would snap back to whichever preset the path started
	 * from, misreporting what will actually play; re-selecting it is a no-op
	 * rather than a reset, so the row can never silently discard a drag.
	 */
	import {
		MOTION_PATH_FAMILIES,
		motionPathFamilyLabelKey,
		motionPathPresetIdForPath,
		motionPathPresetLabelKey,
		motionPathPresetsByFamily,
	} from 'pptx-viewer-shared';

	import { useTranslator } from '../../../i18n/context';

	const {
		motionPath,
		canEdit,
		onchange,
	}: {
		/** The path currently applied to the selected element, if any. */
		motionPath: string | undefined;
		canEdit: boolean;
		/** Receives a catalogue preset id, `'none'` to clear, or `'custom'`. */
		onchange: (presetId: string) => void;
	} = $props();

	const t = useTranslator();

	const presetId = $derived(motionPathPresetIdForPath(motionPath));
	const isCustom = $derived(Boolean(motionPath) && !presetId);
	const value = $derived(isCustom ? 'custom' : (presetId ?? 'none'));
</script>

<label class="pptx-svelte-motionpath-row">
	<span>{t('pptx.animation.motionPath.label')}</span>
	<select
		class="pptx-svelte-animp-motionpath"
		disabled={!canEdit}
		{value}
		onchange={(event) => onchange(event.currentTarget.value)}
	>
		<option value="none">{t('pptx.animation.motionPath.none')}</option>
		{#if isCustom}<option value="custom">{t('pptx.animation.motionPath.custom')}</option>{/if}
		{#each MOTION_PATH_FAMILIES as family (family)}
			<optgroup label={t(motionPathFamilyLabelKey(family))}>
				{#each motionPathPresetsByFamily(family) as preset (preset.id)}
					<option value={preset.id}>{t(motionPathPresetLabelKey(preset.id))}</option>
				{/each}
			</optgroup>
		{/each}
	</select>
	{#if motionPath}
		<small>{t('pptx.animation.motionPath.editHint')}</small>
	{/if}
</label>

<style>
	/* Matches the sibling rows in AnimationPanel, which are scoped there. */
	.pptx-svelte-motionpath-row {
		display: flex;
		flex-direction: column;
		gap: 3px;
	}

	.pptx-svelte-motionpath-row > span {
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-motionpath-row select {
		width: 100%;
		height: 26px;
		box-sizing: border-box;
		padding: 0 6px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-muted, #2a2a3d);
		color: inherit;
		font: inherit;
		font-size: 11px;
	}

	.pptx-svelte-motionpath-row small {
		font-size: 10px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}
</style>

// packages/react/src/viewer/components/inspector/MotionPathRow.tsx
import {
	MOTION_PATH_FAMILIES,
	motionPathFamilyLabelKey,
	motionPathPresetIdForPath,
	motionPathPresetLabelKey,
	motionPathPresetsByFamily,
} from 'pptx-viewer-shared';
import React from 'react';
import { useTranslation } from 'react-i18next';

import { SELECT_CLS } from './animation-panel-constants';

export interface MotionPathRowProps {
	/** The path currently applied to the selected element, if any. */
	motionPath: string | undefined;
	canEdit: boolean;
	/** Receives a catalogue preset id, or `'none'` to clear the path. */
	onChange: (presetId: string) => void;
}

/**
 * The animation panel's motion-path row: pick a catalogue path, clear it, or
 * see that the applied path was hand-dragged.
 *
 * A dragged path no longer matches any catalogue entry, so it is surfaced as a
 * selected "Custom Path" option rather than silently snapping the select back
 * to the preset it started from (which would misreport what will play).
 */
export function MotionPathRow({
	motionPath,
	canEdit,
	onChange,
}: MotionPathRowProps): React.ReactElement {
	const { t } = useTranslation();
	const presetId = motionPathPresetIdForPath(motionPath);
	const isCustom = Boolean(motionPath) && !presetId;

	return (
		<label className='flex flex-col gap-1'>
			<span className='text-muted-foreground text-[11px]'>
				{t('pptx.animation.motionPath.label')}
			</span>
			<select
				value={isCustom ? 'custom' : (presetId ?? 'none')}
				onChange={(event) => onChange(event.target.value)}
				disabled={!canEdit}
				className={SELECT_CLS}
			>
				<option value='none'>{t('pptx.animation.motionPath.none')}</option>
				{isCustom && <option value='custom'>{t('pptx.animation.motionPath.custom')}</option>}
				{MOTION_PATH_FAMILIES.map((family) => (
					<optgroup key={family} label={t(motionPathFamilyLabelKey(family))}>
						{motionPathPresetsByFamily(family).map((preset) => (
							<option key={preset.id} value={preset.id}>
								{t(motionPathPresetLabelKey(preset.id))}
							</option>
						))}
					</optgroup>
				))}
			</select>
			{motionPath && (
				<span className='text-[10px] text-muted-foreground'>
					{t('pptx.animation.motionPath.editHint')}
				</span>
			)}
		</label>
	);
}
