// packages/vue/src/viewer/components/inspector/SmartArtNodeRow.vue
<script setup lang="ts">
import type { PptxSmartArtNode, PptxSmartArtNodeStyle } from 'pptx-viewer-core';
import type { ComponentPublicInstance } from 'vue';
import { computed } from 'vue';

/**
 * SmartArtNodeRow: a single editable node row in the SmartArt text pane.
 *
 * Vue port of the React `SmartArtNodeRow.tsx`, extended with per-node visual
 * overrides (fill colour, font colour, bold, italic). Purely presentational:
 * every mutation is routed back through events so the editing logic stays in the
 * parent composable / core ops. Renders as a `role="listitem"` for AT.
 */
const props = defineProps<{
	node: PptxSmartArtNode;
	/** 1-based display number among top-level nodes (0 for child rows). */
	displayIndex: number;
	isChild: boolean;
	canEdit: boolean;
	removeDisabled: boolean;
	moveUpDisabled: boolean;
	moveDownDisabled: boolean;
}>();

const emit = defineEmits<{
	changeText: [nodeId: string, text: string];
	keydownNode: [event: KeyboardEvent, nodeId: string];
	setStyle: [nodeId: string, style: Partial<PptxSmartArtNodeStyle>];
	addSubItem: [nodeId: string];
	moveUp: [nodeId: string];
	moveDown: [nodeId: string];
	remove: [nodeId: string];
	registerInput: [nodeId: string, el: HTMLInputElement | null];
}>();

/** Child-node marker glyph (U+2022 bullet) shown in the text-pane list. */
const bulletGlyph = String.fromCharCode(0x2022);

const label = computed(() =>
	props.isChild
		? `Sub-item: ${props.node.text || 'empty'}`
		: `Item ${props.displayIndex}: ${props.node.text || 'empty'}`,
);

const fillColor = computed(() => props.node.style?.fillColor ?? '#3b82f6');
const fontColor = computed(() => props.node.style?.fontColor ?? '#ffffff');
const isBold = computed(() => props.node.style?.bold === true);
const isItalic = computed(() => props.node.style?.italic === true);

function onText(event: Event): void {
	emit('changeText', props.node.id, (event.target as HTMLInputElement).value);
}

function onFill(event: Event): void {
	emit('setStyle', props.node.id, { fillColor: (event.target as HTMLInputElement).value });
}

function onFont(event: Event): void {
	emit('setStyle', props.node.id, { fontColor: (event.target as HTMLInputElement).value });
}

function toggleBold(): void {
	emit('setStyle', props.node.id, { bold: !isBold.value });
}

function toggleItalic(): void {
	emit('setStyle', props.node.id, { italic: !isItalic.value });
}

function bindInput(el: Element | ComponentPublicInstance | null): void {
	emit('registerInput', props.node.id, el instanceof HTMLInputElement ? el : null);
}
</script>

<template>
	<div
		role="listitem"
		class="rounded border bg-background/60 p-1.5"
		:class="isChild ? 'border-border/60 ml-4' : 'border-border'"
		data-testid="smartart-node"
	>
		<div class="flex items-center gap-1">
			<span class="text-[9px] text-muted-foreground w-3 shrink-0" aria-hidden="true">
				{{ isChild ? bulletGlyph : `${displayIndex}` }}
			</span>
			<input
				:ref="bindInput"
				type="text"
				:disabled="!canEdit"
				:aria-label="label"
				data-testid="smartart-node-text"
				class="flex-1 bg-muted border border-border rounded px-1.5 py-0.5 text-[11px]"
				:value="node.text"
				placeholder="Type here"
				@input="onText"
				@keydown="emit('keydownNode', $event, node.id)"
			/>
			<div class="flex items-center gap-0.5 shrink-0">
				<button
					type="button"
					:disabled="!canEdit || moveUpDisabled"
					data-testid="smartart-move-up"
					class="text-[9px] text-muted-foreground hover:text-primary px-1 disabled:opacity-40"
					:aria-label="`Move ${label} up`"
					title="Move up"
					@click="emit('moveUp', node.id)"
				>
					&uarr;
				</button>
				<button
					type="button"
					:disabled="!canEdit || moveDownDisabled"
					data-testid="smartart-move-down"
					class="text-[9px] text-muted-foreground hover:text-primary px-1 disabled:opacity-40"
					:aria-label="`Move ${label} down`"
					title="Move down"
					@click="emit('moveDown', node.id)"
				>
					&darr;
				</button>
				<button
					v-if="!isChild"
					type="button"
					:disabled="!canEdit"
					data-testid="smartart-add-sub"
					class="text-[9px] text-muted-foreground hover:text-primary px-1"
					:aria-label="`Add sub-item under ${label}`"
					title="Add sub-item"
					@click="emit('addSubItem', node.id)"
				>
					+Sub
				</button>
				<button
					type="button"
					:disabled="!canEdit || removeDisabled"
					data-testid="smartart-remove"
					class="text-[9px] text-muted-foreground hover:text-red-400 px-1 disabled:opacity-40"
					:aria-label="`Remove ${label}`"
					:title="removeDisabled ? 'Layout minimum reached' : 'Remove'"
					@click="emit('remove', node.id)"
				>
					x
				</button>
			</div>
		</div>
		<div class="flex items-center gap-1.5 mt-1 pl-4">
			<label class="flex items-center gap-1 text-[9px] text-muted-foreground">
				Fill
				<input
					type="color"
					:disabled="!canEdit"
					data-testid="smartart-node-fill"
					:aria-label="`Fill colour for ${label}`"
					class="h-4 w-5 rounded border border-border bg-transparent p-0"
					:value="fillColor"
					@input="onFill"
				/>
			</label>
			<label class="flex items-center gap-1 text-[9px] text-muted-foreground">
				Text
				<input
					type="color"
					:disabled="!canEdit"
					data-testid="smartart-node-font"
					:aria-label="`Font colour for ${label}`"
					class="h-4 w-5 rounded border border-border bg-transparent p-0"
					:value="fontColor"
					@input="onFont"
				/>
			</label>
			<button
				type="button"
				:disabled="!canEdit"
				data-testid="smartart-node-bold"
				:aria-pressed="isBold"
				:aria-label="`Bold ${label}`"
				class="text-[10px] font-bold px-1 rounded border"
				:class="
					isBold
						? 'border-primary bg-primary/20 text-primary'
						: 'border-border text-muted-foreground'
				"
				@click="toggleBold"
			>
				B
			</button>
			<button
				type="button"
				:disabled="!canEdit"
				data-testid="smartart-node-italic"
				:aria-pressed="isItalic"
				:aria-label="`Italic ${label}`"
				class="text-[10px] italic px-1 rounded border"
				:class="
					isItalic
						? 'border-primary bg-primary/20 text-primary'
						: 'border-border text-muted-foreground'
				"
				@click="toggleItalic"
			>
				I
			</button>
		</div>
	</div>
</template>

// packages/react/src/viewer/components/inspector/SmartArtNodeRow.tsx
import type { PptxSmartArtNodeStyle } from 'pptx-viewer-core';
import React from 'react';

import { cn } from '../../utils';
import { INPUT } from './inspector-pane-constants';
import { SmartArtNodeStyleControls } from './SmartArtNodeStyleControls';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface SmartArtNodeRowProps {
	nodeId: string;
	text: string;
	/** 1-based display index for top-level nodes. */
	displayIndex: number;
	isChild: boolean;
	canEdit: boolean;
	/** Disable the remove control (e.g. layout min reached or last node). */
	removeDisabled: boolean;
	/** Disable move-up (already first among siblings). */
	moveUpDisabled: boolean;
	/** Disable move-down (already last among siblings). */
	moveDownDisabled: boolean;
	/** Ref callback so the parent can focus the input after structural edits. */
	inputRef: (el: HTMLInputElement | null) => void;
	/** Current per-node visual override (fill / font colour, bold / italic). */
	style?: PptxSmartArtNodeStyle;
	onChangeText: (nodeId: string, text: string) => void;
	onKeyDown: (e: React.KeyboardEvent, nodeId: string) => void;
	onAddSubItem: (nodeId: string) => void;
	onMoveUp: (nodeId: string) => void;
	onMoveDown: (nodeId: string) => void;
	onRemove: (nodeId: string) => void;
	/** Apply a partial per-node style change (routed to setSmartArtNodeStyle). */
	onChangeStyle: (nodeId: string, patch: Partial<PptxSmartArtNodeStyle>) => void;
}

const MINI_BTN =
	'text-[9px] text-muted-foreground hover:text-primary px-1 disabled:opacity-40 disabled:cursor-not-allowed';

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * A single editable SmartArt node row in the text pane.
 *
 * Purely presentational: all mutations are routed back through callbacks so the
 * editing logic stays in the parent / core ops.
 */
export function SmartArtNodeRow({
	nodeId,
	text,
	displayIndex,
	isChild,
	canEdit,
	removeDisabled,
	moveUpDisabled,
	moveDownDisabled,
	inputRef,
	style,
	onChangeText,
	onKeyDown,
	onAddSubItem,
	onMoveUp,
	onMoveDown,
	onRemove,
	onChangeStyle,
}: SmartArtNodeRowProps): React.ReactElement {
	const label = isChild
		? `Sub-item: ${text || 'empty'}`
		: `Item ${displayIndex}: ${text || 'empty'}`;

	return (
		<div
			role='listitem'
			className={cn(
				'rounded border bg-background/60 p-1.5',
				isChild ? 'border-border/60 ml-4' : 'border-border',
			)}
		>
			<div className='flex items-center gap-1'>
				<span className='text-[9px] text-muted-foreground w-3 shrink-0' aria-hidden='true'>
					{isChild ? '•' : `${displayIndex}`}
				</span>
				<input
					ref={inputRef}
					type='text'
					disabled={!canEdit}
					aria-label={label}
					className={cn(INPUT, 'flex-1 text-[11px] py-0.5')}
					value={text}
					onChange={(e) => onChangeText(nodeId, e.target.value)}
					onKeyDown={(e) => onKeyDown(e, nodeId)}
					placeholder='Type here'
				/>
				<div className='flex items-center gap-0.5 shrink-0'>
					<button
						type='button'
						disabled={!canEdit || moveUpDisabled}
						className={MINI_BTN}
						onClick={() => onMoveUp(nodeId)}
						aria-label={`Move ${label} up`}
						title='Move up'
					>
						↑
					</button>
					<button
						type='button'
						disabled={!canEdit || moveDownDisabled}
						className={MINI_BTN}
						onClick={() => onMoveDown(nodeId)}
						aria-label={`Move ${label} down`}
						title='Move down'
					>
						↓
					</button>
					{!isChild && (
						<button
							type='button'
							disabled={!canEdit}
							className={MINI_BTN}
							onClick={() => onAddSubItem(nodeId)}
							aria-label={`Add sub-item under ${label}`}
							title='Add sub-item'
						>
							+Sub
						</button>
					)}
					<button
						type='button'
						disabled={!canEdit || removeDisabled}
						className={cn(MINI_BTN, 'hover:text-red-400')}
						onClick={() => onRemove(nodeId)}
						aria-label={`Remove ${label}`}
						title={removeDisabled ? 'Layout minimum reached' : 'Remove'}
					>
						x
					</button>
				</div>
			</div>
			<SmartArtNodeStyleControls
				nodeId={nodeId}
				style={style}
				label={label}
				canEdit={canEdit}
				onChangeStyle={onChangeStyle}
			/>
		</div>
	);
}
