// packages/vue/src/viewer/components/ai/AiChatPanel.vue
<script setup lang="ts">
/**
 * AiChatPanel: the right-hand AI assistant pane. Loaded via
 * `defineAsyncComponent` from `PowerPointViewer.vue`, so its `@ai-sdk/vue` +
 * `pptx-viewer-shared/ai` runtime imports only load when the panel is first
 * opened.
 *
 * The panel is a thin shell: it builds/guards the session via {@link useAiChat}
 * and, once ready, delegates the whole conversation to {@link AiConversation}.
 */
import { LoaderCircle, Sparkles, TriangleAlert, X } from 'lucide-vue-next';
import type { PptxAiBridge, PptxAiConfig } from 'pptx-viewer-shared/ai';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { useAiChat } from '../../composables/ai/useAiChat';
import AiConversation from './AiConversation.vue';

const props = defineProps<{
	bridge: PptxAiBridge;
	config: PptxAiConfig;
	panelWidth?: number;
}>();
const emit = defineEmits<{ (e: 'close'): void }>();
const { t } = useI18n();

const { state, session, initError } = useAiChat(props.bridge, props.config);
const panelStyle = computed(() =>
	props.panelWidth ? { width: `${props.panelWidth}px` } : undefined,
);
</script>

<template>
	<div
		data-pptx-ai-panel=""
		class="absolute right-0 top-0 z-30 flex h-full w-80 flex-col border-l border-border bg-card shadow-xl max-md:inset-x-0 max-md:w-full"
		:style="panelStyle"
	>
		<div class="flex items-center gap-2 border-b border-border px-3 py-2">
			<Sparkles class="w-4 h-4 text-primary" />
			<span class="text-sm font-semibold text-foreground">{{ t('pptx.ai.title') }}</span>
			<button
				type="button"
				:title="t('pptx.ai.close')"
				:aria-label="t('pptx.ai.close')"
				class="ml-auto rounded-sm p-1 text-muted-foreground transition-colors hover:bg-accent"
				@click="emit('close')"
			>
				<X class="w-4 h-4" />
			</button>
		</div>

		<div
			v-if="state === 'checking'"
			class="flex flex-1 flex-col items-center justify-center gap-2 text-muted-foreground"
		>
			<LoaderCircle class="w-5 h-5 animate-spin" />
		</div>

		<div
			v-else-if="state === 'unavailable' || state === 'error'"
			class="flex flex-1 flex-col items-center justify-center gap-2 px-6 text-center"
		>
			<TriangleAlert class="w-6 h-6 text-muted-foreground" />
			<p class="text-sm font-medium text-foreground">{{ t('pptx.ai.unavailableTitle') }}</p>
			<p class="text-[12px] text-muted-foreground">
				{{ initError?.message ?? t('pptx.ai.unavailableHint') }}
			</p>
		</div>

		<AiConversation
			v-else-if="state === 'ready' && session"
			:session="session"
			:config="props.config"
		/>
	</div>
</template>

// packages/react/src/viewer/components/ai/AiChatPanel.tsx
/**
 * AiChatPanel: the right-hand AI assistant pane. Default-exported so it can be
 * `React.lazy`-loaded (its `@ai-sdk/react` + `pptx-viewer-shared/ai` runtime
 * imports only load when the panel is first opened).
 *
 * The panel is a thin shell: it builds/guards the session via {@link useAiChat}
 * and, once ready, delegates the whole conversation to {@link AiConversation}.
 */
import type { PptxAiBridge, PptxAiConfig } from 'pptx-viewer-shared/ai';
import { useTranslation } from 'react-i18next';
import { LuLoaderCircle, LuSparkles, LuTriangleAlert, LuX } from 'react-icons/lu';

import { useAiChat } from '../../hooks/ai/useAiChat';
import { AiConversation } from './AiConversation';

export interface AiChatPanelProps {
	bridge: PptxAiBridge;
	config: PptxAiConfig;
	onClose: () => void;
	panelWidth?: number;
}

export default function AiChatPanel({ bridge, config, onClose, panelWidth }: AiChatPanelProps) {
	const { t } = useTranslation();
	const { state, session, initError } = useAiChat(bridge, config);

	return (
		<div
			data-pptx-ai-panel=''
			className='absolute right-0 top-0 z-30 flex h-full w-80 flex-col border-l border-border bg-card shadow-xl max-md:inset-x-0 max-md:w-full'
			style={panelWidth ? { width: panelWidth } : undefined}
		>
			<div className='flex items-center gap-2 border-b border-border px-3 py-2'>
				<LuSparkles className='w-4 h-4 text-primary' />
				<span className='text-sm font-semibold text-foreground'>{t('pptx.ai.title')}</span>
				<button
					type='button'
					onClick={onClose}
					title={t('pptx.ai.close')}
					aria-label={t('pptx.ai.close')}
					className='ml-auto rounded-sm p-1 text-muted-foreground transition-colors hover:bg-accent'
				>
					<LuX className='w-4 h-4' />
				</button>
			</div>

			{state === 'checking' && (
				<div className='flex flex-1 flex-col items-center justify-center gap-2 text-muted-foreground'>
					<LuLoaderCircle className='w-5 h-5 animate-spin' />
				</div>
			)}

			{(state === 'unavailable' || state === 'error') && (
				<div className='flex flex-1 flex-col items-center justify-center gap-2 px-6 text-center'>
					<LuTriangleAlert className='w-6 h-6 text-muted-foreground' />
					<p className='text-sm font-medium text-foreground'>{t('pptx.ai.unavailableTitle')}</p>
					<p className='text-[12px] text-muted-foreground'>
						{initError?.message ?? t('pptx.ai.unavailableHint')}
					</p>
				</div>
			)}

			{state === 'ready' && session && <AiConversation session={session} config={config} />}
		</div>
	);
}
