// demos/demo-angular/src/theme-picker.component.ts
import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	HostListener,
	input,
	output,
	signal,
} from '@angular/core';

import { THEME_KEYS, THEMES } from './themes';

/**
 * Floating theme picker (Angular port of the React demo's `ThemePicker`).
 *
 * A fixed-position pill button (bottom-right on desktop, top-right under the
 * safe-area on mobile <768px) showing a sun icon + the active theme label.
 * Clicking opens a menu listing every theme with a colour swatch dot and the
 * active row highlighted. It floats above the viewer via a high z-index.
 */
@Component({
	selector: 'app-theme-picker',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle],
	template: `
		<div class="picker" [ngStyle]="containerStyle()">
			<button
				type="button"
				class="pill"
				title="Switch theme"
				[ngStyle]="pillStyle()"
				(click)="toggle()"
			>
				<svg
					width="14"
					height="14"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				>
					<circle cx="12" cy="12" r="4" />
					<path d="M12 2v2" />
					<path d="M12 20v2" />
					<path d="m4.93 4.93 1.41 1.41" />
					<path d="m17.66 17.66 1.41 1.41" />
					<path d="M2 12h2" />
					<path d="M20 12h2" />
					<path d="m6.34 17.66-1.41 1.41" />
					<path d="m19.07 4.93-1.41 1.41" />
				</svg>
				{{ preset().label }}
			</button>
			@if (open()) {
				<div class="menu" [ngStyle]="menuStyle()">
					@for (key of themeKeys; track key) {
						<button type="button" class="row" [ngStyle]="rowStyle(key)" (click)="choose(key)">
							<span class="swatch" [ngStyle]="swatchStyle(key)"></span>
							{{ label(key) }}
						</button>
					}
				</div>
			}
		</div>
	`,
	styles: [
		`
			.picker {
				font-family: system-ui, sans-serif;
			}
			.pill {
				display: flex;
				align-items: center;
				gap: 6px;
				padding: 6px 12px;
				border-radius: 9999px;
				cursor: pointer;
				font-size: 13px;
				font-weight: 500;
				box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
			}
			.menu {
				position: absolute;
				right: 0;
				border-radius: 8px;
				overflow-y: auto;
				max-height: 60dvh;
				box-shadow: 0 4px 16px rgba(0, 0, 0, 0.3);
				min-width: 150px;
			}
			.row {
				display: flex;
				align-items: center;
				gap: 8px;
				width: 100%;
				padding: 8px 14px;
				border: none;
				cursor: pointer;
				font-size: 13px;
				text-align: left;
			}
			.swatch {
				width: 14px;
				height: 14px;
				border-radius: 9999px;
				flex-shrink: 0;
			}
		`,
	],
})
export class ThemePickerComponent {
	/** Active theme key. */
	readonly current = input.required<string>();
	/** Emits the newly selected theme key. */
	readonly themeChange = output<string>();

	protected readonly themeKeys = THEME_KEYS;
	protected readonly open = signal(false);
	private readonly isSmallScreen = signal(typeof window !== 'undefined' && window.innerWidth < 768);

	@HostListener('window:resize')
	protected onResize(): void {
		this.isSmallScreen.set(window.innerWidth < 768);
	}

	protected readonly preset = computed(() => THEMES[this.current()] ?? THEMES['dark']);
	private readonly bg = computed(() => this.preset().theme.colors?.card ?? '#111827');
	private readonly border = computed(() => this.preset().theme.colors?.border ?? '#374151');
	private readonly fg = computed(() => this.preset().theme.colors?.mutedForeground ?? '#9ca3af');
	private readonly primary = computed(() => this.preset().theme.colors?.primary ?? '#6366f1');

	protected readonly containerStyle = computed<Record<string, string>>(() => ({
		position: 'fixed',
		zIndex: this.open() ? '100000' : '99999',
		...(this.isSmallScreen()
			? { top: 'calc(env(safe-area-inset-top, 0px) + 60px)', right: '8px' }
			: { bottom: '48px', right: '12px' }),
	}));

	protected readonly pillStyle = computed<Record<string, string>>(() => ({
		border: `1px solid ${this.border()}`,
		background: this.bg(),
		color: this.fg(),
	}));

	protected readonly menuStyle = computed<Record<string, string>>(() => ({
		background: this.bg(),
		border: `1px solid ${this.border()}`,
		...(this.isSmallScreen()
			? { top: '100%', marginTop: '4px' }
			: { bottom: '100%', marginBottom: '4px' }),
	}));

	protected toggle(): void {
		this.open.update((v) => !v);
	}

	protected choose(key: string): void {
		this.themeChange.emit(key);
		this.open.set(false);
	}

	protected label(key: string): string {
		return (THEMES[key] ?? THEMES['dark']).label;
	}

	protected rowStyle(key: string): Record<string, string> {
		const isActive = key === this.current();
		return {
			background: isActive ? `${this.primary()}22` : 'transparent',
			color: isActive ? this.primary() : this.fg(),
			fontWeight: isActive ? '600' : '400',
		};
	}

	protected swatchStyle(key: string): Record<string, string> {
		const colors = (THEMES[key] ?? THEMES['dark']).theme.colors;
		return {
			background: colors?.primary ?? '#6366f1',
			border: `2px solid ${colors?.border ?? '#374151'}`,
		};
	}
}

// demos/demo-vue/src/ThemePicker.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';

import { themeKeys, themes } from './themes';

/**
 * Floating theme picker, ported from the React demo's `ThemePicker`.
 *
 * A fixed-position pill (bottom-right on desktop, top-right under the safe-area
 * on mobile) opens a menu of every theme. Teleported to <body> so it floats
 * above the viewer's own stacking contexts.
 */
const props = defineProps<{ current: string }>();
const emit = defineEmits<{ (e: 'change', key: string): void }>();

const open = ref(false);

// The picker is a fixed sibling of the viewer, so any z-index floats it above
// the viewer's whole subtree. On small screens we anchor it to the top-right
// (clear of the mobile bottom bar / bottom sheets) and keep the familiar
// bottom-right spot on desktop.
const isSmallScreen = ref(typeof window !== 'undefined' && window.innerWidth < 768);
function onResize(): void {
	isSmallScreen.value = window.innerWidth < 768;
}
onMounted(() => window.addEventListener('resize', onResize));
onBeforeUnmount(() => window.removeEventListener('resize', onResize));

const preset = computed(() => themes[props.current] ?? themes.dark);
const bg = computed(() => preset.value.theme.colors?.card ?? '#111827');
const border = computed(() => preset.value.theme.colors?.border ?? '#374151');
const fg = computed(() => preset.value.theme.colors?.mutedForeground ?? '#9ca3af');
const primary = computed(() => preset.value.theme.colors?.primary ?? '#6366f1');

function pick(key: string): void {
	emit('change', key);
	open.value = false;
}
</script>

<template>
	<Teleport to="body">
		<div
			class="theme-picker"
			:class="{ 'theme-picker--small': isSmallScreen }"
			:style="{ zIndex: open ? 100000 : 99999 }"
		>
			<button
				type="button"
				class="theme-picker__btn"
				title="Switch theme"
				:style="{ border: `1px solid ${border}`, background: bg, color: fg }"
				@click="open = !open"
			>
				<svg
					width="14"
					height="14"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				>
					<circle cx="12" cy="12" r="4" />
					<path d="M12 2v2" />
					<path d="M12 20v2" />
					<path d="m4.93 4.93 1.41 1.41" />
					<path d="m17.66 17.66 1.41 1.41" />
					<path d="M2 12h2" />
					<path d="M20 12h2" />
					<path d="m6.34 17.66-1.41 1.41" />
					<path d="m19.07 4.93-1.41 1.41" />
				</svg>
				{{ preset.label }}
			</button>
			<div
				v-if="open"
				class="theme-picker__menu"
				:style="{ background: bg, border: `1px solid ${border}` }"
			>
				<button
					v-for="key in themeKeys"
					:key="key"
					type="button"
					class="theme-picker__item"
					:style="{
						background: key === current ? `${primary}22` : 'transparent',
						color: key === current ? primary : fg,
						fontWeight: key === current ? 600 : 400,
					}"
					@click="pick(key)"
				>
					<span
						class="theme-picker__swatch"
						:style="{
							background: themes[key].theme.colors?.primary ?? '#6366f1',
							border: `2px solid ${themes[key].theme.colors?.border ?? '#374151'}`,
						}"
					/>
					{{ themes[key].label }}
				</button>
			</div>
		</div>
	</Teleport>
</template>

<style scoped>
.theme-picker {
	position: fixed;
	bottom: 48px;
	right: 12px;
	z-index: 99999;
	font-family: system-ui, sans-serif;
}

.theme-picker--small {
	bottom: auto;
	right: 8px;
	top: calc(env(safe-area-inset-top, 0px) + 60px);
}

.theme-picker__btn {
	display: flex;
	align-items: center;
	gap: 6px;
	padding: 6px 12px;
	border-radius: 9999px;
	cursor: pointer;
	font-size: 13px;
	font-weight: 500;
	box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
}

.theme-picker__menu {
	position: absolute;
	bottom: 100%;
	margin-bottom: 4px;
	right: 0;
	border-radius: 8px;
	overflow-y: auto;
	max-height: 60dvh;
	box-shadow: 0 4px 16px rgba(0, 0, 0, 0.3);
	min-width: 150px;
}

/* On mobile the button is anchored near the top, so an upward menu was clipped
   off-screen. Open downward there; keep the bottom-anchored placement on desktop. */
.theme-picker--small .theme-picker__menu {
	bottom: auto;
	margin-bottom: 0;
	top: 100%;
	margin-top: 4px;
}

.theme-picker__item {
	display: flex;
	align-items: center;
	gap: 8px;
	width: 100%;
	padding: 8px 14px;
	border: none;
	cursor: pointer;
	font-size: 13px;
	text-align: left;
}

.theme-picker__swatch {
	width: 14px;
	height: 14px;
	border-radius: 9999px;
	flex-shrink: 0;
}
</style>
