// packages/vue/src/viewer/components/InsertSmartArtDialog.vue
<script setup lang="ts">
import type { PptxElement, SmartArtLayout, SmartArtPptxElement } from 'pptx-viewer-core';
import { buildSmartArtPresetData } from 'pptx-viewer-shared';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import DialogFooter from './DialogFooter.vue';
import ModalDialog from './ModalDialog.vue';
import type { SmartArtCategory } from './smart-art-presets';
import { CATEGORIES, PRESETS } from './smart-art-presets';
import SmartArtPreviews from './SmartArtPreviews.vue';

/**
 * InsertSmartArtDialog: gallery + node-text entry for inserting a SmartArt
 * graphic.
 *
 * Vue port of the React `InsertSmartArtDialog.tsx`. Built on
 * {@link ModalDialog}, it shows a category sidebar + a thumbnail gallery
 * (`SmartArtPreviews.vue`). Picking a preset seeds an editable textarea with one
 * node per line (the preset's `defaultItems`); the user can add/remove/edit
 * lines before inserting.
 *
 * On insert it builds a fully-formed core {@link SmartArtPptxElement} (so
 * `SmartArtRenderer.vue` can render it directly, with no further core call;
 * there is no `createSmartArtElement` factory in core, so the literal is built
 * here exactly as the React `handleInsertSmartArt` handler does) and emits it
 * via the `insert` event. The host routes the payload to `ops.addElement`.
 */
const props = defineProps<{
	/** Whether the dialog is open. */
	open: boolean;
}>();

const emit = defineEmits<{
	/** Emitted with a ready-to-add SmartArt element. */
	(e: 'insert', element: PptxElement): void;
	/** Emitted when the dialog should close without inserting. */
	(e: 'close'): void;
}>();

const { t } = useI18n();

const activeCategory = ref<SmartArtCategory>('list');
const selectedLayout = ref<SmartArtLayout | null>(null);
/** Newline-separated node texts for the currently selected preset. */
const nodeText = ref('');

const filteredPresets = computed(() => PRESETS.filter((p) => p.category === activeCategory.value));

/** Parsed, trimmed, non-empty node lines from the textarea. */
const nodeItems = computed(() =>
	nodeText.value
		.split('\n')
		.map((line) => line.trim())
		.filter((line) => line.length > 0),
);

const canInsert = computed(() => selectedLayout.value !== null && nodeItems.value.length > 0);

/** Re-seed local state whenever the dialog (re)opens. */
watch(
	() => props.open,
	(isOpen) => {
		if (isOpen) {
			activeCategory.value = 'list';
			selectedLayout.value = null;
			nodeText.value = '';
		}
	},
	{ immediate: true },
);

function selectCategory(cat: SmartArtCategory): void {
	activeCategory.value = cat;
	selectedLayout.value = null;
	nodeText.value = '';
}

function selectLayout(layout: SmartArtLayout): void {
	selectedLayout.value = layout;
	const preset = PRESETS.find((p) => p.layout === layout);
	nodeText.value = preset ? preset.defaultItems.join('\n') : '';
}

/** Best-effort unique id, mirroring the core element-factory style. */
function newId(prefix: string): string {
	if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
		return `${prefix}-${crypto.randomUUID()}`;
	}
	return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Build a renderable SmartArt element for the given layout + node texts.
 * Mirrors the React `handleInsertSmartArt`: hierarchy layouts parent every node
 * after the first under the root; all others stay flat.
 */
function buildSmartArtElement(layout: SmartArtLayout, items: string[]): SmartArtPptxElement {
	return {
		id: newId('smartart'),
		type: 'smartArt',
		x: 100,
		y: 120,
		width: 600,
		height: 340,
		smartArtData: buildSmartArtPresetData(layout, items, (i) => newId(`node-${i}`)),
	};
}

function insert(): void {
	if (selectedLayout.value === null || nodeItems.value.length === 0) {
		return;
	}
	emit('insert', buildSmartArtElement(selectedLayout.value, nodeItems.value));
	emit('close');
}

function close(): void {
	emit('close');
}
</script>

<template>
	<ModalDialog :open="open" :title="t('pptx.smartArt.insertTitle')" @close="close">
		<div
			class="pptx-vue-smartart-dialog flex h-[min(60vh,440px)] w-[min(78vw,600px)] gap-3 max-md:h-[min(60dvh,440px)] max-md:w-full"
		>
			<!-- Category sidebar -->
			<nav
				class="pptx-vue-smartart-sidebar flex w-[130px] flex-shrink-0 flex-col gap-0.5 border-r border-border pr-2"
				:aria-label="t('pptx.smartArt.categoriesLabel')"
			>
				<button
					v-for="cat in CATEGORIES"
					:key="cat.id"
					type="button"
					class="pptx-vue-smartart-cat rounded px-2.5 py-1.5 text-left text-xs transition-colors"
					:class="
						activeCategory === cat.id
							? 'pptx-vue-smartart-cat--active bg-primary text-primary-foreground'
							: 'text-foreground hover:bg-muted'
					"
					@click="selectCategory(cat.id)"
				>
					{{ t(cat.labelKey) }}
				</button>
			</nav>

			<!-- Gallery + node-text entry -->
			<div class="pptx-vue-smartart-main flex min-w-0 flex-1 flex-col gap-2.5">
				<div
					class="pptx-vue-smartart-gallery grid flex-1 grid-cols-3 gap-2 overflow-y-auto pr-1"
					role="listbox"
					:aria-label="t('pptx.smartArt.layoutsLabel')"
				>
					<button
						v-for="preset in filteredPresets"
						:key="preset.layout"
						type="button"
						role="option"
						:aria-selected="selectedLayout === preset.layout"
						class="pptx-vue-smartart-tile flex flex-col items-center gap-1 rounded-md border p-2 transition-colors"
						:class="
							selectedLayout === preset.layout
								? 'pptx-vue-smartart-tile--active border-primary bg-primary/20'
								: 'border-border hover:bg-muted/50'
						"
						@click="selectLayout(preset.layout)"
						@dblclick="
							selectLayout(preset.layout);
							insert();
						"
					>
						<span
							class="pptx-vue-smartart-thumb flex h-12 w-16 items-center justify-center rounded bg-muted"
						>
							<SmartArtPreviews :layout="preset.layout" />
						</span>
						<span
							class="pptx-vue-smartart-tile-label text-center text-[10px] leading-tight text-foreground"
							>{{ t(preset.labelKey) }}</span
						>
					</button>
				</div>

				<label
					v-if="selectedLayout"
					class="pptx-vue-smartart-nodes flex flex-shrink-0 flex-col gap-1"
				>
					<span class="pptx-vue-smartart-nodes-label text-xs font-medium text-muted-foreground">{{
						t('pptx.smartArt.nodesLabel')
					}}</span>
					<textarea
						v-model="nodeText"
						class="pptx-vue-smartart-textarea w-full resize-y rounded border border-border bg-background px-2.5 py-2 text-[13px] text-foreground outline-none focus:border-primary focus:ring-1 focus:ring-primary"
						rows="5"
						spellcheck="false"
						:placeholder="t('pptx.smartArt.nodesPlaceholder')"
					/>
				</label>
			</div>
		</div>

		<template #footer>
			<DialogFooter
				:actions="[
					{ id: 'cancel', label: t('pptx.share.cancel') },
					{
						id: 'insert',
						label: t('pptx.smartArt.insert'),
						variant: 'primary',
						disabled: !canInsert,
					},
				]"
				@action="(id) => (id === 'insert' ? insert() : close())"
			/>
		</template>
	</ModalDialog>
</template>

// packages/react/src/viewer/components/InsertSmartArtDialog.tsx
import type { SmartArtLayout } from 'pptx-viewer-core';
import React, { useState, useCallback, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { LuX } from 'react-icons/lu';

import { useModalDismissDrag } from '../hooks';
import { useModalFocus } from '../hooks/useModalFocus';
import { cn } from '../utils';
import { DialogFooter } from './DialogFooter';
import type { SmartArtCategory } from './smart-art-presets';
import { PRESETS, CATEGORIES } from './smart-art-presets';
import { getPreviewForLayout } from './SmartArtPreviews';

// ── Dialog Component ────────────────────────────────────────────────────────

export interface InsertSmartArtDialogProps {
	isOpen: boolean;
	onClose: () => void;
	onInsert: (layout: SmartArtLayout, defaultItems: string[]) => void;
}

export function InsertSmartArtDialog({
	isOpen,
	onClose,
	onInsert,
}: InsertSmartArtDialogProps): React.ReactElement | null {
	const { t } = useTranslation();
	const { panelStyle, handlers: dragHandlers } = useModalDismissDrag(onClose);
	const [activeCategory, setActiveCategory] = useState<SmartArtCategory>('list');
	const [selectedLayout, setSelectedLayout] = useState<SmartArtLayout | null>(null);
	const dialogRef = useRef<HTMLDivElement>(null);
	useModalFocus(isOpen, dialogRef, onClose);

	const filteredPresets = PRESETS.filter((p) => p.category === activeCategory);

	const handleInsert = useCallback(() => {
		if (!selectedLayout) {
			return;
		}
		const preset = PRESETS.find((p) => p.layout === selectedLayout);
		if (!preset) {
			return;
		}
		onInsert(preset.layout, preset.defaultItems);
		onClose();
	}, [selectedLayout, onInsert, onClose]);

	if (!isOpen) {
		return null;
	}

	return (
		<>
			{/* Backdrop */}
			<button
				type='button'
				style={{ zIndex: 1200 }}
				className='fixed inset-0 bg-black/50'
				onClick={onClose}
				aria-label={t('pptx.smartart.close')}
			/>

			{/* Dialog */}
			<div
				style={{ zIndex: 1201 }}
				className='fixed inset-0 flex items-center justify-center pointer-events-none'
			>
				<div
					ref={dialogRef}
					style={panelStyle}
					className='pointer-events-auto w-[600px] max-w-[90vw] max-h-[80vh] rounded-lg border border-border bg-background shadow-2xl flex flex-col max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:w-full max-md:max-w-none max-md:max-h-[88dvh] max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'
					role='dialog'
					aria-modal='true'
					aria-label={t('pptx.smartart.insertTitle')}
					tabIndex={-1}
				>
					{/* Header — also a swipe-down-to-dismiss grab region on touch. */}
					<div
						{...dragHandlers}
						className='flex items-center justify-between px-4 py-3 border-b border-border touch-none'
					>
						<h2 className='text-sm font-medium text-foreground'>
							{t('pptx.smartart.insertTitle')}
						</h2>
						<button
							type='button'
							onClick={onClose}
							className='p-1 rounded hover:bg-muted transition-colors'
							aria-label={t('pptx.smartart.close')}
						>
							<LuX className='w-4 h-4' />
						</button>
					</div>

					{/* Body */}
					<div className='flex flex-1 overflow-hidden'>
						{/* Category sidebar */}
						<nav
							className='w-40 border-r border-border py-2'
							aria-label={t('pptx.insertSmartArt.categories')}
						>
							{CATEGORIES.map((cat) => (
								<button
									key={cat.id}
									type='button'
									onClick={() => {
										setActiveCategory(cat.id);
										setSelectedLayout(null);
									}}
									className={cn(
										'w-full text-left px-3 py-1.5 text-xs transition-colors',
										activeCategory === cat.id
											? 'bg-primary text-white'
											: 'text-foreground hover:bg-muted',
									)}
								>
									{t(cat.label)}
								</button>
							))}
						</nav>

						{/* Gallery grid */}
						<div className='flex-1 p-3 overflow-y-auto'>
							<div
								className='grid grid-cols-3 gap-2'
								role='listbox'
								aria-label={t('pptx.insertSmartArt.layouts')}
							>
								{filteredPresets.map((preset) => (
									<button
										key={preset.layout}
										type='button'
										role='option'
										aria-selected={selectedLayout === preset.layout}
										onClick={() => setSelectedLayout(preset.layout)}
										onDoubleClick={() => {
											setSelectedLayout(preset.layout);
											onInsert(preset.layout, preset.defaultItems);
											onClose();
										}}
										className={cn(
											'flex flex-col items-center gap-1 p-2 rounded border transition-colors',
											selectedLayout === preset.layout
												? 'border-primary bg-primary/20'
												: 'border-border hover:border-border hover:bg-muted/50',
										)}
									>
										<div className='w-16 h-12 flex items-center justify-center bg-muted rounded'>
											{getPreviewForLayout(preset.layout)}
										</div>
										<span className='text-[10px] text-foreground text-center leading-tight'>
											{t(preset.labelKey)}
										</span>
									</button>
								))}
							</div>
						</div>
					</div>

					{/* Footer */}
					<div className='flex items-center justify-end gap-2 px-4 py-3 border-t border-border'>
						<DialogFooter
							actions={[
								{ id: 'cancel', label: t('pptx.smartart.cancel') },
								{
									id: 'insert',
									label: t('pptx.smartart.insert'),
									variant: 'primary',
									disabled: !selectedLayout,
								},
							]}
							onAction={(id) => (id === 'insert' ? handleInsert() : onClose())}
						/>
					</div>
				</div>
			</div>
		</>
	);
}
