// packages/svelte/src/viewer/components/NotesMasterPanel.svelte
<script lang="ts">
	import type { PptxNotesMaster } from 'pptx-viewer-core';
	import { useTranslator } from '../../i18n/context';

	const { notesMaster, onchange } = $props<{
		notesMaster: PptxNotesMaster | undefined;
		onchange: (color: string) => void;
	}>();
	const t = useTranslator();
	const labels: Record<string, string> = {
		body: 'pptx.master.notesMasterBody', sldImg: 'pptx.master.notesMasterSlideImage',
		hdr: 'pptx.master.notesMasterHeader', ftr: 'pptx.master.notesMasterFooter',
		dt: 'pptx.master.notesMasterDate', sldNum: 'pptx.master.notesMasterPageNumber',
	};
</script>

{#if notesMaster}
	<section class="panel" data-testid="notes-master-panel">
		<div class="label">{t('pptx.master.notesMasterBackground')}</div>
		<input type="color" class="swatch" aria-label="Master background color" value={notesMaster.backgroundColor ?? '#ffffff'} oninput={(event) => onchange(event.currentTarget.value)} />
		<div class="label">{t('pptx.master.notesMasterPlaceholders')}</div>
		{#each notesMaster.placeholders ?? [] as placeholder (`${placeholder.type}-${placeholder.idx ?? 'default'}`)}
			<div class="placeholder"><i></i>{t(labels[placeholder.type] ?? placeholder.type)}</div>
		{:else}<small>{t('pptx.master.noPlaceholders')}</small>{/each}
	</section>
{:else}<p class="empty">{t('pptx.master.noNotesMaster')}</p>{/if}

<style>
	.panel { display:flex; flex-direction:column; gap:6px; padding:6px; }
	.label, small { color:var(--pptx-muted-foreground,#a5a5b5); font-size:10px; }
	.swatch { height:32px; border:1px solid var(--pptx-border,#33334d); border-radius:5px; }
	.placeholder { display:flex; align-items:center; gap:7px; padding:5px; border-radius:4px; background:var(--pptx-background,#11111b); font-size:10px; }
	i { width:8px; height:8px; border-radius:50%; background:#22c55e99; }
	.empty { padding:12px; color:var(--pptx-muted-foreground,#a5a5b5); font-size:12px; text-align:center; }
</style>

// packages/react/src/viewer/components/NotesMasterPanel.tsx
import React, { useMemo } from "react";
import { useTranslation } from "react-i18next";

import type { PptxNotesMaster } from "pptx-viewer-core";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface NotesMasterPanelProps {
  notesMaster: PptxNotesMaster | undefined;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function NotesMasterPanel({
  notesMaster,
}: NotesMasterPanelProps): React.ReactElement {
  const { t } = useTranslation();

  const placeholderLabels = useMemo(() => {
    if (!notesMaster?.placeholders) return [];
    return notesMaster.placeholders.map((ph) => {
      const typeLabel =
        ph.type === "body"
          ? t("pptx.master.notesMasterBody")
          : ph.type === "sldImg"
            ? t("pptx.master.notesMasterSlideImage")
            : ph.type === "hdr"
              ? t("pptx.master.notesMasterHeader")
              : ph.type === "ftr"
                ? t("pptx.master.notesMasterFooter")
                : ph.type === "dt"
                  ? t("pptx.master.notesMasterDate")
                  : ph.type === "sldNum"
                    ? t("pptx.master.notesMasterPageNumber")
                    : ph.type;
      return { type: ph.type, label: typeLabel, idx: ph.idx };
    });
  }, [notesMaster?.placeholders, t]);

  if (!notesMaster) {
    return (
      <div className="px-2 py-4 text-center text-xs text-muted-foreground">
        {t("pptx.master.noNotesMaster")}
      </div>
    );
  }

  return (
    <div className="space-y-2 px-1">
      {/* Background info */}
      <div className="rounded-md border border-border/60 bg-muted/40 p-2">
        <div className="text-[10px] text-muted-foreground mb-1">
          {t("pptx.master.notesMasterBackground")}
        </div>
        <div
          className="w-full h-8 rounded border border-border"
          style={{ backgroundColor: notesMaster.backgroundColor ?? "#ffffff" }}
        />
      </div>

      {/* Placeholder list */}
      <div className="rounded-md border border-border/60 bg-muted/40 p-2">
        <div className="text-[10px] text-muted-foreground mb-1.5">
          {t("pptx.master.notesMasterPlaceholders")}
        </div>
        {placeholderLabels.length > 0 ? (
          <div className="space-y-1">
            {placeholderLabels.map((ph) => (
              <div
                key={`${ph.type}-${ph.idx ?? "default"}`}
                className="flex items-center gap-2 rounded px-1.5 py-1 bg-background/50 text-[10px] text-foreground"
              >
                <span className="w-2 h-2 rounded-full bg-green-500/60 flex-shrink-0" />
                {ph.label}
              </div>
            ))}
          </div>
        ) : (
          <div className="text-[10px] text-muted-foreground">
            {t("pptx.master.noPlaceholders")}
          </div>
        )}
      </div>
    </div>
  );
}
