// packages/svelte/src/viewer/components/ribbon/file/PasswordProtectionDialog.svelte
<script lang="ts">
	import DialogFooter from '../../DialogFooter.svelte';
	import CheckCircle2 from '@lucide/svelte/icons/check-circle-2';
	import LockKeyhole from '@lucide/svelte/icons/lock-keyhole';
	import X from '@lucide/svelte/icons/x';
	import { getPasswordStrength, validatePasswordPair } from 'pptx-viewer-shared';

	import { useTranslator } from '../../../../i18n/context';

	const { protected: isProtected, onset, onremove, onclose }: { protected: boolean; onset: (password: string) => void; onremove: () => void; onclose: () => void } = $props();
	const t = useTranslator();
	// eslint-disable-next-line prefer-const
	let password = $state('');
	// eslint-disable-next-line prefer-const
	let confirmation = $state('');
	// eslint-disable-next-line prefer-const
	let visible = $state(false);
	let error = $state('');
	const strength = $derived(getPasswordStrength(password));
	const labels = $derived([t('pptx.security.strengthVeryWeak'), t('pptx.security.strengthWeak'), t('pptx.security.strengthFair'), t('pptx.security.strengthStrong'), t('pptx.security.strengthVeryStrong')]);
	const colors = ['#ef4444','#f97316','#eab308','#84cc16','#22c55e'];

	function submit(): void {
		const validation = validatePasswordPair(password, confirmation);
		if (validation) {
			error = t(validation === 'required' ? 'pptx.security.errorPasswordRequired' : validation === 'mismatch' ? 'pptx.security.errorPasswordMismatch' : 'pptx.security.errorPasswordTooShort');
			return;
		}
		onset(password);
		onclose();
	}
</script>

<div class="backdrop">
	<button class="scrim" type="button" aria-label={t('pptx.common.close')} onclick={onclose}></button>
	<div class="panel" role="dialog" aria-modal="true" aria-labelledby="pptx-svelte-password-title">
		<header><div><span><LockKeyhole size={18} strokeWidth={1.8} aria-hidden="true" /></span><h2 id="pptx-svelte-password-title">{t('pptx.security.protectPresentation')}</h2></div><button type="button" aria-label={t('pptx.common.close')} onclick={onclose}><X size={16} aria-hidden="true" /></button></header>
		<div class="body">
			{#if isProtected}<p class="protected"><CheckCircle2 size={15} aria-hidden="true" /> {t('pptx.security.currentlyProtected')}</p>{/if}
			<p class="description">{t('pptx.security.description')}</p>
			<label><span>{t('pptx.security.password')}</span><div class="password"><input type={visible ? 'text' : 'password'} bind:value={password} oninput={() => (error = '')} /><button type="button" onclick={() => (visible = !visible)}>{visible ? t('pptx.security.hidePassword') : t('pptx.security.showPassword')}</button></div></label>
			{#if password}<div class="strength"><div>{#each Array(5) as _, index}<i style:background={index <= strength ? colors[strength] : 'var(--pptx-accent,#3f3f52)'}></i>{/each}</div><small>{labels[strength]}</small></div>{/if}
			<label><span>{t('pptx.security.confirmPassword')}</span><input type={visible ? 'text' : 'password'} bind:value={confirmation} oninput={() => (error = '')} /></label>
			{#if error}<p class="error" role="alert">{error}</p>{/if}
		</div>
		<footer><DialogFooter actions={[
			...(isProtected ? [{ id: 'remove', label: t('pptx.security.removePassword'), variant: 'danger' as const, align: 'start' as const }] : []),
			{ id: 'cancel', label: t('pptx.common.cancel') },
			{ id: 'submit', label: t(isProtected ? 'pptx.security.updatePassword' : 'pptx.security.setPassword'), variant: 'primary' },
		]} onaction={(id) => { if (id === 'remove') { onremove(); onclose(); } else if (id === 'submit') { submit(); } else { onclose(); } }} /></footer>
	</div>
</div>

<style>
	.backdrop{position:fixed;inset:0;z-index:90;display:grid;place-items:center;background:#0009}.scrim{position:absolute;inset:0;width:100%;height:100%;border:0;background:transparent}.panel{position:relative;width:min(420px,calc(100vw - 32px));border:1px solid var(--pptx-border,#3f3f52);border-radius:12px;background:var(--pptx-card,#1e1e2e);color:var(--pptx-card-foreground,#e2e8f0);box-shadow:0 24px 80px #0008}header,footer{display:flex;align-items:center;gap:8px;padding:14px 18px;border-bottom:1px solid var(--pptx-border,#3f3f52)}header{justify-content:space-between}header div{display:flex;align-items:center;gap:9px}header span{color:var(--pptx-primary,#c43b32)}h2,p{margin:0}h2{font-size:14px}.body{display:grid;gap:13px;padding:18px}.description,label{font-size:12px}.description,label span,small{color:var(--pptx-muted-foreground,#94a3b8)}label{display:grid;gap:5px}.password{display:flex}.password input{min-width:0;flex:1;border-radius:6px 0 0 6px}.password button{border-radius:0 6px 6px 0}input,button{border:1px solid var(--pptx-border,#3f3f52);padding:7px 9px;background:var(--pptx-muted,#2a2a3d);color:inherit}input{border-radius:6px}.protected{padding:9px;border:1px solid #15803d66;border-radius:7px;background:#14532d33;color:#86efac;font-size:12px}.strength div{display:flex;gap:4px}.strength i{height:4px;flex:1;border-radius:4px}.error{color:#f87171;font-size:11px}footer{border-top:1px solid var(--pptx-border,#3f3f52);border-bottom:0}@media(max-width:600px){.panel{position:fixed;inset:auto 0 0;width:100%;border-radius:16px 16px 0 0}}
</style>

// packages/react/src/viewer/components/PasswordProtectionDialog.tsx
import React, { useState, useCallback, useMemo, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { LuLock, LuShieldCheck, LuX, LuEye, LuEyeOff } from 'react-icons/lu';

import { useModalFocus } from '../hooks/useModalFocus';
import { DialogFooter } from './DialogFooter';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PasswordProtectionDialogProps {
	isOpen: boolean;
	isCurrentlyProtected: boolean;
	onClose: () => void;
	onSetPassword: (password: string) => void;
	onRemovePassword: () => void;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Returns a strength score 0-4 for a password. */
function getPasswordStrength(password: string): number {
	if (!password) {
		return 0;
	}
	let score = 0;
	if (password.length >= 8) {
		score++;
	}
	if (password.length >= 12) {
		score++;
	}
	if (/[A-Z]/u.test(password) && /[a-z]/u.test(password)) {
		score++;
	}
	if (/\d/u.test(password)) {
		score++;
	}
	if (/[^A-Za-z0-9]/u.test(password)) {
		score++;
	}
	return Math.min(score, 4);
}

const STRENGTH_COLORS = [
	'bg-red-500',
	'bg-orange-500',
	'bg-yellow-500',
	'bg-lime-500',
	'bg-green-500',
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function PasswordProtectionDialog({
	isOpen,
	isCurrentlyProtected,
	onClose,
	onSetPassword,
	onRemovePassword,
}: PasswordProtectionDialogProps): React.ReactElement | null {
	const { t } = useTranslation();

	const [password, setPassword] = useState('');
	const [confirmPassword, setConfirmPassword] = useState('');
	const [showPassword, setShowPassword] = useState(false);
	const [error, setError] = useState('');
	const dialogRef = useRef<HTMLDivElement>(null);
	const passwordRef = useRef<HTMLInputElement>(null);

	const strength = useMemo(() => getPasswordStrength(password), [password]);

	const strengthLabel = useMemo(() => {
		const labels = [
			t('pptx.security.strengthVeryWeak'),
			t('pptx.security.strengthWeak'),
			t('pptx.security.strengthFair'),
			t('pptx.security.strengthStrong'),
			t('pptx.security.strengthVeryStrong'),
		];
		return password ? labels[strength] : '';
	}, [strength, password, t]);

	const handleSubmit = useCallback(() => {
		setError('');
		if (!password) {
			setError(t('pptx.security.errorPasswordRequired'));
			return;
		}
		if (password !== confirmPassword) {
			setError(t('pptx.security.errorPasswordMismatch'));
			return;
		}
		if (password.length < 4) {
			setError(t('pptx.security.errorPasswordTooShort'));
			return;
		}
		onSetPassword(password);
		setPassword('');
		setConfirmPassword('');
		onClose();
	}, [password, confirmPassword, onSetPassword, onClose, t]);

	const handleRemove = useCallback(() => {
		onRemovePassword();
		setPassword('');
		setConfirmPassword('');
		onClose();
	}, [onRemovePassword, onClose]);

	const handleClose = useCallback(() => {
		setPassword('');
		setConfirmPassword('');
		setError('');
		onClose();
	}, [onClose]);
	useModalFocus(isOpen, dialogRef, handleClose, passwordRef);

	if (!isOpen) {
		return null;
	}

	return (
		<>
			{/* Backdrop */}
			<button
				type='button'
				style={{ zIndex: 1200 }}
				className='fixed inset-0 bg-black/60'
				aria-label={t('pptx.common.close')}
				onClick={handleClose}
			/>
			{/* Dialog */}
			<div
				style={{ zIndex: 1201 }}
				className='fixed inset-0 flex items-center justify-center pointer-events-none'
			>
				<div
					ref={dialogRef}
					role='dialog'
					aria-modal='true'
					aria-labelledby='pptx-password-title'
					tabIndex={-1}
					className='pointer-events-auto w-[420px] overscroll-contain rounded-xl border border-border bg-popover backdrop-blur-xl shadow-2xl max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:w-full max-md:max-h-[88dvh] max-md:overflow-y-auto max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'
				>
					{/* Header */}
					<div className='flex items-center justify-between px-5 py-4 border-b border-border/60'>
						<div className='flex items-center gap-2'>
							<LuLock className='w-5 h-5 text-primary' aria-hidden='true' />
							<h2 id='pptx-password-title' className='text-sm font-semibold text-foreground'>
								{t('pptx.security.protectPresentation')}
							</h2>
						</div>
						<button
							type='button'
							onClick={handleClose}
							className='p-1 rounded hover:bg-accent transition-colors'
							aria-label={t('pptx.common.close')}
						>
							<LuX className='w-4 h-4 text-muted-foreground' aria-hidden='true' />
						</button>
					</div>

					{/* Body */}
					<div className='px-5 py-4 space-y-4'>
						{isCurrentlyProtected && (
							<div className='flex items-center gap-2 rounded-lg bg-green-900/30 border border-green-700/40 px-3 py-2'>
								<LuShieldCheck className='w-4 h-4 text-green-400 shrink-0' aria-hidden='true' />
								<span className='text-xs text-green-300'>
									{t('pptx.security.currentlyProtected')}
								</span>
							</div>
						)}

						<p className='text-xs text-muted-foreground'>{t('pptx.security.description')}</p>

						{/* Password field */}
						<div>
							<label htmlFor='pptx-password' className='block text-xs text-foreground mb-1'>
								{t('pptx.security.password')}
							</label>
							<div className='relative'>
								<input
									ref={passwordRef}
									id='pptx-password'
									name='presentation-password'
									autoComplete='new-password'
									aria-invalid={Boolean(error)}
									aria-describedby={error ? 'pptx-password-error' : 'pptx-password-strength'}
									type={showPassword ? 'text' : 'password'}
									className='w-full rounded-lg border border-border bg-muted px-3 py-2 text-sm text-foreground placeholder-muted-foreground focus:border-primary focus:ring-1 focus:ring-primary outline-none'
									placeholder={t('pptx.security.passwordPlaceholder')}
									value={password}
									onChange={(e) => {
										setPassword(e.target.value);
										setError('');
									}}
								/>
								<button
									type='button'
									onClick={() => setShowPassword(!showPassword)}
									className='absolute right-2 top-1/2 -translate-y-1/2 p-1 text-muted-foreground hover:text-foreground'
									aria-label={
										showPassword ? t('pptx.security.hidePassword') : t('pptx.security.showPassword')
									}
								>
									{showPassword ? (
										<LuEyeOff className='w-4 h-4' aria-hidden='true' />
									) : (
										<LuEye className='w-4 h-4' aria-hidden='true' />
									)}
								</button>
							</div>
						</div>

						{/* Strength indicator */}
						{password && (
							<div className='space-y-1'>
								<div className='flex gap-1'>
									{Array.from({ length: 5 }).map((_, i) => (
										<div
											key={`str-${i}`}
											className={`h-1 flex-1 rounded-full transition-colors ${
												i <= strength ? STRENGTH_COLORS[strength] : 'bg-accent'
											}`}
										/>
									))}
								</div>
								<p
									id='pptx-password-strength'
									className='text-[11px] text-muted-foreground'
									role='status'
									aria-live='polite'
								>
									{strengthLabel}
								</p>
							</div>
						)}

						{/* Confirm password */}
						<div>
							<label htmlFor='pptx-password-confirm' className='block text-xs text-foreground mb-1'>
								{t('pptx.security.confirmPassword')}
							</label>
							<input
								id='pptx-password-confirm'
								name='presentation-password-confirmation'
								autoComplete='new-password'
								aria-invalid={Boolean(error)}
								aria-describedby={error ? 'pptx-password-error' : undefined}
								type={showPassword ? 'text' : 'password'}
								className='w-full rounded-lg border border-border bg-muted px-3 py-2 text-sm text-foreground placeholder-muted-foreground focus:border-primary focus:ring-1 focus:ring-primary outline-none'
								placeholder={t('pptx.security.confirmPasswordPlaceholder')}
								value={confirmPassword}
								onChange={(e) => {
									setConfirmPassword(e.target.value);
									setError('');
								}}
							/>
						</div>

						{/* Error */}
						{error && (
							<p id='pptx-password-error' className='text-xs text-red-400' role='alert'>
								{error}
							</p>
						)}
					</div>

					{/* Footer */}
					<div className='flex items-center justify-between px-5 py-3 border-t border-border/60'>
						<DialogFooter
							actions={[
								...(isCurrentlyProtected
									? [
											{
												id: 'remove',
												label: t('pptx.security.removePassword'),
												variant: 'danger' as const,
												align: 'start' as const,
											},
										]
									: []),
								{ id: 'cancel', label: t('pptx.common.cancel') },
								{
									id: 'submit',
									label: isCurrentlyProtected
										? t('pptx.security.updatePassword')
										: t('pptx.security.setPassword'),
									variant: 'primary',
								},
							]}
							onAction={(id) =>
								id === 'remove' ? handleRemove() : id === 'submit' ? handleSubmit() : handleClose()
							}
						/>
					</div>
				</div>
			</div>
		</>
	);
}
