// packages/svelte/src/viewer/components/PresentationContextMenu.svelte
<script lang="ts">
	/**
	 * The slide-show right-click menu, shown while presenting when Options >
	 * Advanced > "Show menu on right mouse click" is on: Previous / Next /
	 * End Show, PowerPoint style.
	 */
	import { useTranslator } from '../../i18n/context';

	const {
		x,
		y,
		onprev,
		onnext,
		onend,
		onclose,
	}: {
		x: number;
		y: number;
		onprev: () => void;
		onnext: () => void;
		onend: () => void;
		onclose: () => void;
	} = $props();
	const t = useTranslator();

	function run(action: () => void): void {
		action();
		onclose();
	}
</script>

<button class="scrim" type="button" aria-label={t('pptx.settings.close')} onclick={onclose} oncontextmenu={(event) => { event.preventDefault(); onclose(); }}></button>
<div class="menu" role="menu" style={`left:${x}px;top:${y}px`}>
	<button type="button" role="menuitem" onclick={() => run(onprev)}>{t('pptx.presenter.previousSlide')}</button>
	<button type="button" role="menuitem" onclick={() => run(onnext)}>{t('pptx.presenter.nextSlide')}</button>
	<hr />
	<button type="button" role="menuitem" onclick={() => run(onend)}>{t('pptx.presenter.endPresentation')}</button>
</div>

<style>
	.scrim { position: fixed; inset: 0; z-index: 95; border: 0; background: transparent; }
	.menu { position: fixed; z-index: 96; display: flex; min-width: 168px; flex-direction: column; border: 1px solid var(--pptx-border, #3f3f52); border-radius: 7px; background: var(--pptx-popover, #1e1e2e); box-shadow: 0 14px 28px #0008; padding: 4px; }
	.menu button { border: 0; border-radius: 4px; padding: 7px 12px; background: transparent; color: var(--pptx-popover-foreground, #e2e8f0); font: 12px system-ui, sans-serif; text-align: left; cursor: pointer; }
	.menu button:hover { background: var(--pptx-accent, #33334d); }
	hr { margin: 3px 4px; border: 0; border-top: 1px solid var(--pptx-border, #3f3f52); }
</style>

// packages/react/src/viewer/components/PresentationContextMenu.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';

export interface PresentationContextMenuState {
	x: number;
	y: number;
}

export interface PresentationContextMenuProps {
	state: PresentationContextMenuState;
	onNext: () => void;
	onPrevious: () => void;
	onEndShow: () => void;
	onClose: () => void;
}

const itemClass =
	'block w-full whitespace-nowrap px-3 py-1.5 text-left text-xs text-foreground transition-colors hover:bg-accent';

/**
 * Slide-show right-click menu (Next / Previous / End Show), shown while
 * presenting when Options > Advanced > "Show menu on right mouse click"
 * is on. Mirrors PowerPoint's minimal slideshow menu.
 */
export function PresentationContextMenu(p: PresentationContextMenuProps): React.ReactElement {
	const { t } = useTranslation();
	const run = (action: () => void) => {
		action();
		p.onClose();
	};
	return (
		<>
			{/* Transparent backdrop: any press outside the menu dismisses it. */}
			<div
				className='fixed inset-0 z-[1299]'
				onClick={p.onClose}
				onContextMenu={(e) => {
					e.preventDefault();
					p.onClose();
				}}
			/>
			<div
				data-pptx-presentation-menu=''
				role='menu'
				tabIndex={-1}
				className='fixed z-[1300] min-w-[160px] rounded-md border border-border bg-popover py-1 shadow-xl'
				style={{ left: p.state.x, top: p.state.y }}
				onContextMenu={(e) => e.preventDefault()}
			>
				<button type='button' role='menuitem' className={itemClass} onClick={() => run(p.onNext)}>
					{t('pptx.presenter.nextSlide')}
				</button>
				<button
					type='button'
					role='menuitem'
					className={itemClass}
					onClick={() => run(p.onPrevious)}
				>
					{t('pptx.presenter.previousSlide')}
				</button>
				<div className='my-1 border-t border-border/60' />
				<button
					type='button'
					role='menuitem'
					className={itemClass}
					onClick={() => run(p.onEndShow)}
				>
					{t('pptx.presenter.endPresentation')}
				</button>
			</div>
		</>
	);
}
