// packages/vue/src/viewer/components/PresentationAnnotationOverlay.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import { computed, ref } from 'vue';

import type {
	AnnotationStroke,
	LaserPosition,
	PresentationTool,
} from '../composables/usePresentationAnnotations';
import { buildStrokePathD } from '../composables/usePresentationAnnotations';
import type { CanvasSize } from '../types';

/**
 * PresentationAnnotationOverlay — transparent SVG overlay drawn on top of the
 * slide during presentation mode. Captures pointer events for the
 * pen/highlighter/eraser tools and renders the laser-pointer dot. Vue port of
 * the React `PresentationAnnotationOverlay`.
 *
 * Coordinate conversion divides client coordinates by `editorScale` so emitted
 * points are in the slide's unscaled coordinate space (matching
 * `usePresentationAnnotations`). Renders `null` (nothing) when the tool is
 * `'none'`.
 */
const props = defineProps<{
	canvasSize: CanvasSize;
	editorScale: number;
	presentationTool: PresentationTool;
	annotationStrokes: AnnotationStroke[];
	currentStroke: AnnotationStroke | null;
	laserPosition: LaserPosition | null;
}>();

const emit = defineEmits<{
	(e: 'pointer-down', x: number, y: number): void;
	(e: 'pointer-move', x: number, y: number): void;
	(e: 'pointer-up'): void;
	(e: 'laser-move', x: number, y: number): void;
	(e: 'laser-leave'): void;
	(e: 'erase', x: number, y: number): void;
}>();

const svgRef = ref<SVGSVGElement | null>(null);
let isErasing = false;

function toSlideCoords(clientX: number, clientY: number): { x: number; y: number } | null {
	const svg = svgRef.value;
	if (!svg) {
		return null;
	}
	const rect = svg.getBoundingClientRect();
	return {
		x: (clientX - rect.left) / props.editorScale,
		y: (clientY - rect.top) / props.editorScale,
	};
}

function onPointerDown(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	event.preventDefault();
	event.stopPropagation();
	const coords = toSlideCoords(event.clientX, event.clientY);
	if (!coords) {
		return;
	}
	if (props.presentationTool === 'eraser') {
		isErasing = true;
		emit('erase', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'pen' || props.presentationTool === 'highlighter') {
		emit('pointer-down', coords.x, coords.y);
	}
}

function onPointerMove(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	const coords = toSlideCoords(event.clientX, event.clientY);
	if (!coords) {
		return;
	}
	if (props.presentationTool === 'laser') {
		emit('laser-move', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'eraser' && isErasing) {
		emit('erase', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'pen' || props.presentationTool === 'highlighter') {
		emit('pointer-move', coords.x, coords.y);
	}
}

function onPointerUp(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	event.preventDefault();
	if (props.presentationTool === 'eraser') {
		isErasing = false;
		return;
	}
	emit('pointer-up');
}

function onPointerLeave(): void {
	if (props.presentationTool === 'laser') {
		emit('laser-leave');
	}
	if (props.presentationTool === 'eraser') {
		isErasing = false;
	}
	emit('pointer-up');
}

const cursor = computed<string>(() => {
	switch (props.presentationTool) {
		case 'laser':
			return 'none';
		case 'pen':
		case 'highlighter':
		case 'eraser':
			return 'crosshair';
		default:
			return 'default';
	}
});

const allStrokes = computed<AnnotationStroke[]>(() =>
	props.currentStroke ? [...props.annotationStrokes, props.currentStroke] : props.annotationStrokes,
);

const svgStyle = computed<CSSProperties>(() => ({
	position: 'absolute',
	width: `${props.canvasSize.width}px`,
	height: `${props.canvasSize.height}px`,
	transformOrigin: 'top left',
	transform: `scale(${props.editorScale})`,
}));

const laserStyle = computed<CSSProperties | undefined>(() => {
	if (props.presentationTool !== 'laser' || !props.laserPosition) {
		return undefined;
	}
	return {
		position: 'absolute',
		width: '24px',
		height: '24px',
		left: `${props.laserPosition.x * props.editorScale - 12}px`,
		top: `${props.laserPosition.y * props.editorScale - 12}px`,
		backgroundColor: 'rgba(255, 0, 0, 0.85)',
		boxShadow: '0 0 12px 6px rgba(255, 0, 0, 0.5), 0 0 24px 12px rgba(255, 0, 0, 0.25)',
		filter: 'drop-shadow(0 0 8px rgba(255, 0, 0, 0.7))',
		borderRadius: '50%',
		pointerEvents: 'none',
		zIndex: 70,
	};
});
</script>

<template>
	<div v-if="presentationTool !== 'none'" class="pptx-vue-annotation-overlay" :style="{ cursor }">
		<svg
			ref="svgRef"
			:style="svgStyle"
			:viewBox="`0 0 ${canvasSize.width} ${canvasSize.height}`"
			@pointerdown="onPointerDown"
			@pointermove="onPointerMove"
			@pointerup="onPointerUp"
			@pointerleave="onPointerLeave"
		>
			<path
				v-for="stroke in allStrokes"
				:key="stroke.id"
				:d="buildStrokePathD(stroke.points)"
				fill="none"
				:stroke="stroke.color"
				:stroke-width="stroke.width"
				:opacity="stroke.opacity"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</svg>
		<div v-if="laserStyle" class="pptx-vue-annotation-laser" :style="laserStyle" />
	</div>
</template>

<style scoped>
.pptx-vue-annotation-overlay {
	position: absolute;
	inset: 0;
	z-index: 60;
	pointer-events: auto;
}
</style>

// packages/react/src/viewer/components/PresentationAnnotationOverlay.tsx
/**
 * PresentationAnnotationOverlay
 *
 * Transparent SVG overlay rendered on top of the slide during presentation
 * mode. Captures pointer events for pen/highlighter/eraser tools and
 * displays the laser pointer dot.
 */
import React, { useCallback, useRef } from 'react';

import type {
	AnnotationStroke,
	LaserPosition,
	PresentationTool,
} from '../hooks/usePresentationAnnotations';
import type { CanvasSize } from '../types';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface PresentationAnnotationOverlayProps {
	canvasSize: CanvasSize;
	editorScale: number;
	presentationTool: PresentationTool;
	annotationStrokes: AnnotationStroke[];
	currentStroke: AnnotationStroke | null;
	laserPosition: LaserPosition | null;
	onPointerDown: (x: number, y: number) => void;
	onPointerMove: (x: number, y: number) => void;
	onPointerUp: () => void;
	onLaserMove: (x: number, y: number) => void;
	onLaserLeave: () => void;
	onEraseAtPoint: (x: number, y: number) => void;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildPathD(points: Array<{ x: number; y: number }>): string {
	if (points.length === 0) {
		return '';
	}
	const first = points[0];
	let d = `M ${first.x} ${first.y}`;
	for (let i = 1; i < points.length; i++) {
		const pt = points[i];
		d += ` L ${pt.x} ${pt.y}`;
	}
	return d;
}

function getCursorForTool(tool: PresentationTool): string {
	switch (tool) {
		case 'laser':
			return 'none';
		case 'pen':
			return 'crosshair';
		case 'highlighter':
			return 'crosshair';
		case 'eraser':
			return 'crosshair';
		default:
			return 'default';
	}
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function PresentationAnnotationOverlay({
	canvasSize,
	editorScale,
	presentationTool,
	annotationStrokes,
	currentStroke,
	laserPosition,
	onPointerDown,
	onPointerMove,
	onPointerUp,
	onLaserMove,
	onLaserLeave,
	onEraseAtPoint,
}: PresentationAnnotationOverlayProps): React.ReactElement | null {
	const svgRef = useRef<SVGSVGElement>(null);
	const isErasingRef = useRef(false);

	const toSlideCoords = useCallback(
		(clientX: number, clientY: number): { x: number; y: number } | null => {
			const svg = svgRef.current;
			if (!svg) {
				return null;
			}
			const rect = svg.getBoundingClientRect();
			const x = (clientX - rect.left) / editorScale;
			const y = (clientY - rect.top) / editorScale;
			return { x, y };
		},
		[editorScale],
	);

	const handlePointerDown = useCallback(
		(e: React.PointerEvent) => {
			if (presentationTool === 'none') {
				return;
			}
			e.preventDefault();
			e.stopPropagation();
			const coords = toSlideCoords(e.clientX, e.clientY);
			if (!coords) {
				return;
			}

			if (presentationTool === 'eraser') {
				isErasingRef.current = true;
				onEraseAtPoint(coords.x, coords.y);
				return;
			}
			if (presentationTool === 'pen' || presentationTool === 'highlighter') {
				onPointerDown(coords.x, coords.y);
			}
		},
		[presentationTool, toSlideCoords, onPointerDown, onEraseAtPoint],
	);

	const handlePointerMove = useCallback(
		(e: React.PointerEvent) => {
			if (presentationTool === 'none') {
				return;
			}
			const coords = toSlideCoords(e.clientX, e.clientY);
			if (!coords) {
				return;
			}

			if (presentationTool === 'laser') {
				onLaserMove(coords.x, coords.y);
				return;
			}
			if (presentationTool === 'eraser' && isErasingRef.current) {
				onEraseAtPoint(coords.x, coords.y);
				return;
			}
			if (presentationTool === 'pen' || presentationTool === 'highlighter') {
				onPointerMove(coords.x, coords.y);
			}
		},
		[presentationTool, toSlideCoords, onPointerMove, onLaserMove, onEraseAtPoint],
	);

	const handlePointerUp = useCallback(
		(e: React.PointerEvent) => {
			if (presentationTool === 'none') {
				return;
			}
			e.preventDefault();
			if (presentationTool === 'eraser') {
				isErasingRef.current = false;
				return;
			}
			onPointerUp();
		},
		[presentationTool, onPointerUp],
	);

	const handlePointerLeave = useCallback(() => {
		if (presentationTool === 'laser') {
			onLaserLeave();
		}
		if (presentationTool === 'eraser') {
			isErasingRef.current = false;
		}
		onPointerUp();
	}, [presentationTool, onLaserLeave, onPointerUp]);

	const allStrokes = currentStroke ? [...annotationStrokes, currentStroke] : annotationStrokes;

	// With no tool selected the overlay still paints existing ink; PowerPoint
	// keeps annotations on screen after you switch back to the arrow pointer.
	// It just stops intercepting pointer events so clicks advance the slide.
	const isCapturing = presentationTool !== 'none';
	if (!isCapturing && allStrokes.length === 0) {
		return null;
	}

	return (
		<div
			className='absolute inset-0'
			style={{
				zIndex: 60,
				cursor: getCursorForTool(presentationTool),
				pointerEvents: isCapturing ? 'auto' : 'none',
			}}
		>
			<svg
				ref={svgRef}
				className='absolute'
				style={{
					width: canvasSize.width,
					height: canvasSize.height,
					transformOrigin: 'top left',
					transform: `scale(${editorScale})`,
				}}
				viewBox={`0 0 ${canvasSize.width} ${canvasSize.height}`}
				onPointerDown={handlePointerDown}
				onPointerMove={handlePointerMove}
				onPointerUp={handlePointerUp}
				onPointerLeave={handlePointerLeave}
			>
				{allStrokes.map((stroke) => (
					<path
						key={stroke.id}
						d={buildPathD(stroke.points)}
						fill='none'
						stroke={stroke.color}
						strokeWidth={stroke.width}
						strokeLinecap='round'
						strokeLinejoin='round'
						opacity={stroke.opacity}
					/>
				))}
			</svg>

			{/* Laser pointer dot */}
			{presentationTool === 'laser' && laserPosition && (
				<div
					className='absolute rounded-full pointer-events-none'
					style={{
						width: 24,
						height: 24,
						left: laserPosition.x * editorScale - 12,
						top: laserPosition.y * editorScale - 12,
						backgroundColor: 'rgba(255, 0, 0, 0.85)',
						boxShadow: '0 0 12px 6px rgba(255, 0, 0, 0.5), 0 0 24px 12px rgba(255, 0, 0, 0.25)',
						filter: 'drop-shadow(0 0 8px rgba(255, 0, 0, 0.7))',
						zIndex: 70,
					}}
				/>
			)}
		</div>
	);
}
