// packages/angular/src/viewer/ai/ai-focus-bar.component.ts
/**
 * AiFocusBarComponent: the strip under the panel header showing the assistant's
 * current focused targets as chips (live from the canvas selection, pinned, or
 * picked). Angular port of React's `AiFocusBar`.
 *
 * It also hosts the explicit "Point at a slide element" affordance: a crosshair
 * button that enters PICK MODE, after which the user clicks element(s) on the
 * canvas to hand them to the assistant (each pick is highlighted on the slide).
 * A one-click "Merge selected tables" directive surfaces when the focus is
 * exactly two tables. Reads/writes the shared {@link AiPanelStore}; emits the
 * merge directive up to the conversation so it routes through the chat send.
 */
import { ChangeDetectionStrategy, Component, computed, inject, input, output } from '@angular/core';
import { LucideCrosshair, LucideGitMerge, LucidePin, LucidePinOff, LucideX } from '@lucide/angular';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxSlide } from 'pptx-viewer-core';

import { AiPanelStore } from './ai-panel-store';
import { focusTargetChips, isTwoTableFocus } from './focus-targets';

/** Build the directive that fires `merge_tables` without a confirmation round-trip. */
function mergeDirective(slideIndex: number, elementIdA: string, elementIdB: string): string {
	return (
		`Merge the two selected tables (elementIdA=${elementIdA}, elementIdB=${elementIdB}) ` +
		`on slide ${slideIndex + 1} using merge_tables; stage it now, do not ask me to confirm.`
	);
}

@Component({
	selector: 'pptx-ai-focus-bar',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe, LucideCrosshair, LucideGitMerge, LucidePin, LucidePinOff, LucideX],
	template: `
		<div class="border-b border-border bg-secondary/30">
			<div class="flex flex-wrap items-center gap-1 px-2.5 py-1.5">
				<span class="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
					{{ 'pptx.ai.focusScope' | translate }}
				</span>
				@for (chip of chips(); track chip.key) {
					<span
						[class]="
							store.hasPicks() || store.isPinned()
								? 'inline-flex max-w-[10rem] items-center rounded-full px-2 py-0.5 text-[11px] bg-primary/15 text-primary'
								: 'inline-flex max-w-[10rem] items-center rounded-full px-2 py-0.5 text-[11px] bg-muted text-muted-foreground'
						"
						[title]="chip.title"
					>
						<span class="truncate">{{ chip.label }}</span>
					</span>
				}
				@if (store.isPinned()) {
					<span
						class="rounded-full bg-primary/15 px-1.5 py-0.5 text-[10px] font-medium text-primary"
					>
						{{ 'pptx.ai.pinnedFocus' | translate }}
					</span>
				}
				<div class="ml-auto flex items-center gap-0.5">
					@if (twoTables(); as tt) {
						<button
							type="button"
							(click)="onMerge(tt)"
							class="inline-flex items-center gap-1 rounded-sm bg-primary/90 px-1.5 py-0.5 text-[11px] font-medium text-primary-foreground hover:bg-primary"
						>
							<svg lucideGitMerge class="h-3 w-3"></svg>
							{{ 'pptx.ai.mergeSelectedTables' | translate }}
						</button>
					}
					<button
						type="button"
						(click)="store.pickMode() ? store.stopPicking() : store.startPicking()"
						[title]="'pptx.ai.pickElement' | translate"
						[attr.aria-label]="'pptx.ai.pickAria' | translate"
						[attr.aria-pressed]="store.pickMode()"
						[class]="
							store.pickMode()
								? 'rounded-sm p-1 bg-primary text-primary-foreground'
								: 'rounded-sm p-1 text-muted-foreground hover:bg-accent'
						"
					>
						<svg lucideCrosshair class="h-3.5 w-3.5"></svg>
					</button>
					@if (store.hasPicks()) {
						<button
							type="button"
							(click)="store.clearPicks()"
							[title]="'pptx.ai.pickClear' | translate"
							[attr.aria-label]="'pptx.ai.pickClear' | translate"
							class="rounded-sm p-1 text-muted-foreground hover:bg-accent"
						>
							<svg lucideX class="h-3.5 w-3.5"></svg>
						</button>
					} @else {
						<button
							type="button"
							(click)="store.isPinned() ? store.clearPinnedFocus() : store.pinFocus()"
							[title]="(store.isPinned() ? 'pptx.ai.clearFocus' : 'pptx.ai.pinFocus') | translate"
							[attr.aria-label]="
								(store.isPinned() ? 'pptx.ai.clearFocus' : 'pptx.ai.pinFocus') | translate
							"
							class="rounded-sm p-1 text-muted-foreground hover:bg-accent"
						>
							@if (store.isPinned()) {
								<svg lucidePinOff class="h-3.5 w-3.5"></svg>
							} @else {
								<svg lucidePin class="h-3.5 w-3.5"></svg>
							}
						</button>
					}
				</div>
			</div>
			@if (store.pickMode()) {
				<div class="flex items-center gap-2 border-t border-primary/20 bg-primary/5 px-2.5 py-1">
					<svg lucideCrosshair class="h-3.5 w-3.5 shrink-0 animate-pulse text-primary"></svg>
					<span class="text-[11px] font-medium text-primary">
						{{ 'pptx.ai.pickElementHint' | translate }}
					</span>
					<button
						type="button"
						(click)="store.stopPicking()"
						class="ml-auto rounded-sm bg-primary px-2 py-0.5 text-[11px] font-medium text-primary-foreground hover:bg-primary/90"
					>
						{{ 'pptx.ai.pickDone' | translate }}
					</button>
				</div>
			}
		</div>
	`,
})
export class AiFocusBarComponent {
	/** Live deck, for resolving element chip labels + the two-table detection. */
	readonly slides = input.required<readonly PptxSlide[]>();
	/** Emitted with a ready-to-send directive (e.g. the merge-tables request). */
	readonly sendDirective = output<string>();

	protected readonly store = inject(AiPanelStore);

	protected readonly chips = computed(() =>
		focusTargetChips(this.store.effectiveTargets(), this.slides()),
	);
	protected readonly twoTables = computed(() =>
		isTwoTableFocus(this.store.effectiveTargets(), this.slides()),
	);

	protected onMerge(tt: { slideIndex: number; elementIdA: string; elementIdB: string }): void {
		this.sendDirective.emit(mergeDirective(tt.slideIndex, tt.elementIdA, tt.elementIdB));
	}
}

// packages/vue/src/viewer/components/ai/AiFocusBar.vue
<script setup lang="ts">
/**
 * AiFocusBar: the strip under the panel header showing the assistant's current
 * focused targets as chips (live from the canvas selection, pinned, or picked).
 *
 * It also hosts the explicit "Point at a slide element" affordance: a crosshair
 * button that enters PICK MODE, after which the user clicks element(s) on the
 * canvas to hand them to the assistant (each pick is highlighted on the slide).
 * A one-click "Merge selected tables" directive still surfaces when the focus is
 * exactly two tables.
 */
import { Crosshair, GitMerge, Pin, PinOff, X } from 'lucide-vue-next';
import type { PptxSlide } from 'pptx-viewer-core';
import type { PptxAiFocusedTarget } from 'pptx-viewer-shared/ai';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import { focusTargetChips, isTwoTableFocus } from '../../composables/ai/focus-targets';

const props = defineProps<{
	targets: PptxAiFocusedTarget[];
	slides: PptxSlide[];
	isPinned: boolean;
	pickMode: boolean;
	hasPicks: boolean;
}>();

const emit = defineEmits<{
	(e: 'pin' | 'clear-pin' | 'start-pick' | 'stop-pick' | 'clear-picks'): void;
	(e: 'send-directive', text: string): void;
}>();

const { t } = useI18n();

const chips = computed(() => focusTargetChips(props.targets, props.slides));
const twoTables = computed(() => isTwoTableFocus(props.targets, props.slides));

/** Build the directive that fires `merge_tables` without a confirmation round-trip. */
function sendMerge(): void {
	const tt = twoTables.value;
	if (!tt) {
		return;
	}
	emit(
		'send-directive',
		`Merge the two selected tables (elementIdA=${tt.elementIdA}, elementIdB=${tt.elementIdB}) ` +
			`on slide ${tt.slideIndex + 1} using merge_tables; stage it now, do not ask me to confirm.`,
	);
}
</script>

<template>
	<div class="border-b border-border bg-secondary/30">
		<div class="flex flex-wrap items-center gap-1 px-2.5 py-1.5">
			<span class="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
				{{ t('pptx.ai.focusScope') }}
			</span>
			<span
				v-for="chip in chips"
				:key="chip.key"
				:class="
					cn(
						'inline-flex max-w-[10rem] items-center rounded-full px-2 py-0.5 text-[11px]',
						hasPicks || isPinned ? 'bg-primary/15 text-primary' : 'bg-muted text-muted-foreground',
					)
				"
				:title="chip.title"
			>
				<span class="truncate">{{ chip.label }}</span>
			</span>
			<span
				v-if="isPinned"
				class="rounded-full bg-primary/15 px-1.5 py-0.5 text-[10px] font-medium text-primary"
			>
				{{ t('pptx.ai.pinnedFocus') }}
			</span>
			<div class="ml-auto flex items-center gap-0.5">
				<button
					v-if="twoTables"
					type="button"
					class="inline-flex items-center gap-1 rounded-sm bg-primary/90 px-1.5 py-0.5 text-[11px] font-medium text-primary-foreground hover:bg-primary"
					@click="sendMerge"
				>
					<GitMerge class="w-3 h-3" />
					{{ t('pptx.ai.mergeSelectedTables') }}
				</button>
				<button
					type="button"
					:title="t('pptx.ai.pickElement')"
					:aria-label="t('pptx.ai.pickAria')"
					:aria-pressed="pickMode"
					:class="
						cn(
							'rounded-sm p-1',
							pickMode
								? 'bg-primary text-primary-foreground'
								: 'text-muted-foreground hover:bg-accent',
						)
					"
					@click="pickMode ? emit('stop-pick') : emit('start-pick')"
				>
					<Crosshair class="w-3.5 h-3.5" />
				</button>
				<button
					v-if="hasPicks"
					type="button"
					:title="t('pptx.ai.pickClear')"
					:aria-label="t('pptx.ai.pickClear')"
					class="rounded-sm p-1 text-muted-foreground hover:bg-accent"
					@click="emit('clear-picks')"
				>
					<X class="w-3.5 h-3.5" />
				</button>
				<button
					v-else
					type="button"
					:title="isPinned ? t('pptx.ai.clearFocus') : t('pptx.ai.pinFocus')"
					:aria-label="isPinned ? t('pptx.ai.clearFocus') : t('pptx.ai.pinFocus')"
					class="rounded-sm p-1 text-muted-foreground hover:bg-accent"
					@click="isPinned ? emit('clear-pin') : emit('pin')"
				>
					<PinOff v-if="isPinned" class="w-3.5 h-3.5" />
					<Pin v-else class="w-3.5 h-3.5" />
				</button>
			</div>
		</div>
		<div
			v-if="pickMode"
			class="flex items-center gap-2 border-t border-primary/20 bg-primary/5 px-2.5 py-1"
		>
			<Crosshair class="w-3.5 h-3.5 shrink-0 animate-pulse text-primary" />
			<span class="text-[11px] font-medium text-primary">{{ t('pptx.ai.pickElementHint') }}</span>
			<button
				type="button"
				class="ml-auto rounded-sm bg-primary px-2 py-0.5 text-[11px] font-medium text-primary-foreground hover:bg-primary/90"
				@click="emit('stop-pick')"
			>
				{{ t('pptx.ai.pickDone') }}
			</button>
		</div>
	</div>
</template>
