// packages/vue/src/viewer/components/CommentMarkersOverlay.vue
<script setup lang="ts">
import type { PptxComment } from 'pptx-viewer-core';
import { getCommentMarkerPosition } from 'pptx-viewer-shared';
import { computed } from 'vue';

import type { CanvasSize } from '../types';

/**
 * CommentMarkersOverlay: numbered comment marker dots drawn over the slide
 * canvas. Vue port of the React `canvas/CommentMarkersOverlay.tsx`. Positions
 * come from the shared `getCommentMarkerPosition` (explicit x/y clamped to the
 * slide, else a 4-column grid fallback), so markers match React/Angular.
 */
const props = defineProps<{
	comments: PptxComment[];
	canvasSize: CanvasSize;
}>();

const emit = defineEmits<{
	'marker-click': [commentId: string];
}>();

const markers = computed(() =>
	props.comments.map((comment, index) => ({
		comment,
		index,
		pos: getCommentMarkerPosition(comment, index, props.canvasSize.width, props.canvasSize.height),
	})),
);
</script>

<template>
	<div class="pointer-events-none absolute inset-0 z-[45]">
		<button
			v-for="{ comment, index, pos } in markers"
			:key="comment.id"
			type="button"
			class="pptx-vue-comment-marker pointer-events-auto absolute flex cursor-pointer items-center justify-center rounded-full border-2 border-white text-[10px] font-bold leading-none text-white shadow"
			:style="{
				left: `${pos.x - 10}px`,
				top: `${pos.y - 10}px`,
				width: '20px',
				height: '20px',
				backgroundColor: 'rgba(255, 165, 0, 0.9)',
			}"
			:title="`${comment.author ?? 'Comment'}: ${comment.text}`"
			@click.stop="emit('marker-click', comment.id)"
		>
			{{ index + 1 }}
		</button>
	</div>
</template>

// packages/react/src/viewer/components/canvas/CommentMarkersOverlay.tsx
/**
 * Comment marker dots rendered on top of the slide canvas.
 */
import type { PptxComment } from "pptx-viewer-core";
import { getCommentMarkerPosition } from "../../utils";
import type { CanvasSize } from "../../types";

/* ------------------------------------------------------------------ */
/*  Props                                                              */
/* ------------------------------------------------------------------ */

interface CommentMarkersOverlayProps {
  comments: PptxComment[];
  canvasSize: CanvasSize;
  onCommentMarkerClick?: (commentId: string) => void;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function CommentMarkersOverlay({
  comments,
  canvasSize,
  onCommentMarkerClick,
}: CommentMarkersOverlayProps) {
  return (
    <div className="absolute inset-0 pointer-events-none z-[45]">
      {comments.map((comment, idx) => {
        const pos = getCommentMarkerPosition(
          comment,
          idx,
          canvasSize.width,
          canvasSize.height,
        );
        return (
          <div
            key={comment.id}
            className="absolute pointer-events-auto cursor-pointer"
            style={{
              left: pos.x - 10,
              top: pos.y - 10,
              width: 20,
              height: 20,
              borderRadius: "50%",
              backgroundColor: "rgba(255, 165, 0, 0.9)",
              border: "2px solid #fff",
              boxShadow: "0 1px 3px rgba(0,0,0,0.3)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: 10,
              fontWeight: 700,
              color: "#fff",
              lineHeight: 1,
            }}
            title={`${comment.author ?? "Comment"}: ${comment.text}`}
            onClick={(e) => {
              e.stopPropagation();
              onCommentMarkerClick?.(comment.id);
            }}
          >
            {idx + 1}
          </div>
        );
      })}
    </div>
  );
}
