// packages/angular/src/viewer/animation-timeline.component.ts
/* oxlint-disable eslint/one-var -- the component's own field/method
   declarations below are independent, not adjacent initializations of
   related values; merging them would hurt readability far more than it
   helps. */
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type {
	PptxAnimationTimelineAnchor,
	PptxElement,
	PptxElementAnimation,
} from 'pptx-viewer-core';

import {
	animationEffectLabelKey,
	applyAnimationTimelineOrder,
	buildAnimationTimelineBars,
	buildAnimationTimelineRows,
	reorderAnimationTimelineRows,
} from '../internal/shared';
import type { AnimationTimelineBar, AnimationTimelineRow } from '../internal/shared';
import { getAnimationElementLabel } from './animation-author-view';
import { previewAngularAnimation, stopAngularAnimationPreview } from './animation-preview-player';

export type { AnimationTimelineBar };
export { buildAnimationTimelineBars };

@Component({
	selector: 'pptx-animation-timeline',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (rows().length) {
			<section class="timeline" [attr.aria-label]="'pptx.animation.timeline' | translate">
				<h4>{{ 'pptx.animation.timeline' | translate }}</h4>
				<div class="bar" aria-hidden="true">
					@for (item of bars(); track item.elementId) {
						<span
							[class.selected]="item.elementId === selectedElementId()"
							[style.left.%]="item.leftPercent"
							[style.width.%]="item.widthPercent"
						></span>
					}
				</div>
				<div class="list">
					@for (row of rows(); track row.key; let index = $index) {
						@if (row.kind === 'native') {
							<div
								class="item native"
								[class.drag-over]="dragOverIndex() === index"
								[title]="'pptx.animation.nativeEffectHint' | translate"
								(dragover)="onDragOver(index, $event)"
								(drop)="onDrop(index, $event)"
							>
								<span class="grip"></span><span class="order">{{ index + 1 }}.</span
								><span class="name"
									>{{ 'pptx.animation.nativeEffect' | translate }}: {{ nativeLabel(row) }}</span
								>
							</div>
						} @else {
							<div
								class="item"
								[class.selected]="row.elementId === selectedElementId()"
								[class.drag-over]="dragOverIndex() === index"
								[draggable]="canEdit()"
								(dragstart)="onDragStart(index, $event)"
								(dragover)="onDragOver(index, $event)"
								(drop)="onDrop(index, $event)"
								(dragend)="clearDrag()"
								(mouseenter)="previewByElementId(row.elementId)"
								(mouseleave)="stopPreview()"
							>
								<span class="grip">⋮⋮</span><span class="order">{{ index + 1 }}.</span
								><span class="name">{{ label(row.elementId) }}</span
								><span class="effect">{{ effectByElementId(row.elementId) | translate }}</span>
							</div>
						}
					}
				</div>
			</section>
		}
	`,
	styles: `
		.timeline {
			display: grid;
			gap: 6px;
			padding: 8px 0;
			border-top: 1px solid var(--pptx-inspector-border, #333);
		}
		h4 {
			margin: 0;
			color: var(--pptx-inspector-muted, #888);
			font-size: 10px;
			text-transform: uppercase;
		}
		.bar {
			position: relative;
			height: 22px;
			overflow: hidden;
			border: 1px solid var(--pptx-inspector-border, #444);
			border-radius: 3px;
			background: var(--pptx-inspector-input-bg, #2d2d2d);
		}
		.bar span {
			position: absolute;
			top: 3px;
			bottom: 3px;
			min-width: 2%;
			border-radius: 2px;
			background: #6b9a68;
		}
		.bar span.selected {
			outline: 1px solid var(--pptx-primary, #4c9ffe);
		}
		.list {
			display: grid;
			gap: 3px;
			max-height: 160px;
			overflow-y: auto;
		}
		.item {
			display: flex;
			align-items: center;
			gap: 4px;
			min-width: 0;
			padding: 4px;
			border: 1px solid transparent;
			border-radius: 3px;
			background: var(--pptx-inspector-input-bg, #2d2d2d);
			cursor: grab;
			font-size: 10px;
		}
		.item.selected {
			border-color: var(--pptx-primary, #4c9ffe);
		}
		.item.drag-over {
			border-top: 2px solid var(--pptx-primary, #4c9ffe);
		}
		.item.native {
			cursor: default;
			font-style: italic;
			opacity: 0.7;
		}
		.grip,
		.order {
			color: var(--pptx-inspector-muted, #888);
		}
		.name {
			flex: 1;
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
		}
		.effect {
			color: var(--pptx-inspector-muted, #aaa);
		}
	`,
})
export class AnimationTimelineComponent {
	readonly animations = input.required<readonly PptxElementAnimation[]>();
	readonly elements = input<readonly PptxElement[]>([]);
	/** Read-only anchors for the deck's own effect groups; see {@link PptxAnimationTimelineAnchor}. */
	readonly animationTimelineAnchors = input<readonly PptxAnimationTimelineAnchor[]>([]);
	readonly selectedElementId = input<string>('');
	readonly canEdit = input<boolean>(true);
	readonly animationsChange = output<PptxElementAnimation[]>();
	protected readonly dragIndex = signal<number | undefined>(undefined);
	protected readonly dragOverIndex = signal<number | undefined>(undefined);
	// Merges the editor's own animations with the deck's read-only native
	// anchors into one full-sequence drag-and-drop timeline.
	protected readonly rows = computed(() =>
		buildAnimationTimelineRows(this.animations(), this.animationTimelineAnchors()),
	);
	protected readonly bars = computed(() => buildAnimationTimelineBars(this.animations()));
	private readonly animationByElementId = computed(
		() => new Map(this.animations().map((animation) => [animation.elementId, animation])),
	);

	protected label(elementId: string): string {
		const element = this.elements().find((candidate) => candidate.id === elementId);
		if (!element) {
			return elementId;
		}
		return getAnimationElementLabel(element);
	}
	protected nativeLabel(row: Extract<AnimationTimelineRow, { kind: 'native' }>): string {
		return row.targetIds.map((id) => this.label(id)).join(', ');
	}
	/**
	 * The i18n key naming the row's effect, not finished text: resolving text in
	 * an `OnPush` getter would freeze the wording at the language that happened
	 * to be active when the view last rendered. The row used to print the raw
	 * preset token (`fadeIn`) here.
	 */
	protected effectByElementId(elementId: string): string {
		const animation = this.animationByElementId().get(elementId);
		return animation ? animationEffectLabelKey(animation) : '';
	}
	protected previewByElementId(elementId: string): void {
		const animation = this.animationByElementId().get(elementId);
		if (animation) {
			previewAngularAnimation(animation);
		}
	}
	protected stopPreview(): void {
		stopAngularAnimationPreview();
	}
	protected onDragStart(index: number, event: DragEvent): void {
		// Only an editor-authored row may be a drag SOURCE: the deck's own
		// effect groups are read-only, though they remain valid drop targets.
		if (!this.canEdit() || this.rows()[index]?.kind !== 'editor') {
			return;
		}
		this.dragIndex.set(index);
		event.dataTransfer?.setData('text/plain', String(index));
	}
	protected onDragOver(index: number, event: DragEvent): void {
		event.preventDefault();
		this.dragOverIndex.set(index);
	}
	protected onDrop(index: number, event: DragEvent): void {
		event.preventDefault();
		const source = this.dragIndex();
		if (source !== undefined) {
			const rows = this.rows();
			const sourceRow = rows[source];
			if (sourceRow?.kind === 'editor') {
				const nextRows = reorderAnimationTimelineRows(rows, sourceRow.key, index);
				this.animationsChange.emit(applyAnimationTimelineOrder(this.animations(), nextRows));
			}
		}
		this.clearDrag();
	}
	protected clearDrag(): void {
		this.dragIndex.set(undefined);
		this.dragOverIndex.set(undefined);
	}
}

// packages/svelte/src/viewer/components/ribbon/animations/AnimationTimeline.svelte
<script lang="ts">
	import GripVertical from '@lucide/svelte/icons/grip-vertical';
	import type { PptxAnimationDirection, PptxAnimationRepeatMode, PptxAnimationSequence, PptxAnimationTimingCurve, PptxAnimationTrigger, PptxElementAnimation } from 'pptx-viewer-core';
	import { buildAnimationTimelineRows, DIRECTION_VALUES, REPEAT_MODE_VALUES, schemaLabel, SEQUENCE_VALUES, TIMING_CURVE_VALUES, TRIGGER_VALUES } from 'pptx-viewer-shared';

	import { useTranslator } from '../../../../i18n/context';
	import type { EditorState } from '../../../editor/editor-state.svelte';
	import { animationTypeLabel, timelineLabel } from '../../inspector/animation-panel-helpers';
	import { reorderAnimationEntries } from './animation-timeline-editing';
	import { DIRECTION_LABEL_KEYS, REPEAT_MODE_LABEL_KEYS, SEQUENCE_LABEL_KEYS, TIMING_CURVE_LABEL_KEYS, TRIGGER_LABEL_KEYS } from './animation-timeline-labels';

	const { editor }: { editor: EditorState } = $props();
	const t = useTranslator();
	const slide = $derived(editor.slides[editor.currentSlideIndex]);
	const animations = $derived(slide?.animations ?? []);
	// Merges the editor's own animations with the deck's read-only native
	// anchors into one full-sequence drag-and-drop timeline.
	const rows = $derived(buildAnimationTimelineRows(animations, slide?.animationTimelineAnchors ?? []));
	const animationByElementId = $derived(new Map(animations.map((anim) => [anim.elementId, anim])));
	let draggingId = $state<string | null>(null);

	function commit(next: PptxElementAnimation[]): void {
		if (!slide) {
			return;
		}
		editor.commitSlides(editor.slides.map((item, index) => index === editor.currentSlideIndex ? { ...item, animations: next } : item));
	}
	function replace(elementId: string, patch: Partial<PptxElementAnimation>): void {
		commit(animations.map((item) => item.elementId === elementId ? { ...item, ...patch } : item));
	}
	/**
	 * The row's caption: the animated element, then the effect.
	 *
	 * Both used to be wire values here: the element was printed as its raw
	 * `elementId` (`ppt/slides/slide1.xml-shape-0`) and the effect was not shown
	 * at all, so the row named nothing a user could recognise. The other four
	 * bindings name both.
	 */
	function rowLabel(animation: PptxElementAnimation): string {
		const target = timelineLabel(animation, slide?.elements ?? []);
		return `${target} - ${animationTypeLabel(animation, t)}`;
	}
	function nativeLabel(targetIds: readonly string[]): string {
		return targetIds.map((id) => timelineLabel({ elementId: id } as PptxElementAnimation, slide?.elements ?? [])).join(', ');
	}
	function drop(targetKey: string): void {
		if (draggingId) {
			commit(reorderAnimationEntries(animations, slide?.animationTimelineAnchors ?? [], draggingId, targetKey));
		}
		draggingId = null;
	}
</script>

{#if rows.length}<div class="timeline"><h4>{t('pptx.animation.timeline')}</h4>{#each rows as row, index (row.key)}{#if row.kind === 'native'}<div role="listitem" class="native" title={t('pptx.animation.nativeEffectHint')} ondragover={(event) => event.preventDefault()} ondrop={() => drop(row.key)}>
	<span class="target">{index + 1}. {t('pptx.animation.nativeEffect')}: {nativeLabel(row.targetIds)}</span>
</div>{:else}{@const animation = animationByElementId.get(row.elementId)}{#if animation}<div role="listitem" class:selected={row.elementId === editor.selectedElementId} draggable="true" ondragstart={() => (draggingId = row.elementId)} ondragover={(event) => event.preventDefault()} ondrop={() => drop(row.key)}>
	<button type="button" class="target" onclick={() => editor.select(row.elementId)}><GripVertical size={12} aria-hidden="true" /> {index + 1}. {rowLabel(animation)}</button>
	<select aria-label={t('pptx.animation.trigger')} value={animation.trigger ?? 'onClick'} onchange={(event) => replace(row.elementId, { trigger: event.currentTarget.value as PptxAnimationTrigger })}>{#each TRIGGER_VALUES as trigger}<option value={trigger}>{schemaLabel(TRIGGER_LABEL_KEYS, trigger, t)}</option>{/each}</select>
	{#if animation.trigger === 'onShapeClick' || animation.trigger === 'onHover'}<select aria-label={t('pptx.animation.trigger.shapeLabel')} value={animation.triggerShapeId ?? ''} onchange={(event) => replace(row.elementId, { triggerShapeId: event.currentTarget.value || undefined })}><option value="">{t('pptx.animation.trigger.selectShape')}</option>{#each slide?.elements ?? [] as element}<option value={element.id}>{timelineLabel({ elementId: element.id }, slide?.elements ?? [])}</option>{/each}</select>{/if}
	<select aria-label={t('pptx.animation.direction')} value={animation.direction ?? 'fromBottom'} onchange={(event) => replace(row.elementId, { direction: event.currentTarget.value as PptxAnimationDirection })}>{#each DIRECTION_VALUES as direction}<option value={direction}>{schemaLabel(DIRECTION_LABEL_KEYS, direction, t)}</option>{/each}</select>
	<select aria-label={t('pptx.animation.sequence')} value={animation.sequence ?? 'asOne'} onchange={(event) => replace(row.elementId, { sequence: event.currentTarget.value as PptxAnimationSequence })}>{#each SEQUENCE_VALUES as sequence}<option value={sequence}>{schemaLabel(SEQUENCE_LABEL_KEYS, sequence, t)}</option>{/each}</select>
	<select aria-label={t('pptx.animation.timingCurve')} value={animation.timingCurve ?? 'ease'} onchange={(event) => replace(row.elementId, { timingCurve: event.currentTarget.value as PptxAnimationTimingCurve })}>{#each TIMING_CURVE_VALUES as curve}<option value={curve}>{schemaLabel(TIMING_CURVE_LABEL_KEYS, curve, t)}</option>{/each}</select>
	<select aria-label={t('pptx.animations.repeat')} value={animation.repeatMode ?? 'none'} onchange={(event) => replace(row.elementId, { repeatMode: event.currentTarget.value === 'none' ? undefined : event.currentTarget.value as PptxAnimationRepeatMode })}>{#each REPEAT_MODE_VALUES as repeat}<option value={repeat}>{schemaLabel(REPEAT_MODE_LABEL_KEYS, repeat, t)}</option>{/each}</select>
	<label>{t('pptx.animation.duration')}<input type="number" min="0" step="100" value={animation.durationMs ?? 500} onchange={(event) => replace(row.elementId, { durationMs: Number(event.currentTarget.value) })} /></label><label>{t('pptx.animation.delay')}<input type="number" min="0" step="100" value={animation.delayMs ?? 0} onchange={(event) => replace(row.elementId, { delayMs: Number(event.currentTarget.value) })} /></label><label>{t('pptx.animation.repeatCount')}<input type="number" min="1" value={animation.repeatCount ?? 1} onchange={(event) => replace(row.elementId, { repeatCount: Number(event.currentTarget.value) })} /></label>
</div>{/if}{/if}{/each}</div>{/if}

<style>.timeline{display:grid;flex-basis:100%;gap:4px;padding-top:6px;border-top:1px solid var(--pptx-border)}h4{margin:0;font-size:10px;text-transform:uppercase}.timeline>div{display:grid;grid-template-columns:minmax(130px,1fr) repeat(5,minmax(84px,auto)) repeat(3,64px);gap:4px;align-items:end;padding:4px;border-radius:5px;background:var(--pptx-muted);font-size:9px}.timeline>div.selected{box-shadow:inset 3px 0 var(--pptx-primary)}.timeline>div.native{grid-template-columns:1fr;font-style:italic;opacity:0.7}.target{display:inline-flex;align-items:center;gap:4px;text-align:left}label{display:grid;gap:2px;color:var(--pptx-muted-foreground)}input,select,button{min-width:0;height:24px;border:1px solid var(--pptx-border);border-radius:4px;background:var(--pptx-background);color:inherit;font-size:9px}</style>
