// packages/vue/src/viewer/components/ribbon/MotionPathGallery.vue
<script setup lang="ts">
/**
 * MotionPathGallery: the Animations tab's motion-path gallery, PowerPoint's
 * Lines / Arcs / Turns / Shapes / Loops families with every path a real button.
 *
 * It is a sibling of the entrance/emphasis/exit gallery rather than a fourth
 * column of it because a motion path is not one of those three buckets: it is
 * geometry that coexists with them on the same animation entry, so mixing it
 * into the preset columns would imply a choice the model does not make.
 *
 * Every path is a `<button>` in the accessibility tree rather than an entry
 * behind a hover menu: a gallery a screen-reader user cannot enumerate is a
 * gallery they do not have. The family captions are inert `<span>`s for the
 * mirrored reason, a caption that answers to a click is a control the tab does
 * not really offer.
 *
 * The columns are derived from the shared catalogue once at module scope, so a
 * preset added to `pptx-viewer-shared` reaches this binding with no follow-up
 * here and every binding's gallery stays identical by construction.
 */
import { MoveRight } from 'lucide-vue-next';
import {
	MOTION_PATH_FAMILIES,
	motionPathFamilyLabelKey,
	motionPathPresetLabelKey,
	motionPathPresetsByFamily,
} from 'pptx-viewer-shared';
import { useI18n } from 'vue-i18n';

interface Props {
	disabled: boolean;
	/** Applies a catalogue motion path to the selected element by preset id. */
	onApplyMotionPath?: (presetId: string) => void;
}

const props = defineProps<Props>();
const { t } = useI18n();

/** One gallery column: a family's caption plus the paths that belong to it. */
const FAMILY_COLUMNS = MOTION_PATH_FAMILIES.map((family) => ({
	family,
	labelKey: motionPathFamilyLabelKey(family),
	presets: motionPathPresetsByFamily(family),
}));

/** A path's visible caption AND its tooltip, so both name the same control. */
function presetLabel(presetId: string): string {
	return t(motionPathPresetLabelKey(presetId));
}
</script>

<template>
	<div
		class="flex max-h-[62px] items-start gap-2 overflow-y-auto rounded-sm border border-border/60 bg-muted/30 px-1.5 py-1"
		:aria-label="t('pptx.animations.motionPathGalleryAria')"
	>
		<div v-for="column in FAMILY_COLUMNS" :key="column.family" class="flex flex-col gap-0.5">
			<span class="text-[9px] font-semibold leading-3 text-muted-foreground">
				{{ t(column.labelKey) }}
			</span>
			<div class="flex max-w-[150px] flex-wrap gap-0.5">
				<button
					v-for="preset in column.presets"
					:key="preset.id"
					type="button"
					:disabled="props.disabled"
					:title="presetLabel(preset.id)"
					class="inline-flex items-center gap-0.5 rounded-sm px-1 py-0.5 text-[9px] leading-3 text-foreground transition-colors hover:bg-accent disabled:opacity-35"
					@click="props.onApplyMotionPath?.(preset.id)"
				>
					<MoveRight class="h-2.5 w-2.5 text-sky-500" aria-hidden="true" />
					<span class="whitespace-nowrap">{{ presetLabel(preset.id) }}</span>
				</button>
			</div>
		</div>
	</div>
</template>

// packages/svelte/src/viewer/components/ribbon/animations/MotionPathGallery.svelte
<script lang="ts">
	/**
	 * MotionPathGallery: the Animations tab's motion-path gallery (Svelte port of
	 * React's `toolbar/MotionPathGallery.tsx`), offering PowerPoint's Lines /
	 * Arcs / Turns / Shapes / Loops families with every path as a real button.
	 *
	 * WHY it is a sibling of the entrance/emphasis/exit gallery rather than a
	 * fourth column of it: a motion path is not one of those three buckets, it is
	 * geometry that coexists with them on the SAME animation entry. Folding it
	 * into the preset columns would imply an either/or choice the model does not
	 * make, and clicking a path would then look like it replaced the entrance.
	 *
	 * The catalogue, the label keys and the apply mutation all come from
	 * `pptx-viewer-shared`, so every binding's gallery lists the same paths under
	 * the same accessible names (an e2e spec diffs them against React).
	 */
	import {
		MOTION_PATH_FAMILIES,
		motionPathFamilyLabelKey,
		motionPathPresetLabelKey,
		motionPathPresetsByFamily,
	} from 'pptx-viewer-shared';

	import { useTranslator } from '../../../../i18n/context';

	const {
		disabled,
		onapply,
	}: {
		disabled: boolean;
		/** Applies a catalogue motion path to the selected element by preset id. */
		onapply?: (presetId: string) => void;
	} = $props();

	const t = useTranslator();
</script>

<div class="pptx-svelte-motionpaths" aria-label={t('pptx.animations.motionPathGalleryAria')}>
	{#each MOTION_PATH_FAMILIES as family (family)}
		<div class="pptx-svelte-motionpaths-family">
			<span class="pptx-svelte-motionpaths-label">{t(motionPathFamilyLabelKey(family))}</span>
			<div class="pptx-svelte-motionpaths-row">
				{#each motionPathPresetsByFamily(family) as preset (preset.id)}
					<button
						type="button"
						{disabled}
						title={t(motionPathPresetLabelKey(preset.id))}
						onclick={() => onapply?.(preset.id)}
					>
						<!-- Decorative arrow only: the button's accessible name must stay
						     exactly the preset label, byte for byte with React's. -->
						<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M3 10h11M11 6.5 14.5 10 11 13.5" /></svg>
						<span>{t(motionPathPresetLabelKey(preset.id))}</span>
					</button>
				{/each}
			</div>
		</div>
	{/each}
</div>

<style>
	.pptx-svelte-motionpaths {
		display: flex;
		align-items: flex-start;
		gap: 8px;
		max-height: 62px;
		overflow-y: auto;
		padding: 2px 4px;
		border: 1px solid color-mix(in srgb, var(--pptx-border, #33334d) 60%, transparent);
		border-radius: 4px;
		background: color-mix(in srgb, var(--pptx-muted, #2a2a3d) 40%, transparent);
	}

	.pptx-svelte-motionpaths-family {
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.pptx-svelte-motionpaths-label {
		font-size: 9px;
		font-weight: 600;
		line-height: 12px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-motionpaths-row {
		display: flex;
		flex-wrap: wrap;
		gap: 2px;
		max-width: 150px;
	}

	.pptx-svelte-motionpaths-row button {
		display: inline-flex;
		align-items: center;
		gap: 2px;
		padding: 1px 4px;
		border: none;
		border-radius: 4px;
		background: transparent;
		color: inherit;
		cursor: pointer;
		font: inherit;
		font-size: 9px;
		line-height: 12px;
		white-space: nowrap;
	}

	.pptx-svelte-motionpaths-row button svg {
		width: 10px;
		height: 10px;
		fill: none;
		stroke: #0ea5e9;
		stroke-width: 1.6;
	}

	.pptx-svelte-motionpaths-row button:hover:not(:disabled) {
		background: var(--pptx-accent, #33334d);
		color: var(--pptx-accent-foreground, #f8fafc);
	}

	.pptx-svelte-motionpaths-row button:disabled {
		opacity: 0.35;
		cursor: default;
	}
</style>
