// packages/svelte/src/viewer/components/inspector/ChartDataGrid.svelte
<script lang="ts">
	/**
	 * ChartDataGrid: the spreadsheet-style category x series editor, mirroring
	 * React's `inspector/ChartDataGrid.tsx`.
	 *
	 * WHY this exists: before it, Svelte could only edit a series' values as a
	 * comma-joined string, which is unusable for anything past a toy chart and
	 * loses a value silently on a typo. This is the surface that makes chart
	 * data genuinely editable.
	 *
	 * Every mutation goes through `pptx-viewer-shared`'s `chart-data-grid-ops`,
	 * which owns the guards (auto-naming, never delete the last row/column,
	 * refuse a non-numeric cell instead of writing zero) so this component is
	 * pure presentation. Value inputs carry a `"<series> value <n>"` accessible
	 * name matching React's, so one e2e spec drives both.
	 */
	import type { PptxChartData } from 'pptx-viewer-core';
	import {
		addChartCategory,
		addChartSeries,
		removeChartCategory,
		removeChartSeries,
		setChartCategoryLabel,
		setChartCellValue,
	} from 'pptx-viewer-shared';

	import { useTranslator } from '../../../i18n/context';

	const {
		data,
		canEdit,
		onreplace,
		onrenameseries,
	}: {
		data: PptxChartData;
		canEdit: boolean;
		onreplace: (next: PptxChartData) => void;
		onrenameseries: (seriesIndex: number, name: string) => void;
	} = $props();
	const t = useTranslator();

	/** Apply an op result, ignoring the `null` "refused" outcome. */
	function apply(next: PptxChartData | null): void {
		if (next) {
			onreplace(next);
		}
	}
</script>

<div class="pptx-svelte-chart-grid">
	<div class="pptx-svelte-chart-grid-head">
		<span class="pptx-svelte-chart-grid-title">{t('pptx.chart.data')}</span>
		{#if canEdit}
			<div class="pptx-svelte-chart-grid-actions">
				<button
					type="button"
					title={t('pptx.chart.addCategory')}
					aria-label={t('pptx.chart.addCategory')}
					onclick={() => apply(addChartCategory(data))}
				>
					+ {t('pptx.chart.cat')}
				</button>
				<button
					type="button"
					title={t('pptx.chart.addSeries')}
					aria-label={t('pptx.chart.addSeries')}
					onclick={() => apply(addChartSeries(data))}
				>
					+ {t('pptx.chart.seriesShort')}
				</button>
			</div>
		{/if}
	</div>

	<div class="pptx-svelte-chart-grid-scroll">
		<table>
			<thead>
				<tr>
					<th aria-label={t('pptx.chart.categories')}></th>
					{#each data.series as series, seriesIndex (seriesIndex)}
						<th>
							<div class="pptx-svelte-chart-grid-cell">
								<input
									type="text"
									disabled={!canEdit}
									aria-label={`${t('pptx.chart.seriesShort')} ${seriesIndex + 1}`}
									value={series.name}
									onchange={(event) => onrenameseries(seriesIndex, event.currentTarget.value)}
								/>
								{#if canEdit && data.series.length > 1}
									<button
										type="button"
										class="pptx-svelte-chart-grid-remove"
										title={t('pptx.chart.removeSeries')}
										aria-label={t('pptx.chart.removeSeries')}
										onclick={() => apply(removeChartSeries(data, seriesIndex))}
									>
										&times;
									</button>
								{/if}
							</div>
						</th>
					{/each}
				</tr>
			</thead>
			<tbody>
				{#each data.categories as category, categoryIndex (categoryIndex)}
					<tr>
						<td>
							<div class="pptx-svelte-chart-grid-cell">
								<input
									type="text"
									disabled={!canEdit}
									aria-label={`${t('pptx.chart.categories')} ${categoryIndex + 1}`}
									value={category}
									onchange={(event) =>
										apply(setChartCategoryLabel(data, categoryIndex, event.currentTarget.value))}
								/>
								{#if canEdit && data.categories.length > 1}
									<button
										type="button"
										class="pptx-svelte-chart-grid-remove"
										title={t('pptx.chart.removeCategory')}
										aria-label={t('pptx.chart.removeCategory')}
										onclick={() => apply(removeChartCategory(data, categoryIndex))}
									>
										&times;
									</button>
								{/if}
							</div>
						</td>
						{#each data.series as series, seriesIndex (seriesIndex)}
							<td>
								<input
									type="number"
									disabled={!canEdit}
									aria-label={`${series.name} value ${categoryIndex + 1}`}
									value={series.values[categoryIndex] ?? 0}
									onchange={(event) =>
										apply(
											setChartCellValue(
												data,
												seriesIndex,
												categoryIndex,
												event.currentTarget.value,
											),
										)}
								/>
							</td>
						{/each}
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</div>

<style>
	.pptx-svelte-chart-grid {
		display: grid;
		gap: 6px;
		margin-top: 8px;
		padding-top: 7px;
		border-top: 1px solid var(--pptx-border, #33334d);
	}

	.pptx-svelte-chart-grid-head {
		display: flex;
		align-items: center;
		gap: 6px;
	}

	.pptx-svelte-chart-grid-title {
		font-weight: 600;
	}

	.pptx-svelte-chart-grid-actions {
		display: flex;
		gap: 4px;
		margin-left: auto;
	}

	.pptx-svelte-chart-grid-actions button {
		padding: 2px 6px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 5px;
		background: var(--pptx-muted, #2a2a3d);
		color: inherit;
		font: inherit;
		font-size: 10px;
		cursor: pointer;
	}

	/* Wide grids scroll inside the card; the inspector must never scroll sideways. */
	.pptx-svelte-chart-grid-scroll {
		overflow-x: auto;
	}

	table {
		width: 100%;
		border-collapse: collapse;
		font-size: 11px;
	}

	th,
	td {
		padding: 1px;
		font-weight: 400;
		text-align: left;
	}

	th {
		min-width: 76px;
	}

	.pptx-svelte-chart-grid-cell {
		display: flex;
		align-items: center;
		gap: 2px;
	}

	input {
		width: 100%;
		min-width: 0;
		height: 22px;
		box-sizing: border-box;
		padding: 0 4px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 4px;
		background: var(--pptx-background, #11111b);
		color: inherit;
		font: inherit;
		font-size: 11px;
	}

	.pptx-svelte-chart-grid-remove {
		flex: none;
		width: 16px;
		padding: 0;
		border: none;
		background: transparent;
		color: var(--pptx-muted-foreground, #94a3b8);
		cursor: pointer;
	}

	.pptx-svelte-chart-grid-remove:hover {
		color: #f87171;
	}
</style>

// packages/vue/src/viewer/components/inspector/ChartDataGrid.vue
<script setup lang="ts">
import type { PptxChartSeries } from 'pptx-viewer-core';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * ChartDataGrid: an editable spreadsheet-style grid of the chart's underlying
 * data. Mirrors React's `ChartDataGrid`. Categories run down the rows, series
 * across the columns; every cell is a numeric value. Series names and category
 * labels are editable in the header column/row, and series/categories can be
 * added or removed. A read-only summary line reports the current counts.
 *
 * All mutation is emitted upward; the parent routes it through `useChartEditing`
 * so the full new `chartData` is emitted via the panel's `update` contract.
 */
const props = defineProps<{
	series: readonly PptxChartSeries[];
	categories: readonly string[];
}>();

const emit = defineEmits<{
	updateSeries: [index: number, patch: Partial<PptxChartSeries>];
	updateCategoryLabel: [catIndex: number, value: string];
	updateValue: [seriesIndex: number, catIndex: number, raw: string];
	addSeries: [];
	removeSeries: [seriesIndex: number];
	addCategory: [];
	removeCategory: [catIndex: number];
}>();

const { t } = useI18n();

const summary = computed(
	() =>
		`${props.series.length} ${t('pptx.chart.series')} · ${props.categories.length} ${t('pptx.chart.categories')}`,
);

function onSeriesName(event: Event, index: number): void {
	emit('updateSeries', index, { name: (event.target as HTMLInputElement).value });
}

function onCategoryLabel(event: Event, catIndex: number): void {
	emit('updateCategoryLabel', catIndex, (event.target as HTMLInputElement).value);
}

function onValue(event: Event, seriesIndex: number, catIndex: number): void {
	emit('updateValue', seriesIndex, catIndex, (event.target as HTMLInputElement).value);
}

const CELL_INPUT =
	'pptx-vue-chart-cell w-full bg-muted border border-border rounded px-1 py-0.5 text-[11px]';
const BTN =
	'pptx-vue-chart-grid-btn px-1.5 py-0.5 rounded border border-border bg-muted hover:bg-accent text-[11px]';
</script>

<template>
	<div class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2">
		<div class="flex items-center justify-between">
			<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
				{{ t('pptx.chart.data') }}
			</div>
			<div class="flex gap-1">
				<button
					type="button"
					:class="BTN"
					data-testid="chart-add-category"
					:title="t('pptx.chart.addCategory')"
					@click="emit('addCategory')"
				>
					+ {{ t('pptx.chart.cat') }}
				</button>
				<button
					type="button"
					:class="BTN"
					data-testid="chart-add-series"
					:title="t('pptx.chart.addSeries')"
					@click="emit('addSeries')"
				>
					+ {{ t('pptx.chart.seriesShort') }}
				</button>
			</div>
		</div>

		<div
			class="pptx-vue-chart-summary text-[11px] text-muted-foreground"
			data-testid="chart-data-summary"
		>
			{{ summary }}
		</div>

		<div class="overflow-x-auto">
			<table class="w-full text-[11px] border-collapse">
				<thead>
					<tr>
						<th class="text-muted-foreground p-0.5 text-left min-w-[60px]"></th>
						<th
							v-for="(s, si) in props.series"
							:key="`h-${s.name}-${si}`"
							class="p-0.5 font-normal min-w-[72px]"
						>
							<div class="flex items-center gap-0.5">
								<input
									type="text"
									:class="CELL_INPUT"
									data-testid="chart-grid-series-name"
									:value="s.name"
									@input="onSeriesName($event, si)"
								/>
								<button
									v-if="props.series.length > 1"
									type="button"
									class="text-muted-foreground hover:text-red-400 shrink-0"
									data-testid="chart-remove-series"
									:title="t('pptx.chart.removeSeries')"
									@click="emit('removeSeries', si)"
								>
									&times;
								</button>
							</div>
						</th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="(cat, ci) in props.categories" :key="`r-${cat}-${ci}`">
						<td class="p-0.5">
							<div class="flex items-center gap-0.5">
								<input
									type="text"
									:class="CELL_INPUT"
									data-testid="chart-grid-cat-label"
									:value="cat"
									@input="onCategoryLabel($event, ci)"
								/>
								<button
									v-if="props.categories.length > 1"
									type="button"
									class="text-muted-foreground hover:text-red-400 shrink-0"
									data-testid="chart-remove-category"
									:title="t('pptx.chart.removeCategory')"
									@click="emit('removeCategory', ci)"
								>
									&times;
								</button>
							</div>
						</td>
						<td v-for="(s, si) in props.series" :key="`c-${si}-${ci}`" class="p-0.5">
							<input
								type="number"
								:class="CELL_INPUT"
								data-testid="chart-grid-value"
								:value="s.values[ci] ?? 0"
								@input="onValue($event, si, ci)"
							/>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</template>
