// packages/angular/src/viewer/chart-datapoint-options.component.ts
/**
 * chart-datapoint-options.component.ts: Per-data-point fill + slice explosion.
 *
 * Selector: `pptx-chart-datapoint-options`
 *
 * Mirrors React's `ChartDataPointOptions.tsx`: a series picker (per-point edits
 * target one series at a time) and, per category, a fill-colour override (with a
 * clear button) plus a pie/doughnut slice-explosion amount for the chart types
 * that support it. Routes through `setDataPointFill` / `setDataPointExplosion`
 * and emits a new `ChartPptxElement`.
 *
 * @module angular-viewer/chart-datapoint-options
 */

import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import type {
	ChartPptxElement,
	PptxChartDataPoint,
	PptxChartSeries,
	PptxChartType,
} from 'pptx-viewer-core';

import { EXPLOSION_SUPPORTED_TYPES } from '../internal/shared';
import { setDataPointExplosion, setDataPointFill } from './chart-data-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { numFromEvent, selectValue, stringFromEvent } from './chart-event-helpers';

@Component({
	selector: 'pptx-chart-datapoint-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		@if (categories().length > 0 && series().length > 0) {
			<section class="pptx-chart-card" aria-label="Data point options">
				<h4 class="pptx-chart-card__heading">Data Points</h4>

				@if (series().length > 1) {
					<label class="pptx-chart-card__row">
						<span class="pptx-chart-card__label">Series</span>
						<select
							class="pptx-chart-card__input"
							[disabled]="!canEdit()"
							[value]="activeIndex()"
							(change)="onSeries($event)"
						>
							@for (s of series(); track $index; let i = $index) {
								<option [value]="i">{{ s.name }}</option>
							}
						</select>
					</label>
				}

				<div class="pptx-chart-card__group">
					@for (cat of categories(); track $index; let ci = $index) {
						<div class="pptx-chart-card__row">
							<span class="pptx-chart-card__name" [title]="cat">{{ cat }}</span>
							<input
								type="color"
								class="pptx-chart-card__color"
								title="Point fill"
								[disabled]="!canEdit()"
								[value]="pointFill(ci)"
								(input)="onFill(ci, $event)"
							/>
							@if (pointAt(ci)?.spPr?.fillColor) {
								<button
									type="button"
									class="pptx-chart-card__clear"
									title="Clear point fill"
									[disabled]="!canEdit()"
									(click)="onClearFill(ci)"
								>
									&times;
								</button>
							}
							@if (showExplosion()) {
								<input
									type="number"
									min="0"
									max="100"
									class="pptx-chart-card__input pptx-chart-card__input--num"
									title="Slice explosion"
									placeholder="0"
									[disabled]="!canEdit()"
									[value]="pointAt(ci)?.explosion ?? ''"
									(change)="onExplosion(ci, $event)"
								/>
							}
						</div>
					}
				</div>
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartDatapointOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	private readonly seriesIndex = signal(0);

	protected readonly series = computed<PptxChartSeries[]>(
		() => this.element().chartData?.series ?? [],
	);
	protected readonly categories = computed<string[]>(
		() => this.element().chartData?.categories ?? [],
	);

	/** Clamp the chosen series index to the current series count. */
	protected readonly activeIndex = computed(() =>
		Math.min(this.seriesIndex(), Math.max(0, this.series().length - 1)),
	);

	protected readonly showExplosion = computed(() => {
		const type = this.element().chartData?.chartType as PptxChartType | undefined;
		return type !== undefined && EXPLOSION_SUPPORTED_TYPES.has(type);
	});

	protected pointAt(pointIndex: number): PptxChartDataPoint | undefined {
		return this.series()[this.activeIndex()]?.dataPoints?.find((p) => p.idx === pointIndex);
	}

	protected pointFill(pointIndex: number): string {
		const active = this.series()[this.activeIndex()];
		return this.pointAt(pointIndex)?.spPr?.fillColor ?? active?.color ?? '#4472c4';
	}

	protected onSeries(event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		const num = Number.parseInt(value, 10);
		if (Number.isFinite(num)) {
			this.seriesIndex.set(num);
		}
	}

	protected onFill(pointIndex: number, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(
			setDataPointFill(this.element(), this.activeIndex(), pointIndex, value),
		);
	}

	protected onClearFill(pointIndex: number): void {
		this.elementChange.emit(setDataPointFill(this.element(), this.activeIndex(), pointIndex, null));
	}

	protected onExplosion(pointIndex: number, event: Event): void {
		const num = numFromEvent(event);
		if (num === undefined) {
			return;
		}
		this.elementChange.emit(
			setDataPointExplosion(this.element(), this.activeIndex(), pointIndex, num),
		);
	}
}

// packages/vue/src/viewer/components/inspector/ChartDataPointOptions.vue
<script setup lang="ts">
import type { PptxChartDataPoint, PptxChartSeries, PptxChartType } from 'pptx-viewer-core';
import { EXPLOSION_SUPPORTED_TYPES } from 'pptx-viewer-shared';
import { computed, ref } from 'vue';

/**
 * ChartDataPointOptions: per-data-point fill override + pie/doughnut slice
 * explosion, targeting one series at a time. Mirrors React's
 * `ChartDataPointOptions`. Emits `setPointFill` / `setPointExplosion`.
 */
const props = defineProps<{
	chartType: PptxChartType;
	categories: readonly string[];
	series: readonly PptxChartSeries[];
}>();

const emit = defineEmits<{
	setPointFill: [seriesIndex: number, pointIndex: number, color: string | null];
	setPointExplosion: [seriesIndex: number, pointIndex: number, explosion: number | null];
}>();

const seriesIndex = ref(0);

const visible = computed(() => props.series.length > 0 && props.categories.length > 0);

const activeIndex = computed(() => Math.min(seriesIndex.value, props.series.length - 1));
const activeSeries = computed<PptxChartSeries | undefined>(() => props.series[activeIndex.value]);
const showExplosion = computed(() => EXPLOSION_SUPPORTED_TYPES.has(props.chartType));

function pointFor(idx: number): PptxChartDataPoint | undefined {
	return activeSeries.value?.dataPoints?.find((p) => p.idx === idx);
}

function onSeriesPick(event: Event): void {
	seriesIndex.value = Number.parseInt((event.target as HTMLSelectElement).value, 10);
}

function onFill(event: Event, idx: number): void {
	emit('setPointFill', activeIndex.value, idx, (event.target as HTMLInputElement).value);
}

function onClearFill(idx: number): void {
	emit('setPointFill', activeIndex.value, idx, null);
}

function onExplosion(event: Event, idx: number): void {
	const raw = (event.target as HTMLInputElement).value;
	if (raw === '') {
		emit('setPointExplosion', activeIndex.value, idx, null);
		return;
	}
	const num = Number.parseInt(raw, 10);
	if (Number.isFinite(num)) {
		emit('setPointExplosion', activeIndex.value, idx, num);
	}
}
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			Data points
		</div>

		<label v-if="props.series.length > 1" class="flex items-center gap-2 text-[11px]">
			<span class="w-12 text-muted-foreground shrink-0">Series</span>
			<select
				class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
				data-testid="chart-point-series"
				:value="activeIndex"
				@change="onSeriesPick"
			>
				<option v-for="(s, i) in props.series" :key="`${s.name}-${i}`" :value="i">
					{{ s.name }}
				</option>
			</select>
		</label>

		<div class="space-y-1.5">
			<div
				v-for="(cat, idx) in props.categories"
				:key="`${cat}-${idx}`"
				class="flex items-center gap-2 text-[11px]"
			>
				<span class="flex-1 truncate" :title="cat">{{ cat }}</span>

				<input
					type="color"
					data-testid="chart-point-fill"
					class="h-6 w-8 cursor-pointer rounded border border-border bg-transparent"
					:value="pointFor(idx)?.spPr?.fillColor ?? activeSeries?.color ?? '#4472c4'"
					@input="onFill($event, idx)"
				/>
				<button
					v-if="pointFor(idx)?.spPr?.fillColor"
					type="button"
					data-testid="chart-point-fill-clear"
					class="text-muted-foreground hover:text-foreground"
					title="Clear point fill"
					@click="onClearFill(idx)"
				>
					&times;
				</button>

				<input
					v-if="showExplosion"
					type="number"
					min="0"
					max="100"
					data-testid="chart-point-explosion"
					class="w-14 bg-muted border border-border rounded px-1.5 py-0.5"
					:value="pointFor(idx)?.explosion ?? ''"
					placeholder="0"
					title="Slice explosion"
					@input="onExplosion($event, idx)"
				/>
			</div>
		</div>
	</div>
</template>
