// packages/react/src/viewer/components/inspector/ChartAxisOptions.tsx
import type { PptxChartAxisFormatting } from 'pptx-viewer-core';
import { useTranslation } from 'react-i18next';

import {
	CARD,
	DISPLAY_UNITS_OPTIONS,
	HEADING,
	INPUT,
	TICK_LABEL_POSITION_OPTIONS,
} from './chart-panel-constants';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------
export interface ChartAxisOptionsProps {
	axes: PptxChartAxisFormatting[] | undefined;
	canEdit: boolean;
	onUpdateAxis: (
		axisType: PptxChartAxisFormatting['axisType'],
		patch: Partial<PptxChartAxisFormatting>,
	) => void;
}

/** Axis kinds the inspector exposes, with their label keys and whether they carry a numeric scale. */
const AXIS_ROWS: ReadonlyArray<{
	type: PptxChartAxisFormatting['axisType'];
	labelKey: string;
	hasScale: boolean;
}> = [
	{ type: 'valAx', labelKey: 'pptx.chart.valueAxis', hasScale: true },
	{ type: 'dateAx', labelKey: 'pptx.chart.dateAxis', hasScale: true },
	{ type: 'catAx', labelKey: 'pptx.chart.categoryAxis', hasScale: false },
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export function ChartAxisOptions({ axes, canEdit, onUpdateAxis }: ChartAxisOptionsProps) {
	const { t } = useTranslation();

	// Only render axes that actually exist on the chart (e.g. pie charts have none).
	const rows = AXIS_ROWS.map((row) => ({
		...row,
		axis: axes?.find((a) => a.axisType === row.type),
	})).filter((row): row is typeof row & { axis: PptxChartAxisFormatting } => Boolean(row.axis));

	if (rows.length === 0) {
		return null;
	}

	const numberField = (
		axisType: PptxChartAxisFormatting['axisType'],
		labelKey: string,
		value: number | undefined,
		key: 'min' | 'max' | 'majorUnit' | 'minorUnit',
	) => (
		<label className='flex items-center gap-2 text-[11px]'>
			<span className='w-16 text-muted-foreground shrink-0'>{t(labelKey)}</span>
			<input
				type='number'
				disabled={!canEdit}
				className={INPUT}
				value={value ?? ''}
				placeholder={t('pptx.chart.auto')}
				onChange={(e) => {
					const raw = e.target.value;
					if (raw === '') {
						onUpdateAxis(axisType, { [key]: undefined });
						return;
					}
					const num = Number.parseFloat(raw);
					if (Number.isFinite(num)) {
						onUpdateAxis(axisType, { [key]: num });
					}
				}}
			/>
		</label>
	);

	return (
		<div className={CARD}>
			<div className={HEADING}>{t('pptx.chart.axes')}</div>
			{rows.map(({ type, labelKey, hasScale, axis }) => (
				<div key={type} className='space-y-1.5'>
					<div className='text-[11px] font-medium'>{t(labelKey)}</div>

					{hasScale && (
						<div className='space-y-1.5 ml-2'>
							{numberField(type, 'pptx.chart.min', axis.min, 'min')}
							{numberField(type, 'pptx.chart.max', axis.max, 'max')}
							{numberField(type, 'pptx.chart.majorUnit', axis.majorUnit, 'majorUnit')}
							{numberField(type, 'pptx.chart.minorUnit', axis.minorUnit, 'minorUnit')}

							{/* Display units */}
							<label className='flex items-center gap-2 text-[11px]'>
								<span className='w-16 text-muted-foreground shrink-0'>
									{t('pptx.chart.displayUnits')}
								</span>
								<select
									disabled={!canEdit}
									className={INPUT}
									value={axis.displayUnits ?? ''}
									onChange={(e) =>
										onUpdateAxis(type, {
											displayUnits: (e.target.value ||
												undefined) as PptxChartAxisFormatting['displayUnits'],
										})
									}
								>
									{DISPLAY_UNITS_OPTIONS.map((opt) => (
										<option key={opt.value} value={opt.value}>
											{t(opt.labelKey)}
										</option>
									))}
								</select>
							</label>
						</div>
					)}

					<div className='space-y-1.5 ml-2'>
						{/* Axis title */}
						<label className='flex items-center gap-2 text-[11px]'>
							<span className='w-16 text-muted-foreground shrink-0'>
								{t('pptx.chart.axisTitle')}
							</span>
							<input
								type='text'
								disabled={!canEdit}
								className={INPUT}
								value={axis.titleText ?? ''}
								placeholder={t('pptx.chart.axisTitlePlaceholder')}
								onChange={(e) => onUpdateAxis(type, { titleText: e.target.value })}
							/>
						</label>

						{/* Number format */}
						<label className='flex items-center gap-2 text-[11px]'>
							<span className='w-16 text-muted-foreground shrink-0'>
								{t('pptx.chart.numberFormat')}
							</span>
							<input
								type='text'
								disabled={!canEdit}
								className={INPUT}
								value={axis.numFmt?.formatCode ?? ''}
								placeholder='General'
								onChange={(e) =>
									onUpdateAxis(type, {
										numFmt: e.target.value
											? { formatCode: e.target.value, sourceLinked: false }
											: undefined,
									})
								}
							/>
						</label>

						{/* Tick label position */}
						<label className='flex items-center gap-2 text-[11px]'>
							<span className='w-16 text-muted-foreground shrink-0'>
								{t('pptx.chart.tickLabels')}
							</span>
							<select
								disabled={!canEdit}
								className={INPUT}
								value={axis.tickLblPos ?? 'nextTo'}
								onChange={(e) =>
									onUpdateAxis(type, {
										tickLblPos: e.target.value as PptxChartAxisFormatting['tickLblPos'],
									})
								}
							>
								{TICK_LABEL_POSITION_OPTIONS.map((opt) => (
									<option key={opt.value} value={opt.value}>
										{t(opt.labelKey)}
									</option>
								))}
							</select>
						</label>

						{/* Gridlines */}
						<label className='flex items-center gap-2 cursor-pointer'>
							<input
								type='checkbox'
								disabled={!canEdit}
								checked={axis.majorGridlines ?? false}
								onChange={(e) => onUpdateAxis(type, { majorGridlines: e.target.checked })}
								className='accent-primary'
							/>
							<span className='text-[11px]'>{t('pptx.chart.majorGridlines')}</span>
						</label>
						<label className='flex items-center gap-2 cursor-pointer'>
							<input
								type='checkbox'
								disabled={!canEdit}
								checked={axis.minorGridlines ?? false}
								onChange={(e) => onUpdateAxis(type, { minorGridlines: e.target.checked })}
								className='accent-primary'
							/>
							<span className='text-[11px]'>{t('pptx.chart.minorGridlines')}</span>
						</label>
					</div>
				</div>
			))}
		</div>
	);
}

// packages/vue/src/viewer/components/inspector/ChartAxisOptions.vue
<script setup lang="ts">
import type { PptxChartAxisFormatting } from 'pptx-viewer-core';
import {
	DISPLAY_UNITS_OPTIONS,
	EDITABLE_AXIS_ROWS,
	TICK_LABEL_POSITION_OPTIONS,
} from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * ChartAxisOptions: per-axis scale (min/max/major/minor), display units, axis
 * title text, number format, tick-label position, and major/minor gridline
 * visibility. Mirrors React's `ChartAxisOptions`. Emits `updateAxis(type,patch)`.
 */
const props = defineProps<{
	axes: readonly PptxChartAxisFormatting[] | undefined;
}>();

const emit = defineEmits<{
	updateAxis: [
		axisType: PptxChartAxisFormatting['axisType'],
		patch: Partial<PptxChartAxisFormatting>,
	];
}>();

const { t } = useI18n();

type AxisRow = (typeof EDITABLE_AXIS_ROWS)[number] & { axis: PptxChartAxisFormatting };

const rows = computed<AxisRow[]>(() =>
	EDITABLE_AXIS_ROWS.map((row) => ({
		...row,
		axis: props.axes?.find((a) => a.axisType === row.type),
	})).filter((row): row is AxisRow => Boolean(row.axis)),
);

type ScaleKey = 'min' | 'max' | 'majorUnit' | 'minorUnit';

function onNumber(
	event: Event,
	axisType: PptxChartAxisFormatting['axisType'],
	key: ScaleKey,
): void {
	const raw = (event.target as HTMLInputElement).value;
	if (raw === '') {
		emit('updateAxis', axisType, { [key]: undefined });
		return;
	}
	const num = Number.parseFloat(raw);
	if (Number.isFinite(num)) {
		emit('updateAxis', axisType, { [key]: num });
	}
}

function onDisplayUnits(event: Event, axisType: PptxChartAxisFormatting['axisType']): void {
	const value = (event.target as HTMLSelectElement).value;
	emit('updateAxis', axisType, {
		displayUnits: (value || undefined) as PptxChartAxisFormatting['displayUnits'],
	});
}

function onTitle(event: Event, axisType: PptxChartAxisFormatting['axisType']): void {
	emit('updateAxis', axisType, { titleText: (event.target as HTMLInputElement).value });
}

function onNumberFormat(event: Event, axisType: PptxChartAxisFormatting['axisType']): void {
	const value = (event.target as HTMLInputElement).value;
	emit('updateAxis', axisType, {
		numFmt: value ? { formatCode: value, sourceLinked: false } : undefined,
	});
}

function onTickPos(event: Event, axisType: PptxChartAxisFormatting['axisType']): void {
	emit('updateAxis', axisType, {
		tickLblPos: (event.target as HTMLSelectElement).value as PptxChartAxisFormatting['tickLblPos'],
	});
}

function onGridline(
	event: Event,
	axisType: PptxChartAxisFormatting['axisType'],
	key: 'majorGridlines' | 'minorGridlines',
): void {
	emit('updateAxis', axisType, { [key]: (event.target as HTMLInputElement).checked });
}

const SCALE_FIELDS: ReadonlyArray<{ key: ScaleKey; labelKey: string }> = [
	{ key: 'min', labelKey: 'pptx.chart.min' },
	{ key: 'max', labelKey: 'pptx.chart.max' },
	{ key: 'majorUnit', labelKey: 'pptx.chart.majorUnit' },
	{ key: 'minorUnit', labelKey: 'pptx.chart.minorUnit' },
];

const INPUT = 'flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full';
</script>

<template>
	<div
		v-if="rows.length > 0"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.axes') }}
		</div>
		<div v-for="row in rows" :key="row.type" class="space-y-1.5">
			<div class="text-[11px] font-medium">{{ t(row.labelKey) }}</div>

			<div v-if="row.hasScale" class="space-y-1.5 ml-2">
				<label
					v-for="field in SCALE_FIELDS"
					:key="field.key"
					class="flex items-center gap-2 text-[11px]"
				>
					<span class="w-16 text-muted-foreground shrink-0">{{ t(field.labelKey) }}</span>
					<input
						type="number"
						:class="INPUT"
						data-testid="chart-axis-scale"
						:value="row.axis[field.key] ?? ''"
						:placeholder="t('pptx.chart.auto')"
						@input="onNumber($event, row.type, field.key)"
					/>
				</label>

				<label class="flex items-center gap-2 text-[11px]">
					<span class="w-16 text-muted-foreground shrink-0">{{
						t('pptx.chart.displayUnits')
					}}</span>
					<select
						:class="INPUT"
						data-testid="chart-axis-display-units"
						:value="row.axis.displayUnits ?? ''"
						@change="onDisplayUnits($event, row.type)"
					>
						<option v-for="opt in DISPLAY_UNITS_OPTIONS" :key="opt.value" :value="opt.value">
							{{ t(opt.labelKey) }}
						</option>
					</select>
				</label>
			</div>

			<div class="space-y-1.5 ml-2">
				<label class="flex items-center gap-2 text-[11px]">
					<span class="w-16 text-muted-foreground shrink-0">{{ t('pptx.chart.axisTitle') }}</span>
					<input
						type="text"
						:class="INPUT"
						data-testid="chart-axis-title"
						:value="row.axis.titleText ?? ''"
						:placeholder="t('pptx.chart.axisTitlePlaceholder')"
						@input="onTitle($event, row.type)"
					/>
				</label>

				<label class="flex items-center gap-2 text-[11px]">
					<span class="w-16 text-muted-foreground shrink-0">{{
						t('pptx.chart.numberFormat')
					}}</span>
					<input
						type="text"
						:class="INPUT"
						data-testid="chart-axis-number-format"
						:value="row.axis.numFmt?.formatCode ?? ''"
						placeholder="General"
						@input="onNumberFormat($event, row.type)"
					/>
				</label>

				<label class="flex items-center gap-2 text-[11px]">
					<span class="w-16 text-muted-foreground shrink-0">{{ t('pptx.chart.tickLabels') }}</span>
					<select
						:class="INPUT"
						data-testid="chart-axis-tick-pos"
						:value="row.axis.tickLblPos ?? 'nextTo'"
						@change="onTickPos($event, row.type)"
					>
						<option v-for="opt in TICK_LABEL_POSITION_OPTIONS" :key="opt.value" :value="opt.value">
							{{ t(opt.labelKey) }}
						</option>
					</select>
				</label>

				<label class="flex items-center gap-2 cursor-pointer">
					<input
						type="checkbox"
						data-testid="chart-axis-major-gridlines"
						class="accent-primary"
						:checked="row.axis.majorGridlines ?? false"
						@change="onGridline($event, row.type, 'majorGridlines')"
					/>
					<span class="text-[11px]">{{ t('pptx.chart.majorGridlines') }}</span>
				</label>
				<label class="flex items-center gap-2 cursor-pointer">
					<input
						type="checkbox"
						data-testid="chart-axis-minor-gridlines"
						class="accent-primary"
						:checked="row.axis.minorGridlines ?? false"
						@change="onGridline($event, row.type, 'minorGridlines')"
					/>
					<span class="text-[11px]">{{ t('pptx.chart.minorGridlines') }}</span>
				</label>
			</div>
		</div>
	</div>
</template>
