// packages/angular/src/viewer/chart-datapoint-marker-options.component.ts
/**
 * chart-datapoint-marker-options.component.ts: Per-data-point marker overrides.
 *
 * Selector: `pptx-chart-datapoint-marker-options`
 *
 * Mirrors React's `ChartDataPointMarkerOptions.tsx`, the one advanced chart
 * control Angular had never been given: `pptx-chart-datapoint-options` covers a
 * point's fill and slice explosion, but a `c:dPt` can also carry its own
 * `c:marker`, which replaces the series marker for that point alone (the usual
 * use is calling out a single outlier on an otherwise uniform line).
 *
 * The checkbox is the presence of the override, not a value: ticking it seeds a
 * circle, clearing it removes the whole `c:dPt/c:marker`. Edits route through
 * `setDataPointMarker`, which wraps core's headless op, so the `c:dPt`
 * bookkeeping matches React, Vue, Svelte and Vanilla exactly.
 *
 * @module angular-viewer/chart-datapoint-marker-options
 */

import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type {
	ChartPptxElement,
	PptxChartMarker,
	PptxChartMarkerSymbol,
	PptxChartSeries,
	PptxChartType,
} from 'pptx-viewer-core';

import { MARKER_SUPPORTED_TYPES, MARKER_SYMBOL_OPTIONS } from '../internal/shared';
import { setDataPointMarker } from './chart-data-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { boolFromEvent, numFromEvent, selectValue, stringFromEvent } from './chart-event-helpers';

/** Concrete symbols only; '' is the "series default" sentinel, which the
 * presence checkbox already expresses. */
const SYMBOL_OPTIONS = MARKER_SYMBOL_OPTIONS.filter((option) => option.value !== '');

@Component({
	selector: 'pptx-chart-datapoint-marker-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (supported()) {
			<section class="pptx-chart-card" [attr.aria-label]="'pptx.chart.pointMarkers' | translate">
				<h4 class="pptx-chart-card__heading">{{ 'pptx.chart.pointMarkers' | translate }}</h4>

				@if (series().length > 1) {
					<label class="pptx-chart-card__row">
						<span class="pptx-chart-card__label">{{ 'pptx.chart.series' | translate }}</span>
						<select
							[attr.aria-label]="'pptx.chart.series' | translate"
							class="pptx-chart-card__input"
							[disabled]="!canEdit()"
							[value]="activeIndex()"
							(change)="onSeries($event)"
						>
							@for (s of series(); track $index; let i = $index) {
								<option [value]="i">{{ s.name }}</option>
							}
						</select>
					</label>
				}

				<div class="pptx-chart-card__group">
					@for (cat of categories(); track $index; let ci = $index) {
						<div class="pptx-chart-card__row">
							<span class="pptx-chart-card__name" [title]="cat">{{ cat }}</span>
							<label class="pptx-chart-card__check">
								<input
									type="checkbox"
									[disabled]="!canEdit()"
									[checked]="markerAt(ci) !== undefined"
									(change)="onToggle(ci, $event)"
								/>
								{{ 'pptx.chart.markerOverride' | translate }}
							</label>
						</div>

						@if (markerAt(ci); as marker) {
							<div class="pptx-chart-card__row pptx-chart-card__group--indent">
								<select
									class="pptx-chart-card__input"
									[disabled]="!canEdit()"
									[value]="marker.symbol"
									(change)="onSymbol(ci, $event)"
								>
									@for (opt of symbolOptions; track opt.value) {
										<option [value]="opt.value">{{ opt.labelKey | translate }}</option>
									}
								</select>
								<input
									type="number"
									min="1"
									max="20"
									class="pptx-chart-card__input pptx-chart-card__input--num"
									[title]="'pptx.chart.markerSize' | translate"
									[placeholder]="'pptx.chart.auto' | translate"
									[disabled]="!canEdit()"
									[value]="marker.size ?? ''"
									(change)="onSize(ci, $event)"
								/>
								<input
									type="color"
									class="pptx-chart-card__color"
									[title]="'pptx.chart.markerFill' | translate"
									[disabled]="!canEdit()"
									[value]="marker.spPr?.fillColor ?? '#4472c4'"
									(input)="onFill(ci, $event)"
								/>
							</div>
						}
					}
				</div>
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartDatapointMarkerOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	protected readonly symbolOptions = SYMBOL_OPTIONS;

	private readonly seriesIndex = signal(0);

	protected readonly series = computed<PptxChartSeries[]>(
		() => this.element().chartData?.series ?? [],
	);
	protected readonly categories = computed<string[]>(
		() => this.element().chartData?.categories ?? [],
	);

	/** Clamp the picker: removing a series must not strand the index past the end. */
	protected readonly activeIndex = computed(() =>
		Math.min(this.seriesIndex(), Math.max(0, this.series().length - 1)),
	);

	protected readonly supported = computed(() => {
		const type = this.element().chartData?.chartType as PptxChartType | undefined;
		return (
			type !== undefined &&
			MARKER_SUPPORTED_TYPES.has(type) &&
			this.series().length > 0 &&
			this.categories().length > 0
		);
	});

	protected markerAt(pointIndex: number): PptxChartMarker | undefined {
		return this.series()[this.activeIndex()]?.dataPoints?.find((p) => p.idx === pointIndex)?.marker;
	}

	protected onSeries(event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		const num = Number.parseInt(value, 10);
		if (Number.isFinite(num)) {
			this.seriesIndex.set(num);
		}
	}

	protected onToggle(pointIndex: number, event: Event): void {
		this.emit(pointIndex, boolFromEvent(event) ? { symbol: 'circle' } : null);
	}

	protected onSymbol(pointIndex: number, event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.emit(pointIndex, { symbol: value as PptxChartMarkerSymbol });
	}

	protected onSize(pointIndex: number, event: Event): void {
		const num = numFromEvent(event);
		this.emit(pointIndex, { size: typeof num === 'number' ? num : undefined });
	}

	protected onFill(pointIndex: number, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.emit(pointIndex, { fillColor: value });
	}

	private emit(
		pointIndex: number,
		marker: { symbol?: PptxChartMarkerSymbol; size?: number; fillColor?: string } | null,
	): void {
		this.elementChange.emit(
			setDataPointMarker(this.element(), this.activeIndex(), pointIndex, marker),
		);
	}
}

// packages/vue/src/viewer/components/inspector/ChartDataPointMarkerOptions.vue
<script setup lang="ts">
import type {
	PptxChartDataPoint,
	PptxChartMarkerSymbol,
	PptxChartSeries,
	PptxChartType,
} from 'pptx-viewer-core';
import { MARKER_SUPPORTED_TYPES, MARKER_SYMBOL_OPTIONS } from 'pptx-viewer-shared';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import type { ChartMarkerEdit } from '../../composables/useChartEditing';

/**
 * ChartDataPointMarkerOptions: per-data-point marker overrides for line/scatter/
 * bubble/radar charts, targeting one series at a time. Mirrors React's
 * `ChartDataPointMarkerOptions`. Emits `setPointMarker(seriesIndex, pointIndex,
 * edit)` where `null` clears the override.
 */
const props = defineProps<{
	chartType: PptxChartType;
	categories: readonly string[];
	series: readonly PptxChartSeries[];
}>();

const emit = defineEmits<{
	setPointMarker: [seriesIndex: number, pointIndex: number, marker: ChartMarkerEdit | null];
}>();

// Concrete symbols only (drop the '' auto sentinel used by the series picker).
const SYMBOL_OPTIONS = MARKER_SYMBOL_OPTIONS.filter((o) => o.value !== '');

const { t } = useI18n();

const seriesIndex = ref(0);

const visible = computed(
	() =>
		MARKER_SUPPORTED_TYPES.has(props.chartType) &&
		props.series.length > 0 &&
		props.categories.length > 0,
);

const activeIndex = computed(() => Math.min(seriesIndex.value, props.series.length - 1));
const activeSeries = computed<PptxChartSeries | undefined>(() => props.series[activeIndex.value]);

function pointFor(idx: number): PptxChartDataPoint | undefined {
	return activeSeries.value?.dataPoints?.find((p) => p.idx === idx);
}

function onSeriesPick(event: Event): void {
	seriesIndex.value = Number.parseInt((event.target as HTMLSelectElement).value, 10);
}

function onToggle(event: Event, idx: number): void {
	const checked = (event.target as HTMLInputElement).checked;
	emit('setPointMarker', activeIndex.value, idx, checked ? { symbol: 'circle' } : null);
}

function onSymbol(event: Event, idx: number): void {
	emit('setPointMarker', activeIndex.value, idx, {
		symbol: (event.target as HTMLSelectElement).value as PptxChartMarkerSymbol,
	});
}

function onSize(event: Event, idx: number): void {
	const num = Number.parseInt((event.target as HTMLInputElement).value, 10);
	emit('setPointMarker', activeIndex.value, idx, { size: Number.isFinite(num) ? num : undefined });
}

function onFill(event: Event, idx: number): void {
	emit('setPointMarker', activeIndex.value, idx, {
		fillColor: (event.target as HTMLInputElement).value,
	});
}
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.pointMarkers') }}
		</div>

		<label v-if="props.series.length > 1" class="flex items-center gap-2 text-[11px]">
			<span class="w-12 text-muted-foreground shrink-0">{{ t('pptx.chart.series') }}</span>
			<select
				:aria-label="t('pptx.chart.series')"
				class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
				data-testid="chart-point-marker-series"
				:value="activeIndex"
				@change="onSeriesPick"
			>
				<option v-for="(s, i) in props.series" :key="`${s.name}-${i}`" :value="i">
					{{ s.name }}
				</option>
			</select>
		</label>

		<div class="space-y-2">
			<div v-for="(cat, idx) in props.categories" :key="`${cat}-${idx}`" class="space-y-1">
				<div class="flex items-center gap-2 text-[11px]">
					<span class="flex-1 truncate" :title="cat">{{ cat }}</span>
					<label class="flex items-center gap-1 shrink-0">
						<input
							type="checkbox"
							data-testid="chart-point-marker-toggle"
							:checked="pointFor(idx)?.marker !== undefined"
							@change="onToggle($event, idx)"
						/>
						<span class="text-muted-foreground">{{ t('pptx.chart.markerOverride') }}</span>
					</label>
				</div>

				<div v-if="pointFor(idx)?.marker" class="flex items-center gap-2 ml-2 flex-wrap">
					<select
						class="bg-muted border border-border rounded px-1.5 py-0.5 text-[11px]"
						data-testid="chart-point-marker-symbol"
						:value="pointFor(idx)?.marker?.symbol"
						@change="onSymbol($event, idx)"
					>
						<option v-for="opt in SYMBOL_OPTIONS" :key="opt.value" :value="opt.value">
							{{ t(opt.labelKey) }}
						</option>
					</select>
					<input
						type="number"
						min="1"
						max="20"
						data-testid="chart-point-marker-size"
						class="w-14 bg-muted border border-border rounded px-1.5 py-0.5 text-[11px]"
						:value="pointFor(idx)?.marker?.size ?? ''"
						:placeholder="t('pptx.chart.auto')"
						:title="t('pptx.chart.markerSize')"
						@input="onSize($event, idx)"
					/>
					<input
						type="color"
						data-testid="chart-point-marker-fill"
						class="h-6 w-8 cursor-pointer rounded border border-border bg-transparent"
						:value="pointFor(idx)?.marker?.spPr?.fillColor ?? '#4472c4'"
						:title="t('pptx.chart.markerFill')"
						@input="onFill($event, idx)"
					/>
				</div>
			</div>
		</div>
	</div>
</template>
