// packages/svelte/src/viewer/components/inspector/CustomPropertiesBlock.svelte
<script lang="ts">
	/**
	 * CustomPropertiesBlock: editable custom document properties (name / value
	 * rows + add / remove), the Svelte port of Vue's `CustomPropertiesBlock`
	 * (React `inspector/DocumentPropertiesCards.tsx`). Emits the full
	 * replacement array on every change.
	 */
	import type { PptxCustomProperty } from 'pptx-viewer-core';

	import { useTranslator } from '../../../i18n/context';

	const {
		customProperties,
		canEdit = true,
		onupdate,
	}: {
		customProperties: PptxCustomProperty[];
		canEdit?: boolean;
		onupdate: (next: PptxCustomProperty[]) => void;
	} = $props();
	const t = useTranslator();

	function addProperty(): void {
		onupdate([
			...customProperties,
			{ name: `Property ${customProperties.length + 1}`, value: '', type: 'lpwstr' },
		]);
	}

	function patchAt(index: number, patch: Partial<PptxCustomProperty>): void {
		onupdate(customProperties.map((entry, i) => (i === index ? { ...entry, ...patch } : entry)));
	}

	function removeAt(index: number): void {
		onupdate(customProperties.filter((_, i) => i !== index));
	}
</script>

<div class="pptx-svelte-custom-props">
	<div class="head">
		<span>{t('pptx.documentProperties.custom.heading')}</span>
		{#if canEdit}
			<button type="button" onclick={addProperty}>{t('pptx.documentProperties.custom.add')}</button>
		{/if}
	</div>
	{#if customProperties.length === 0}
		<p class="empty">{t('pptx.documentProperties.custom.empty')}</p>
	{/if}
	{#each customProperties as entry, index (index)}
		<div class="row">
			<input
				type="text"
				aria-label={t('pptx.documentProperties.custom.heading')}
				disabled={!canEdit}
				value={entry.name}
				onchange={(event) => patchAt(index, { name: event.currentTarget.value })}
			/>
			<input
				type="text"
				aria-label={entry.name}
				disabled={!canEdit}
				value={entry.value}
				onchange={(event) => patchAt(index, { value: event.currentTarget.value })}
			/>
			{#if canEdit}
				<button type="button" class="remove" onclick={() => removeAt(index)}>×</button>
			{/if}
		</div>
	{/each}
</div>

<style>
	.pptx-svelte-custom-props {
		display: grid;
		gap: 5px;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 11px;
	}

	.head {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
	}

	.empty {
		margin: 0;
		font-size: 10px;
	}

	.row {
		display: grid;
		grid-template-columns: 1fr 1fr auto;
		gap: 4px;
	}

	input {
		min-width: 0;
		height: 25px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 5px;
		background: var(--pptx-background, #11111b);
		color: inherit;
	}

	button {
		padding: 3px 7px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 5px;
		background: var(--pptx-muted, #2a2a3d);
		color: inherit;
		cursor: pointer;
		font: inherit;
		font-size: 11px;
	}

	.remove {
		color: #f87171;
	}
</style>

// packages/vue/src/viewer/components/inspector/CustomPropertiesBlock.vue
<script setup lang="ts">
/**
 * CustomPropertiesBlock: editable custom document properties (name / value
 * rows + add / remove), mirroring React's `CustomPropertiesBlock` in
 * `inspector/DocumentPropertiesCards.tsx`. Emits the full replacement array.
 */
import type { PptxCustomProperty } from 'pptx-viewer-core';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import { BTN, INPUT } from './inspector-cards';

const props = withDefaults(
	defineProps<{
		customProperties: PptxCustomProperty[];
		canEdit?: boolean;
	}>(),
	{ canEdit: true },
);

const emit = defineEmits<{ update: [props: PptxCustomProperty[]] }>();

const { t } = useI18n();

function addProperty(): void {
	emit('update', [
		...props.customProperties,
		{ name: `Property ${props.customProperties.length + 1}`, value: '', type: 'lpwstr' },
	]);
}

function patchAt(index: number, patch: Partial<PptxCustomProperty>): void {
	emit(
		'update',
		props.customProperties.map((entry, i) => (i === index ? { ...entry, ...patch } : entry)),
	);
}

function removeAt(index: number): void {
	emit(
		'update',
		props.customProperties.filter((_, i) => i !== index),
	);
}
</script>

<template>
	<div class="space-y-1">
		<div class="flex items-center justify-between">
			<span class="text-muted-foreground">{{ t('pptx.documentProperties.custom.heading') }}</span>
			<button v-if="props.canEdit" type="button" :class="BTN" @click="addProperty">
				{{ t('pptx.documentProperties.custom.add') }}
			</button>
		</div>
		<div v-if="props.customProperties.length === 0" class="text-[10px] text-muted-foreground">
			{{ t('pptx.documentProperties.custom.empty') }}
		</div>
		<div
			v-for="(entry, index) in props.customProperties"
			:key="`${entry.name}-${index}`"
			class="grid grid-cols-[1fr,1fr,auto] gap-1"
		>
			<input
				type="text"
				:class="INPUT"
				:disabled="!props.canEdit"
				:value="entry.name"
				@input="(e) => patchAt(index, { name: (e.target as HTMLInputElement).value })"
			/>
			<input
				type="text"
				:class="INPUT"
				:disabled="!props.canEdit"
				:value="entry.value"
				@input="(e) => patchAt(index, { value: (e.target as HTMLInputElement).value })"
			/>
			<button
				v-if="props.canEdit"
				type="button"
				:class="cn(BTN, 'px-1.5 text-red-400 hover:text-red-300')"
				@click="removeAt(index)"
			>
				×
			</button>
		</div>
	</div>
</template>
