// packages/react/src/viewer/components/inspector/DirectionPicker.tsx
import React from "react";
import { useTranslation } from "react-i18next";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Arrow labels for direction tokens. */
export const DIR_ARROWS: Record<string, string> = {
  l: "\u2190",
  r: "\u2192",
  u: "\u2191",
  d: "\u2193",
  lu: "\u2196",
  ld: "\u2199",
  ru: "\u2197",
  rd: "\u2198",
  in: "\u25C9",
  out: "\u25CE",
  horz: "\u2194",
  vert: "\u2195",
};

/** Grid positions for 4/8-direction layout. */
const GRID_POSITIONS: Record<string, [number, number]> = {
  lu: [0, 0],
  u: [0, 1],
  ru: [0, 2],
  l: [1, 0],
  r: [1, 2],
  ld: [2, 0],
  d: [2, 1],
  rd: [2, 2],
};

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface DirectionPickerProps {
  directions: readonly string[];
  value: string | undefined;
  onChange: (dir: string) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function DirectionPicker({
  directions,
  value,
  onChange,
}: DirectionPickerProps): React.ReactElement {
  const { t } = useTranslation();

  if (directions.length <= 3) {
    return (
      <div className="flex gap-1">
        {directions.map((dir) => (
          <button
            key={dir}
            type="button"
            onClick={() => onChange(dir)}
            className={`px-2 py-1 rounded text-xs border ${
              value === dir
                ? "bg-primary text-primary-foreground border-primary"
                : "bg-muted border-border hover:bg-accent"
            }`}
            title={t(`pptx.transition.dir.${dir}`, dir)}
          >
            {DIR_ARROWS[dir] ?? dir}
          </button>
        ))}
      </div>
    );
  }

  const cells: (string | null)[][] = [
    [null, null, null],
    [null, null, null],
    [null, null, null],
  ];

  for (const dir of directions) {
    const pos = GRID_POSITIONS[dir];
    if (pos) cells[pos[0]][pos[1]] = dir;
  }

  return (
    <div className="inline-grid grid-cols-3 gap-0.5">
      {cells.flatMap((row, ri) =>
        row.map((cell, ci) => {
          if (!cell) return <div key={`${ri}-${ci}`} className="w-6 h-6" />;
          return (
            <button
              key={cell}
              type="button"
              onClick={() => onChange(cell)}
              className={`w-6 h-6 rounded text-xs flex items-center justify-center border ${
                value === cell
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-muted border-border hover:bg-accent"
              }`}
              title={t(`pptx.transition.dir.${cell}`, cell)}
            >
              {DIR_ARROWS[cell] ?? cell}
            </button>
          );
        }),
      )}
    </div>
  );
}

// packages/vue/src/viewer/components/inspector/DirectionPicker.vue
<script setup lang="ts">
/**
 * DirectionPicker: choose a transition direction token. Vue port of React's
 * `DirectionPicker`. Renders a row for 3-or-fewer directions, otherwise a 3x3
 * arrow grid placed by compass position.
 */
import { computed } from 'vue';

/** Arrow glyphs for direction tokens. */
const DIR_ARROWS: Record<string, string> = {
	l: '←',
	r: '→',
	u: '↑',
	d: '↓',
	lu: '↖',
	ld: '↙',
	ru: '↗',
	rd: '↘',
	in: '◉',
	out: '◎',
	horz: '↔',
	vert: '↕',
};

/** Grid positions (row, col) for the 8-direction layout. */
const GRID_POSITIONS: Record<string, [number, number]> = {
	lu: [0, 0],
	u: [0, 1],
	ru: [0, 2],
	l: [1, 0],
	r: [1, 2],
	ld: [2, 0],
	d: [2, 1],
	rd: [2, 2],
};

const props = defineProps<{ directions: readonly string[]; value: string | undefined }>();
const emit = defineEmits<{ change: [direction: string] }>();

const isGrid = computed(() => props.directions.length > 3);

/** 3x3 grid cells, each holding a direction token or null (empty slot). */
const cells = computed<(string | null)[]>(() => {
	const grid: (string | null)[] = Array.from({ length: 9 }, () => null);
	for (const dir of props.directions) {
		const pos = GRID_POSITIONS[dir];
		if (pos) {
			grid[pos[0] * 3 + pos[1]] = dir;
		}
	}
	return grid;
});

function glyph(dir: string): string {
	return DIR_ARROWS[dir] ?? dir;
}
</script>

<template>
	<div v-if="!isGrid" class="flex gap-1">
		<button
			v-for="dir in directions"
			:key="dir"
			type="button"
			class="rounded border px-2 py-1 text-xs"
			:class="
				value === dir
					? 'border-primary bg-primary text-white'
					: 'border-border bg-muted hover:bg-accent'
			"
			:title="dir"
			:aria-pressed="value === dir"
			@click="emit('change', dir)"
		>
			{{ glyph(dir) }}
		</button>
	</div>
	<div v-else class="inline-grid grid-cols-3 gap-0.5">
		<template v-for="(cell, i) in cells" :key="i">
			<div v-if="!cell" class="h-6 w-6" />
			<button
				v-else
				type="button"
				class="flex h-6 w-6 items-center justify-center rounded border text-xs"
				:class="
					value === cell
						? 'border-primary bg-primary text-white'
						: 'border-border bg-muted hover:bg-accent'
				"
				:title="cell"
				:aria-pressed="value === cell"
				@click="emit('change', cell)"
			>
				{{ glyph(cell) }}
			</button>
		</template>
	</div>
</template>
