// packages/react/src/viewer/components/inspector/ImageAdjustmentsPanel.tsx
/**
 * Inspector panel for alpha (transparency) and bi-level (1-bit threshold)
 * image adjustments.  Maps to `a:alphaModFix` and `a:biLevel` in OOXML.
 */
import React, { useCallback, useMemo } from "react";
import { useTranslation } from "react-i18next";

import type {
  PptxElement,
  PptxImageEffects,
} from "pptx-viewer-core";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface ImageAdjustmentsPanelProps {
  selectedElement: PptxElement;
  canEdit: boolean;
  onUpdateElement: (updates: Partial<PptxElement>) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ImageAdjustmentsPanel({
  selectedElement,
  canEdit,
  onUpdateElement,
}: ImageAdjustmentsPanelProps): React.ReactElement {
  const { t } = useTranslation();

  const effects: PptxImageEffects | undefined = useMemo(
    () =>
      "imageEffects" in selectedElement
        ? (selectedElement as unknown as { imageEffects?: PptxImageEffects })
            .imageEffects
        : undefined,
    [selectedElement],
  );

  // alphaModFix: 100 = fully opaque.  PowerPoint shows "Transparency" inverted.
  const alphaModFix = effects?.alphaModFix ?? 100;
  const transparency = 100 - alphaModFix;

  const biLevelThreshold = effects?.biLevel ?? 0;

  const hasValues =
    effects?.alphaModFix !== undefined || effects?.biLevel !== undefined;

  // ── handlers ──────────────────────────────────────────────────────────

  const commitEffects = useCallback(
    (patch: Partial<PptxImageEffects>) => {
      onUpdateElement({
        imageEffects: {
          ...(effects ?? {}),
          ...patch,
        },
      } as Partial<PptxElement>);
    },
    [effects, onUpdateElement],
  );

  const handleTransparencyChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const val = Number(e.target.value);
      commitEffects({ alphaModFix: 100 - val });
    },
    [commitEffects],
  );

  const handleBiLevelChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      commitEffects({ biLevel: Number(e.target.value) });
    },
    [commitEffects],
  );

  const handleReset = useCallback(() => {
    commitEffects({ alphaModFix: undefined, biLevel: undefined });
  }, [commitEffects]);

  // ── render ────────────────────────────────────────────────────────────

  return (
    <div className="space-y-3 text-[11px]">
      <div className="flex items-center justify-between">
        <span className="text-muted-foreground font-medium">
          {t("pptx.imageAdjustments.title")}
        </span>
        {hasValues && (
          <button
            type="button"
            disabled={!canEdit}
            className="rounded bg-muted hover:bg-accent border border-border px-1.5 py-0.5 text-[10px] text-foreground disabled:opacity-50"
            onClick={handleReset}
          >
            {t("common.reset")}
          </button>
        )}
      </div>

      {/* Transparency slider */}
      <label className="flex flex-col gap-1">
        <span className="text-muted-foreground">
          {t("pptx.imageAdjustments.transparency")}
        </span>
        <div className="flex items-center gap-2">
          <input
            type="range"
            min={0}
            max={100}
            step={1}
            disabled={!canEdit}
            className="accent-primary flex-1"
            value={transparency}
            onChange={handleTransparencyChange}
          />
          <span className="w-8 text-right tabular-nums text-muted-foreground">
            {transparency}%
          </span>
        </div>
      </label>

      {/* Bi-Level threshold slider */}
      <label className="flex flex-col gap-1">
        <span className="text-muted-foreground">
          {t("pptx.imageAdjustments.biLevelThreshold")}
        </span>
        <p className="text-[10px] text-muted-foreground/70">
          {t("pptx.imageAdjustments.biLevelDescription")}
        </p>
        <div className="flex items-center gap-2">
          <input
            type="range"
            min={0}
            max={100}
            step={1}
            disabled={!canEdit}
            className="accent-primary flex-1"
            value={biLevelThreshold}
            onChange={handleBiLevelChange}
          />
          <span className="w-8 text-right tabular-nums text-muted-foreground">
            {biLevelThreshold}
          </span>
        </div>
      </label>
    </div>
  );
}

// packages/vue/src/viewer/components/inspector/ImageAdjustmentsPanel.vue
<script setup lang="ts">
import type { PptxElement, PptxImageEffects } from 'pptx-viewer-core';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { mergeEffectsPatch } from '../../composables/useImageEditing';

/**
 * ImageAdjustmentsPanel: brightness / contrast / saturation sliders plus the
 * alpha (transparency) and bi-level (1-bit threshold) adjustments. Emits the
 * FULL merged `imageEffects` sub-object per change, exactly like ImagePanel.
 *
 * `alphaModFix` is stored as opacity (100 = fully opaque); PowerPoint's UI
 * shows it inverted as "Transparency", so we present `100 - alphaModFix`.
 */
const props = defineProps<{
	fx: PptxImageEffects | undefined;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxElement>];
}>();

const { t } = useI18n();

const brightness = computed<number>(() => props.fx?.brightness ?? 0);
const contrast = computed<number>(() => props.fx?.contrast ?? 0);
const saturation = computed<number>(() => props.fx?.saturation ?? 0);

const transparency = computed<number>(() => 100 - (props.fx?.alphaModFix ?? 100));
const biLevel = computed<number>(() => props.fx?.biLevel ?? 0);

const hasThreshold = computed<boolean>(
	() => props.fx?.alphaModFix !== undefined || props.fx?.biLevel !== undefined,
);

function commit(patch: Partial<PptxImageEffects>): void {
	emit('update', mergeEffectsPatch(props.fx, patch));
}

function onBrightness(event: Event): void {
	commit({ brightness: Number((event.target as HTMLInputElement).value) });
}
function onContrast(event: Event): void {
	commit({ contrast: Number((event.target as HTMLInputElement).value) });
}
function onSaturation(event: Event): void {
	commit({ saturation: Number((event.target as HTMLInputElement).value) });
}
function onTransparency(event: Event): void {
	commit({ alphaModFix: 100 - Number((event.target as HTMLInputElement).value) });
}
function onBiLevel(event: Event): void {
	commit({ biLevel: Number((event.target as HTMLInputElement).value) });
}
function onResetThreshold(): void {
	commit({ alphaModFix: undefined, biLevel: undefined });
}
</script>

<template>
	<div class="pptx-vue-image-adjust flex flex-col gap-2 text-[11px]">
		<label class="pptx-vue-image-adjust__slider grid grid-cols-[72px_1fr_36px] items-center gap-2">
			<span class="text-muted-foreground">{{ t('pptx.imageAdjustments.brightness') }}</span>
			<input
				type="range"
				class="w-full accent-primary"
				min="-100"
				max="100"
				step="1"
				:value="brightness"
				@input="onBrightness"
			/>
			<span class="text-right tabular-nums text-muted-foreground">{{ brightness }}</span>
		</label>

		<label class="pptx-vue-image-adjust__slider grid grid-cols-[72px_1fr_36px] items-center gap-2">
			<span class="text-muted-foreground">{{ t('pptx.imageAdjustments.contrast') }}</span>
			<input
				type="range"
				class="w-full accent-primary"
				min="-100"
				max="100"
				step="1"
				:value="contrast"
				@input="onContrast"
			/>
			<span class="text-right tabular-nums text-muted-foreground">{{ contrast }}</span>
		</label>

		<label class="pptx-vue-image-adjust__slider grid grid-cols-[72px_1fr_36px] items-center gap-2">
			<span class="text-muted-foreground">{{ t('pptx.image.saturation') }}</span>
			<input
				type="range"
				class="w-full accent-primary"
				min="-100"
				max="100"
				step="1"
				:value="saturation"
				@input="onSaturation"
			/>
			<span class="text-right tabular-nums text-muted-foreground">{{ saturation }}</span>
		</label>

		<div class="pptx-vue-image-adjust__head flex items-center justify-between pt-1">
			<span class="font-semibold text-muted-foreground">{{
				t('pptx.imageAdjustments.title')
			}}</span>
			<button
				v-if="hasThreshold"
				type="button"
				class="pptx-vue-image-adjust__reset rounded border border-border bg-muted hover:bg-accent px-1.5 py-0.5 text-[10px] transition-colors"
				@click="onResetThreshold"
			>
				{{ t('pptx.imageAdjustments.reset') }}
			</button>
		</div>

		<label class="pptx-vue-image-adjust__slider grid grid-cols-[72px_1fr_36px] items-center gap-2">
			<span class="text-muted-foreground">{{ t('pptx.imageAdjustments.transparency') }}</span>
			<input
				type="range"
				class="w-full accent-primary"
				min="0"
				max="100"
				step="1"
				:value="transparency"
				@input="onTransparency"
			/>
			<span class="text-right tabular-nums text-muted-foreground">{{ transparency }}%</span>
		</label>

		<label class="pptx-vue-image-adjust__slider grid grid-cols-[72px_1fr_36px] items-center gap-2">
			<span class="text-muted-foreground">{{ t('pptx.imageAdjustments.biLevelThreshold') }}</span>
			<input
				type="range"
				class="w-full accent-primary"
				min="0"
				max="100"
				step="1"
				:value="biLevel"
				@input="onBiLevel"
			/>
			<span class="text-right tabular-nums text-muted-foreground">{{ biLevel }}</span>
		</label>
	</div>
</template>
