// packages/angular/src/viewer/notes-handout-card.component.ts
/**
 * notes-handout-card.component.ts: NOTES & HANDOUT card of the default
 * (no-selection) inspector, mirroring React's `NotesHandoutCard`: read-only
 * notes-page size and notes/handout master placeholder counts.
 */
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';

import { INSPECTOR_CARD_STYLES } from './inspector-card-styles';
import { LoadContentService } from './load-content.service';

@Component({
	selector: 'pptx-notes-handout-card',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<section class="icard" data-pptx-chrome="inspector-card">
			<h3 class="icard__heading" data-pptx-chrome="inspector-heading">
				{{ 'pptx.documentProperties.notesHandoutHeading' | translate }}
			</h3>
			<div class="icard__row">
				<span class="icard__label">{{ 'pptx.documentProperties.notesSize' | translate }}</span>
				<span class="icard__value">{{ notesSizeText() }}</span>
			</div>
			<div class="icard__row">
				<span class="icard__label">{{ 'pptx.master.notesMasterTitle' | translate }}</span>
				<span class="icard__value">{{ notesMasterText() }}</span>
			</div>
			<div class="icard__row">
				<span class="icard__label">{{ 'pptx.master.handoutMasterTitle' | translate }}</span>
				<span class="icard__value">{{ handoutMasterText() }}</span>
			</div>
		</section>
	`,
	styles: [INSPECTOR_CARD_STYLES],
})
export class NotesHandoutCardComponent {
	private readonly loader = inject(LoadContentService);
	private readonly translate = inject(TranslateService);

	private notAvailable(): string {
		return this.translate.instant('pptx.digitalSignatures.notAvailable');
	}

	private placeholders(count: number): string {
		return `${count} ${this.translate.instant('pptx.notesMaster.placeholders')}`;
	}

	protected readonly notesSizeText = computed(() => {
		const size = this.loader.notesCanvasSize();
		return size ? `${size.width} × ${size.height}px` : this.notAvailable();
	});

	protected readonly notesMasterText = computed(() => {
		const master = this.loader.notesMaster();
		return master ? this.placeholders(master.placeholders?.length ?? 0) : this.notAvailable();
	});

	protected readonly handoutMasterText = computed(() => {
		const master = this.loader.handoutMaster();
		return master ? this.placeholders(master.placeholders?.length ?? 0) : this.notAvailable();
	});
}

// packages/vue/src/viewer/components/inspector/NotesHandoutCard.vue
<script setup lang="ts">
/**
 * NotesHandoutCard: read-only NOTES & HANDOUT card (Notes Size / Notes Master /
 * Handout Master rows), mirroring React's `NotesHandoutCard` in
 * `inspector/DocumentPropertiesCards.tsx`.
 */
import type { PptxHandoutMaster, PptxNotesMaster } from 'pptx-viewer-core';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import type { CanvasSize } from '../../types';
import { CARD, HEADING } from './inspector-cards';

const props = defineProps<{
	notesCanvasSize?: CanvasSize;
	notesMaster?: PptxNotesMaster;
	handoutMaster?: PptxHandoutMaster;
}>();

const { t } = useI18n();

const rows = computed<Array<{ label: string; value: string }>>(() => [
	{
		label: t('pptx.documentProperties.notesSize'),
		value: props.notesCanvasSize
			? `${props.notesCanvasSize.width} × ${props.notesCanvasSize.height}px`
			: t('pptx.digitalSignatures.notAvailable'),
	},
	{
		label: t('pptx.master.notesMasterTitle'),
		value: props.notesMaster
			? `${props.notesMaster.placeholders?.length ?? 0} placeholders`
			: t('pptx.digitalSignatures.notAvailable'),
	},
	{
		label: t('pptx.master.handoutMasterTitle'),
		value: props.handoutMaster
			? `${props.handoutMaster.placeholders?.length ?? 0} placeholders`
			: t('pptx.digitalSignatures.notAvailable'),
	},
]);
</script>

<template>
	<div :class="CARD">
		<div :class="HEADING">{{ t('pptx.documentProperties.notesHandoutHeading') }}</div>
		<div class="space-y-1 text-[11px] text-muted-foreground">
			<div v-for="row in rows" :key="row.label" class="flex items-center justify-between gap-2">
				<span>{{ row.label }}</span>
				<span class="text-muted-foreground">{{ row.value }}</span>
			</div>
		</div>
	</div>
</template>
