// packages/react/src/viewer/components/inspector/SmartArtPropertiesPanel.tsx
import type {
	PptxElement,
	PptxSmartArtData,
	SmartArtColorScheme,
	SmartArtStyle,
} from 'pptx-viewer-core';
import {
	addSmartArtNodeAsChild,
	removeSmartArtNode,
	updateSmartArtNodeText,
} from 'pptx-viewer-core';
import React from 'react';
import { useTranslation } from 'react-i18next';

import { cn } from '../../utils';
import { HEADING, CARD, INPUT, BTN } from './inspector-pane-constants';
import {
	canAddTopLevelNode,
	canRemoveTopLevelNode,
	describeSmartArtBounds,
} from './smartart-node-limits';
import {
	addSiblingAfter,
	demote,
	promote,
	removeEmptyNode,
	reorder,
	siblingCount,
	siblingIndex,
} from './smartart-node-pane-handlers';
import { SmartArtLayoutSwitcher } from './SmartArtLayoutSwitcher';
import { SmartArtNodeRow } from './SmartArtNodeRow';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface SmartArtPropertiesPanelProps {
	smartArtData: PptxSmartArtData;
	canEdit: boolean;
	onUpdateElement: (updates: Partial<PptxElement>) => void;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const COLOR_SCHEMES: SmartArtColorScheme[] = [
	'colorful1',
	'colorful2',
	'colorful3',
	'monochromatic1',
	'monochromatic2',
];

const STYLE_OPTIONS: SmartArtStyle[] = ['flat', 'moderate', 'intense'];

/** Connection types that represent the plain parent/child tree we edit inline. */
const TREE_CONNECTION_TYPES = new Set(['parOf', 'presParOf', undefined]);

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function SmartArtPropertiesPanel({
	smartArtData,
	canEdit,
	onUpdateElement,
}: SmartArtPropertiesPanelProps): React.ReactElement {
	const { t } = useTranslation();
	const nodes = smartArtData.nodes ?? [];
	const layout = smartArtData.resolvedLayoutType;
	const topLevelCount = nodes.filter((n) => !n.parentId).length;

	// Focus the input of a node after a structural edit (Enter / Delete / move).
	const inputRefs = React.useRef<Map<string, HTMLInputElement | null>>(new Map());
	const pendingFocusId = React.useRef<string | null>(null);

	React.useEffect(() => {
		const id = pendingFocusId.current;
		if (id) {
			inputRefs.current.get(id)?.focus();
			pendingFocusId.current = null;
		}
	});

	const applySmartArtData = (newData: PptxSmartArtData, focusId?: string) => {
		if (focusId) {
			pendingFocusId.current = focusId;
		}
		onUpdateElement({ smartArtData: newData } as Partial<PptxElement>);
	};

	const updateSmartArt = (patch: Partial<PptxSmartArtData>) => {
		applySmartArtData({ ...smartArtData, ...patch });
	};

	const handleUpdateNodeText = (nodeId: string, text: string) => {
		applySmartArtData(updateSmartArtNodeText(smartArtData, nodeId, text));
	};

	const addNode = () => {
		if (!canAddTopLevelNode(layout, topLevelCount)) {
			return;
		}
		applySmartArtData(addSmartArtNodeAsChild(smartArtData));
	};

	const addSubItem = (parentId: string) => {
		applySmartArtData(addSmartArtNodeAsChild(smartArtData, parentId, 'Sub-item'));
	};

	const removeNode = (nodeId: string) => {
		const isTopLevel = !nodes.find((n) => n.id === nodeId)?.parentId;
		if (isTopLevel && !canRemoveTopLevelNode(layout, topLevelCount)) {
			return;
		}
		applySmartArtData(removeSmartArtNode(smartArtData, nodeId));
	};

	const moveNode = (nodeId: string, direction: 1 | -1) => {
		const next = reorder(smartArtData, nodeId, direction);
		if (next) {
			applySmartArtData(next, nodeId);
		}
	};

	const handleKeyDown = (e: React.KeyboardEvent, nodeId: string) => {
		const node = nodes.find((n) => n.id === nodeId);
		const isEmpty = !node?.text;

		if (e.key === 'Enter') {
			e.preventDefault();
			const result = addSiblingAfter(smartArtData, nodeId);
			if (result) {
				applySmartArtData(result.data, result.focusNodeId);
			}
		} else if ((e.key === 'Backspace' || e.key === 'Delete') && isEmpty) {
			const isTop = !node?.parentId;
			if (isTop && !canRemoveTopLevelNode(layout, topLevelCount)) {
				return;
			}
			e.preventDefault();
			const result = removeEmptyNode(smartArtData, nodeId);
			if (result) {
				applySmartArtData(result.data, result.focusNodeId);
			}
		} else if (e.key === 'Tab' && !e.shiftKey) {
			e.preventDefault();
			const next = demote(smartArtData, nodeId);
			if (next) {
				applySmartArtData(next, nodeId);
			}
		} else if (e.key === 'Tab' && e.shiftKey) {
			e.preventDefault();
			const next = promote(smartArtData, nodeId);
			if (next) {
				applySmartArtData(next, nodeId);
			}
		}
	};

	const setInputRef = (nodeId: string) => (el: HTMLInputElement | null) => {
		if (el) {
			inputRefs.current.set(nodeId, el);
		} else {
			inputRefs.current.delete(nodeId);
		}
	};

	const boundsHint = describeSmartArtBounds(layout);
	const addDisabled = !canEdit || !canAddTopLevelNode(layout, topLevelCount);

	// Connections beyond the editable parent/child tree (read-only awareness).
	const extraConnections = (smartArtData.connections ?? []).filter(
		(c) => !TREE_CONNECTION_TYPES.has(c.type),
	);

	let topDisplayIndex = 0;

	return (
		<div className={CARD} role='group' aria-label={t('pptx.smartart.title')}>
			<div className={HEADING}>{t('pptx.smartart.title')}</div>
			<div className='space-y-2'>
				<SmartArtLayoutSwitcher
					smartArtData={smartArtData}
					canEdit={canEdit}
					onUpdateSmartArt={updateSmartArt}
				/>

				<label className='flex flex-col gap-1 text-[11px]'>
					<span className='text-muted-foreground'>{t('pptx.smartart.colorScheme')}</span>
					<select
						disabled={!canEdit}
						aria-label={t('pptx.smartart.colorScheme')}
						className={cn(INPUT, 'w-full')}
						value={smartArtData.colorScheme ?? 'colorful1'}
						onChange={(e) => updateSmartArt({ colorScheme: e.target.value as SmartArtColorScheme })}
					>
						{COLOR_SCHEMES.map((cs) => (
							<option key={cs} value={cs}>
								{cs}
							</option>
						))}
					</select>
				</label>

				<label className='flex flex-col gap-1 text-[11px]'>
					<span className='text-muted-foreground'>{t('pptx.smartart.style')}</span>
					<div className='flex gap-1' role='group' aria-label={t('pptx.smartart.style')}>
						{STYLE_OPTIONS.map((s) => (
							<button
								key={s}
								type='button'
								disabled={!canEdit}
								aria-pressed={(smartArtData.style ?? 'flat') === s}
								className={cn(
									'flex-1 px-2 py-1 text-[10px] rounded border transition-colors',
									(smartArtData.style ?? 'flat') === s
										? 'border-primary bg-primary/20 text-primary'
										: 'border-border text-muted-foreground hover:bg-muted',
								)}
								onClick={() => updateSmartArt({ style: s })}
							>
								{s}
							</button>
						))}
					</div>
				</label>

				<div className='flex items-center justify-between'>
					<span className='text-[11px] text-muted-foreground'>
						{t('pptx.smartart.textPane')} ({nodes.length})
					</span>
					<button
						type='button'
						disabled={addDisabled}
						className={BTN}
						onClick={addNode}
						title={addDisabled ? boundsHint : undefined}
					>
						{t('pptx.smartart.addItem')}
					</button>
				</div>

				{boundsHint && (
					<div className='text-[9px] text-muted-foreground' role='note'>
						{boundsHint}
					</div>
				)}

				<div className='max-h-52 overflow-y-auto space-y-1 pr-1' role='list'>
					{nodes.map((node) => {
						const isChild = Boolean(node.parentId);
						if (!isChild) {
							topDisplayIndex += 1;
						}
						const sIdx = siblingIndex(smartArtData, node.id);
						const sCount = siblingCount(smartArtData, node.id);
						const removeDisabled =
							nodes.length <= 1 || (!isChild && !canRemoveTopLevelNode(layout, topLevelCount));
						return (
							<SmartArtNodeRow
								key={node.id}
								nodeId={node.id}
								text={node.text}
								displayIndex={topDisplayIndex}
								isChild={isChild}
								canEdit={canEdit}
								removeDisabled={removeDisabled}
								moveUpDisabled={sIdx <= 0}
								moveDownDisabled={sIdx < 0 || sIdx >= sCount - 1}
								inputRef={setInputRef(node.id)}
								onChangeText={handleUpdateNodeText}
								onKeyDown={handleKeyDown}
								onAddSubItem={addSubItem}
								onMoveUp={(id) => moveNode(id, -1)}
								onMoveDown={(id) => moveNode(id, 1)}
								onRemove={removeNode}
							/>
						);
					})}
				</div>

				{extraConnections.length > 0 && (
					<div className='text-[9px] text-muted-foreground' role='note'>
						{t('pptx.smartart.extraConnections', { count: extraConnections.length })}
					</div>
				)}

				<div className='text-[9px] text-muted-foreground mt-1'>{t('pptx.smartart.tabHint')}</div>
			</div>
		</div>
	);
}

// packages/vue/src/viewer/components/inspector/SmartArtPropertiesPanel.vue
<script setup lang="ts">
import type {
	PptxElement,
	PptxSmartArtData,
	PptxSmartArtNodeStyle,
	SmartArtColorScheme,
	SmartArtLayoutType,
	SmartArtStyle,
} from 'pptx-viewer-core';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import {
	SMARTART_COLOR_SCHEMES,
	SMARTART_STYLE_OPTIONS,
	useSmartArtEditing,
} from '../../composables/useSmartArtEditing';
import SmartArtLayoutSwitcher from './SmartArtLayoutSwitcher.vue';
import SmartArtNodeRow from './SmartArtNodeRow.vue';

/**
 * SmartArtPropertiesPanel: inspector panel for `smartArt` elements.
 *
 * Vue port of the React `SmartArtPropertiesPanel.tsx`. Provides per-node text
 * editing, keyboard structural edits (Enter inserts a sibling, Backspace/Delete
 * removes an empty node, Tab/Shift+Tab demote/promote), focus management after a
 * structural edit, add item / add sub-item, remove, reorder, colour-scheme,
 * style, a layout switcher, per-node visual overrides (fill / font / bold /
 * italic), layout node-count bounds, and read-only awareness of non-tree
 * connections. All logic lives in `useSmartArtEditing` (core ops only); this SFC
 * is thin presentation.
 *
 * Follows the uniform inspector-panel contract: `props { element }`, emits
 * `update` with a shallow `Partial<PptxElement>` patch the host merges via
 * `useEditorOperations.updateElement` (history-tracked, so undo/redo works).
 */
const props = withDefaults(
	defineProps<{
		element: PptxElement;
		canEdit?: boolean;
	}>(),
	{ canEdit: true },
);

const emit = defineEmits<{ update: [patch: Partial<PptxElement>] }>();

const { t } = useI18n();

const editable = computed(() => props.canEdit !== false);

const smartArtData = computed<PptxSmartArtData>(() => {
	if (props.element.type === 'smartArt' && props.element.smartArtData) {
		return props.element.smartArtData;
	}
	return { nodes: [] } as PptxSmartArtData;
});

const isSmartArt = computed(
	() => props.element.type === 'smartArt' && Boolean(props.element.smartArtData),
);

const editing = useSmartArtEditing({
	smartArtData,
	apply: (patch) => emit('update', patch),
});

const colorSchemes = SMARTART_COLOR_SCHEMES;
const styleOptions = SMARTART_STYLE_OPTIONS;

const addDisabled = computed(() => !editable.value || !editing.canAdd.value);

function onColorSchemeChange(event: Event): void {
	editing.setColorScheme((event.target as HTMLSelectElement).value as SmartArtColorScheme);
}

function onSwitchLayout(layout: SmartArtLayoutType): void {
	editing.switchLayout(layout);
}

function onSetStyle(value: SmartArtStyle): void {
	editing.setStyle(value);
}

function onSetNodeStyle(nodeId: string, style: Partial<PptxSmartArtNodeStyle>): void {
	editing.setNodeStyle(nodeId, style);
}

function onRegisterInput(nodeId: string, el: HTMLInputElement | null): void {
	editing.setInputEl(nodeId, el);
}
</script>

<template>
	<div
		class="pptx-vue-smartart-panel flex flex-col gap-2 text-xs"
		data-testid="smartart-panel"
		role="group"
		:aria-label="t('pptx.smartart.title')"
	>
		<p v-if="!isSmartArt" class="text-muted-foreground italic">
			{{ t('pptx.smartArt.selectPrompt') }}
		</p>

		<template v-else>
			<SmartArtLayoutSwitcher
				:current="editing.currentLayout.value"
				:can-edit="editable"
				@switch="onSwitchLayout"
			/>

			<label class="flex flex-col gap-1 text-[11px]">
				<span class="text-muted-foreground">{{ t('pptx.smartart.colorScheme') }}</span>
				<select
					class="flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
					data-testid="smartart-color-scheme"
					:aria-label="t('pptx.smartart.colorScheme')"
					:disabled="!editable"
					:value="editing.colorScheme.value"
					@change="onColorSchemeChange"
				>
					<option v-for="cs in colorSchemes" :key="cs" :value="cs">{{ cs }}</option>
				</select>
			</label>

			<div class="flex flex-col gap-1 text-[11px]">
				<span class="text-muted-foreground">{{ t('pptx.smartart.style') }}</span>
				<div class="flex gap-1" role="group" :aria-label="t('pptx.smartart.style')">
					<button
						v-for="s in styleOptions"
						:key="s"
						type="button"
						:disabled="!editable"
						:data-testid="`smartart-style-${s}`"
						:aria-pressed="editing.style.value === s"
						class="flex-1 px-2 py-1 text-[10px] rounded border transition-colors"
						:class="
							editing.style.value === s
								? 'border-primary bg-primary/20 text-primary'
								: 'border-border text-muted-foreground hover:bg-muted'
						"
						@click="onSetStyle(s)"
					>
						{{ s }}
					</button>
				</div>
			</div>

			<div class="flex items-center justify-between">
				<span class="text-[11px] text-muted-foreground">
					{{ t('pptx.smartart.textPane') }} ({{ editing.nodes.value.length }})
				</span>
				<button
					type="button"
					:disabled="addDisabled"
					data-testid="smartart-add-item"
					class="rounded bg-muted hover:bg-accent px-2 py-1 text-[11px] transition-colors disabled:opacity-40"
					:title="addDisabled ? editing.boundsHint.value : undefined"
					@click="editing.addItem()"
				>
					{{ t('pptx.smartart.addItem') }}
				</button>
			</div>

			<div
				v-if="editing.boundsHint.value"
				class="text-[9px] text-muted-foreground"
				role="note"
				data-testid="smartart-bounds-hint"
			>
				{{ editing.boundsHint.value }}
			</div>

			<div
				class="max-h-52 overflow-y-auto space-y-1 pr-1"
				data-testid="smartart-node-list"
				role="list"
			>
				<SmartArtNodeRow
					v-for="row in editing.rows.value"
					:key="row.node.id"
					:node="row.node"
					:display-index="row.displayIndex"
					:is-child="row.isChild"
					:can-edit="editable"
					:remove-disabled="row.removeDisabled"
					:move-up-disabled="row.moveUpDisabled"
					:move-down-disabled="row.moveDownDisabled"
					@change-text="editing.updateNodeText"
					@keydown-node="editing.onNodeKeyDown"
					@set-style="onSetNodeStyle"
					@add-sub-item="editing.addSubItem"
					@move-up="editing.moveUp"
					@move-down="editing.moveDown"
					@remove="editing.removeNode"
					@register-input="onRegisterInput"
				/>
			</div>

			<div
				v-if="editing.extraConnections.value > 0"
				class="text-[9px] text-muted-foreground"
				role="note"
				data-testid="smartart-extra-connections"
			>
				{{ t('pptx.smartart.extraConnections', { count: editing.extraConnections.value }) }}
			</div>

			<p class="text-[9px] text-muted-foreground mt-1">
				{{ t('pptx.smartart.tabHint') }}
			</p>
		</template>
	</div>
</template>
