// packages/react/src/viewer/components/OleEditorDialog.tsx
import type {
	OleNestedDeckSlideDetail,
	OlePptxElement,
	OleSheetGrid,
	PptxElement,
} from 'pptx-viewer-core';
import {
	applyOleDocumentParagraphEdit,
	applyOleNestedDeckElementTextEdit,
	applyOleSheetCellEdit,
	getOleDocumentParagraphs,
	getOleNestedDeckDetail,
	getOleSheetGrid,
	replaceOleFile,
} from 'pptx-viewer-core';
import { buildOleContentUpdatePatch, buildOleEditDialogDescriptor } from 'pptx-viewer-shared';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuX } from 'react-icons/lu';

import { DialogFooter } from './DialogFooter';
import { OleDeckEditor, OleDocumentEditor, OleSheetGridEditor } from './OleEditorDialogTabs';

/** Props for {@link OleEditorDialog}. */
export interface OleEditorDialogProps {
	isOpen: boolean;
	onClose: () => void;
	element: OlePptxElement;
	onUpdateElement: (updates: Partial<PptxElement>) => void;
}

/**
 * "Edit content" dialog for an embedded OLE object: a spreadsheet grid,
 * document paragraph list, or nested-deck slide title list depending on
 * the payload kind (`buildOleEditDialogDescriptor`), plus a Replace File
 * action always available regardless of kind.
 *
 * Every edit commits through the same core `ole-edit-api.ts` functions
 * every other binding calls, and the same `onUpdateElement` patch API every
 * other inspector field already uses, so undo/history/collaboration sync
 * works exactly like a typed-field edit.
 */
export function OleEditorDialog({
	isOpen,
	onClose,
	element,
	onUpdateElement,
}: OleEditorDialogProps): React.ReactElement | null {
	const { t } = useTranslation();
	const dialogRef = useRef<HTMLDivElement>(null);
	const fileInputRef = useRef<HTMLInputElement>(null);
	const descriptor = buildOleEditDialogDescriptor(element);

	const [grid, setGrid] = useState<OleSheetGrid | undefined>(undefined);
	const [paragraphs, setParagraphs] = useState<string[] | undefined>(undefined);
	const [deckSlides, setDeckSlides] = useState<OleNestedDeckSlideDetail[] | undefined>(undefined);
	const [loading, setLoading] = useState(false);
	const [saveError, setSaveError] = useState(false);

	// Async edit/save handlers below settle after their own awaits, which can
	// outlive the component (dialog closed, or unmounted entirely) if the OLE
	// round-trip is slow. Guard every post-await setState with this so a late
	// resolution never dispatches into an unmounted tree.
	const mountedRef = useRef(true);
	useEffect(
		() => () => {
			mountedRef.current = false;
		},
		[],
	);

	useEffect(() => {
		if (!isOpen || !descriptor.contentTab) {
			return;
		}
		let cancelled = false;
		setLoading(true);
		const kind = descriptor.contentTab.kind;
		const load = async () => {
			if (kind === 'sheet') {
				const value = await getOleSheetGrid(element);
				if (!cancelled) {
					setGrid(value);
				}
			} else if (kind === 'document') {
				const value = await getOleDocumentParagraphs(element);
				if (!cancelled) {
					setParagraphs(value);
				}
			} else if (kind === 'deck') {
				const value = await getOleNestedDeckDetail(element);
				if (!cancelled) {
					setDeckSlides(value);
				}
			}
			if (!cancelled) {
				setLoading(false);
			}
		};
		void load();
		return () => {
			cancelled = true;
		};
		// eslint-disable-next-line react-hooks/exhaustive-deps -- re-fetch only on open/element identity, not on every render
	}, [isOpen, element]);

	const commit = useCallback(
		(updated: OlePptxElement) => {
			if (!updated.oleContentDirty) {
				return;
			}
			onUpdateElement(buildOleContentUpdatePatch(updated) as Partial<PptxElement>);
		},
		[onUpdateElement],
	);

	const handleCellEdit = useCallback(
		async (row: number, col: number, value: string) => {
			try {
				const updated = await applyOleSheetCellEdit(element, { row, col, value });
				commit(updated);
				const refreshed = await getOleSheetGrid(updated);
				if (mountedRef.current) {
					setGrid(refreshed);
				}
			} catch {
				if (mountedRef.current) {
					setSaveError(true);
				}
			}
		},
		[element, commit],
	);

	const handleParagraphEdit = useCallback(
		async (index: number, text: string) => {
			try {
				const updated = await applyOleDocumentParagraphEdit(element, index, text);
				commit(updated);
				const refreshed = await getOleDocumentParagraphs(updated);
				if (mountedRef.current) {
					setParagraphs(refreshed);
				}
			} catch {
				if (mountedRef.current) {
					setSaveError(true);
				}
			}
		},
		[element, commit],
	);

	const handleDeckElementEdit = useCallback(
		async (slideIndex: number, deckElementId: string, text: string) => {
			try {
				const updated = await applyOleNestedDeckElementTextEdit(
					element,
					slideIndex,
					deckElementId,
					text,
				);
				commit(updated);
				const refreshed = await getOleNestedDeckDetail(updated);
				if (mountedRef.current) {
					setDeckSlides(refreshed);
				}
			} catch {
				if (mountedRef.current) {
					setSaveError(true);
				}
			}
		},
		[element, commit],
	);

	const handleReplaceFile = useCallback(
		async (file: File) => {
			try {
				const bytes = new Uint8Array(await file.arrayBuffer());
				const updated = await replaceOleFile(element, bytes, file.name);
				commit(updated);
				if (mountedRef.current) {
					onClose();
				}
			} catch {
				if (mountedRef.current) {
					setSaveError(true);
				}
			}
		},
		[element, commit, onClose],
	);

	const handleKeyDown = useCallback(
		(e: React.KeyboardEvent) => {
			if (e.key === 'Escape') {
				e.preventDefault();
				onClose();
			}
		},
		[onClose],
	);

	if (!isOpen) {
		return null;
	}

	return (
		<div
			className='fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-sm'
			onClick={(e) => {
				if (e.target === e.currentTarget) {
					onClose();
				}
			}}
			onKeyDown={handleKeyDown}
		>
			{/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions -- stopPropagation only */}
			<div
				ref={dialogRef}
				className='bg-background border border-border rounded-xl shadow-2xl w-[560px] max-h-[80vh] flex flex-col overflow-hidden'
				onClick={(e) => e.stopPropagation()}
				role='dialog'
				aria-modal='true'
				tabIndex={-1}
				aria-label={t(descriptor.titleKey)}
			>
				<div className='flex items-center justify-between px-5 py-3 border-b border-border'>
					<h2 className='text-sm font-semibold text-foreground'>{t(descriptor.titleKey)}</h2>
					<button
						type='button'
						onClick={onClose}
						className='p-1 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors'
						aria-label={t('pptx.settings.close')}
					>
						<LuX className='w-4 h-4' />
					</button>
				</div>

				<div className='flex-1 overflow-y-auto px-5 py-4 space-y-3 text-sm'>
					{loading && (
						<p className='text-muted-foreground text-xs'>{t('pptx.ole.editDialog.loading')}</p>
					)}
					{saveError && (
						<p className='text-destructive text-xs'>{t('pptx.ole.editDialog.saveError')}</p>
					)}

					{!loading && descriptor.contentTab?.kind === 'sheet' && (
						<OleSheetGridEditor grid={grid} onCellEdit={handleCellEdit} t={t} />
					)}
					{!loading && descriptor.contentTab?.kind === 'document' && (
						<OleDocumentEditor paragraphs={paragraphs} onEdit={handleParagraphEdit} t={t} />
					)}
					{!loading && descriptor.contentTab?.kind === 'deck' && (
						<OleDeckEditor slides={deckSlides} onEdit={handleDeckElementEdit} t={t} />
					)}
					{!descriptor.contentTab && (
						<p className='text-muted-foreground text-xs'>{t('pptx.ole.editDialog.unsupported')}</p>
					)}
				</div>

				<div className='flex items-center justify-between gap-2 px-5 py-3 border-t border-border'>
					<input
						ref={fileInputRef}
						type='file'
						className='hidden'
						onChange={(e) => {
							const file = e.target.files?.[0];
							if (file) {
								void handleReplaceFile(file);
							}
						}}
					/>
					<DialogFooter
						actions={[
							{ id: 'replace', label: t('pptx.ole.editDialog.replaceFile'), align: 'start' },
							{ id: 'save', label: t('pptx.ole.editDialog.save'), variant: 'primary' },
						]}
						onAction={(id) => (id === 'replace' ? fileInputRef.current?.click() : onClose())}
					/>
					<button
						type='button'
						onClick={onClose}
						className='px-4 py-1.5 rounded-lg text-xs font-medium bg-primary hover:bg-primary/80 text-white transition-colors'
					>
						{t('pptx.ole.editDialog.save')}
					</button>
				</div>
			</div>
		</div>
	);
}

// packages/svelte/src/viewer/components/inspector/OleEditorDialog.svelte
<script lang="ts">
	/**
	 * OleEditorDialog: "Edit content" modal for an embedded OLE object,
	 * mirroring React's `OleEditorDialog.tsx`. Which content tab it shows
	 * (spreadsheet grid / document paragraphs / nested-deck slide titles, or
	 * just Replace File) comes from the shared, framework-neutral
	 * `buildOleEditDialogDescriptor`; the actual tab is delegated to one of
	 * `OleEditorDialogSheetTab` / `OleEditorDialogDocumentTab` /
	 * `OleEditorDialogDeckTab`, split into their own files (a `.svelte` file
	 * can only default-export one component, unlike React's
	 * `OleEditorDialogTabs.tsx`) to respect the 300-LOC file limit.
	 *
	 * Replace File is always offered regardless of payload kind and lives here
	 * (not in a tab) since it applies to every kind, including an unsupported
	 * one. Every edit commits through core's `ole-edit-api.ts` and the same
	 * `editor.applyElementPatch` path every other inspector field uses, so
	 * undo/history/collaboration sync works exactly like a typed-field edit.
	 */
	import DialogFooter from '../DialogFooter.svelte';
	import type { OlePptxElement, PptxElement } from 'pptx-viewer-core';
	import { replaceOleFile } from 'pptx-viewer-core';
	import { buildOleContentUpdatePatch, buildOleEditDialogDescriptor } from 'pptx-viewer-shared';
	import { onDestroy } from 'svelte';

	import { useTranslator } from '../../../i18n/context';
	import type { EditorState } from '../../editor/editor-state.svelte';
	import OleEditorDialogDeckTab from './OleEditorDialogDeckTab.svelte';
	import OleEditorDialogDocumentTab from './OleEditorDialogDocumentTab.svelte';
	import OleEditorDialogSheetTab from './OleEditorDialogSheetTab.svelte';

	const {
		editor,
		el,
		open,
		onclose,
	}: {
		editor: EditorState;
		el: OlePptxElement;
		open: boolean;
		onclose: () => void;
	} = $props();
	const t = useTranslator();

	let fileInputEl = $state<HTMLInputElement | null>(null);
	let saveError = $state(false);

	// `handleReplaceFile` below settles after its own await, which can outlive
	// the component if it is destroyed first. Guard the post-await state
	// writes with this so a late resolution never writes into a destroyed
	// component.
	let alive = true;
	onDestroy(() => {
		alive = false;
	});

	const descriptor = $derived(buildOleEditDialogDescriptor(el));

	function commit(updated: OlePptxElement): void {
		if (!updated.oleContentDirty) {
			return;
		}
		editor.applyElementPatch(el.id, buildOleContentUpdatePatch(updated) as Partial<PptxElement>);
	}

	async function handleReplaceFile(file: File): Promise<void> {
		try {
			const bytes = new Uint8Array(await file.arrayBuffer());
			const updated = await replaceOleFile(el, bytes, file.name);
			commit(updated);
			if (alive) {
				onclose();
			}
		} catch {
			if (alive) {
				saveError = true;
			}
		}
	}

	function onFileChange(event: Event): void {
		const input = event.currentTarget as HTMLInputElement;
		const file = input.files?.[0];
		if (file) {
			void handleReplaceFile(file);
		}
		input.value = '';
	}

	function onKeydown(event: KeyboardEvent): void {
		event.stopPropagation();
		if (event.key === 'Escape') {
			onclose();
		}
	}

	function onBackdropClick(event: MouseEvent): void {
		if (event.target === event.currentTarget) {
			onclose();
		}
	}
</script>

{#if open}
	<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
	<div class="backdrop" onclick={onBackdropClick} onkeydown={onKeydown} role="presentation">
		<!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
		<section role="dialog" tabindex="-1" aria-modal="true" aria-label={t(descriptor.titleKey)}>
			<header>
				<h2>{t(descriptor.titleKey)}</h2>
				<button type="button" class="close" aria-label={t('pptx.settings.close')} onclick={onclose}>&times;</button>
			</header>

			<div class="content">
				{#if saveError}
					<p class="error">{t('pptx.ole.editDialog.saveError')}</p>
				{/if}
				{#if descriptor.contentTab?.kind === 'sheet'}
					<OleEditorDialogSheetTab {editor} {el} onerror={() => (saveError = true)} />
				{:else if descriptor.contentTab?.kind === 'document'}
					<OleEditorDialogDocumentTab {editor} {el} onerror={() => (saveError = true)} />
				{:else if descriptor.contentTab?.kind === 'deck'}
					<OleEditorDialogDeckTab {editor} {el} onerror={() => (saveError = true)} />
				{:else}
					<p class="unsupported">{t('pptx.ole.editDialog.unsupported')}</p>
				{/if}
			</div>

			<footer>
				<input bind:this={fileInputEl} type="file" class="hidden-file-input" onchange={onFileChange} />
				<DialogFooter actions={[{ id: 'replace', label: t('pptx.ole.editDialog.replaceFile'), align: 'start' }, { id: 'save', label: t('pptx.ole.editDialog.save'), variant: 'primary' }]} onaction={(id) => (id === 'replace' ? fileInputEl?.click() : onclose())} /></footer>
		</section>
	</div>
{/if}

<style>
	.backdrop {
		position: fixed;
		inset: 0;
		z-index: 1200;
		display: grid;
		place-items: center;
		background: #0009;
	}

	section {
		display: flex;
		flex-direction: column;
		gap: 12px;
		width: min(560px, calc(100vw - 32px));
		max-height: 80vh;
		overflow-y: auto;
		padding: 18px;
		border: 1px solid var(--pptx-border, #3f3f52);
		border-radius: 11px;
		background: var(--pptx-card, #1e1e2e);
		color: var(--pptx-foreground, #f3f4f6);
	}

	header {
		display: flex;
		align-items: center;
		justify-content: space-between;
	}

	h2 {
		margin: 0;
		font-size: 14px;
	}

	.close {
		border: none;
		background: none;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 16px;
		cursor: pointer;
		padding: 2px 6px;
		border-radius: var(--pptx-radius, 6px);
	}

	.close:hover {
		background: var(--pptx-accent, #33334d);
		color: var(--pptx-accent-foreground, #f8fafc);
	}

	.content {
		display: flex;
		flex-direction: column;
		gap: 8px;
		font-size: 12px;
	}

	.error {
		margin: 0;
		font-size: 11px;
		color: var(--pptx-destructive, #ef4444);
	}

	.unsupported {
		margin: 0;
		font-size: 11px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.hidden-file-input {
		display: none;
	}

	footer {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
	}
	</style>
