// packages/vue/src/viewer/components/inspector/TableStyleEditorFields.vue
<script setup lang="ts">
import type {
	TableStyleBorderSide,
	TableStyleEditorDescriptor,
	TableStyleEditorFieldEdit,
} from 'pptx-viewer-shared';
import {
	TABLE_STYLE_BORDER_SIDE_LABEL_KEYS,
	TABLE_STYLE_BORDER_SIDES,
	TABLE_STYLE_DASH_PRESETS,
} from 'pptx-viewer-shared';
import { useI18n } from 'vue-i18n';

import ThemeColorSwatchGrid from './ThemeColorSwatchGrid.vue';

/**
 * Field editors for whichever part `TableStyleEditor.vue` currently has
 * selected. Mirrors React's `TableStyleEditorFields.tsx`.
 */
defineProps<{
	descriptor: TableStyleEditorDescriptor;
	canEdit: boolean;
}>();

const emit = defineEmits<{
	edit: [edit: TableStyleEditorFieldEdit];
}>();

const { t } = useI18n();

function textFlagEdit(
	flag: 'bold' | 'italic' | 'underline',
	value: boolean,
): TableStyleEditorFieldEdit {
	if (flag === 'bold') {
		return { kind: 'textBold', value };
	}
	if (flag === 'italic') {
		return { kind: 'textItalic', value };
	}
	return { kind: 'textUnderline', value };
}

function borderSide(descriptor: TableStyleEditorDescriptor, side: TableStyleBorderSide) {
	return descriptor.borders[side];
}
</script>

<template>
	<div class="flex flex-col gap-2">
		<div class="flex flex-col gap-1">
			<div class="text-[11px] uppercase tracking-wide text-muted-foreground">
				{{ t('pptx.tableStyleEditor.fillSection') }}
			</div>
			<div class="flex items-center gap-2 text-[11px]">
				<input
					type="color"
					:disabled="!canEdit"
					:value="descriptor.fill.color.hex"
					class="h-6 w-8 rounded border border-border bg-transparent cursor-pointer"
					@change="
						emit('edit', {
							kind: 'fillColor',
							hex: ($event.target as HTMLInputElement).value,
							ref: undefined,
						})
					"
				/>
				<label class="flex items-center gap-1">
					<input
						type="checkbox"
						:disabled="!canEdit"
						:checked="descriptor.fill.noFill"
						@change="
							emit('edit', {
								kind: 'fillNone',
								noFill: ($event.target as HTMLInputElement).checked,
							})
						"
					/>
					{{ t('pptx.tableStyleEditor.noFill') }}
				</label>
			</div>
			<ThemeColorSwatchGrid
				:disabled="!canEdit"
				:selected-ref="descriptor.fill.color.ref"
				:selected-hex="descriptor.fill.color.hex"
				@pick="(c) => emit('edit', { kind: 'fillColor', hex: c.hex, ref: c.ref })"
			/>
		</div>

		<template v-if="descriptor.hasTextAndBorders">
			<div class="flex flex-col gap-1">
				<div class="text-[11px] uppercase tracking-wide text-muted-foreground">
					{{ t('pptx.tableStyleEditor.textSection') }}
				</div>
				<div class="flex gap-1">
					<button
						v-for="flag in ['bold', 'italic', 'underline'] as const"
						:key="flag"
						type="button"
						:disabled="!canEdit"
						class="rounded px-2 py-1 text-[11px] transition-colors max-md:min-w-[44px] max-md:min-h-[44px]"
						:class="descriptor.text[flag] ? 'bg-accent' : 'bg-muted hover:bg-accent'"
						@click="emit('edit', textFlagEdit(flag, !descriptor.text[flag]))"
					>
						{{ t(`pptx.format.${flag}`) }}
					</button>
				</div>
				<label class="flex items-center gap-2 text-[11px]">
					<span>{{ t('pptx.tableStyleEditor.textColor') }}</span>
					<input
						type="color"
						:disabled="!canEdit"
						:value="descriptor.text.color.hex"
						class="h-6 w-8 rounded border border-border bg-transparent cursor-pointer"
						@change="
							emit('edit', {
								kind: 'textColor',
								hex: ($event.target as HTMLInputElement).value,
								ref: undefined,
							})
						"
					/>
				</label>
				<ThemeColorSwatchGrid
					:disabled="!canEdit"
					:selected-ref="descriptor.text.color.ref"
					:selected-hex="descriptor.text.color.hex"
					@pick="(c) => emit('edit', { kind: 'textColor', hex: c.hex, ref: c.ref })"
				/>
			</div>

			<div class="flex flex-col gap-1">
				<div class="text-[11px] uppercase tracking-wide text-muted-foreground">
					{{ t('pptx.tableStyleEditor.bordersSection') }}
				</div>
				<div
					v-for="side in TABLE_STYLE_BORDER_SIDES"
					:key="side"
					class="flex items-center gap-1.5 text-[11px]"
				>
					<span class="w-28 shrink-0 text-muted-foreground">{{
						t(TABLE_STYLE_BORDER_SIDE_LABEL_KEYS[side])
					}}</span>
					<input
						type="color"
						:disabled="!canEdit"
						:value="borderSide(descriptor, side).color.hex"
						class="h-6 w-7 rounded border border-border bg-transparent cursor-pointer"
						@change="
							emit('edit', {
								kind: 'borderColor',
								side,
								hex: ($event.target as HTMLInputElement).value,
								ref: undefined,
							})
						"
					/>
					<input
						type="number"
						min="0"
						max="20"
						:disabled="!canEdit"
						:value="borderSide(descriptor, side).width"
						class="w-12 rounded border border-border bg-background px-1 py-0.5"
						@change="
							emit('edit', {
								kind: 'borderWidth',
								side,
								width: Number(($event.target as HTMLInputElement).value),
							})
						"
					/>
					<select
						:disabled="!canEdit"
						:value="borderSide(descriptor, side).dash"
						class="rounded border border-border bg-background px-1 py-0.5"
						@change="
							emit('edit', {
								kind: 'borderDash',
								side,
								dash: ($event.target as HTMLSelectElement).value,
							})
						"
					>
						<option v-for="dash in TABLE_STYLE_DASH_PRESETS" :key="dash" :value="dash">
							{{ dash }}
						</option>
					</select>
					<label class="flex items-center gap-1 shrink-0">
						<input
							type="checkbox"
							:disabled="!canEdit"
							:checked="borderSide(descriptor, side).noFill"
							@change="
								emit('edit', {
									kind: 'borderNone',
									side,
									noFill: ($event.target as HTMLInputElement).checked,
								})
							"
						/>
						{{ t('pptx.tableStyleEditor.noBorder') }}
					</label>
				</div>
			</div>
		</template>
	</div>
</template>

// packages/svelte/src/viewer/components/inspector/TableStyleEditorFields.svelte
<script lang="ts">
	/**
	 * Field editors for whichever part `TableStyleEditor.svelte` currently has
	 * selected. Mirrors React's `TableStyleEditorFields.tsx` / Vue's
	 * `TableStyleEditorFields.vue`.
	 */
	import type { TableStyleEditorDescriptor, TableStyleEditorFieldEdit } from 'pptx-viewer-shared';
	import {
		TABLE_STYLE_BORDER_SIDE_LABEL_KEYS,
		TABLE_STYLE_BORDER_SIDES,
		TABLE_STYLE_DASH_PRESETS,
	} from 'pptx-viewer-shared';

	import { useTranslator } from '../../../i18n/context';
	import ThemeColorSwatchGrid from './ThemeColorSwatchGrid.svelte';

	const {
		descriptor,
		themeColorMap,
		canEdit,
		onedit,
	}: {
		descriptor: TableStyleEditorDescriptor;
		themeColorMap: Record<string, string> | undefined;
		canEdit: boolean;
		onedit: (edit: TableStyleEditorFieldEdit) => void;
	} = $props();

	const t = useTranslator();
</script>

<div class="fields">
	<div class="group">
		<span class="hdg">{t('pptx.tableStyleEditor.fillSection')}</span>
		<div class="row">
			<input type="color" disabled={!canEdit} value={descriptor.fill.color.hex} onchange={(e) => onedit({ kind: 'fillColor', hex: e.currentTarget.value, ref: undefined })} />
			<label class="check"><pptx-ui-checkbox disabled={!canEdit} checked={descriptor.fill.noFill} onchange={(e) => onedit({ kind: 'fillNone', noFill: e.currentTarget.checked })} ></pptx-ui-checkbox>{t('pptx.tableStyleEditor.noFill')}</label>
		</div>
		<ThemeColorSwatchGrid {themeColorMap} disabled={!canEdit} selectedRef={descriptor.fill.color.ref} selectedHex={descriptor.fill.color.hex} onpick={(c) => onedit({ kind: 'fillColor', hex: c.hex, ref: c.ref })} />
	</div>

	{#if descriptor.hasTextAndBorders}
		<div class="group">
			<span class="hdg">{t('pptx.tableStyleEditor.textSection')}</span>
			<div class="row">
				<button type="button" disabled={!canEdit} class:active={descriptor.text.bold} onclick={() => onedit({ kind: 'textBold', value: !descriptor.text.bold })}>{t('pptx.format.bold')}</button>
				<button type="button" disabled={!canEdit} class:active={descriptor.text.italic} onclick={() => onedit({ kind: 'textItalic', value: !descriptor.text.italic })}>{t('pptx.format.italic')}</button>
				<button type="button" disabled={!canEdit} class:active={descriptor.text.underline} onclick={() => onedit({ kind: 'textUnderline', value: !descriptor.text.underline })}>{t('pptx.format.underline')}</button>
			</div>
			<label class="row">{t('pptx.tableStyleEditor.textColor')}<input type="color" disabled={!canEdit} value={descriptor.text.color.hex} onchange={(e) => onedit({ kind: 'textColor', hex: e.currentTarget.value, ref: undefined })} /></label>
			<ThemeColorSwatchGrid {themeColorMap} disabled={!canEdit} selectedRef={descriptor.text.color.ref} selectedHex={descriptor.text.color.hex} onpick={(c) => onedit({ kind: 'textColor', hex: c.hex, ref: c.ref })} />
		</div>

		<div class="group">
			<span class="hdg">{t('pptx.tableStyleEditor.bordersSection')}</span>
			{#each TABLE_STYLE_BORDER_SIDES as side (side)}
				{@const border = descriptor.borders[side]}
				<div class="border-row">
					<span class="side-lbl">{t(TABLE_STYLE_BORDER_SIDE_LABEL_KEYS[side])}</span>
					<input type="color" disabled={!canEdit} value={border.color.hex} onchange={(e) => onedit({ kind: 'borderColor', side, hex: e.currentTarget.value, ref: undefined })} />
					<input type="number" min="0" max="20" disabled={!canEdit} value={border.width} onchange={(e) => onedit({ kind: 'borderWidth', side, width: Number(e.currentTarget.value) })} />
					<pptx-ui-select disabled={!canEdit} value={border.dash} onchange={(e) => onedit({ kind: 'borderDash', side, dash: e.currentTarget.value })}>
						{#each TABLE_STYLE_DASH_PRESETS as dash (dash)}<option value={dash}>{dash}</option>{/each}
					</pptx-ui-select>
					<label class="check"><pptx-ui-checkbox disabled={!canEdit} checked={border.noFill} onchange={(e) => onedit({ kind: 'borderNone', side, noFill: e.currentTarget.checked })} ></pptx-ui-checkbox>{t('pptx.tableStyleEditor.noBorder')}</label>
				</div>
			{/each}
		</div>
	{/if}
</div>

<style>
	.fields { display: flex; flex-direction: column; gap: 8px; }
	.group { display: flex; flex-direction: column; gap: 4px; }
	.hdg { font-size: 10px; text-transform: uppercase; letter-spacing: 0.03em; color: var(--pptx-muted-foreground); }
	.row { display: flex; align-items: center; gap: 6px; font-size: 11px; }
	.check { display: flex; align-items: center; gap: 4px; font-size: 11px; }
	.border-row { display: flex; align-items: center; gap: 5px; font-size: 11px; }
	.side-lbl { width: 110px; flex-shrink: 0; color: var(--pptx-muted-foreground); }
	input[type='color'] { height: 24px; width: 32px; border: 1px solid var(--pptx-border); border-radius: 4px; background: transparent; cursor: pointer; padding: 0; }
	input[type='number'], select { height: 24px; border: 1px solid var(--pptx-border); border-radius: 4px; background: var(--pptx-background); color: inherit; }
	input[type='number'] { width: 48px; }
	button { border: 1px solid var(--pptx-border); border-radius: 4px; padding: 3px 6px; background: var(--pptx-muted); color: inherit; }
	button.active { background: var(--pptx-primary, #c43b32); color: #fff; }
	/* Touch target: matches MIN_TOUCH_TARGET_PX (44) from pptx-viewer-shared's
	   render/responsive module. Bold/Italic/Underline are single-letter
	   labels, so both dimensions need the floor, not just height. */
	@media (max-width: 767px) {
		.row button, select, input[type='number'] { min-height: 44px; }
		.row button { min-width: 44px; }
	}
</style>
