// packages/react/src/viewer/components/inspector/ThemeColorSchemeEditor.tsx
import React, { useMemo, useCallback } from "react";
import { useTranslation } from "react-i18next";

import type { PptxThemeColorScheme } from "pptx-viewer-core";
import { THEME_COLOR_SCHEME_KEYS } from "pptx-viewer-core";
import { buildThemeColorGrid, THEME_COLOR_LABELS } from "../../utils/theme";
import { COMMON_FONTS } from "./theme-editor-presets";
import {
  THEME_EDITOR_CARD as CARD,
  THEME_EDITOR_HEADING as HEADING,
  THEME_EDITOR_INPUT as INPUT,
} from "./theme-editor-constants";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface ThemeColorSchemeEditorProps {
  editColors: PptxThemeColorScheme;
  canEdit: boolean;
  activePickerKey: keyof PptxThemeColorScheme | null;
  majorFont: string;
  minorFont: string;
  onSetActivePickerKey: (key: keyof PptxThemeColorScheme | null) => void;
  onColorChange: (key: keyof PptxThemeColorScheme, hex: string) => void;
  onMajorFontChange: (font: string) => void;
  onMinorFontChange: (font: string) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ThemeColorSchemeEditor({
  editColors,
  canEdit,
  activePickerKey,
  majorFont,
  minorFont,
  onSetActivePickerKey,
  onColorChange,
  onMajorFontChange,
  onMinorFontChange,
}: ThemeColorSchemeEditorProps): React.ReactElement {
  const { t } = useTranslation();

  const previewGrid = useMemo(
    () => buildThemeColorGrid(editColors),
    [editColors],
  );

  const handleColorText = useCallback(
    (val: string) => {
      if (activePickerKey && /^#[0-9a-fA-F]{6}$/.test(val)) {
        onColorChange(activePickerKey, val);
      }
    },
    [activePickerKey, onColorChange],
  );

  return (
    <>
      {/* Color Scheme Editor */}
      <div className={CARD}>
        <div className={HEADING}>{t("pptx.themeEditor.colorScheme")}</div>
        <div className="grid grid-cols-4 gap-1.5">
          {THEME_COLOR_SCHEME_KEYS.map((key) => (
            <div key={key} className="flex flex-col items-center gap-0.5">
              <button
                type="button"
                disabled={!canEdit}
                className={`h-6 w-full rounded-sm border transition-colors ${
                  activePickerKey === key
                    ? "border-primary ring-1 ring-primary"
                    : "border-border hover:border-muted-foreground"
                } disabled:opacity-40 disabled:cursor-not-allowed`}
                style={{ backgroundColor: editColors[key] }}
                title={`${THEME_COLOR_LABELS[key]}: ${editColors[key]}`}
                onClick={() =>
                  onSetActivePickerKey(activePickerKey === key ? null : key)
                }
              />
              <span className="text-[9px] text-muted-foreground truncate w-full text-center">
                {THEME_COLOR_LABELS[key]}
              </span>
            </div>
          ))}
        </div>

        {/* Inline color picker for active slot */}
        {activePickerKey && (
          <div className="mt-2 flex items-center gap-2 rounded bg-background p-2">
            <span className="text-[10px] text-muted-foreground min-w-[60px]">
              {THEME_COLOR_LABELS[activePickerKey]}
            </span>
            <input
              type="color"
              disabled={!canEdit}
              className="h-6 w-8 cursor-pointer rounded border-0 bg-transparent p-0"
              value={editColors[activePickerKey]}
              onChange={(e) => onColorChange(activePickerKey, e.target.value)}
            />
            <input
              type="text"
              disabled={!canEdit}
              className="flex-1 rounded border border-border bg-muted px-1.5 py-0.5 text-[10px] text-foreground font-mono"
              value={editColors[activePickerKey]}
              onChange={(e) => handleColorText(e.target.value)}
            />
          </div>
        )}
      </div>

      {/* Live Preview Grid */}
      {previewGrid && (
        <div className={CARD}>
          <div className={HEADING}>{t("pptx.themeEditor.preview")}</div>
          <div className="flex flex-col gap-px">
            {previewGrid.map((row, rowIdx) => (
              <div key={rowIdx} className="grid grid-cols-12 gap-px">
                {row.map((cell) => (
                  <div
                    key={`${cell.schemeKey}-${rowIdx}`}
                    className="h-3.5 rounded-sm"
                    style={{ backgroundColor: cell.hex }}
                    title={`${cell.colLabel} -- ${cell.rowLabel} (${cell.hex})`}
                  />
                ))}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Font Pair */}
      <div className={CARD}>
        <div className={HEADING}>{t("pptx.themeEditor.fonts")}</div>
        <div className="space-y-1.5">
          <label className="flex flex-col gap-0.5">
            <span className="text-[10px] text-muted-foreground">
              {t("pptx.themeEditor.headingFont")}
            </span>
            <select
              className={INPUT}
              disabled={!canEdit}
              value={
                COMMON_FONTS.includes(majorFont) ? majorFont : "__custom__"
              }
              onChange={(e) => {
                if (e.target.value !== "__custom__")
                  onMajorFontChange(e.target.value);
              }}
            >
              {COMMON_FONTS.map((f) => (
                <option key={f} value={f}>
                  {f}
                </option>
              ))}
              {!COMMON_FONTS.includes(majorFont) && (
                <option value="__custom__">{majorFont}</option>
              )}
            </select>
          </label>
          <label className="flex flex-col gap-0.5">
            <span className="text-[10px] text-muted-foreground">
              {t("pptx.themeEditor.bodyFont")}
            </span>
            <select
              className={INPUT}
              disabled={!canEdit}
              value={
                COMMON_FONTS.includes(minorFont) ? minorFont : "__custom__"
              }
              onChange={(e) => {
                if (e.target.value !== "__custom__")
                  onMinorFontChange(e.target.value);
              }}
            >
              {COMMON_FONTS.map((f) => (
                <option key={f} value={f}>
                  {f}
                </option>
              ))}
              {!COMMON_FONTS.includes(minorFont) && (
                <option value="__custom__">{minorFont}</option>
              )}
            </select>
          </label>
          <div className="flex items-center gap-2 pt-1 text-[10px] text-muted-foreground">
            <span style={{ fontFamily: majorFont }} className="text-foreground">
              {t("pptx.themeEditor.headingSample")}
            </span>
            <span className="text-muted-foreground">|</span>
            <span style={{ fontFamily: minorFont }} className="text-foreground">
              {t("pptx.themeEditor.bodySample")}
            </span>
          </div>
        </div>
      </div>
    </>
  );
}

// packages/svelte/src/viewer/components/inspector/ThemeColorSchemeEditor.svelte
<script lang="ts">
	/**
	 * ThemeColorSchemeEditor: the twelve theme-colour swatches, the picker that
	 * opens under the selected one, and the tint/shade preview grid (mirrors
	 * React's component of the same name). Split out of `ThemeEditorPanel` to
	 * keep that file within the repo's file-size budget.
	 *
	 * The labels and the preview-grid tint/shade maths are framework-agnostic
	 * and come from `pptx-viewer-shared`; this file is only the view.
	 */
	import type { PptxThemeColorScheme } from 'pptx-viewer-core';
	import { THEME_COLOR_SCHEME_KEYS } from 'pptx-viewer-core';
	import { buildThemeColorGrid, THEME_COLOR_LABELS } from 'pptx-viewer-shared';

	import { useTranslator } from '../../../i18n/context';
	import type { ThemeEditorState } from './theme-editor-state.svelte';

	const { state, canEdit }: { state: ThemeEditorState; canEdit: boolean } = $props();
	const t = useTranslator();

	const previewGrid = $derived(buildThemeColorGrid(state.colors));
	const activeKey = $derived(state.activePickerKey);

	function togglePicker(key: keyof PptxThemeColorScheme): void {
		state.activePickerKey = state.activePickerKey === key ? null : key;
	}
</script>

<div class="pptx-svelte-theme-block">
	<span class="pptx-svelte-theme-heading">{t('pptx.themeEditor.colorScheme')}</span>
	<div class="pptx-svelte-theme-swatches">
		{#each THEME_COLOR_SCHEME_KEYS as key (key)}
			<div class="pptx-svelte-theme-swatch">
				<button
					type="button"
					disabled={!canEdit}
					title={`${THEME_COLOR_LABELS[key]}: ${state.colors[key]}`}
					aria-label={`${THEME_COLOR_LABELS[key]}: ${state.colors[key]}`}
					aria-pressed={activeKey === key}
					class:pptx-svelte-theme-swatch-active={activeKey === key}
					style={`background:${state.colors[key]}`}
					onclick={() => togglePicker(key)}
				></button>
				<small>{THEME_COLOR_LABELS[key]}</small>
			</div>
		{/each}
	</div>
	{#if activeKey}
		<div class="pptx-svelte-theme-picker">
			<span>{THEME_COLOR_LABELS[activeKey]}</span>
			<input
				type="color"
				disabled={!canEdit}
				aria-label={THEME_COLOR_LABELS[activeKey]}
				value={state.colors[activeKey]}
				oninput={(event) => state.setColor(activeKey, event.currentTarget.value)}
			/>
			<input
				type="text"
				disabled={!canEdit}
				aria-label={`${THEME_COLOR_LABELS[activeKey]} hex`}
				value={state.colors[activeKey]}
				onchange={(event) => state.setColorText(event.currentTarget.value)}
			/>
		</div>
	{/if}
</div>

{#if previewGrid}
	<div class="pptx-svelte-theme-block">
		<span class="pptx-svelte-theme-heading">{t('pptx.themeEditor.preview')}</span>
		<div class="pptx-svelte-theme-preview">
			{#each previewGrid as row, rowIndex (rowIndex)}
				<div>
					{#each row as cell (cell.schemeKey)}
						<span
							style={`background:${cell.hex}`}
							title={`${cell.colLabel} - ${cell.rowLabel} (${cell.hex})`}
						></span>
					{/each}
				</div>
			{/each}
		</div>
	</div>
{/if}

<style>
	.pptx-svelte-theme-block {
		display: grid;
		gap: 5px;
	}

	.pptx-svelte-theme-heading {
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 10px;
		font-weight: 600;
		text-transform: uppercase;
	}

	input {
		min-width: 0;
		height: 25px;
		box-sizing: border-box;
		padding: 0 5px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 5px;
		background: var(--pptx-background, #11111b);
		color: inherit;
		font: inherit;
	}

	.pptx-svelte-theme-swatches {
		display: grid;
		grid-template-columns: repeat(4, 1fr);
		gap: 5px;
	}

	.pptx-svelte-theme-swatch {
		display: grid;
		gap: 2px;
		justify-items: center;
	}

	.pptx-svelte-theme-swatch button {
		width: 100%;
		height: 24px;
		padding: 0;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 3px;
		cursor: pointer;
	}

	.pptx-svelte-theme-swatch-active {
		outline: 1px solid var(--pptx-primary, #6366f1);
	}

	.pptx-svelte-theme-swatch small {
		width: 100%;
		overflow: hidden;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 9px;
		text-align: center;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.pptx-svelte-theme-picker {
		display: grid;
		grid-template-columns: auto 32px 1fr;
		gap: 6px;
		align-items: center;
		padding: 5px;
		border-radius: 5px;
		background: var(--pptx-background, #11111b);
		font-size: 10px;
	}

	.pptx-svelte-theme-picker input[type='color'] {
		height: 22px;
		padding: 0;
		border: none;
		background: transparent;
		cursor: pointer;
	}

	.pptx-svelte-theme-preview {
		display: grid;
		gap: 1px;
	}

	.pptx-svelte-theme-preview > div {
		display: grid;
		grid-template-columns: repeat(12, 1fr);
		gap: 1px;
	}

	.pptx-svelte-theme-preview span {
		height: 13px;
		border-radius: 2px;
	}

	button:disabled,
	input:disabled {
		cursor: not-allowed;
		opacity: 0.4;
	}
</style>
