// packages/vue/src/viewer/components/inspector/AfterAnimationRow.vue
<script setup lang="ts">
import type { PptxAfterAnimationAction } from 'pptx-viewer-core';
import { AFTER_ANIMATION_VALUES } from 'pptx-viewer-shared';
import { useI18n } from 'vue-i18n';

defineProps<{
	action: PptxAfterAnimationAction;
	color: string | undefined;
}>();
const emit = defineEmits<{
	action: [action: PptxAfterAnimationAction];
	color: [color: string];
}>();
const { t } = useI18n();

function onActionChange(event: Event): void {
	emit('action', (event.target as HTMLSelectElement).value as PptxAfterAnimationAction);
}
function onColorChange(event: Event): void {
	emit('color', (event.target as HTMLInputElement).value);
}
</script>

<template>
	<div class="pptx-vue-after-animation">
		<label
			>{{ t('pptx.animation.afterAnimation') }}
			<select
				:aria-label="t('pptx.animation.afterAnimation')"
				:value="action"
				@change="onActionChange"
			>
				<option v-for="value in AFTER_ANIMATION_VALUES" :key="value" :value="value">
					{{ t(`pptx.animation.afterAnimation.${value}`) }}
				</option>
			</select>
		</label>
		<label v-if="action === 'dimToColor'" class="pptx-vue-after-animation-color"
			>{{ t('pptx.animation.afterAnimation.color') }}
			<input
				type="color"
				:aria-label="t('pptx.animation.afterAnimation.color')"
				:value="color ?? '#808080'"
				@change="onColorChange"
			/>
		</label>
	</div>
</template>

<style scoped>
.pptx-vue-after-animation {
	display: grid;
	gap: 6px;
}
.pptx-vue-after-animation-color {
	display: flex;
	align-items: center;
	gap: 6px;
}
.pptx-vue-after-animation-color input[type='color'] {
	width: 40px;
	height: 24px;
	padding: 0;
}
</style>

// packages/angular/src/viewer/after-animation-row.component.ts
/**
 * after-animation-row.component.ts: the animation panel's "after animation"
 * row (dim to colour / hide after animation / hide on next click / don't dim).
 *
 * Selector: `pptx-after-animation-row`
 *
 * Its own component for the same reason as {@link MotionPathRowComponent}:
 * keeps {@link AnimationAuthorPanelComponent} under this repo's 300-LOC cap.
 *
 * Reference binding: packages/react/src/viewer/components/inspector/AfterAnimationRow.tsx
 *
 * @module viewer/after-animation-row
 */
import {
	ChangeDetectionStrategy,
	Component,
	input,
	output,
	CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxAfterAnimationAction } from 'pptx-viewer-core';

import { AFTER_ANIMATION_VALUES } from '../internal/shared';

@Component({
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	selector: 'pptx-after-animation-row',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<div class="pptx-ng-anim__section pptx-ng-after-animation">
			<label>
				<span class="pptx-ng-anim__label">{{ 'pptx.animation.afterAnimation' | translate }}</span>
				<pptx-ui-select
					[attr.aria-label]="'pptx.animation.afterAnimation' | translate"
					[attr.value]="action()"
					class="pptx-ng-anim__select"
					[disabled]="!canEdit()"
					(change)="onActionChange($event)"
				>
					@for (value of values; track value) {
						<option [value]="value" [selected]="action() === value">
							{{ 'pptx.animation.afterAnimation.' + value | translate }}
						</option>
					}
				</pptx-ui-select>
			</label>
			@if (action() === 'dimToColor') {
				<label class="pptx-ng-after-animation__color">
					<span class="pptx-ng-anim__label">{{
						'pptx.animation.afterAnimation.color' | translate
					}}</span>
					<input
						type="color"
						[attr.aria-label]="'pptx.animation.afterAnimation.color' | translate"
						[disabled]="!canEdit()"
						[value]="color() ?? '#808080'"
						(change)="onColorChange($event)"
					/>
				</label>
			}
		</div>
	`,
	styles: `
		.pptx-ng-after-animation {
			display: grid;
			gap: 6px;
		}
		.pptx-ng-after-animation__color {
			display: flex;
			align-items: center;
			gap: 6px;
		}
		.pptx-ng-after-animation__color input[type='color'] {
			width: 40px;
			height: 24px;
			padding: 0;
		}
	`,
})
export class AfterAnimationRowComponent {
	readonly action = input.required<PptxAfterAnimationAction>();
	readonly color = input<string | undefined>(undefined);
	readonly canEdit = input<boolean>(true);
	readonly actionChange = output<PptxAfterAnimationAction>();
	readonly colorChange = output<string>();

	protected readonly values = AFTER_ANIMATION_VALUES;

	protected onActionChange(event: Event): void {
		const target = event.target;
		if (!(target instanceof HTMLSelectElement)) {
			return;
		}
		this.actionChange.emit(target.value as PptxAfterAnimationAction);
	}

	protected onColorChange(event: Event): void {
		const target = event.target;
		if (!(target instanceof HTMLInputElement)) {
			return;
		}
		this.colorChange.emit(target.value);
	}
}
