// packages/vue/src/viewer/components/inspector/ChartTrendlineOptions.vue
<script setup lang="ts">
import type { PptxChartSeries, PptxChartTrendline, PptxChartType } from 'pptx-viewer-core';
import { TRENDLINE_SUPPORTED_TYPES, TRENDLINE_TYPE_OPTIONS } from 'pptx-viewer-shared';
import { computed } from 'vue';

/**
 * ChartTrendlineOptions: per-series trendline regression type + equation/R^2
 * display flags. Mirrors React's `ChartTrendlineOptions`. Emits
 * `setTrendline(index, trendline)` where `null` removes the trendline.
 */
const props = defineProps<{
	chartType: PptxChartType;
	series: readonly PptxChartSeries[];
}>();

const emit = defineEmits<{
	setTrendline: [index: number, trendline: PptxChartTrendline | null];
}>();

const visible = computed(
	() => TRENDLINE_SUPPORTED_TYPES.has(props.chartType) && props.series.length > 0,
);

function firstTrendline(s: PptxChartSeries): PptxChartTrendline | undefined {
	return s.trendlines?.[0];
}

function onType(event: Event, index: number, current: PptxChartTrendline | undefined): void {
	const value = (event.target as HTMLSelectElement).value;
	if (!value) {
		emit('setTrendline', index, null);
		return;
	}
	emit('setTrendline', index, {
		...current,
		trendlineType: value as PptxChartTrendline['trendlineType'],
	});
}

function onFlag(
	event: Event,
	index: number,
	current: PptxChartTrendline,
	key: 'displayEq' | 'displayRSq',
): void {
	emit('setTrendline', index, { ...current, [key]: (event.target as HTMLInputElement).checked });
}
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			Trendlines
		</div>
		<div class="space-y-2">
			<div v-for="(s, i) in props.series" :key="`${s.name}-${i}`" class="space-y-1">
				<div class="flex items-center gap-2 text-[11px]">
					<span class="flex-1 truncate" :title="s.name">{{ s.name }}</span>
					<select
						class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
						data-testid="chart-trendline-type"
						:value="firstTrendline(s)?.trendlineType ?? ''"
						@change="onType($event, i, firstTrendline(s))"
					>
						<option v-for="opt in TRENDLINE_TYPE_OPTIONS" :key="opt.value" :value="opt.value">
							{{ opt.label }}
						</option>
					</select>
				</div>

				<div v-if="firstTrendline(s)" class="flex items-center gap-3 ml-2">
					<label class="flex items-center gap-1 text-[11px] cursor-pointer">
						<input
							type="checkbox"
							data-testid="chart-trendline-eq"
							class="accent-primary"
							:checked="firstTrendline(s)?.displayEq ?? false"
							@change="onFlag($event, i, firstTrendline(s)!, 'displayEq')"
						/>
						<span>Equation</span>
					</label>
					<label class="flex items-center gap-1 text-[11px] cursor-pointer">
						<input
							type="checkbox"
							data-testid="chart-trendline-rsq"
							class="accent-primary"
							:checked="firstTrendline(s)?.displayRSq ?? false"
							@change="onFlag($event, i, firstTrendline(s)!, 'displayRSq')"
						/>
						<span>R-squared</span>
					</label>
				</div>
			</div>
		</div>
	</div>
</template>

// packages/angular/src/viewer/chart-trendline-options.component.ts
/**
 * chart-trendline-options.component.ts: Per-series trendline controls.
 *
 * Selector: `pptx-chart-trendline-options`
 *
 * Mirrors React's `ChartTrendlineOptions.tsx`: for bar/line/area/scatter/bubble
 * charts, each series gets a trendline-type selector plus (when a trendline is
 * set) display-equation and display-R-squared toggles. Routes through the
 * `setSeriesTrendline` immutable wrapper and emits a new `ChartPptxElement`.
 *
 * @module angular-viewer/chart-trendline-options
 */

import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import type {
	ChartPptxElement,
	PptxChartSeries,
	PptxChartTrendline,
	PptxChartType,
} from 'pptx-viewer-core';

import { TRENDLINE_SUPPORTED_TYPES, TRENDLINE_TYPE_OPTIONS } from '../internal/shared';
import { setSeriesTrendline } from './chart-advanced-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { boolFromEvent, selectValue } from './chart-event-helpers';

@Component({
	selector: 'pptx-chart-trendline-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		@if (supported()) {
			<section class="pptx-chart-card" aria-label="Trendline options">
				<h4 class="pptx-chart-card__heading">Trendlines</h4>
				@for (s of series(); track $index; let i = $index) {
					<div class="pptx-chart-card__group">
						<div class="pptx-chart-card__row">
							<span class="pptx-chart-card__name" [title]="s.name">{{ s.name }}</span>
							<select
								class="pptx-chart-card__input"
								[disabled]="!canEdit()"
								[value]="trendlineOf(s)?.trendlineType ?? ''"
								(change)="onType(i, s, $event)"
							>
								@for (opt of typeOptions; track opt.value) {
									<option [value]="opt.value">{{ opt.label }}</option>
								}
							</select>
						</div>

						@if (trendlineOf(s); as tl) {
							<div class="pptx-chart-card__row pptx-chart-card__group--indent">
								<label class="pptx-chart-card__check">
									<input
										type="checkbox"
										[disabled]="!canEdit()"
										[checked]="tl.displayEq ?? false"
										(change)="onToggleEq(i, tl, $event)"
									/>
									<span>Equation</span>
								</label>
								<label class="pptx-chart-card__check">
									<input
										type="checkbox"
										[disabled]="!canEdit()"
										[checked]="tl.displayRSq ?? false"
										(change)="onToggleRSq(i, tl, $event)"
									/>
									<span>R-squared</span>
								</label>
							</div>
						}
					</div>
				}
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartTrendlineOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	protected readonly typeOptions = TRENDLINE_TYPE_OPTIONS;

	protected readonly series = computed<PptxChartSeries[]>(
		() => this.element().chartData?.series ?? [],
	);

	protected readonly supported = computed(() => {
		const type = this.element().chartData?.chartType as PptxChartType | undefined;
		return type !== undefined && TRENDLINE_SUPPORTED_TYPES.has(type) && this.series().length > 0;
	});

	protected trendlineOf(s: PptxChartSeries): PptxChartTrendline | undefined {
		return s.trendlines?.[0];
	}

	protected onType(index: number, s: PptxChartSeries, event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		if (value === '') {
			this.elementChange.emit(setSeriesTrendline(this.element(), index, null));
			return;
		}
		const existing = this.trendlineOf(s);
		this.elementChange.emit(
			setSeriesTrendline(this.element(), index, {
				...existing,
				trendlineType: value as PptxChartTrendline['trendlineType'],
			}),
		);
	}

	protected onToggleEq(index: number, tl: PptxChartTrendline, event: Event): void {
		this.elementChange.emit(
			setSeriesTrendline(this.element(), index, { ...tl, displayEq: boolFromEvent(event) }),
		);
	}

	protected onToggleRSq(index: number, tl: PptxChartTrendline, event: Event): void {
		this.elementChange.emit(
			setSeriesTrendline(this.element(), index, { ...tl, displayRSq: boolFromEvent(event) }),
		);
	}
}
