// packages/vue/src/viewer/components/inspector/ChartDataLabelOptions.vue
<script setup lang="ts">
import type { PptxChartDataLabelOptions, PptxChartStyle } from 'pptx-viewer-core';
import { DATA_LABEL_CONTENT_OPTIONS, DATA_LABEL_POSITION_OPTIONS } from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * ChartDataLabelOptions: data-label content flags + position. Only rendered once
 * the master data-labels toggle (in ChartDisplayOptions) is on. Mirrors React's
 * `ChartDataLabelOptions`; emits a shallow `PptxChartStyle` patch.
 */
const props = defineProps<{
	style: PptxChartStyle | undefined;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxChartStyle>];
}>();

const { t } = useI18n();

const visible = computed(() => Boolean(props.style?.hasDataLabels));
const labels = computed<PptxChartDataLabelOptions>(() => props.style?.dataLabels ?? {});

function patchLabels(patch: Partial<PptxChartDataLabelOptions>): void {
	emit('update', { dataLabels: { ...labels.value, ...patch } });
}

function onContentToggle(event: Event, key: keyof PptxChartDataLabelOptions): void {
	patchLabels({ [key]: (event.target as HTMLInputElement).checked });
}

function onPosition(event: Event): void {
	const value = (event.target as HTMLSelectElement).value;
	patchLabels({
		position: (value || undefined) as PptxChartDataLabelOptions['position'],
	});
}
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.dataLabels') }}
		</div>
		<div class="space-y-1.5">
			<label
				v-for="opt in DATA_LABEL_CONTENT_OPTIONS"
				:key="opt.key"
				class="flex items-center gap-2 cursor-pointer"
			>
				<pptx-ui-checkbox
					data-testid="chart-data-label-content"
					:checked="labels[opt.key] ?? false"
					@change="onContentToggle($event, opt.key)"
				/>
				<span class="text-[11px]">{{ t(opt.labelKey) }}</span>
			</label>

			<label class="flex items-center gap-2 text-[11px]">
				<span class="w-16 text-muted-foreground shrink-0">{{ t('pptx.chart.labelPosition') }}</span>
				<pptx-ui-select
					:aria-label="t('pptx.chart.labelPosition')"
					class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
					data-testid="chart-data-label-position"
					:value="labels.position ?? ''"
					@change="onPosition"
				>
					<option v-for="opt in DATA_LABEL_POSITION_OPTIONS" :key="opt.value" :value="opt.value">
						{{ t(opt.labelKey) }}
					</option>
				</pptx-ui-select>
			</label>
		</div>
	</div>
</template>

// packages/angular/src/viewer/chart-data-label-options.component.ts
/**
 * chart-data-label-options.component.ts: Chart-level data-label content +
 * position controls.
 *
 * Selector: `pptx-chart-data-label-options`
 *
 * Mirrors React's `ChartDataLabelOptions.tsx`: only renders when data labels are
 * switched on (the master toggle lives in `pptx-chart-display-options`). Lets the
 * user pick which content appears (value/category/series name/percent/legend key)
 * and the label position. Emits a complete new `ChartPptxElement`.
 *
 * @module angular-viewer/chart-data-label-options
 */

import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { ChartPptxElement, PptxChartDataLabelOptions } from 'pptx-viewer-core';

import type { ChartDataLabelContentKey } from '../internal/shared';
import { DATA_LABEL_CONTENT_OPTIONS, DATA_LABEL_POSITION_OPTIONS } from '../internal/shared';
import { setDataLabels } from './chart-advanced-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { boolFromEvent, selectValue } from './chart-event-helpers';

@Component({
	selector: 'pptx-chart-data-label-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (style().hasDataLabels) {
			<section class="pptx-chart-card" [attr.aria-label]="'pptx.chart.dataLabels' | translate">
				<h4 class="pptx-chart-card__heading">{{ 'pptx.chart.dataLabels' | translate }}</h4>
				<div class="pptx-chart-card__group">
					@for (opt of contentOptions; track opt.key) {
						<label class="pptx-chart-card__check">
							<input
								type="checkbox"
								[disabled]="!canEdit()"
								[checked]="labels()[opt.key] ?? false"
								(change)="onToggleContent(opt.key, $event)"
							/>
							<span>{{ opt.labelKey | translate }}</span>
						</label>
					}

					<label class="pptx-chart-card__row">
						<span class="pptx-chart-card__label">{{ 'pptx.chart.labelPosition' | translate }}</span>
						<select
							class="pptx-chart-card__input"
							[disabled]="!canEdit()"
							[value]="labels().position ?? ''"
							(change)="onPosition($event)"
						>
							@for (opt of positionOptions; track opt.value) {
								<option [value]="opt.value">{{ opt.labelKey | translate }}</option>
							}
						</select>
					</label>
				</div>
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartDataLabelOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	protected readonly contentOptions = DATA_LABEL_CONTENT_OPTIONS;
	protected readonly positionOptions = DATA_LABEL_POSITION_OPTIONS;

	protected readonly style = computed(() => this.element().chartData?.style ?? {});
	protected readonly labels = computed<PptxChartDataLabelOptions>(
		() => this.style().dataLabels ?? {},
	);

	protected onToggleContent(key: ChartDataLabelContentKey, event: Event): void {
		this.elementChange.emit(setDataLabels(this.element(), { [key]: boolFromEvent(event) }));
	}

	protected onPosition(event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(
			setDataLabels(this.element(), {
				position: (value || undefined) as PptxChartDataLabelOptions['position'],
			}),
		);
	}
}
