// packages/vue/src/viewer/components/ComparePanel.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import type { CompareResult } from '../composables/slide-compare';
import type { CanvasSize } from '../types';
import SlideDiffRow from './SlideDiffRow.vue';

/**
 * ComparePanel — side panel showing slide-level diffs between two versions.
 *
 * Vue port of the React `ComparePanel.tsx`. Lists each non-trivial
 * {@link SlideDiff} as a {@link SlideDiffRow}; the user can accept/reject
 * individual diffs or accept all at once. Accepted/rejected state is tracked
 * locally and propagated to the host via emits, which carry the diff index.
 */
const props = defineProps<{
	/** Whether the panel is visible. */
	open: boolean;
	/** The comparison result, or `null` when nothing to compare. */
	compareResult: CompareResult | null;
	/** Canvas dimensions used to render diff thumbnails. */
	canvasSize: CanvasSize;
	/** Resolved media data URLs for thumbnail rendering. */
	mediaDataUrls: Map<string, string>;
}>();

const emit = defineEmits<{
	(e: 'close'): void;
	(e: 'accept-slide', diffIndex: number): void;
	(e: 'reject-slide', diffIndex: number): void;
	(e: 'accept-all'): void;
}>();

const accepted = ref<Record<number, boolean>>({});
const rejected = ref<Record<number, boolean>>({});

const nonTrivialCount = computed(
	() => props.compareResult?.diffs.filter((d) => d.status !== 'unchanged').length ?? 0,
);

function handleAccept(index: number): void {
	accepted.value = { ...accepted.value, [index]: true };
	const next = { ...rejected.value };
	delete next[index];
	rejected.value = next;
	emit('accept-slide', index);
}

function handleReject(index: number): void {
	rejected.value = { ...rejected.value, [index]: true };
	const next = { ...accepted.value };
	delete next[index];
	accepted.value = next;
	emit('reject-slide', index);
}

function handleAcceptAll(): void {
	if (!props.compareResult) {
		return;
	}
	const acc: Record<number, boolean> = {};
	props.compareResult.diffs.forEach((d, i) => {
		if (d.status !== 'unchanged') {
			acc[i] = true;
		}
	});
	accepted.value = acc;
	rejected.value = {};
	emit('accept-all');
}
</script>

<template>
	<aside v-if="open && compareResult" class="pptx-vue-compare-panel">
		<header class="pptx-vue-compare-header">
			<div>
				<h3 class="pptx-vue-compare-title">Compare versions</h3>
				<p class="pptx-vue-compare-summary">
					{{ compareResult.addedCount }} added · {{ compareResult.removedCount }} removed ·
					{{ compareResult.changedCount }} changed
				</p>
			</div>
			<button
				type="button"
				class="pptx-vue-compare-close"
				aria-label="Close"
				@click="emit('close')"
			>
				&times;
			</button>
		</header>

		<div v-if="nonTrivialCount > 0" class="pptx-vue-compare-actions">
			<button type="button" class="pptx-vue-compare-accept-all" @click="handleAcceptAll">
				Accept all
			</button>
		</div>

		<div class="pptx-vue-compare-list">
			<p v-if="nonTrivialCount === 0" class="pptx-vue-compare-empty">No differences</p>
			<template v-else>
				<SlideDiffRow
					v-for="(diff, i) in compareResult.diffs"
					:key="`diff-${i}-${diff.status}`"
					:diff="diff"
					:diff-index="i"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:accepted="Boolean(accepted[i])"
					:rejected="Boolean(rejected[i])"
					@accept="handleAccept"
					@reject="handleReject"
				/>
			</template>
		</div>
	</aside>
</template>

<style scoped>
.pptx-vue-compare-panel {
	position: fixed;
	top: 0;
	bottom: 0;
	right: 0;
	z-index: 50;
	display: flex;
	flex-direction: column;
	width: 440px;
	max-width: 100vw;
	background: var(--pptx-vue-popover, #ffffff);
	color: var(--pptx-vue-foreground, #111827);
	border-left: 1px solid var(--pptx-vue-border, #e5e7eb);
	box-shadow: -8px 0 32px rgba(0, 0, 0, 0.25);
}

.pptx-vue-compare-header {
	display: flex;
	align-items: flex-start;
	justify-content: space-between;
	gap: 12px;
	padding: 12px 16px;
	border-bottom: 1px solid var(--pptx-vue-border, #e5e7eb);
}

.pptx-vue-compare-title {
	margin: 0;
	font-size: 14px;
	font-weight: 600;
}

.pptx-vue-compare-summary {
	margin: 2px 0 0;
	font-size: 11px;
	color: var(--pptx-vue-muted-foreground, #6b7280);
}

.pptx-vue-compare-close {
	display: inline-flex;
	align-items: center;
	justify-content: center;
	width: 24px;
	height: 24px;
	padding: 0;
	font-size: 18px;
	line-height: 1;
	color: var(--pptx-vue-muted-foreground, #6b7280);
	background: transparent;
	border: none;
	border-radius: 4px;
	cursor: pointer;
}

.pptx-vue-compare-actions {
	padding: 8px 16px;
	border-bottom: 1px solid var(--pptx-vue-border, #e5e7eb);
}

.pptx-vue-compare-accept-all {
	display: inline-flex;
	align-items: center;
	padding: 6px 12px;
	font-size: 12px;
	color: #f0fdf4;
	background: #15803d;
	border: none;
	border-radius: 4px;
	cursor: pointer;
}

.pptx-vue-compare-list {
	display: flex;
	flex-direction: column;
	gap: 8px;
	flex: 1;
	overflow-y: auto;
	padding: 12px;
}

.pptx-vue-compare-empty {
	margin: 0;
	padding: 32px 0;
	text-align: center;
	font-size: 12px;
	color: var(--pptx-vue-muted-foreground, #6b7280);
}
</style>

// packages/angular/src/viewer/compare-panel.component.ts
/**
 * compare-panel.component.ts: right-docked slide comparison review panel.
 *
 * Selector: `pptx-compare-panel`
 *
 * Angular port of the React `ComparePanel` (packages/react/src/viewer/
 * components/ComparePanel.tsx). Displays the slide-level {@link CompareResult}
 * diff between two presentations as a scrollable list of
 * {@link SlideDiffRowComponent} cards. Users accept or reject individual slide
 * changes (or accept all at once); accepted/rejected state is tracked locally
 * and surfaced to the host through the `acceptSlide` / `rejectSlide` /
 * `acceptAll` outputs.
 */

import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';

import type { CanvasSize, CompareResult } from '../internal/shared';
import { SlideDiffRowComponent } from './slide-diff-row.component';

@Component({
	selector: 'pptx-compare-panel',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [SlideDiffRowComponent],
	template: `
		@if (open() && compareResult(); as result) {
			<div class="pptx-ng-compare">
				<!-- Header -->
				<div class="pptx-ng-compare-head">
					<div>
						<h3 class="pptx-ng-compare-title">Compare Presentations</h3>
						<p class="pptx-ng-compare-summary">
							{{ result.addedCount }} added, {{ result.removedCount }} removed,
							{{ result.changedCount }} changed
						</p>
					</div>
					<button
						type="button"
						class="pptx-ng-compare-close"
						title="Close"
						aria-label="Close compare panel"
						(click)="close.emit()"
					>
						✕
					</button>
				</div>

				<!-- Accept all -->
				@if (nonTrivialCount() > 0) {
					<div class="pptx-ng-compare-acceptall">
						<button type="button" class="pptx-ng-compare-acceptall-btn" (click)="handleAcceptAll()">
							✓ Accept all
						</button>
					</div>
				}

				<!-- Diff list -->
				<div class="pptx-ng-compare-list">
					@if (nonTrivialCount() === 0) {
						<div class="pptx-ng-compare-empty">No differences</div>
					} @else {
						@for (diff of result.diffs; track $index; let i = $index) {
							<pptx-slide-diff-row
								[diff]="diff"
								[diffIndex]="i"
								[canvasSize]="canvasSize()"
								[mediaDataUrls]="mediaDataUrls()"
								[accepted]="isAccepted(i)"
								[rejected]="isRejected(i)"
								(accept)="handleAccept($event)"
								(reject)="handleReject($event)"
							/>
						}
					}
				</div>
			</div>
		}
	`,
	styles: [
		`
			.pptx-ng-compare {
				position: fixed;
				inset-block: 0;
				right: 0;
				z-index: 50;
				display: flex;
				flex-direction: column;
				width: 440px;
				max-width: 100%;
				border-left: 1px solid var(--pptx-border, #374151);
				background: var(--pptx-popover, #0b1220);
				backdrop-filter: blur(12px);
				box-shadow: -12px 0 40px rgba(0, 0, 0, 0.5);
			}
			.pptx-ng-compare-head {
				display: flex;
				align-items: center;
				justify-content: space-between;
				padding: 0.75rem 1rem;
				border-bottom: 1px solid var(--pptx-border, #374151);
			}
			.pptx-ng-compare-title {
				margin: 0;
				font-size: 0.875rem;
				font-weight: 500;
				color: var(--pptx-foreground, #f3f4f6);
			}
			.pptx-ng-compare-summary {
				margin: 0.125rem 0 0;
				font-size: 0.6875rem;
				color: var(--pptx-muted-foreground, #9ca3af);
			}
			.pptx-ng-compare-close {
				padding: 0.375rem;
				border: none;
				border-radius: 0.25rem;
				background: transparent;
				color: var(--pptx-muted-foreground, #9ca3af);
				cursor: pointer;
				transition: background 0.15s ease;
			}
			.pptx-ng-compare-close:hover {
				background: var(--pptx-muted, #1f2937);
				color: var(--pptx-foreground, #f3f4f6);
			}
			.pptx-ng-compare-acceptall {
				padding: 0.5rem 1rem;
				border-bottom: 1px solid var(--pptx-border, #374151);
			}
			.pptx-ng-compare-acceptall-btn {
				display: inline-flex;
				align-items: center;
				gap: 0.375rem;
				padding: 0.375rem 0.75rem;
				border: none;
				border-radius: 0.25rem;
				background: rgba(21, 128, 61, 0.8);
				color: #f0fdf4;
				font-size: 0.75rem;
				cursor: pointer;
				transition: background 0.15s ease;
			}
			.pptx-ng-compare-acceptall-btn:hover {
				background: #16a34a;
			}
			.pptx-ng-compare-list {
				flex: 1;
				overflow-y: auto;
				display: flex;
				flex-direction: column;
				gap: 0.5rem;
				padding: 0.75rem;
			}
			.pptx-ng-compare-empty {
				padding: 2rem 0;
				text-align: center;
				font-size: 0.75rem;
				color: var(--pptx-muted-foreground, #9ca3af);
			}
		`,
	],
})
export class ComparePanelComponent {
	readonly open = input<boolean>(false);
	readonly compareResult = input<CompareResult | null>(null);
	readonly canvasSize = input.required<CanvasSize>();
	readonly mediaDataUrls = input<Record<string, string>>({});

	readonly close = output<void>();
	readonly acceptSlide = output<number>();
	readonly rejectSlide = output<number>();
	readonly acceptAll = output<void>();

	/** Diff indices the user has accepted. */
	private readonly accepted = signal<Record<number, boolean>>({});
	/** Diff indices the user has rejected. */
	private readonly rejected = signal<Record<number, boolean>>({});

	/** Count of diffs worth reviewing (everything except `unchanged`). */
	readonly nonTrivialCount = computed(
		() => this.compareResult()?.diffs.filter((d) => d.status !== 'unchanged').length ?? 0,
	);

	isAccepted(index: number): boolean {
		return Boolean(this.accepted()[index]);
	}

	isRejected(index: number): boolean {
		return Boolean(this.rejected()[index]);
	}

	handleAccept(index: number): void {
		this.accepted.update((p) => ({ ...p, [index]: true }));
		this.rejected.update((p) => {
			const next = { ...p };
			delete next[index];
			return next;
		});
		this.acceptSlide.emit(index);
	}

	handleReject(index: number): void {
		this.rejected.update((p) => ({ ...p, [index]: true }));
		this.accepted.update((p) => {
			const next = { ...p };
			delete next[index];
			return next;
		});
		this.rejectSlide.emit(index);
	}

	handleAcceptAll(): void {
		const result = this.compareResult();
		if (!result) {
			return;
		}
		const acc: Record<number, boolean> = {};
		result.diffs.forEach((d, i) => {
			if (d.status !== 'unchanged') {
				acc[i] = true;
			}
		});
		this.accepted.set(acc);
		this.rejected.set({});
		this.acceptAll.emit();
	}
}
