// packages/vue/src/viewer/components/inspector/DocumentPropertiesCard.vue
<script setup lang="ts">
/**
 * DocumentPropertiesCard: DOCUMENT card (Title / Author / Company /
 * Application text fields + custom properties), mirroring React's
 * `DocumentPropertiesCard` in `inspector/DocumentPropertiesCards.tsx`.
 */
import type { PptxAppProperties, PptxCoreProperties, PptxCustomProperty } from 'pptx-viewer-core';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import CustomPropertiesBlock from './CustomPropertiesBlock.vue';
import { CARD, HEADING, INPUT } from './inspector-cards';

const props = withDefaults(
	defineProps<{
		coreProperties?: PptxCoreProperties;
		appProperties?: PptxAppProperties;
		customProperties: PptxCustomProperty[];
		canEdit?: boolean;
	}>(),
	{ canEdit: true },
);

const emit = defineEmits<{
	'update-core': [patch: Partial<PptxCoreProperties>];
	'update-app': [patch: Partial<PptxAppProperties>];
	'update-custom': [props: PptxCustomProperty[]];
}>();

const { t } = useI18n();

interface FieldRow {
	label: string;
	value: string;
	commit: (value: string) => void;
}

const fields = computed<FieldRow[]>(() => [
	{
		label: t('pptx.properties.titleLabel'),
		value: props.coreProperties?.title ?? '',
		commit: (v) => emit('update-core', { title: v }),
	},
	{
		label: t('pptx.properties.author'),
		value: props.coreProperties?.creator ?? '',
		commit: (v) => emit('update-core', { creator: v }),
	},
	{
		label: t('pptx.documentProperties.summary.company'),
		value: props.appProperties?.company ?? '',
		commit: (v) => emit('update-app', { company: v }),
	},
	{
		label: t('pptx.documentProperties.statistics.application'),
		value: props.appProperties?.application ?? '',
		commit: (v) => emit('update-app', { application: v }),
	},
]);
</script>

<template>
	<div :class="CARD">
		<div :class="HEADING">{{ t('pptx.documentProperties.documentHeading') }}</div>
		<div class="space-y-2 text-[11px] text-muted-foreground">
			<label v-for="field in fields" :key="field.label" class="flex flex-col gap-1">
				<span class="text-muted-foreground">{{ field.label }}</span>
				<input
					type="text"
					:class="INPUT"
					:disabled="!props.canEdit"
					:value="field.value"
					@input="(e) => field.commit((e.target as HTMLInputElement).value)"
				/>
			</label>
			<CustomPropertiesBlock
				:custom-properties="props.customProperties"
				:can-edit="props.canEdit"
				@update="(next) => emit('update-custom', next)"
			/>
		</div>
	</div>
</template>

// packages/angular/src/viewer/document-properties-card.component.ts
/**
 * document-properties-card.component.ts: DOCUMENT card of the default
 * (no-selection) inspector, mirroring React's `DocumentPropertiesCard`
 * (DocumentPropertiesCards.tsx): title / author / company / application text
 * fields plus the editable custom-properties list.
 *
 * Edits patch the loader's `coreProperties` / `appProperties` /
 * `customProperties` signals and mark the editor dirty.
 */
import { ChangeDetectionStrategy, Component, inject, input } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxAppProperties, PptxCoreProperties, PptxCustomProperty } from 'pptx-viewer-core';

import { EditorStateService } from './editor-state.service';
import { INSPECTOR_CARD_STYLES } from './inspector-card-styles';
import { LoadContentService } from './load-content.service';

@Component({
	selector: 'pptx-document-properties-card',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<section class="icard">
			<h3 class="icard__heading">{{ 'pptx.documentProperties.documentHeading' | translate }}</h3>
			<label class="icard__col">
				<span class="icard__label">{{ 'pptx.properties.titleLabel' | translate }}</span>
				<input
					type="text"
					class="icard__input"
					[disabled]="!canEdit()"
					[value]="core()?.title ?? ''"
					(change)="onCoreChange($event, 'title')"
				/>
			</label>
			<label class="icard__col">
				<span class="icard__label">{{ 'pptx.properties.author' | translate }}</span>
				<input
					type="text"
					class="icard__input"
					[disabled]="!canEdit()"
					[value]="core()?.creator ?? ''"
					(change)="onCoreChange($event, 'creator')"
				/>
			</label>
			<label class="icard__col">
				<span class="icard__label">{{
					'pptx.documentProperties.summary.company' | translate
				}}</span>
				<input
					type="text"
					class="icard__input"
					[disabled]="!canEdit()"
					[value]="app()?.company ?? ''"
					(change)="onAppChange($event, 'company')"
				/>
			</label>
			<label class="icard__col">
				<span class="icard__label">
					{{ 'pptx.documentProperties.statistics.application' | translate }}
				</span>
				<input
					type="text"
					class="icard__input"
					[disabled]="!canEdit()"
					[value]="app()?.application ?? ''"
					(change)="onAppChange($event, 'application')"
				/>
			</label>
			<div class="icard__row">
				<span class="icard__label">{{ 'pptx.documentProperties.custom.heading' | translate }}</span>
				@if (canEdit()) {
					<button type="button" class="icard__btn" style="flex: 0 0 auto" (click)="onAddCustom()">
						{{ 'pptx.documentProperties.custom.add' | translate }}
					</button>
				}
			</div>
			@if (custom().length === 0) {
				<span class="icard__label">{{ 'pptx.documentProperties.custom.empty' | translate }}</span>
			} @else {
				@for (entry of custom(); track $index) {
					<div class="icard__row">
						<input
							type="text"
							class="icard__input"
							[disabled]="!canEdit()"
							[value]="entry.name"
							(change)="onCustomChange($event, $index, 'name')"
						/>
						<input
							type="text"
							class="icard__input"
							[disabled]="!canEdit()"
							[value]="entry.value"
							(change)="onCustomChange($event, $index, 'value')"
						/>
						@if (canEdit()) {
							<button
								type="button"
								class="icard__btn icard__btn--danger"
								[title]="'pptx.documentProperties.custom.deleteProperty' | translate"
								(click)="onRemoveCustom($index)"
							>
								&#215;
							</button>
						}
					</div>
				}
			}
		</section>
	`,
	styles: [INSPECTOR_CARD_STYLES],
})
export class DocumentPropertiesCardComponent {
	/** Whether the fields are editable. */
	readonly canEdit = input<boolean>(true);

	private readonly loader = inject(LoadContentService);
	private readonly editor = inject(EditorStateService);

	protected readonly core = this.loader.coreProperties;
	protected readonly app = this.loader.appProperties;
	protected readonly custom = this.loader.customProperties;

	private markDirty(): void {
		this.editor.dirty.set(true);
	}

	protected onCoreChange(event: Event, key: 'title' | 'creator'): void {
		const value = (event.target as HTMLInputElement).value;
		this.loader.coreProperties.update(
			(current): PptxCoreProperties => ({ ...(current ?? {}), [key]: value }),
		);
		this.markDirty();
	}

	protected onAppChange(event: Event, key: 'company' | 'application'): void {
		const value = (event.target as HTMLInputElement).value;
		this.loader.appProperties.update(
			(current): PptxAppProperties => ({ ...(current ?? {}), [key]: value }),
		);
		this.markDirty();
	}

	protected onAddCustom(): void {
		const next: PptxCustomProperty[] = [
			...this.custom(),
			{ name: `Property ${this.custom().length + 1}`, value: '', type: 'lpwstr' },
		];
		this.loader.customProperties.set(next);
		this.markDirty();
	}

	protected onCustomChange(event: Event, index: number, key: 'name' | 'value'): void {
		const value = (event.target as HTMLInputElement).value;
		this.loader.customProperties.update((current) =>
			current.map((entry, i) => (i === index ? { ...entry, [key]: value } : entry)),
		);
		this.markDirty();
	}

	protected onRemoveCustom(index: number): void {
		this.loader.customProperties.update((current) => current.filter((_, i) => i !== index));
		this.markDirty();
	}
}
