// packages/svelte/src/viewer/components/inspector/EffectsPanel.svelte
<script lang="ts">
	/**
	 * EffectsPanel: the shape effects section (Outer Shadow, Inner Shadow, Glow,
	 * Reflection, Soft Edge), built entirely on the shared, framework-agnostic
	 * `effects-helpers.ts` / `effects-shadow-helpers.ts` reader + patch-builder
	 * pair (`effectsStateOf`, `enable*Patch` / `disable*Patch` / `update*Patch`).
	 * Bevel/3D is out of scope here (no shared decision function yet). Rendered
	 * by `InspectorPanel` alongside `FillStrokeSection` for shape-property
	 * elements only.
	 */
	import type { PptxElement } from 'pptx-viewer-core';
	import {
		disableGlowPatch,
		disableInnerShadowPatch,
		disableOuterShadowPatch,
		disableReflectionPatch,
		disableSoftEdgePatch,
		effectsStateOf,
		enableGlowPatch,
		enableInnerShadowPatch,
		enableOuterShadowPatch,
		enableReflectionPatch,
		enableSoftEdgePatch,
		updateGlowPatch,
		updateInnerShadowPatch,
		updateOuterShadowPatch,
		updateReflectionPatch,
	} from 'pptx-viewer-shared';

	import { useTranslator } from '../../../i18n/context';
	import type { EditorState } from '../../editor/editor-state.svelte';

	const { editor, el }: { editor: EditorState; el: PptxElement } = $props();
	const t = useTranslator();

	const effects = $derived(effectsStateOf(el));

	function pushColor(hex: string): void {
		editor.recordRecentColor(hex);
	}
</script>

<div class="pptx-svelte-effects">
	<!-- Outer Shadow -->
	<label class="pptx-svelte-effects-toggle">
		<pptx-ui-checkbox
			checked={effects.outerShadow.enabled}
			onchange={(e) =>
				editor.patchSelected(
					e.currentTarget.checked
						? enableOuterShadowPatch(el, effects.outerShadow)
						: disableOuterShadowPatch(el),
				)}
		></pptx-ui-checkbox>
		<span>{t('pptx.effects.outerShadow')}</span>
	</label>
	{#if effects.outerShadow.enabled}
		<div class="pptx-svelte-effects-fields">
			<label>{t('pptx.effects.color')}<input type="color" value={effects.outerShadow.color} onchange={(e) => { editor.patchSelected(updateOuterShadowPatch(el, { color: e.currentTarget.value })); pushColor(e.currentTarget.value); }} /></label>
			<label>{t('pptx.effects.opacityPercent', { value: Math.round(effects.outerShadow.opacity * 100) })}<input type="range" min="0" max="100" value={Math.round(effects.outerShadow.opacity * 100)} oninput={(e) => editor.patchSelected(updateOuterShadowPatch(el, { opacity: Number(e.currentTarget.value) / 100 }))} /></label>
			<label>{t('pptx.effects.blur')}<input type="number" min="0" max="96" value={Math.round(effects.outerShadow.blur)} onchange={(e) => editor.patchSelected(updateOuterShadowPatch(el, { blur: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.angle')}<input type="number" min="0" max="359" value={Math.round(effects.outerShadow.angle)} onchange={(e) => editor.patchSelected(updateOuterShadowPatch(el, { angle: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.distance')}<input type="number" min="0" max="200" value={Math.round(effects.outerShadow.distance)} onchange={(e) => editor.patchSelected(updateOuterShadowPatch(el, { distance: Number(e.currentTarget.value) }))} /></label>
			<label class="pptx-svelte-effects-check">
				<pptx-ui-checkbox checked={effects.outerShadow.rotateWithShape} onchange={(e) => editor.patchSelected(updateOuterShadowPatch(el, { rotateWithShape: e.currentTarget.checked }))} ></pptx-ui-checkbox>
				<span>{t('pptx.effects.rotateWithShape')}</span>
			</label>
		</div>
	{/if}

	<!-- Inner Shadow -->
	<label class="pptx-svelte-effects-toggle">
		<pptx-ui-checkbox
			checked={effects.innerShadow.enabled}
			onchange={(e) =>
				editor.patchSelected(
					e.currentTarget.checked
						? enableInnerShadowPatch(el, effects.innerShadow)
						: disableInnerShadowPatch(el),
				)}
		></pptx-ui-checkbox>
		<span>{t('pptx.effects.innerShadow')}</span>
	</label>
	{#if effects.innerShadow.enabled}
		<div class="pptx-svelte-effects-fields">
			<label>{t('pptx.effects.color')}<input type="color" value={effects.innerShadow.color} onchange={(e) => { editor.patchSelected(updateInnerShadowPatch(el, { color: e.currentTarget.value })); pushColor(e.currentTarget.value); }} /></label>
			<label>{t('pptx.effects.opacityPercent', { value: Math.round(effects.innerShadow.opacity * 100) })}<input type="range" min="0" max="100" value={Math.round(effects.innerShadow.opacity * 100)} oninput={(e) => editor.patchSelected(updateInnerShadowPatch(el, { opacity: Number(e.currentTarget.value) / 100 }))} /></label>
			<label>{t('pptx.effects.blur')}<input type="number" min="0" max="96" value={Math.round(effects.innerShadow.blur)} onchange={(e) => editor.patchSelected(updateInnerShadowPatch(el, { blur: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.offsetX')}<input type="number" min="-96" max="96" value={Math.round(effects.innerShadow.offsetX)} onchange={(e) => editor.patchSelected(updateInnerShadowPatch(el, { offsetX: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.offsetY')}<input type="number" min="-96" max="96" value={Math.round(effects.innerShadow.offsetY)} onchange={(e) => editor.patchSelected(updateInnerShadowPatch(el, { offsetY: Number(e.currentTarget.value) }))} /></label>
		</div>
	{/if}

	<!-- Glow -->
	<label class="pptx-svelte-effects-toggle">
		<pptx-ui-checkbox
			checked={effects.glow.enabled}
			onchange={(e) =>
				editor.patchSelected(
					e.currentTarget.checked ? enableGlowPatch(el, effects.glow) : disableGlowPatch(el),
				)}
		></pptx-ui-checkbox>
		<span>{t('pptx.effects.glow')}</span>
	</label>
	{#if effects.glow.enabled}
		<div class="pptx-svelte-effects-fields">
			<label>{t('pptx.effects.color')}<input type="color" value={effects.glow.color} onchange={(e) => { editor.patchSelected(updateGlowPatch(el, { color: e.currentTarget.value })); pushColor(e.currentTarget.value); }} /></label>
			<label>{t('pptx.effects.radius')}<input type="number" min="0" max="96" value={Math.round(effects.glow.radius)} onchange={(e) => editor.patchSelected(updateGlowPatch(el, { radius: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.opacityPercent', { value: Math.round(effects.glow.opacity * 100) })}<input type="range" min="0" max="100" value={Math.round(effects.glow.opacity * 100)} oninput={(e) => editor.patchSelected(updateGlowPatch(el, { opacity: Number(e.currentTarget.value) / 100 }))} /></label>
		</div>
	{/if}

	<!-- Reflection -->
	<label class="pptx-svelte-effects-toggle">
		<pptx-ui-checkbox
			checked={effects.reflection.enabled}
			onchange={(e) =>
				editor.patchSelected(
					e.currentTarget.checked
						? enableReflectionPatch(el, effects.reflection)
						: disableReflectionPatch(el),
				)}
		></pptx-ui-checkbox>
		<span>{t('pptx.effects.reflection')}</span>
	</label>
	{#if effects.reflection.enabled}
		<div class="pptx-svelte-effects-fields">
			<label>{t('pptx.effects.blur')}<input type="number" min="0" max="96" value={Math.round(effects.reflection.blurRadius)} onchange={(e) => editor.patchSelected(updateReflectionPatch(el, { blurRadius: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.startPercent')}<input type="number" min="0" max="100" value={Math.round(effects.reflection.startOpacity)} onchange={(e) => editor.patchSelected(updateReflectionPatch(el, { startOpacity: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.endPercent')}<input type="number" min="0" max="100" value={Math.round(effects.reflection.endOpacity)} onchange={(e) => editor.patchSelected(updateReflectionPatch(el, { endOpacity: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.distance')}<input type="number" min="0" max="96" value={Math.round(effects.reflection.distance)} onchange={(e) => editor.patchSelected(updateReflectionPatch(el, { distance: Number(e.currentTarget.value) }))} /></label>
			<label>{t('pptx.effects.direction')}<input type="number" min="0" max="359" value={Math.round(effects.reflection.direction)} onchange={(e) => editor.patchSelected(updateReflectionPatch(el, { direction: Number(e.currentTarget.value) }))} /></label>
		</div>
	{/if}

	<!-- Soft Edge -->
	<label class="pptx-svelte-effects-toggle">
		<pptx-ui-checkbox
			checked={effects.softEdge.enabled}
			onchange={(e) =>
				editor.patchSelected(
					e.currentTarget.checked
						? enableSoftEdgePatch(el, effects.softEdge.radius || 2.5)
						: disableSoftEdgePatch(el),
				)}
		></pptx-ui-checkbox>
		<span>{t('pptx.effects.softEdge')}</span>
	</label>
	{#if effects.softEdge.enabled}
		<div class="pptx-svelte-effects-fields">
			<label>{t('pptx.effects.radius')}<input type="number" min="0" max="96" step="0.5" value={effects.softEdge.radius} onchange={(e) => editor.patchSelected(enableSoftEdgePatch(el, Number(e.currentTarget.value)))} /></label>
		</div>
	{/if}
</div>

<style>
	.pptx-svelte-effects {
		display: flex;
		flex-direction: column;
		gap: 4px;
		margin-top: 6px;
	}

	.pptx-svelte-effects-toggle {
		display: flex;
		align-items: center;
		gap: 6px;
		margin-top: 8px;
		cursor: pointer;
	}

	.pptx-svelte-effects-fields {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 6px;
		margin-left: 4px;
	}

	.pptx-svelte-effects-fields label {
		display: grid;
		gap: 3px;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 10px;
	}

	.pptx-svelte-effects-check {
		grid-column: 1 / -1;
		display: flex !important;
		flex-direction: row !important;
		align-items: center;
		gap: 6px;
	}

	.pptx-svelte-effects-fields input {
		height: 26px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 5px;
		background: var(--pptx-background, #0f172a);
		color: inherit;
	}
</style>

// packages/angular/src/viewer/effects-panel.component.ts
/**
 * effects-panel.component.ts: Standalone Angular component for editing
 * visual effects (outer/inner shadow, glow, reflection, soft edge) on a
 * selected PPTX element.
 *
 * Selector: `pptx-effects-panel`
 *
 * Ported from / models the patterns in:
 *   packages/react/src/viewer/components/inspector/fill-stroke-effect-configs.ts
 *   packages/react/src/viewer/components/inspector/fill-stroke-visual-configs.ts
 *   packages/angular/src/viewer/inspector-panel.component.ts
 *
 * Contract:
 *   [element]     : the selected PptxElement (required)
 *   (patch)       : emits a Partial<PptxElement> for the orchestrator to
 *                   commit via EditorStateService.updateElement
 *
 * @module viewer/effects-panel
 */

import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxElement } from 'pptx-viewer-core';

import {
	disableGlowPatch,
	disableInnerShadowPatch,
	disableOuterShadowPatch,
	disableReflectionPatch,
	disableSoftEdgePatch,
	effectsStateOf,
	enableGlowPatch,
	enableInnerShadowPatch,
	enableOuterShadowPatch,
	enableReflectionPatch,
	enableSoftEdgePatch,
	updateGlowPatch,
	updateInnerShadowPatch,
	updateOuterShadowPatch,
	updateReflectionPatch,
} from './effects-helpers';
import type { EffectsState } from './effects-helpers';

@Component({
	selector: 'pptx-effects-panel',
	standalone: true,
	imports: [TranslatePipe],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div class="pptx-ng-fx">
			<!-- ── Outer Shadow ─────────────────────────────────────────── -->
			<section class="pptx-ng-fx__section">
				<label class="pptx-ng-fx__toggle-row">
					<input
						type="checkbox"
						class="pptx-ng-fx__checkbox"
						[checked]="state().outerShadow.enabled"
						(change)="onOuterShadowToggle($event)"
					/>
					<span class="pptx-ng-fx__section-title">{{
						'pptx.effects.outerShadow' | translate
					}}</span>
				</label>
				@if (state().outerShadow.enabled) {
					<div class="pptx-ng-fx__fields" [attr.data-el-key]="elementKey()">
						<label class="pptx-ng-fx__label" for="fx-os-color">{{
							'pptx.effects.color' | translate
						}}</label>
						<input
							id="fx-os-color"
							class="pptx-ng-fx__color"
							type="color"
							[value]="state().outerShadow.color"
							(change)="onOuterShadowField('color', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-os-opacity">{{
							'pptx.effects.opacity' | translate
						}}</label>
						<input
							id="fx-os-opacity"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="decimal"
							min="0"
							max="1"
							step="0.05"
							[value]="state().outerShadow.opacity"
							(change)="onOuterShadowField('opacity', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-os-blur">{{
							'pptx.effects.blur' | translate
						}}</label>
						<input
							id="fx-os-blur"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="96"
							[value]="state().outerShadow.blur"
							(change)="onOuterShadowField('blur', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-os-angle">{{
							'pptx.effects.angle' | translate
						}}</label>
						<input
							id="fx-os-angle"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="359"
							[value]="state().outerShadow.angle"
							(change)="onOuterShadowField('angle', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-os-dist">{{
							'pptx.effects.distance' | translate
						}}</label>
						<input
							id="fx-os-dist"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="decimal"
							min="0"
							max="100"
							step="0.5"
							[value]="state().outerShadow.distance"
							(change)="onOuterShadowField('distance', $event)"
						/>
					</div>
				}
			</section>

			<!-- ── Inner Shadow ─────────────────────────────────────────── -->
			<section class="pptx-ng-fx__section">
				<label class="pptx-ng-fx__toggle-row">
					<input
						type="checkbox"
						class="pptx-ng-fx__checkbox"
						[checked]="state().innerShadow.enabled"
						(change)="onInnerShadowToggle($event)"
					/>
					<span class="pptx-ng-fx__section-title">{{
						'pptx.effects.innerShadow' | translate
					}}</span>
				</label>
				@if (state().innerShadow.enabled) {
					<div class="pptx-ng-fx__fields" [attr.data-el-key]="elementKey()">
						<label class="pptx-ng-fx__label" for="fx-is-color">{{
							'pptx.effects.color' | translate
						}}</label>
						<input
							id="fx-is-color"
							class="pptx-ng-fx__color"
							type="color"
							[value]="state().innerShadow.color"
							(change)="onInnerShadowField('color', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-is-opacity">{{
							'pptx.effects.opacity' | translate
						}}</label>
						<input
							id="fx-is-opacity"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="decimal"
							min="0"
							max="1"
							step="0.05"
							[value]="state().innerShadow.opacity"
							(change)="onInnerShadowField('opacity', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-is-blur">{{
							'pptx.effects.blur' | translate
						}}</label>
						<input
							id="fx-is-blur"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="96"
							[value]="state().innerShadow.blur"
							(change)="onInnerShadowField('blur', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-is-ox">{{
							'pptx.effects.offsetX' | translate
						}}</label>
						<input
							id="fx-is-ox"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="-96"
							max="96"
							[value]="state().innerShadow.offsetX"
							(change)="onInnerShadowField('offsetX', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-is-oy">{{
							'pptx.effects.offsetY' | translate
						}}</label>
						<input
							id="fx-is-oy"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="-96"
							max="96"
							[value]="state().innerShadow.offsetY"
							(change)="onInnerShadowField('offsetY', $event)"
						/>
					</div>
				}
			</section>

			<!-- ── Glow ─────────────────────────────────────────────────── -->
			<section class="pptx-ng-fx__section">
				<label class="pptx-ng-fx__toggle-row">
					<input
						type="checkbox"
						class="pptx-ng-fx__checkbox"
						[checked]="state().glow.enabled"
						(change)="onGlowToggle($event)"
					/>
					<span class="pptx-ng-fx__section-title">{{ 'pptx.effects.glow' | translate }}</span>
				</label>
				@if (state().glow.enabled) {
					<div class="pptx-ng-fx__fields" [attr.data-el-key]="elementKey()">
						<label class="pptx-ng-fx__label" for="fx-glow-color">{{
							'pptx.effects.color' | translate
						}}</label>
						<input
							id="fx-glow-color"
							class="pptx-ng-fx__color"
							type="color"
							[value]="state().glow.color"
							(change)="onGlowField('color', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-glow-radius">{{
							'pptx.effects.size' | translate
						}}</label>
						<input
							id="fx-glow-radius"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="96"
							[value]="state().glow.radius"
							(change)="onGlowField('radius', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-glow-opacity">{{
							'pptx.effects.opacity' | translate
						}}</label>
						<input
							id="fx-glow-opacity"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="decimal"
							min="0"
							max="1"
							step="0.05"
							[value]="state().glow.opacity"
							(change)="onGlowField('opacity', $event)"
						/>
					</div>
				}
			</section>

			<!-- ── Reflection ───────────────────────────────────────────── -->
			<section class="pptx-ng-fx__section">
				<label class="pptx-ng-fx__toggle-row">
					<input
						type="checkbox"
						class="pptx-ng-fx__checkbox"
						[checked]="state().reflection.enabled"
						(change)="onReflectionToggle($event)"
					/>
					<span class="pptx-ng-fx__section-title">{{ 'pptx.effects.reflection' | translate }}</span>
				</label>
				@if (state().reflection.enabled) {
					<div class="pptx-ng-fx__fields" [attr.data-el-key]="elementKey()">
						<label class="pptx-ng-fx__label" for="fx-ref-blur">{{
							'pptx.effects.blur' | translate
						}}</label>
						<input
							id="fx-ref-blur"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="decimal"
							min="0"
							max="20"
							step="0.5"
							[value]="state().reflection.blurRadius"
							(change)="onReflectionField('blurRadius', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-ref-so">{{
							'pptx.effects.startPercent' | translate
						}}</label>
						<input
							id="fx-ref-so"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="100"
							[value]="state().reflection.startOpacity"
							(change)="onReflectionField('startOpacity', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-ref-eo">{{
							'pptx.effects.endPercent' | translate
						}}</label>
						<input
							id="fx-ref-eo"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="100"
							[value]="state().reflection.endOpacity"
							(change)="onReflectionField('endOpacity', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-ref-dist">{{
							'pptx.effects.distance' | translate
						}}</label>
						<input
							id="fx-ref-dist"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="50"
							[value]="state().reflection.distance"
							(change)="onReflectionField('distance', $event)"
						/>
						<label class="pptx-ng-fx__label" for="fx-ref-dir">{{
							'pptx.effects.direction' | translate
						}}</label>
						<input
							id="fx-ref-dir"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="360"
							[value]="state().reflection.direction"
							(change)="onReflectionField('direction', $event)"
						/>
					</div>
				}
			</section>

			<!-- ── Soft Edge ─────────────────────────────────────────────── -->
			<section class="pptx-ng-fx__section">
				<label class="pptx-ng-fx__toggle-row">
					<input
						type="checkbox"
						class="pptx-ng-fx__checkbox"
						[checked]="state().softEdge.enabled"
						(change)="onSoftEdgeToggle($event)"
					/>
					<span class="pptx-ng-fx__section-title">{{ 'pptx.effects.softEdge' | translate }}</span>
				</label>
				@if (state().softEdge.enabled) {
					<div class="pptx-ng-fx__fields" [attr.data-el-key]="elementKey()">
						<label class="pptx-ng-fx__label" for="fx-se-radius">{{
							'pptx.effects.radius' | translate
						}}</label>
						<input
							id="fx-se-radius"
							class="pptx-ng-fx__input pptx-ng-fx__input--number"
							type="number"
							inputmode="numeric"
							min="0"
							max="96"
							[value]="state().softEdge.radius"
							(change)="onSoftEdgeRadius($event)"
						/>
					</div>
				}
			</section>
		</div>
	`,
	styles: `
		.pptx-ng-fx {
			display: flex;
			flex-direction: column;
			gap: 0;
			padding: 0.5rem;
			font-size: 12px;
			color: var(--pptx-inspector-fg, #e0e0e0);
		}

		.pptx-ng-fx__section {
			padding: 0.35rem 0;
			border-bottom: 1px solid var(--pptx-inspector-border, #333);
		}

		.pptx-ng-fx__section:last-child {
			border-bottom: none;
		}

		.pptx-ng-fx__section-title {
			font-size: 11px;
			font-weight: 500;
		}

		.pptx-ng-fx__toggle-row {
			display: flex;
			align-items: center;
			gap: 0.4rem;
			cursor: pointer;
		}

		.pptx-ng-fx__checkbox {
			cursor: pointer;
		}

		.pptx-ng-fx__fields {
			display: flex;
			flex-wrap: wrap;
			align-items: center;
			gap: 0.3rem;
			padding: 0.35rem 0 0 1.25rem;
		}

		.pptx-ng-fx__label {
			font-size: 10px;
			color: var(--pptx-inspector-muted, #888);
			min-width: 36px;
			text-align: right;
			flex-shrink: 0;
		}

		.pptx-ng-fx__input {
			background: var(--pptx-inspector-input-bg, #2d2d2d);
			border: 1px solid var(--pptx-inspector-border, #444);
			color: inherit;
			border-radius: 3px;
			padding: 2px 4px;
			font-size: 12px;
		}

		.pptx-ng-fx__input--number {
			width: 56px;
			text-align: right;
		}

		.pptx-ng-fx__color {
			width: 32px;
			height: 22px;
			border: 1px solid var(--pptx-inspector-border, #444);
			border-radius: 3px;
			padding: 1px;
			cursor: pointer;
			background: transparent;
			flex-shrink: 0;
		}
	`,
})
export class EffectsPanelComponent {
	/** The element whose effects are being edited. */
	readonly element = input.required<PptxElement>();

	/**
	 * Emits a Partial<PptxElement> patch each time the user commits a change.
	 * The orchestrator should call EditorStateService.updateElement(slideIndex, element().id, patch).
	 */
	readonly patch = output<Partial<PptxElement>>();

	/** Derived EffectsState from the current element. */
	protected readonly state = computed<EffectsState>(() => effectsStateOf(this.element()));

	/** Stable key for keying inputs to the current element (prevents caret-reset). */
	protected readonly elementKey = computed(() => this.element().id);

	// ── Outer shadow ──────────────────────────────────────────────────────────

	protected onOuterShadowToggle(event: Event): void {
		const checked = checkedFromEvent(event);
		if (checked === null) {
			return;
		}
		const el = this.element();
		this.emit(
			checked ? enableOuterShadowPatch(el, this.state().outerShadow) : disableOuterShadowPatch(el),
		);
	}

	protected onOuterShadowField(
		field: 'color' | 'opacity' | 'blur' | 'angle' | 'distance',
		event: Event,
	): void {
		const el = this.element();
		if (field === 'color') {
			const val = stringFromEvent(event);
			if (val) {
				this.emit(updateOuterShadowPatch(el, { color: val }));
			}
			return;
		}
		const val = numberFromEvent(event);
		if (val === null) {
			return;
		}
		this.emit(updateOuterShadowPatch(el, { [field]: val }));
	}

	// ── Inner shadow ──────────────────────────────────────────────────────────

	protected onInnerShadowToggle(event: Event): void {
		const checked = checkedFromEvent(event);
		if (checked === null) {
			return;
		}
		const el = this.element();
		this.emit(
			checked ? enableInnerShadowPatch(el, this.state().innerShadow) : disableInnerShadowPatch(el),
		);
	}

	protected onInnerShadowField(
		field: 'color' | 'opacity' | 'blur' | 'offsetX' | 'offsetY',
		event: Event,
	): void {
		const el = this.element();
		if (field === 'color') {
			const val = stringFromEvent(event);
			if (val) {
				this.emit(updateInnerShadowPatch(el, { color: val }));
			}
			return;
		}
		const val = numberFromEvent(event);
		if (val === null) {
			return;
		}
		this.emit(updateInnerShadowPatch(el, { [field]: val }));
	}

	// ── Glow ──────────────────────────────────────────────────────────────────

	protected onGlowToggle(event: Event): void {
		const checked = checkedFromEvent(event);
		if (checked === null) {
			return;
		}
		const el = this.element();
		this.emit(checked ? enableGlowPatch(el, this.state().glow) : disableGlowPatch(el));
	}

	protected onGlowField(field: 'color' | 'radius' | 'opacity', event: Event): void {
		const el = this.element();
		if (field === 'color') {
			const val = stringFromEvent(event);
			if (val) {
				this.emit(updateGlowPatch(el, { color: val }));
			}
			return;
		}
		const val = numberFromEvent(event);
		if (val === null) {
			return;
		}
		this.emit(updateGlowPatch(el, { [field]: val }));
	}

	// ── Reflection ────────────────────────────────────────────────────────────

	protected onReflectionToggle(event: Event): void {
		const checked = checkedFromEvent(event);
		if (checked === null) {
			return;
		}
		const el = this.element();
		this.emit(
			checked ? enableReflectionPatch(el, this.state().reflection) : disableReflectionPatch(el),
		);
	}

	protected onReflectionField(
		field: 'blurRadius' | 'startOpacity' | 'endOpacity' | 'distance' | 'direction',
		event: Event,
	): void {
		const val = numberFromEvent(event);
		if (val === null) {
			return;
		}
		this.emit(updateReflectionPatch(this.element(), { [field]: val }));
	}

	// ── Soft edge ─────────────────────────────────────────────────────────────

	protected onSoftEdgeToggle(event: Event): void {
		const checked = checkedFromEvent(event);
		if (checked === null) {
			return;
		}
		const el = this.element();
		this.emit(
			checked
				? enableSoftEdgePatch(el, this.state().softEdge.radius || 6)
				: disableSoftEdgePatch(el),
		);
	}

	protected onSoftEdgeRadius(event: Event): void {
		const val = numberFromEvent(event);
		if (val === null) {
			return;
		}
		this.emit(enableSoftEdgePatch(this.element(), val));
	}

	// ── Internal ──────────────────────────────────────────────────────────────

	private emit(p: Partial<PptxElement>): void {
		this.patch.emit(p);
	}
}

// ── Module-private helpers ────────────────────────────────────────────────────

function numberFromEvent(event: Event): number | null {
	const target = event.target;
	if (!(target instanceof HTMLInputElement)) {
		return null;
	}
	const parsed = parseFloat(target.value);
	return Number.isFinite(parsed) ? parsed : null;
}

function stringFromEvent(event: Event): string | null {
	const target = event.target;
	if (!(target instanceof HTMLInputElement)) {
		return null;
	}
	const val = target.value.trim();
	return val.length > 0 ? val : null;
}

function checkedFromEvent(event: Event): boolean | null {
	const target = event.target;
	if (!(target instanceof HTMLInputElement)) {
		return null;
	}
	return target.checked;
}
