// packages/svelte/src/viewer/components/ExportProgressModal.svelte
<script lang="ts">
	/**
	 * ExportProgressModal: a centered, non-dismissable overlay shown while a
	 * multi-slide export (PDF / GIF / WebM) runs. Svelte port of Vue's
	 * `ExportProgressModal.vue` (same layout and theme tokens, scoped CSS over
	 * the `--pptx-*` variables instead of Tailwind utilities).
	 *
	 * It deliberately does NOT close on backdrop click or Escape: an export in
	 * flight should only end by completing, erroring, or the user pressing
	 * Cancel. `oncancel` aborts cooperatively (the export loops check the
	 * signal between slides).
	 */
	import { clampPercent } from 'pptx-viewer-shared';

	import { useTranslator } from '../../i18n/context';

	const {
		open,
		title,
		progress,
		statusMessage,
		oncancel,
	}: {
		open: boolean;
		title: string;
		progress: number;
		statusMessage?: string;
		oncancel: () => void;
	} = $props();

	const t = useTranslator();

	const clamped = $derived(clampPercent(progress));
</script>

{#if open}
	<div class="pptx-svelte-export-progress-backdrop" role="dialog" aria-modal="true" aria-label={title}>
		<div class="pptx-svelte-export-progress-panel">
			<h3>{title}</h3>
			<div class="pptx-svelte-export-progress-track">
				<div class="pptx-svelte-export-progress-fill" style={`width: ${clamped}%`}></div>
			</div>
			<div class="pptx-svelte-export-progress-status">
				<span>{statusMessage ?? t('pptx.export.processing')}</span>
				<span class="pptx-svelte-export-progress-pct">{clamped}%</span>
			</div>
			<div class="pptx-svelte-export-progress-actions">
				<button type="button" onclick={() => oncancel()}>{t('pptx.export.cancel')}</button>
			</div>
		</div>
	</div>
{/if}

<style>
	.pptx-svelte-export-progress-backdrop {
		position: fixed;
		inset: 0;
		z-index: 1200;
		display: flex;
		align-items: center;
		justify-content: center;
		background: rgba(0, 0, 0, 0.6);
		backdrop-filter: blur(4px);
	}

	.pptx-svelte-export-progress-panel {
		width: min(92vw, 384px);
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: calc(var(--pptx-radius, 6px) + 6px);
		background: var(--pptx-popover, #111827);
		color: var(--pptx-popover-foreground, #f3f4f6);
		padding: 24px;
		box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
		font-family: system-ui, sans-serif;
	}

	.pptx-svelte-export-progress-panel h3 {
		margin: 0 0 16px;
		font-size: 14px;
		font-weight: 600;
	}

	.pptx-svelte-export-progress-track {
		height: 10px;
		width: 100%;
		overflow: hidden;
		border-radius: 9999px;
		background: var(--pptx-muted, #1f2937);
		margin-bottom: 12px;
	}

	.pptx-svelte-export-progress-fill {
		height: 100%;
		border-radius: 9999px;
		background: var(--pptx-primary, #6366f1);
		transition: width 0.3s ease-out;
	}

	.pptx-svelte-export-progress-status {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 16px;
		font-size: 12px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-export-progress-pct {
		font-variant-numeric: tabular-nums;
	}

	.pptx-svelte-export-progress-actions {
		display: flex;
		justify-content: flex-end;
	}

	.pptx-svelte-export-progress-actions button {
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-muted, #1f2937);
		color: var(--pptx-foreground, #f3f4f6);
		padding: 6px 16px;
		font-size: 12px;
		font-family: inherit;
		cursor: pointer;
		transition: background 0.15s;
	}

	.pptx-svelte-export-progress-actions button:hover {
		background: var(--pptx-accent, #33334d);
	}
</style>

// packages/angular/src/viewer/export-progress-modal.component.ts
/**
 * export-progress-modal.component.ts: progress overlay shown while a multi-slide
 * export (PDF / GIF / WebM) runs.
 *
 * Selector: `pptx-export-progress-modal`
 *
 * Mirrors React's `ExportProgressModal` and the Vue `ExportProgressModal.vue`: a
 * centered card with a determinate progress bar, a status line, and a Cancel
 * button. It is deliberately NOT dismissable by backdrop click or Escape - an
 * export in flight should only end by completing, erroring, or the user pressing
 * Cancel (which emits `cancel`; the host aborts the `AbortController` the export
 * loop checks between slides and clears `open`).
 *
 * Usage:
 * ```html
 * <pptx-export-progress-modal
 *   [open]="exportModalOpen()"
 *   [title]="exportModalTitle()"
 *   [progress]="exportProgress()"
 *   [statusMessage]="exportStatusMessage()"
 *   (cancel)="onCancelExport()"
 * />
 * ```
 */

import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';

import { clampPercent } from '../internal/shared';

@Component({
	selector: 'pptx-export-progress-modal',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		@if (open()) {
			<div
				class="pptx-ng-export-progress__backdrop"
				role="dialog"
				aria-modal="true"
				[attr.aria-label]="title()"
			>
				<div class="pptx-ng-export-progress">
					<h3 class="pptx-ng-export-progress__title">{{ title() }}</h3>

					<div class="pptx-ng-export-progress__track">
						<div class="pptx-ng-export-progress__fill" [style.width.%]="clampedProgress()"></div>
					</div>

					<div class="pptx-ng-export-progress__status">
						<span>{{ statusMessage() || 'Processing...' }}</span>
						<span class="pptx-ng-export-progress__pct">{{ clampedProgress() }}%</span>
					</div>

					<div class="pptx-ng-export-progress__actions">
						<button type="button" class="pptx-ng-export-progress__btn" (click)="cancel.emit()">
							Cancel
						</button>
					</div>
				</div>
			</div>
		}
	`,
	styles: [
		`
			.pptx-ng-export-progress__backdrop {
				position: fixed;
				inset: 0;
				z-index: 1200;
				display: flex;
				align-items: center;
				justify-content: center;
				background: rgba(0, 0, 0, 0.6);
				backdrop-filter: blur(2px);
			}

			.pptx-ng-export-progress {
				display: flex;
				flex-direction: column;
				width: min(92vw, 384px);
				padding: 1.5rem;
				border: 1px solid rgba(255, 255, 255, 0.12);
				border-radius: 0.75rem;
				background: #1e1e1e;
				color: #e5e5e5;
				box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6);
			}

			.pptx-ng-export-progress__title {
				margin: 0 0 1rem;
				font-size: 0.875rem;
				font-weight: 600;
				color: #ffffff;
			}

			.pptx-ng-export-progress__track {
				width: 100%;
				height: 0.625rem;
				margin-bottom: 0.75rem;
				overflow: hidden;
				border-radius: 9999px;
				background: rgba(255, 255, 255, 0.12);
			}

			.pptx-ng-export-progress__fill {
				height: 100%;
				border-radius: 9999px;
				background: #2563eb;
				transition: width 300ms ease-out;
			}

			.pptx-ng-export-progress__status {
				display: flex;
				align-items: center;
				justify-content: space-between;
				margin-bottom: 1rem;
				font-size: 0.75rem;
				color: rgba(255, 255, 255, 0.6);
			}

			.pptx-ng-export-progress__pct {
				font-variant-numeric: tabular-nums;
			}

			.pptx-ng-export-progress__actions {
				display: flex;
				justify-content: flex-end;
			}

			.pptx-ng-export-progress__btn {
				padding: 0.375rem 1rem;
				font-size: 0.75rem;
				color: #e5e5e5;
				border: 1px solid rgba(255, 255, 255, 0.16);
				border-radius: 0.375rem;
				background: rgba(255, 255, 255, 0.06);
				cursor: pointer;
				transition: background 150ms ease;
			}

			.pptx-ng-export-progress__btn:hover {
				background: rgba(255, 255, 255, 0.12);
			}
		`,
	],
})
export class ExportProgressModalComponent {
	/** Whether the overlay is visible. */
	readonly open = input<boolean>(false);
	/** Heading shown at the top (e.g. "Export as PDF"). */
	readonly title = input<string>('');
	/** Current progress, 0-100. */
	readonly progress = input<number>(0);
	/** Optional status line (e.g. "Rendering slide 3 of 10..."). */
	readonly statusMessage = input<string>('');

	/** Emitted when the user presses Cancel. */
	readonly cancel = output<void>();

	/** Progress clamped to the inclusive `[0, 100]` integer range for display. */
	readonly clampedProgress = computed(() => clampPercent(this.progress()));
}
