// packages/vue/src/viewer/components/FontEmbeddingPanel.vue
<script setup lang="ts">
import { scanAvailableFontFamilies } from 'pptx-viewer-shared';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import ModalDialog from './ModalDialog.vue';

/**
 * FontEmbeddingPanel: toggle font embedding on save and preview which of the
 * presentation's used fonts are available locally / already embedded. Vue port
 * of the React `FontEmbeddingPanel.tsx`. Availability is detected with the
 * browser `document.fonts` API when the dialog opens.
 */
const props = withDefaults(
	defineProps<{
		open: boolean;
		embedFontsEnabled: boolean;
		usedFontFamilies: string[];
		embeddedFonts: string[];
		/**
		 * False when the deck embeds nothing, in which case the switch is inert
		 * and says why. The viewer can keep or strip embedded font data on save,
		 * but it cannot manufacture it: a browser will not hand over the bytes of
		 * an installed system face.
		 */
		canEmbedFonts?: boolean;
		/** i18n key for the explanation shown when `canEmbedFonts` is false. */
		embedUnavailableKey?: string;
	}>(),
	{ canEmbedFonts: true, embedUnavailableKey: undefined },
);

const emit = defineEmits<{
	toggleEmbedFonts: [enabled: boolean];
	close: [];
}>();

const { t } = useI18n();

const availableFamilies = ref<Set<string>>(new Set());
const scanning = ref(false);
const scanned = ref(false);

async function scanFonts(): Promise<void> {
	scanning.value = true;
	try {
		availableFamilies.value = await scanAvailableFontFamilies(props.usedFontFamilies);
		scanned.value = true;
	} catch {
		// silently fail; families stay marked as not found
	} finally {
		scanning.value = false;
	}
}

watch(
	() => props.open,
	(open) => {
		if (open && !scanned.value) {
			void scanFonts();
		}
	},
	{ immediate: true },
);

const embeddedSet = computed(() => new Set(props.embeddedFonts));
const missingCount = computed(
	() => props.usedFontFamilies.filter((f) => !availableFamilies.value.has(f)).length,
);
</script>

<template>
	<ModalDialog :open="props.open" :title="t('pptx.fontEmbedding.title')" @close="emit('close')">
		<div class="space-y-4">
			<p class="text-xs text-muted-foreground">
				{{ t('pptx.fontEmbedding.description') }}
			</p>

			<label
				class="flex items-center gap-3"
				:class="props.canEmbedFonts ? 'cursor-pointer' : 'cursor-not-allowed opacity-60'"
			>
				<div class="relative">
					<pptx-ui-checkbox
						class="sr-only"
						:checked="props.embedFontsEnabled"
						:disabled="!props.canEmbedFonts"
						@change="emit('toggleEmbedFonts', ($event.target as HTMLInputElement).checked)"
					/>
					<div
						class="h-5 w-9 rounded-full transition-colors"
						:class="props.embedFontsEnabled ? 'bg-primary' : 'bg-muted-foreground'"
					/>
					<div
						class="absolute left-0.5 top-0.5 h-4 w-4 rounded-full bg-white transition-transform"
						:class="props.embedFontsEnabled ? 'translate-x-4' : ''"
					/>
				</div>
				<span class="text-xs text-foreground">{{ t('pptx.fontEmbedding.embedInFile') }}</span>
			</label>
			<!--
				The switch used to move and change nothing at all. It now decides
				whether save keeps the deck's embedded font data, so it has to say
				which of those two things it is doing - and admit when it can do
				neither.
			-->
			<p class="text-[11px] text-muted-foreground">
				{{
					props.canEmbedFonts
						? t('pptx.fonts.embedKeepsExisting')
						: t(props.embedUnavailableKey ?? 'pptx.fonts.embedUnavailable')
				}}
			</p>

			<div class="space-y-1">
				<h3 class="text-xs font-medium text-foreground">
					{{ t('pptx.fontEmbedding.usedFonts', { count: props.usedFontFamilies.length }) }}
				</h3>
				<div v-if="scanning" class="flex items-center justify-center gap-2 py-4">
					<span class="text-xs text-muted-foreground">{{ t('pptx.fontEmbedding.scanning') }}</span>
				</div>
				<div v-else class="max-h-[280px] space-y-1 overflow-y-auto">
					<div
						v-for="family in props.usedFontFamilies"
						:key="family"
						class="flex items-center justify-between rounded-lg bg-muted/60 px-3 py-2"
					>
						<span class="text-xs text-foreground">{{ family }}</span>
						<div class="flex items-center gap-2">
							<span
								v-if="embeddedSet.has(family)"
								class="rounded border border-green-700/40 bg-green-900/40 px-1.5 py-0.5 text-[10px] text-green-400"
							>
								{{ t('pptx.fontEmbedding.embedded') }}
							</span>
							<span v-if="availableFamilies.has(family)" class="text-[10px] text-green-400">
								{{ t('pptx.fontEmbedding.available') }}
							</span>
							<span v-else class="text-[10px] text-yellow-400">{{
								t('pptx.fontEmbedding.notFound')
							}}</span>
						</div>
					</div>
					<p
						v-if="props.usedFontFamilies.length === 0"
						class="px-3 py-2 text-xs italic text-muted-foreground"
					>
						{{ t('pptx.fontEmbedding.noCustomFonts') }}
					</p>
				</div>
			</div>

			<p v-if="missingCount > 0 && !scanning" class="text-[11px] text-yellow-400/80">
				{{ t('pptx.fontEmbedding.missingWarning', { count: missingCount }) }}
			</p>
		</div>

		<template #footer>
			<button
				type="button"
				class="rounded-lg bg-primary px-3 py-1.5 text-xs text-white transition-colors hover:bg-primary/80"
				@click="emit('close')"
			>
				{{ t('pptx.fontEmbedding.done') }}
			</button>
		</template>
	</ModalDialog>
</template>

// packages/angular/src/viewer/font-embedding-panel.component.ts
/**
 * font-embedding-panel.component.ts: Font-embedding settings dialog.
 *
 * Selector: `pptx-font-embedding-panel`
 *
 * Angular port of the React `FontEmbeddingPanel` component
 * (`packages/react/src/viewer/components/FontEmbeddingPanel.tsx`). Composes the
 * reusable {@link ModalDialogComponent} and {@link FontEmbeddingListComponent}.
 * Lets the user toggle font embedding and shows, for every font family used by
 * the deck, whether it is available in the current browser (scanned via
 * {@link scanAvailableFonts}) and whether it is already embedded. The host owns
 * `open`, `embedFontsEnabled`, and the font lists.
 */

import {
	ChangeDetectionStrategy,
	Component,
	CUSTOM_ELEMENTS_SCHEMA,
	computed,
	effect,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { scanAvailableFonts } from './font-embedding-helpers';
import { FontEmbeddingListComponent } from './font-embedding-list.component';
import { ModalDialogComponent } from './modal-dialog.component';

@Component({
	selector: 'pptx-font-embedding-panel',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [ModalDialogComponent, FontEmbeddingListComponent, TranslatePipe],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	template: `
		<pptx-modal-dialog
			[open]="open()"
			[title]="'pptx.fontEmbedding.title' | translate"
			(close)="close.emit()"
		>
			<div class="pptx-ng-fonts">
				<p class="pptx-ng-fonts-desc">
					{{ 'pptx.fontEmbedding.description' | translate }}
				</p>

				<label class="pptx-ng-fonts-toggle" [class.is-disabled]="!canEmbedFonts()">
					<pptx-ui-checkbox
						[checked]="embedFontsEnabled()"
						[disabled]="!canEmbedFonts()"
						(change)="onToggle($event)"
					></pptx-ui-checkbox>
					<span class="pptx-ng-fonts-toggle-label">{{
						'pptx.fontEmbedding.embedWhenSaving' | translate
					}}</span>
				</label>
				<!--
					The switch used to move and change nothing at all. It now decides
					whether save keeps the deck's embedded font data, so it has to say
					which of those two things it is doing - and admit when it can do
					neither.
				-->
				<p class="pptx-ng-fonts-note">{{ toggleNoteKey() | translate }}</p>

				<pptx-font-embedding-list
					[usedFontFamilies]="usedFontFamilies()"
					[availableFamilies]="availableFamilies()"
					[embeddedSet]="embeddedSet()"
					[scanning]="scanning()"
					[missingCount]="missingCount()"
				/>
			</div>

			<div footer>
				<button type="button" class="pptx-ng-fonts-done" (click)="close.emit()">
					{{ 'pptx.fontEmbedding.done' | translate }}
				</button>
			</div>
		</pptx-modal-dialog>
	`,
	styles: [
		`
			.pptx-ng-fonts {
				display: flex;
				flex-direction: column;
				gap: 1rem;
			}
			.pptx-ng-fonts-desc {
				margin: 0;
				font-size: 0.75rem;
				line-height: 1.5;
				color: var(--pptx-muted-foreground, #9ca3af);
			}
			.pptx-ng-fonts-toggle {
				display: flex;
				align-items: center;
				gap: 0.75rem;
				cursor: pointer;
			}
			.pptx-ng-fonts-toggle.is-disabled {
				cursor: not-allowed;
				opacity: 0.6;
			}
			.pptx-ng-fonts-toggle-label {
				font-size: 0.75rem;
				color: var(--pptx-foreground, #f3f4f6);
			}
			.pptx-ng-fonts-note {
				margin: -0.5rem 0 0;
				font-size: 0.6875rem;
				line-height: 1.5;
				color: var(--pptx-muted-foreground, #9ca3af);
			}
			.pptx-ng-fonts-done {
				padding: 0.375rem 0.75rem;
				font-size: 0.75rem;
				color: #ffffff;
				background: var(--pptx-primary, #6366f1);
				border: 1px solid var(--pptx-primary, #6366f1);
				border-radius: 0.5rem;
				cursor: pointer;
				transition: filter 0.15s ease;
			}
			.pptx-ng-fonts-done:hover {
				filter: brightness(1.1);
			}
		`,
	],
})
export class FontEmbeddingPanelComponent {
	/** Whether the dialog is visible. */
	readonly open = input<boolean>(false);

	/** Whether font embedding is currently enabled. */
	readonly embedFontsEnabled = input<boolean>(false);

	/** Font families referenced by the presentation. */
	readonly usedFontFamilies = input<string[]>([]);

	/** Font families already embedded in the file. */
	readonly embeddedFonts = input<string[]>([]);

	/**
	 * False when the deck embeds nothing, in which case the switch is inert and
	 * says why. The viewer can keep or strip embedded font data on save, but it
	 * cannot manufacture it: a browser will not hand over the bytes of an
	 * installed system face.
	 */
	readonly canEmbedFonts = input<boolean>(true);

	/** i18n key for the explanation shown when `canEmbedFonts` is false. */
	readonly embedUnavailableKey = input<string | undefined>(undefined);

	/** Fired when the dialog is dismissed. */
	readonly close = output<void>();

	/** Fired when the embed toggle changes; carries the new checked state. */
	readonly toggleEmbedFonts = output<boolean>();

	/** Families that resolve in the current browser (populated by the scan). */
	readonly availableFamilies = signal<Set<string>>(new Set<string>());

	/** True while the font-availability scan is running. */
	readonly scanning = signal(false);

	/** True once a scan has completed for the current open cycle. */
	readonly scanned = signal(false);

	/** Set view of {@link embeddedFonts} for fast membership checks. */
	readonly embeddedSet = computed(() => new Set(this.embeddedFonts()));

	/** Line of copy under the switch: what it does, or why it cannot. */
	readonly toggleNoteKey = computed(() =>
		this.canEmbedFonts()
			? 'pptx.fonts.embedKeepsExisting'
			: (this.embedUnavailableKey() ?? 'pptx.fonts.embedUnavailable'),
	);

	/** How many used families failed to resolve in the browser. */
	readonly missingCount = computed(() => {
		const available = this.availableFamilies();
		return this.usedFontFamilies().filter((f) => !available.has(f)).length;
	});

	constructor() {
		// Kick off a scan when the dialog opens, and reset so reopening rescans.
		effect(() => {
			if (this.open()) {
				if (!this.scanned()) {
					void this.scanFonts();
				}
			} else if (this.scanned()) {
				this.scanned.set(false);
			}
		});
	}

	onToggle(event: Event): void {
		this.toggleEmbedFonts.emit((event.target as HTMLInputElement).checked);
	}

	private async scanFonts(): Promise<void> {
		this.scanning.set(true);
		try {
			this.availableFamilies.set(await scanAvailableFonts(this.usedFontFamilies()));
			this.scanned.set(true);
		} finally {
			this.scanning.set(false);
		}
	}
}
