// packages/vue/src/viewer/components/OleSheetGridEditor.vue
<script setup lang="ts">
/**
 * Editable spreadsheet grid for `OleEditorDialog`'s "sheet" content tab.
 * Vue port of React's `OleSheetGridEditor` (`OleEditorDialogTabs.tsx`).
 */
import type { OleSheetGrid } from 'pptx-viewer-core';
import { useI18n } from 'vue-i18n';

const props = defineProps<{
	grid: OleSheetGrid | undefined;
}>();

const emit = defineEmits<{
	(e: 'cellEdit', row: number, col: number, value: string): void;
}>();

const { t } = useI18n();

function onCellBlur(rowIndex: number, colIndex: number, originalValue: string, event: Event): void {
	const value = (event.target as HTMLInputElement).value;
	if (value !== originalValue) {
		emit('cellEdit', rowIndex, colIndex, value);
	}
}
</script>

<template>
	<p v-if="!props.grid || props.grid.rows.length === 0" class="text-xs text-muted-foreground">
		{{ t('pptx.ole.editDialog.emptySheet') }}
	</p>
	<div v-else class="max-h-[50vh] overflow-auto rounded border border-border">
		<table class="w-full border-collapse text-xs">
			<tbody>
				<tr v-for="(row, rowIndex) in props.grid.rows" :key="rowIndex">
					<td
						v-for="(cell, colIndex) in row.cells"
						:key="colIndex"
						class="border border-border p-0"
					>
						<input
							type="text"
							:value="cell.value"
							:aria-label="t('pptx.ole.editDialog.cellEditLabel')"
							class="w-full bg-transparent px-1.5 py-1 focus:bg-accent/40 focus:outline-none"
							@blur="onCellBlur(rowIndex, colIndex, cell.value, $event)"
						/>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</template>

// packages/angular/src/viewer/ole-sheet-grid-editor.component.ts
/**
 * ole-sheet-grid-editor.component.ts: editable spreadsheet grid for the OLE
 * "Edit content" dialog's sheet tab.
 *
 * Selector: `pptx-ole-sheet-grid-editor`
 *
 * Extracted from `ole-editor-dialog.component.ts` to respect the 300-LOC
 * file-size limit, matching the split React took in `OleEditorDialogTabs.tsx`
 * (`OleSheetGridEditor`). One `<input>` per cell; a value is committed on
 * blur only when it actually changed, so a click-through without editing
 * never triggers a write.
 */
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { OleSheetGrid } from 'pptx-viewer-core';

/** One committed cell edit: `{row, col}` are the grid's own 0-based indices. */
export interface OleSheetCellEdit {
	row: number;
	col: number;
	value: string;
}

@Component({
	selector: 'pptx-ole-sheet-grid-editor',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (!grid() || grid()!.rows.length === 0) {
			<p class="pptx-ole-edit-empty">{{ 'pptx.ole.editDialog.emptySheet' | translate }}</p>
		} @else {
			<div class="pptx-ole-edit-grid-wrap">
				<table class="pptx-ole-edit-grid">
					<tbody>
						@for (row of grid()!.rows; track $index; let rowIndex = $index) {
							<tr>
								@for (cell of row.cells; track $index; let colIndex = $index) {
									<td>
										<input
											type="text"
											[attr.aria-label]="'pptx.ole.editDialog.cellEditLabel' | translate"
											[value]="cell.value"
											(blur)="onBlur(rowIndex, colIndex, cell.value, $event)"
										/>
									</td>
								}
							</tr>
						}
					</tbody>
				</table>
			</div>
		}
	`,
	styles: [
		`
			.pptx-ole-edit-empty {
				margin: 0;
				font-size: 11px;
				color: var(--pptx-muted-foreground, #9ca3af);
			}
			.pptx-ole-edit-grid-wrap {
				max-height: 50vh;
				overflow: auto;
				border: 1px solid var(--pptx-border, #374151);
				border-radius: 4px;
			}
			.pptx-ole-edit-grid {
				width: 100%;
				border-collapse: collapse;
				font-size: 11px;
			}
			.pptx-ole-edit-grid td {
				padding: 0;
				border: 1px solid var(--pptx-border, #374151);
			}
			.pptx-ole-edit-grid input {
				width: 100%;
				box-sizing: border-box;
				padding: 4px 6px;
				border: none;
				background: transparent;
				color: inherit;
				font: inherit;
			}
			.pptx-ole-edit-grid input:focus {
				outline: none;
				background: var(--pptx-accent, rgba(99, 102, 241, 0.15));
			}
		`,
	],
})
export class OleSheetGridEditorComponent {
	/** The grid to render; `undefined` while still loading. */
	readonly grid = input<OleSheetGrid | undefined>(undefined);

	/** Fired when a cell's committed value differs from what was loaded. */
	readonly cellEdit = output<OleSheetCellEdit>();

	protected onBlur(row: number, col: number, original: string, event: Event): void {
		const value = (event.target as HTMLInputElement).value;
		if (value !== original) {
			this.cellEdit.emit({ row, col, value });
		}
	}
}
