// packages/vue/src/viewer/components/PresentationSubtitleBar.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';

/**
 * PresentationSubtitleBar — live subtitle/caption bar shown during presentation
 * mode. Uses the Web Speech API (`SpeechRecognition` / `webkitSpeechRecognition`)
 * when available and falls back to a "not supported" message otherwise. Vue port
 * of the React `PresentationSubtitleBar`.
 *
 * Recognition runs only while `visible` is true; toggling `visible` off stops
 * the recogniser and clears the caption.
 */

interface SpeechRecognitionAlternativeLite {
	transcript: string;
	confidence: number;
}

interface SpeechRecognitionResultLite {
	readonly isFinal: boolean;
	readonly length: number;
	item(index: number): SpeechRecognitionAlternativeLite;
	[index: number]: SpeechRecognitionAlternativeLite;
}

interface SpeechRecognitionResultListLite {
	readonly length: number;
	item(index: number): SpeechRecognitionResultLite;
	[index: number]: SpeechRecognitionResultLite;
}

interface SpeechRecognitionEventLite extends Event {
	readonly resultIndex: number;
	readonly results: SpeechRecognitionResultListLite;
}

interface SpeechRecognitionLite extends EventTarget {
	continuous: boolean;
	interimResults: boolean;
	lang: string;
	onresult: ((event: SpeechRecognitionEventLite) => void) | null;
	onerror: ((event: Event) => void) | null;
	onend: (() => void) | null;
	start(): void;
	stop(): void;
}

type SpeechRecognitionCtor = new () => SpeechRecognitionLite;

interface WindowWithSpeechRecognition {
	SpeechRecognition?: SpeechRecognitionCtor;
	webkitSpeechRecognition?: SpeechRecognitionCtor;
}

const props = defineProps<{
	visible: boolean;
}>();

const captionText = ref('');
const supportState = ref<'unknown' | 'supported' | 'unsupported'>('unknown');

let recognition: SpeechRecognitionLite | null = null;
let shouldRun = false;

function stopRecognition(): void {
	shouldRun = false;
	recognition?.stop();
	recognition = null;
}

function startRecognition(): void {
	if (typeof window === 'undefined') {
		supportState.value = 'unsupported';
		return;
	}
	shouldRun = true;
	const speechWindow = window as unknown as WindowWithSpeechRecognition;
	const RecognitionCtor = speechWindow.SpeechRecognition ?? speechWindow.webkitSpeechRecognition;
	if (!RecognitionCtor) {
		supportState.value = 'unsupported';
		return;
	}
	supportState.value = 'supported';

	const recog = new RecognitionCtor();
	recog.continuous = true;
	recog.interimResults = true;
	recog.lang = navigator.language || 'en-US';

	recog.onresult = (event: SpeechRecognitionEventLite): void => {
		let finalText = '';
		let interimText = '';
		for (let index = event.resultIndex; index < event.results.length; index += 1) {
			const result = event.results[index];
			const fragment = result?.[0]?.transcript ?? '';
			if (result?.isFinal) {
				finalText += fragment;
			} else {
				interimText += fragment;
			}
		}
		const merged = `${finalText} ${interimText}`.trim();
		if (merged.length > 0) {
			captionText.value = merged;
		}
	};

	recog.onerror = (): void => {
		// Keep the bar active; `onend` attempts a restart while visible.
	};
	recog.onend = (): void => {
		if (!shouldRun) {
			return;
		}
		try {
			recog.start();
		} catch {
			// Browser may throttle rapid restarts; next visibility toggle retries.
		}
	};

	recognition = recog;
	try {
		recog.start();
	} catch {
		supportState.value = 'unsupported';
	}
}

watch(
	() => props.visible,
	(visible) => {
		if (!visible) {
			stopRecognition();
			captionText.value = '';
			return;
		}
		startRecognition();
	},
	{ immediate: true },
);

onBeforeUnmount(stopRecognition);

const renderedText = computed<string>(() => {
	if (supportState.value === 'unsupported') {
		return 'Live captions are not supported in this browser.';
	}
	return captionText.value.length > 0 ? captionText.value : 'Listening…';
});
</script>

<template>
	<div v-if="visible" class="pptx-vue-subtitle-bar">
		<div class="pptx-vue-subtitle-inner">
			<p class="pptx-vue-subtitle-text">{{ renderedText }}</p>
		</div>
	</div>
</template>

<style scoped>
.pptx-vue-subtitle-bar {
	position: absolute;
	bottom: 56px;
	left: 50%;
	transform: translateX(-50%);
	z-index: 70;
	max-width: 80%;
	min-width: 300px;
}

.pptx-vue-subtitle-inner {
	padding: 12px 24px;
	border-radius: 8px;
	background: rgba(0, 0, 0, 0.75);
	backdrop-filter: blur(4px);
	border: 1px solid rgba(255, 255, 255, 0.1);
}

.pptx-vue-subtitle-text {
	margin: 0;
	text-align: center;
	font-size: 15px;
	font-style: italic;
	color: rgba(255, 255, 255, 0.7);
}
</style>

// packages/angular/src/viewer/presentation-subtitle-bar.component.ts
/**
 * presentation-subtitle-bar.component.ts: Live caption/subtitle bar for
 * presentation mode, driven by the Web Speech API when available.
 *
 * Ported from React:
 *   packages/react/src/viewer/components/PresentationSubtitleBar.tsx
 *
 * Selector: `pptx-presentation-subtitle-bar`
 *
 * Inputs:
 *   - `visible` (required): show/hide the bar and start/stop recognition.
 *
 * When `visible` is false the component renders nothing and stops the
 * recognition session. When the Web Speech API is unavailable the bar still
 * renders but shows a "not supported" message.
 *
 * All speech-API access is isolated behind `_createRecognition()` so the rest
 * of the component (and tests) can stay pure. Caption text accumulation logic
 * lives in {@link mergeCaptionResults} (pure helper, unit-tested separately).
 */

import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	OnChanges,
	SimpleChanges,
	inject,
	input,
	signal,
} from '@angular/core';

import {
	captionDisplayText,
	getSpeechRecognitionCtor,
	mergeCaptionResults,
} from './presentation-subtitle-helpers';
import type { SpeechRecognitionLite, SpeechSupportState } from './presentation-subtitle-helpers';

@Component({
	selector: 'pptx-presentation-subtitle-bar',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	styles: `
		:host {
			display: block;
			position: absolute;
			bottom: 3.5rem; /* 56 px: clear the slide-counter / nav row */
			left: 50%;
			transform: translateX(-50%);
			z-index: 70;
			max-width: 80%;
			min-width: 300px;
			pointer-events: none;
		}

		.pptx-ng-subtitle-inner {
			padding: 0.75rem 1.5rem;
			border-radius: 0.5rem;
			background: rgba(0, 0, 0, 0.75);
			border: 1px solid rgba(255, 255, 255, 0.1);
			/* Very light blur, safe to omit if the browser doesn't support it. */
			backdrop-filter: blur(4px);
		}

		.pptx-ng-subtitle-text {
			display: block;
			text-align: center;
			font-size: 0.9375rem; /* 15 px */
			line-height: 1.5;
			color: rgba(255, 255, 255, 0.7);
			font-style: italic;
			font-family: system-ui, sans-serif;
			white-space: pre-wrap;
			word-break: break-word;
		}
	`,
	template: `
		@if (visible()) {
			<div class="pptx-ng-subtitle-inner">
				<span class="pptx-ng-subtitle-text">{{ displayText() }}</span>
			</div>
		}
	`,
})
export class PresentationSubtitleBarComponent implements OnChanges {
	// ------------------------------------------------------------------
	// Inputs
	// ------------------------------------------------------------------

	/** Show the subtitle bar and start speech recognition when true. */
	readonly visible = input.required<boolean>();

	// ------------------------------------------------------------------
	// Internal signals
	// ------------------------------------------------------------------

	private readonly _captionText = signal<string>('');
	private readonly _supportState = signal<SpeechSupportState>('unknown');

	/** The text string rendered in the caption bar. */
	protected readonly displayText = signal<string>('Listening…');

	// ------------------------------------------------------------------
	// Recognition lifecycle bookkeeping
	// ------------------------------------------------------------------

	/**
	 * Whether the recognition session should remain running.
	 * Toggled on `visible` changes; checked in `onend` to decide whether
	 * to restart.
	 */
	private _shouldRun = false;

	/** Active recognition instance, or null when stopped. */
	private _recognition: SpeechRecognitionLite | null = null;

	private readonly _destroyRef = inject(DestroyRef);

	constructor() {
		this._destroyRef.onDestroy(() => {
			this._stopRecognition();
		});
	}

	// ------------------------------------------------------------------
	// Lifecycle
	// ------------------------------------------------------------------

	ngOnChanges(changes: SimpleChanges): void {
		if (!('visible' in changes)) {
			return;
		}
		if (this.visible()) {
			this._startRecognition();
		} else {
			this._stopRecognition();
		}
	}

	// ------------------------------------------------------------------
	// Speech recognition management
	// ------------------------------------------------------------------

	private _startRecognition(): void {
		this._shouldRun = true;
		this._captionText.set('');
		this._updateDisplayText();

		const Ctor = this._getSpeechCtor();
		if (!Ctor) {
			this._supportState.set('unsupported');
			this._updateDisplayText();
			return;
		}
		this._supportState.set('supported');

		const recognition = new Ctor();
		recognition.continuous = true;
		recognition.interimResults = true;
		recognition.lang = typeof navigator !== 'undefined' ? navigator.language || 'en-US' : 'en-US';

		recognition.onresult = (event) => {
			const merged = mergeCaptionResults(event.resultIndex, event.results);
			if (merged.length > 0) {
				this._captionText.set(merged);
				this._updateDisplayText();
			}
		};

		recognition.onerror = () => {
			// Keep the bar alive; `onend` will attempt restart if still visible.
		};

		recognition.onend = () => {
			if (!this._shouldRun) {
				return;
			}
			try {
				recognition.start();
			} catch {
				// Browser may throttle rapid restarts; the next visibility toggle will retry.
			}
		};

		this._recognition = recognition;
		try {
			recognition.start();
		} catch {
			this._supportState.set('unsupported');
			this._updateDisplayText();
		}
	}

	private _stopRecognition(): void {
		this._shouldRun = false;
		if (this._recognition) {
			this._recognition.stop();
			this._recognition = null;
		}
		this._captionText.set('');
		this._updateDisplayText();
	}

	/**
	 * Thin wrapper around {@link getSpeechRecognitionCtor} so tests can spy on
	 * or override this method without patching `globalThis`.
	 */
	protected _getSpeechCtor() {
		return getSpeechRecognitionCtor();
	}

	// ------------------------------------------------------------------
	// Display text derivation
	// ------------------------------------------------------------------

	private _updateDisplayText(): void {
		const text = captionDisplayText(
			this._supportState(),
			this._captionText(),
			'Subtitles not supported in this browser.',
			'Listening…',
		);
		this.displayText.set(text);
	}
}
