// packages/svelte/src/viewer/components/SettingsDialog.svelte
<script lang="ts">
	import { VIEWER_PREFERENCE_TOGGLES, VIEWER_SHORTCUT_REFERENCE, updateViewerPreference } from 'pptx-viewer-shared';
	import type { ViewerPreferences } from 'pptx-viewer-shared';
	import { useTranslator } from '../../i18n/context';

	const { preferences, onclose, onchange }: { preferences: ViewerPreferences; onclose: () => void; onchange: (next: ViewerPreferences) => void } = $props();
	const t = useTranslator();
	// eslint-disable-next-line prefer-const
	let tab = $state<'general' | 'shortcuts'>('general');
</script>
<div class="backdrop"><button class="scrim" type="button" aria-label={t('pptx.settings.closeSettings')} onclick={onclose}></button>
	<!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
	<section role="dialog" tabindex="-1" aria-modal="true" aria-labelledby="settings-title"><header><div><b>⚙</b><h2 id="settings-title">{t('pptx.settings.title')}</h2></div><button type="button" aria-label={t('pptx.settings.close')} onclick={onclose}>×</button></header>
		<nav aria-label={t('pptx.settings.title')}><button class:active={tab === 'general'} onclick={() => (tab = 'general')}>{t('pptx.settings.general')}</button><button class:active={tab === 'shortcuts'} onclick={() => (tab = 'shortcuts')}>{t('pptx.settings.keyboardShortcuts')}</button></nav>
		<div class="body">{#if tab === 'general'}{#each VIEWER_PREFERENCE_TOGGLES as item}<label><span>{t(item.labelKey)}</span><button class:enabled={preferences[item.key]} role="switch" aria-checked={preferences[item.key]} aria-label={t(item.labelKey)} onclick={() => onchange(updateViewerPreference(preferences, item.key, !preferences[item.key]))}><i></i></button></label>{/each}{:else}{#each VIEWER_SHORTCUT_REFERENCE as shortcut, index}<p class:stripe={index % 2 === 0}><span>{t(shortcut.actionKey)}</span><kbd>{shortcut.shortcut}</kbd></p>{/each}{/if}</div>
	</section>
</div>
<style>
	.backdrop{position:fixed;inset:0;z-index:1200;display:grid;place-items:center;background:#0009}.scrim{position:absolute;inset:0;border:0;background:transparent}section{position:relative;width:min(512px,calc(100vw - 32px));overflow:hidden;border:1px solid var(--pptx-border,#3f3f52);border-radius:13px;background:var(--pptx-card,#1e1e2e);box-shadow:0 24px 80px #0009}header,header div{display:flex;align-items:center}header{justify-content:space-between;padding:14px 18px;border-bottom:1px solid var(--pptx-border,#3f3f52)}header div{gap:9px}h2{margin:0;font-size:14px}header b{color:var(--pptx-primary,#c43b32)}header>button{border:0;background:transparent;color:inherit;font-size:20px}nav{display:flex;padding:0 18px;border-bottom:1px solid var(--pptx-border,#3f3f52)}nav button{position:relative;border:0;padding:10px;background:transparent;color:var(--pptx-muted-foreground,#94a3b8);font-size:12px}.active{color:var(--pptx-primary,#c43b32)!important}.active:after{position:absolute;right:0;bottom:0;left:0;height:2px;background:currentColor;content:''}.body{max-height:60vh;overflow:auto;padding:14px 18px}.body label,.body p{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0;padding:9px 11px;border-radius:6px;font-size:12px}.body label button{position:relative;width:36px;height:20px;border:0;border-radius:12px;background:#687080}.body label button.enabled{background:var(--pptx-primary,#c43b32)}.body label i{position:absolute;top:3px;left:3px;width:14px;height:14px;border-radius:50%;background:#fff;transition:transform .15s}.body label button.enabled i{transform:translateX(16px)}.stripe{background:var(--pptx-muted,#2a2a3d)}kbd{color:var(--pptx-muted-foreground,#94a3b8);font:11px ui-monospace,monospace;white-space:nowrap}@media(max-width:600px){section{position:fixed;inset:auto 0 0;width:100%;max-height:88dvh;border-radius:16px 16px 0 0}}
</style>

// packages/angular/src/viewer/settings-dialog.component.ts
import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import {
	SETTING_TOGGLES,
	SHORTCUT_REFERENCE_ITEMS,
	updateViewerPreference,
} from '../internal/shared';
import type { ViewerSettings } from '../internal/shared';
import { ModalDialogComponent } from './modal-dialog.component';

export type { ViewerSettings } from '../internal/shared';

export function toggleViewerSetting(
	settings: ViewerSettings,
	key: keyof ViewerSettings,
): ViewerSettings {
	return updateViewerPreference(settings, key, !settings[key]);
}

@Component({
	selector: 'pptx-settings-dialog',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [ModalDialogComponent, TranslatePipe],
	template: `
		<pptx-modal-dialog
			[open]="open()"
			[title]="'pptx.settings.title' | translate"
			(close)="close.emit()"
		>
			<div class="pptx-ng-settings">
				<div class="pptx-ng-settings-tabs" role="tablist">
					<button
						type="button"
						role="tab"
						[attr.aria-selected]="activeTab() === 'general'"
						[class.is-active]="activeTab() === 'general'"
						(click)="activeTab.set('general')"
					>
						{{ 'pptx.settings.general' | translate }}
					</button>
					<button
						type="button"
						role="tab"
						[attr.aria-selected]="activeTab() === 'shortcuts'"
						[class.is-active]="activeTab() === 'shortcuts'"
						(click)="activeTab.set('shortcuts')"
					>
						{{ 'pptx.settings.keyboardShortcuts' | translate }}
					</button>
				</div>

				@if (activeTab() === 'general') {
					<div class="pptx-ng-settings-list">
						@for (spec of specs; track spec.key) {
							<div class="pptx-ng-settings-row">
								<span>{{ spec.labelKey | translate }}</span>
								<button
									type="button"
									role="switch"
									[attr.aria-checked]="settings()[spec.key]"
									[attr.aria-label]="spec.labelKey | translate"
									[class.is-on]="settings()[spec.key]"
									(click)="toggle(spec.key)"
								>
									<span></span>
								</button>
							</div>
						}
					</div>
				} @else {
					<div class="pptx-ng-settings-list">
						@for (item of shortcuts; track item.actionKey; let even = $even) {
							<div class="pptx-ng-shortcut-row" [class.is-alt]="even">
								<span>{{ item.actionKey | translate }}</span>
								<kbd>{{ item.shortcut }}</kbd>
							</div>
						}
					</div>
				}
			</div>
			<button footer type="button" class="pptx-ng-settings-done" (click)="close.emit()">
				{{ 'pptx.settings.done' | translate }}
			</button>
		</pptx-modal-dialog>
	`,
	styles: [
		`
			.pptx-ng-settings {
				min-width: 320px;
			}
			.pptx-ng-settings-tabs {
				display: flex;
				gap: 4px;
				border-bottom: 1px solid var(--pptx-border);
			}
			.pptx-ng-settings-tabs button {
				padding: 7px 10px;
				border: 0;
				border-bottom: 2px solid transparent;
				background: transparent;
				color: var(--pptx-muted-foreground);
				font-size: 12px;
				cursor: pointer;
			}
			.pptx-ng-settings-tabs button.is-active {
				border-bottom-color: var(--pptx-primary);
				color: var(--pptx-primary);
			}
			.pptx-ng-settings-list {
				max-height: 56vh;
				overflow-y: auto;
				padding-top: 8px;
			}
			.pptx-ng-settings-row,
			.pptx-ng-shortcut-row {
				display: flex;
				align-items: center;
				justify-content: space-between;
				gap: 12px;
				padding: 9px 10px;
				font-size: 13px;
			}
			.pptx-ng-settings-row button {
				position: relative;
				width: 36px;
				height: 20px;
				padding: 0;
				border: 0;
				border-radius: 999px;
				background: color-mix(in srgb, var(--pptx-muted-foreground) 30%, transparent);
				cursor: pointer;
			}
			.pptx-ng-settings-row button span {
				position: absolute;
				top: 3px;
				left: 3px;
				width: 14px;
				height: 14px;
				border-radius: 50%;
				background: white;
				transition: transform 120ms ease;
			}
			.pptx-ng-settings-row button.is-on {
				background: var(--pptx-primary);
			}
			.pptx-ng-settings-row button.is-on span {
				transform: translateX(16px);
			}
			.pptx-ng-shortcut-row.is-alt {
				background: var(--pptx-muted);
			}
			.pptx-ng-shortcut-row kbd {
				color: var(--pptx-muted-foreground);
				font:
					11px ui-monospace,
					monospace;
				white-space: nowrap;
			}
			.pptx-ng-settings-done {
				border: 0;
				border-radius: 4px;
				padding: 7px 14px;
				background: var(--pptx-primary);
				color: white;
				cursor: pointer;
			}
		`,
	],
})
export class SettingsDialogComponent {
	readonly open = input(false);
	readonly settings = input.required<ViewerSettings>();
	readonly settingsChange = output<ViewerSettings>();
	readonly close = output<void>();
	protected readonly activeTab = signal<'general' | 'shortcuts'>('general');
	protected readonly specs = SETTING_TOGGLES;
	protected readonly shortcuts = SHORTCUT_REFERENCE_ITEMS;

	protected toggle(key: keyof ViewerSettings): void {
		this.settingsChange.emit(toggleViewerSetting(this.settings(), key));
	}
}
