// src/viewer/components/DigitalSignaturesDialog.tsx
import React from "react";
import {
  LuShieldCheck,
  LuShieldAlert,
  LuX,
  LuInfo,
  LuSignature,
} from "react-icons/lu";
import { useTranslation } from "react-i18next";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DigitalSignaturesDialogProps {
  isOpen: boolean;
  onClose: () => void;
  hasSignatures: boolean;
  signatureCount: number;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function DigitalSignaturesDialog({
  isOpen,
  onClose,
  hasSignatures,
  signatureCount,
}: DigitalSignaturesDialogProps): React.ReactElement | null {
  const { t } = useTranslation();

  if (!isOpen) return null;

  return (
    <>
      {/* Backdrop */}
      <button
        type="button"
        className="fixed inset-0 z-50 bg-black/60"
        aria-label={t("common.close")}
        onClick={onClose}
      />
      {/* Dialog */}
      <div className="fixed inset-0 z-50 flex items-center justify-center pointer-events-none">
        <div className="pointer-events-auto w-[420px] rounded-xl border border-border bg-popover backdrop-blur-xl shadow-2xl">
          {/* Header */}
          <div className="flex items-center justify-between px-5 py-4 border-b border-border/60">
            <div className="flex items-center gap-2">
              {hasSignatures ? (
                <LuShieldCheck className="w-5 h-5 text-green-400" />
              ) : (
                <LuShieldAlert className="w-5 h-5 text-amber-400" />
              )}
              <h2 className="text-sm font-semibold text-foreground">
                {t("pptx.digitalSignatures.title")}
              </h2>
            </div>
            <button
              type="button"
              onClick={onClose}
              className="p-1 rounded hover:bg-accent transition-colors"
              aria-label={t("common.close")}
            >
              <LuX className="w-4 h-4 text-muted-foreground" />
            </button>
          </div>

          {/* Body */}
          <div className="px-5 py-6 space-y-4">
            {hasSignatures ? (
              <>
                {/* Signed status */}
                <div className="flex items-start gap-3 rounded-lg bg-green-900/20 border border-green-700/30 px-4 py-3">
                  <LuSignature className="w-5 h-5 text-green-400 shrink-0 mt-0.5" />
                  <div className="space-y-1">
                    <p className="text-xs text-green-200">
                      {t("pptx.digitalSignatures.signed")}
                    </p>
                    <p className="text-[11px] text-green-300/70">
                      {t("pptx.digitalSignatures.signatureCount", {
                        count: signatureCount,
                      })}
                    </p>
                  </div>
                </div>

                {/* Edit warning */}
                <div className="flex items-start gap-3 rounded-lg bg-amber-900/20 border border-amber-700/30 px-4 py-3">
                  <LuInfo className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
                  <p className="text-xs text-amber-200">
                    {t("pptx.digitalSignatures.editWarning")}
                  </p>
                </div>
              </>
            ) : (
              <>
                {/* No signatures */}
                <div className="flex items-start gap-3 rounded-lg bg-muted/30 border border-border/40 px-4 py-3">
                  <LuInfo className="w-5 h-5 text-muted-foreground shrink-0 mt-0.5" />
                  <p className="text-xs text-muted-foreground">
                    {t("pptx.digitalSignatures.noSignatures")}
                  </p>
                </div>
              </>
            )}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-end px-5 py-3 border-t border-border/60">
            <button
              type="button"
              onClick={onClose}
              className="px-3 py-1.5 text-xs rounded-lg bg-accent text-foreground hover:bg-accent/80 transition-colors"
            >
              {t("common.close")}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

// packages/svelte/src/viewer/components/ribbon/file/DigitalSignaturesDialog.svelte
<script lang="ts">
	import { useTranslator } from '../../../../i18n/context';

	const { hasSignatures, signatureCount, onclose }: { hasSignatures: boolean; signatureCount: number; onclose: () => void } = $props();
	const t = useTranslator();
</script>

<div class="backdrop">
	<button class="scrim" type="button" aria-label={t('pptx.common.close')} onclick={onclose}></button>
	<div class="panel" role="dialog" aria-modal="true" aria-labelledby="pptx-svelte-signatures-title">
		<header><div><span class:signed={hasSignatures}>{hasSignatures ? '✓' : '!'}</span><h2 id="pptx-svelte-signatures-title">{t('pptx.digitalSignatures.title')}</h2></div><button type="button" aria-label={t('pptx.common.close')} onclick={onclose}>×</button></header>
		<div class="body">
			{#if hasSignatures}
				<div class="notice signed"><b>✓</b><p>{t('pptx.digitalSignatures.signed')}<small>{t('pptx.digitalSignatures.signatureCount', { count: signatureCount })}</small></p></div>
				<div class="notice warning"><b>i</b><p>{t('pptx.digitalSignatures.editWarning')}</p></div>
			{:else}
				<div class="notice"><b>i</b><p>{t('pptx.digitalSignatures.noSignatures')}</p></div>
			{/if}
		</div>
		<footer><button type="button" onclick={onclose}>{t('pptx.common.close')}</button></footer>
	</div>
</div>

<style>
	.backdrop{position:fixed;inset:0;z-index:90;display:grid;place-items:center;background:#0009}.scrim{position:absolute;inset:0;width:100%;height:100%;border:0;background:transparent}.panel{position:relative;width:min(420px,calc(100vw - 32px));border:1px solid var(--pptx-border,#3f3f52);border-radius:12px;background:var(--pptx-card,#1e1e2e);color:var(--pptx-card-foreground,#e2e8f0);box-shadow:0 24px 80px #0008}header,footer{display:flex;align-items:center;justify-content:space-between;padding:14px 18px;border-bottom:1px solid var(--pptx-border,#3f3f52)}header div{display:flex;align-items:center;gap:9px}header span{display:grid;width:24px;height:24px;place-items:center;border-radius:50%;background:#92400e55;color:#fbbf24;font-weight:700}header span.signed{background:#16653455;color:#4ade80}h2,p{margin:0}h2{font-size:14px}.body{display:grid;gap:12px;padding:20px}.notice{display:flex;align-items:flex-start;gap:11px;padding:12px;border:1px solid var(--pptx-border,#3f3f52);border-radius:9px;background:var(--pptx-muted,#2a2a3d);font-size:12px}.notice.signed{border-color:#15803d66;background:#14532d33;color:#bbf7d0}.notice.warning{border-color:#b4530966;background:#78350f33;color:#fde68a}.notice b{display:grid;width:20px;height:20px;flex:none;place-items:center;border-radius:50%;border:1px solid currentColor}.notice small{display:block;margin-top:5px;opacity:.75}button{border:1px solid var(--pptx-border,#3f3f52);border-radius:6px;padding:6px 10px;background:var(--pptx-muted,#2a2a3d);color:inherit}footer{justify-content:flex-end;border-top:1px solid var(--pptx-border,#3f3f52);border-bottom:0}@media(max-width:600px){.panel{position:fixed;inset:auto 0 0;width:100%;border-radius:16px 16px 0 0}}
</style>
