// packages/react/src/viewer/components/FontEmbeddingPanel.tsx
import { scanAvailableFontFamilies } from 'pptx-viewer-shared';
import React, { useState, useCallback, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { LuType, LuX, LuCheck, LuLoader } from 'react-icons/lu';

import { WebCheckbox } from './WebControls';
import { DialogFooter } from './DialogFooter';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FontEmbeddingPanelProps {
	isOpen: boolean;
	embedFontsEnabled: boolean;
	usedFontFamilies: string[];
	embeddedFonts: string[];
	/**
	 * False when the deck embeds nothing, in which case the switch is inert and
	 * says why. The viewer can keep or strip embedded font data on save, but it
	 * cannot manufacture it: a browser will not hand over the bytes of an
	 * installed system face.
	 */
	canEmbedFonts?: boolean;
	/** i18n key for the explanation shown when `canEmbedFonts` is false. */
	embedUnavailableKey?: string;
	onClose: () => void;
	onToggleEmbedFonts: (enabled: boolean) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function FontEmbeddingPanel({
	isOpen,
	embedFontsEnabled,
	usedFontFamilies,
	embeddedFonts,
	canEmbedFonts = true,
	embedUnavailableKey,
	onClose,
	onToggleEmbedFonts,
}: FontEmbeddingPanelProps): React.ReactElement | null {
	const { t } = useTranslation();
	const [availableFamilies, setAvailableFamilies] = useState<Set<string>>(new Set());
	const [scanning, setScanning] = useState(false);
	const [scanned, setScanned] = useState(false);

	const scanFonts = useCallback(async () => {
		setScanning(true);
		try {
			setAvailableFamilies(await scanAvailableFontFamilies(usedFontFamilies));
			setScanned(true);
		} catch {
			// silently fail
		} finally {
			setScanning(false);
		}
	}, [usedFontFamilies]);

	useEffect(() => {
		if (isOpen && !scanned) {
			void scanFonts();
		}
	}, [isOpen, scanned, scanFonts]);

	if (!isOpen) {
		return null;
	}

	const missingFamilies = usedFontFamilies.filter((f) => !availableFamilies.has(f));
	const embeddedSet = new Set(embeddedFonts);

	return (
		<>
			{/* Backdrop */}
			<button
				type='button'
				style={{ zIndex: 1200 }}
				className='fixed inset-0 bg-black/60'
				aria-label={t('pptx.common.close')}
				onClick={onClose}
			/>
			{/* Dialog */}
			<div
				style={{ zIndex: 1201 }}
				className='fixed inset-0 flex items-center justify-center pointer-events-none'
			>
				<div className='pointer-events-auto w-[460px] max-h-[80vh] rounded-xl border border-border bg-popover backdrop-blur-xl shadow-2xl flex flex-col max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:w-full max-md:max-w-none max-md:max-h-[88dvh] max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'>
					{/* Header */}
					<div className='flex items-center justify-between px-5 py-4 border-b border-border/60 shrink-0'>
						<div className='flex items-center gap-2'>
							<LuType className='w-5 h-5 text-primary' />
							<h2 className='text-sm font-semibold text-foreground'>
								{t('pptx.fonts.embedFonts')}
							</h2>
						</div>
						<button
							type='button'
							onClick={onClose}
							className='p-1 rounded hover:bg-accent transition-colors'
							aria-label={t('pptx.common.close')}
						>
							<LuX className='w-4 h-4 text-muted-foreground' />
						</button>
					</div>

					{/* Body */}
					<div className='px-5 py-4 space-y-4 overflow-y-auto flex-1'>
						<p className='text-xs text-muted-foreground'>{t('pptx.fonts.embedDescription')}</p>

						{/* Toggle */}
						<label
							className={`flex items-center gap-3 ${
								canEmbedFonts ? 'cursor-pointer' : 'cursor-not-allowed opacity-60'
							}`}
						>
							<WebCheckbox
								checked={embedFontsEnabled}
								disabled={!canEmbedFonts}
								onChange={(e) => onToggleEmbedFonts(e.target.checked)}
							/>
							<span className='text-xs text-foreground'>{t('pptx.fonts.enableEmbedding')}</span>
						</label>
						{/*
						 * The switch used to move and change nothing at all. It now decides
						 * whether save keeps the deck's embedded font data, so it has to
						 * say which of those two things it is doing - and admit when it can
						 * do neither.
						 */}
						<p className='text-[11px] text-muted-foreground'>
							{canEmbedFonts
								? t('pptx.fonts.embedKeepsExisting')
								: t(embedUnavailableKey ?? 'pptx.fonts.embedUnavailable')}
						</p>

						{/* Font list */}
						<div className='space-y-1'>
							<h3 className='text-xs font-medium text-foreground'>
								{t('pptx.fonts.usedFonts')} ({usedFontFamilies.length})
							</h3>
							{scanning ? (
								<div className='flex items-center gap-2 py-4 justify-center'>
									<LuLoader className='w-4 h-4 text-muted-foreground animate-spin' />
									<span className='text-xs text-muted-foreground'>{t('pptx.fonts.scanning')}</span>
								</div>
							) : (
								<div className='space-y-1 max-h-[280px] overflow-y-auto'>
									{usedFontFamilies.map((family) => {
										const found = availableFamilies.has(family);
										const embedded = embeddedSet.has(family);
										return (
											<div
												key={family}
												className='flex items-center justify-between px-3 py-2 rounded-lg bg-muted/60'
											>
												<span className='text-xs text-foreground'>{family}</span>
												<div className='flex items-center gap-2'>
													{embedded && (
														<span className='text-[10px] px-1.5 py-0.5 rounded bg-green-900/40 text-green-400 border border-green-700/40'>
															{t('pptx.fonts.embedded')}
														</span>
													)}
													{found ? (
														<LuCheck className='w-3.5 h-3.5 text-green-400' />
													) : (
														<span className='text-[10px] text-yellow-400'>
															{t('pptx.fonts.notFound')}
														</span>
													)}
												</div>
											</div>
										);
									})}
								</div>
							)}
						</div>

						{missingFamilies.length > 0 && !scanning && (
							<p className='text-[11px] text-yellow-400/80'>
								{t('pptx.fonts.missingWarning', {
									count: missingFamilies.length,
								})}
							</p>
						)}
					</div>

					{/* Footer */}
					<div className='flex items-center justify-end px-5 py-3 border-t border-border/60 shrink-0'>
						<DialogFooter
							actions={[{ id: 'done', label: t('pptx.common.done'), variant: 'primary' }]}
							onAction={onClose}
						/>
					</div>
				</div>
			</div>
		</>
	);
}

// packages/svelte/src/viewer/components/ribbon/file/FontEmbeddingPanel.svelte
<script lang="ts">
	import DialogFooter from '../../DialogFooter.svelte';
	import Check from '@lucide/svelte/icons/check';
	import Type from '@lucide/svelte/icons/type';
	import X from '@lucide/svelte/icons/x';
	import { scanAvailableFontFamilies } from 'pptx-viewer-shared';

	import { useTranslator } from '../../../../i18n/context';

	const {
		usedFontFamilies,
		embeddedFonts,
		enabled,
		canEmbed = true,
		unavailableKey,
		ontoggle,
		onclose,
	}: {
		usedFontFamilies: string[];
		embeddedFonts: string[];
		enabled: boolean;
		/**
		 * False when the deck embeds nothing, in which case the switch is inert and
		 * says why: the viewer can keep or strip embedded font data on save, but it
		 * cannot manufacture it from an installed system face.
		 */
		canEmbed?: boolean;
		/** i18n key for the explanation shown when `canEmbed` is false. */
		unavailableKey?: string;
		ontoggle: (enabled: boolean) => void;
		onclose: () => void;
	} = $props();
	const t = useTranslator();
	let available = $state<Set<string>>(new Set());
	let scanning = $state(true);
	const embedded = $derived(new Set(embeddedFonts));
	const missingCount = $derived(usedFontFamilies.filter((font) => !available.has(font)).length);

	$effect(() => {
		let active = true;
		scanning = true;
		void scanAvailableFontFamilies(usedFontFamilies).then((found) => {
			if (active) {
				available = found;
				scanning = false;
			}
			return found;
		});
		return () => {
			active = false;
		};
	});
</script>

<div class="backdrop">
	<button class="scrim" type="button" aria-label={t('pptx.common.close')} onclick={onclose}></button>
	<div class="panel" role="dialog" aria-modal="true" aria-labelledby="pptx-svelte-fonts-title">
		<header>
			<div><span><Type size={17} aria-hidden="true" /></span><h2 id="pptx-svelte-fonts-title">{t('pptx.fonts.embedFonts')}</h2></div>
			<button type="button" aria-label={t('pptx.common.close')} onclick={onclose}><X size={16} aria-hidden="true" /></button>
		</header>
		<div class="body">
			<p>{t('pptx.fonts.embedDescription')}</p>
			<label class="toggle" class:inert={!canEmbed}><pptx-ui-checkbox checked={enabled} disabled={!canEmbed} onchange={(event) => ontoggle(event.currentTarget.checked)}></pptx-ui-checkbox><span>{t('pptx.fonts.enableEmbedding')}</span></label>
			<!-- The switch used to move and change nothing at all. It now decides
			     whether save keeps the deck's embedded font data, so it has to say
			     which of the two it is doing, and admit when it can do neither. -->
			<p class="status">{canEmbed ? t('pptx.fonts.embedKeepsExisting') : t(unavailableKey ?? 'pptx.fonts.embedUnavailable')}</p>
			<h3>{t('pptx.fonts.usedFonts')} ({usedFontFamilies.length})</h3>
			{#if scanning}
				<p class="status">{t('pptx.fonts.scanning')}</p>
			{:else if usedFontFamilies.length === 0}
				<p class="status">{t('pptx.fontEmbedding.noCustomFonts')}</p>
			{:else}
				<div class="fonts">
					{#each usedFontFamilies as family}
						<div class="font"><span>{family}</span><span class="badges">{#if embedded.has(family)}<b>{t('pptx.fonts.embedded')}</b>{/if}{#if available.has(family)}<i><Check size={14} aria-hidden="true" /></i>{:else}<em>{t('pptx.fonts.notFound')}</em>{/if}</span></div>
					{/each}
				</div>
			{/if}
			{#if !scanning && missingCount > 0}<p class="warning">{t('pptx.fonts.missingWarning', { count: missingCount })}</p>{/if}
		</div>
		<footer><DialogFooter actions={[{ id: 'done', label: t('pptx.common.done'), variant: 'primary' }]} onaction={onclose} /></footer>
	</div>
</div>

<style>
	.backdrop{position:fixed;inset:0;z-index:90;display:grid;place-items:center;background:#0009}.scrim{position:absolute;inset:0;width:100%;height:100%;border:0;background:transparent}.panel{position:relative;width:min(460px,calc(100vw - 32px));max-height:80vh;overflow:auto;border:1px solid var(--pptx-border,#3f3f52);border-radius:12px;background:var(--pptx-card,#1e1e2e);color:var(--pptx-card-foreground,#e2e8f0);box-shadow:0 24px 80px #0008}header,footer{display:flex;align-items:center;justify-content:space-between;padding:14px 18px;border-bottom:1px solid var(--pptx-border,#3f3f52)}header div{display:flex;align-items:center;gap:9px}header span{display:grid;width:24px;height:24px;place-items:center;border-radius:6px;background:color-mix(in srgb,var(--pptx-primary,#c43b32) 18%,transparent);color:var(--pptx-primary,#c43b32);font-weight:700}h2,h3,p{margin:0}h2{font-size:14px}h3{font-size:12px}.body{display:grid;gap:16px;padding:18px}.body>p,.status{font-size:12px;color:var(--pptx-muted-foreground,#94a3b8)}button,input{accent-color:var(--pptx-primary,#c43b32)}button{border:1px solid var(--pptx-border,#3f3f52);border-radius:6px;padding:6px 10px;background:var(--pptx-muted,#2a2a3d);color:inherit}.toggle{display:flex;align-items:center;gap:10px;font-size:12px}.toggle.inert{opacity:.6;cursor:not-allowed}.fonts{display:grid;gap:6px;max-height:280px;overflow:auto}.font{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:9px 10px;border-radius:8px;background:var(--pptx-muted,#2a2a3d);font-size:12px}.badges{display:flex;align-items:center;gap:7px}.badges b{padding:2px 5px;border-radius:4px;background:#16653455;color:#86efac;font-size:10px}.badges i{color:#4ade80;font-style:normal}.badges em,.warning{color:#fbbf24;font-size:10px;font-style:normal}.warning{font-size:11px}footer{justify-content:flex-end;border-top:1px solid var(--pptx-border,#3f3f52);border-bottom:0}@media(max-width:600px){.panel{position:fixed;inset:auto 0 0;width:100%;max-height:88dvh;border-radius:16px 16px 0 0}}
</style>
