// packages/vue/src/viewer/components/AutosaveIndicator.vue
<script setup lang="ts">
/**
 * AutosaveIndicator — a tiny status pill for the editor toolbar.
 *
 * Reflects the autosave lifecycle (`status`) and the unsaved-edits flag
 * (`isDirty`) as a short label: "Saving…", "Saved", "Save failed", or
 * "Unsaved changes". Purely presentational; the logic lives in
 * `useAutosave`.
 */
import { computed } from 'vue';

import type { AutosaveStatus } from '../composables/useAutosave';

const props = defineProps<{
	status: AutosaveStatus;
	isDirty: boolean;
}>();

type Tone = 'idle' | 'saving' | 'saved' | 'error' | 'dirty';

const tone = computed<Tone>(() => {
	if (props.status === 'saving') {
		return 'saving';
	}
	if (props.status === 'error') {
		return 'error';
	}
	if (props.isDirty) {
		return 'dirty';
	}
	if (props.status === 'saved') {
		return 'saved';
	}
	return 'idle';
});

const label = computed(() => {
	switch (tone.value) {
		case 'saving':
			return 'Saving…';
		case 'error':
			return 'Save failed';
		case 'dirty':
			return 'Unsaved changes';
		case 'saved':
			return 'Saved';
		default:
			return 'All changes saved';
	}
});
</script>

<template>
	<span
		class="pptx-vue-autosave"
		:class="`pptx-vue-autosave--${tone}`"
		role="status"
		aria-live="polite"
	>
		<span v-if="tone === 'saving'" class="pptx-vue-autosave__spinner" aria-hidden="true" />
		<span v-else class="pptx-vue-autosave__dot" aria-hidden="true" />
		{{ label }}
	</span>
</template>

<style scoped>
.pptx-vue-autosave {
	display: inline-flex;
	align-items: center;
	gap: 0.4em;
	padding: 0.15em 0.6em;
	font-size: 0.75rem;
	line-height: 1.4;
	border-radius: 999px;
	white-space: nowrap;
	user-select: none;
	background: var(--pptx-vue-autosave-bg, rgba(127, 127, 127, 0.14));
	color: var(--pptx-vue-autosave-fg, currentColor);
}

.pptx-vue-autosave__dot {
	width: 0.5em;
	height: 0.5em;
	border-radius: 50%;
	background: currentColor;
	opacity: 0.7;
}

.pptx-vue-autosave--saved {
	color: var(--pptx-vue-autosave-saved, #2f9e44);
}

.pptx-vue-autosave--dirty {
	color: var(--pptx-vue-autosave-dirty, #e8920c);
}

.pptx-vue-autosave--error {
	color: var(--pptx-vue-autosave-error, #e03131);
}

.pptx-vue-autosave__spinner {
	width: 0.7em;
	height: 0.7em;
	border-radius: 50%;
	border: 2px solid currentColor;
	border-top-color: transparent;
	opacity: 0.85;
	animation: pptx-vue-autosave-spin 0.7s linear infinite;
}

@keyframes pptx-vue-autosave-spin {
	to {
		transform: rotate(360deg);
	}
}
</style>

// packages/svelte/src/viewer/components/AutosaveIndicator.svelte
<script lang="ts">
	/**
	 * AutosaveIndicator: a tiny status pill for the viewer toolbar, mirroring the
	 * Vue binding's `AutosaveIndicator.vue`. Purely presentational; the autosave
	 * lifecycle lives in `state/autosave.svelte.ts`. Strings come from the shared
	 * i18n dictionary via the context translator (`pptx.autosave.*`).
	 */
	import { useTranslator } from '../../i18n/context';
	import type { AutosaveStatus } from '../state/autosave.svelte';

	const { status, isDirty = false }: { status: AutosaveStatus; isDirty?: boolean } = $props();

	const t = useTranslator();

	type Tone = 'idle' | 'saving' | 'saved' | 'error' | 'dirty' | 'disabled';

	const tone = $derived.by<Tone>(() => {
		if (status === 'saving') {
			return 'saving';
		}
		if (status === 'error') {
			return 'error';
		}
		if (isDirty) {
			return 'dirty';
		}
		if (status === 'saved') {
			return 'saved';
		}
		if (status === 'disabled') {
			return 'disabled';
		}
		return 'idle';
	});

	const label = $derived.by(() => {
		switch (tone) {
			case 'saving':
				return t('pptx.autosave.saving');
			case 'error':
				return t('pptx.autosave.error');
			case 'dirty':
				return t('pptx.statusBar.unsavedChanges');
			case 'saved':
				return t('pptx.autosave.savedShort');
			default:
				return t('pptx.statusBar.allSaved');
		}
	});
</script>

{#if tone !== 'disabled'}
	<span
		class="pptx-svelte-autosave"
		class:pptx-svelte-autosave-saving={tone === 'saving'}
		class:pptx-svelte-autosave-saved={tone === 'saved'}
		class:pptx-svelte-autosave-error={tone === 'error'}
		class:pptx-svelte-autosave-dirty={tone === 'dirty'}
		role="status"
		aria-live="polite"
	>
		{#if tone === 'saving'}
			<span class="pptx-svelte-autosave-spinner" aria-hidden="true"></span>
		{:else}
			<span class="pptx-svelte-autosave-dot" aria-hidden="true"></span>
		{/if}
		{label}
	</span>
{/if}

<style>
	.pptx-svelte-autosave {
		display: inline-flex;
		align-items: center;
		gap: 5px;
		padding: 2px 9px;
		border-radius: 999px;
		background: var(--pptx-muted, #33334d);
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 12px;
		line-height: 1.4;
		white-space: nowrap;
		user-select: none;
	}

	.pptx-svelte-autosave-dot,
	.pptx-svelte-autosave-spinner {
		width: 7px;
		height: 7px;
		border-radius: 50%;
		background: currentColor;
		opacity: 0.7;
	}

	.pptx-svelte-autosave-spinner {
		background: transparent;
		border: 2px solid currentColor;
		border-top-color: transparent;
		opacity: 0.85;
		animation: pptx-svelte-autosave-spin 0.7s linear infinite;
	}

	.pptx-svelte-autosave-saving {
		color: #eab308;
	}

	.pptx-svelte-autosave-saved {
		color: #22c55e;
	}

	.pptx-svelte-autosave-error {
		color: #ef4444;
	}

	.pptx-svelte-autosave-dirty {
		color: #f59e0b;
	}

	@keyframes pptx-svelte-autosave-spin {
		to {
			transform: rotate(360deg);
		}
	}
</style>
