// packages/angular/src/viewer/element-renderer.component.ts
import { NgStyle } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import type { PptxElement, TextSegment } from 'pptx-viewer-core';
import { hasTextProperties } from 'pptx-viewer-core';

import {
	getContainerStyle,
	getImageSrc,
	getShapeFillStrokeStyle,
	getTextBlockStyle,
} from './element-style';
import type { StyleMap } from './element-style';

interface TextRun {
	text: string;
	style: StyleMap;
}

/**
 * ElementRendererComponent — Angular port of the React `ElementRenderer.tsx`
 * and the Vue `ElementRenderer.vue`.
 *
 * Renders a single slide element by its `type` discriminant (viewer-first
 * subset):
 *  - `text` / `shape`    → positioned box with fill/stroke + rich text
 *  - `picture` / `image` → `<img>`
 *  - `media`             → poster frame (`<img>`) — playback TODO
 *  - `group`             → recursive children (self-referencing selector)
 *  - everything else     → labelled placeholder (TODO, see PORTING.md)
 *
 * Interaction (selection, resize, inline editing), connectors, charts, tables,
 * SmartArt, ink, OLE, and 3D are not yet ported.
 */
@Component({
	selector: 'pptx-element-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle],
	template: `
		@switch (true) {
			@case (element().type === 'group') {
				<div
					class="pptx-ng-element pptx-ng-group"
					[ngStyle]="containerStyle()"
					[attr.data-element-id]="element().id"
				>
					@for (child of children(); track child.id) {
						<pptx-element-renderer
							[element]="child"
							[mediaDataUrls]="mediaDataUrls()"
							[zIndex]="$index"
						/>
					}
				</div>
			}
			@case (isImageLike()) {
				<div
					class="pptx-ng-element pptx-ng-image"
					[ngStyle]="containerStyle()"
					[attr.data-element-id]="element().id"
				>
					@if (imageSrc()) {
						<img [src]="imageSrc()" alt="" class="pptx-ng-img" />
					}
				</div>
			}
			@case (element().type === 'media') {
				<div
					class="pptx-ng-element pptx-ng-media"
					[ngStyle]="containerStyle()"
					[attr.data-element-id]="element().id"
				>
					@if (imageSrc()) {
						<img [src]="imageSrc()" alt="" class="pptx-ng-img" />
					} @else {
						<div class="pptx-ng-placeholder">{{ placeholderLabel() }}</div>
					}
				</div>
			}
			@case (isShapeLike()) {
				<div
					class="pptx-ng-element pptx-ng-shape"
					[ngStyle]="shapeContainerStyle()"
					[attr.data-element-id]="element().id"
				>
					@if (hasText()) {
						<div class="pptx-ng-text" [ngStyle]="textStyle()">
							@for (para of paragraphs(); track $index) {
								<p class="pptx-ng-para">
									@for (run of para; track $index) {
										@if (
											run.text ===
											'
'
										) {
											<br />
										} @else {
											<span [ngStyle]="run.style">{{ run.text }}</span>
										}
									}
								</p>
							}
						</div>
					}
				</div>
			}
			@default {
				<div
					class="pptx-ng-element pptx-ng-unsupported"
					[ngStyle]="containerStyle()"
					[attr.data-element-id]="element().id"
				>
					<div class="pptx-ng-placeholder">{{ placeholderLabel() }}</div>
				</div>
			}
		}
	`,
})
export class ElementRendererComponent {
	readonly element = input.required<PptxElement>();
	readonly mediaDataUrls = input<Map<string, string>>(new Map());
	readonly zIndex = input<number>(0);

	readonly containerStyle = computed<StyleMap>(() =>
		getContainerStyle(this.element(), this.zIndex()),
	);
	readonly shapeContainerStyle = computed<StyleMap>(() => ({
		...this.containerStyle(),
		...getShapeFillStrokeStyle(this.element()),
	}));
	readonly textStyle = computed<StyleMap>(() => getTextBlockStyle(this.element()));
	readonly imageSrc = computed(() => getImageSrc(this.element(), this.mediaDataUrls()));

	readonly children = computed<PptxElement[]>(() => {
		const el = this.element();
		return el.type === 'group' ? (el.children ?? []) : [];
	});

	readonly isShapeLike = computed(
		() => this.element().type === 'text' || this.element().type === 'shape',
	);
	readonly isImageLike = computed(
		() => this.element().type === 'picture' || this.element().type === 'image',
	);

	readonly paragraphs = computed<TextRun[][]>(() => {
		const el = this.element();
		if (!hasTextProperties(el)) {
			return [];
		}
		const segments = el.textSegments;
		if (!segments || segments.length === 0) {
			return el.text ? [[{ text: el.text, style: {} }]] : [];
		}
		const out: TextRun[][] = [[]];
		for (const seg of segments) {
			if (seg.isParagraphBreak) {
				out.push([]);
				continue;
			}
			const current = out[out.length - 1];
			const text = seg.isLineBreak ? '\n' : seg.text;
			if (text) {
				current.push({ text, style: this.segmentStyle(seg) });
			}
		}
		return out.filter((p) => p.length > 0 || out.length === 1);
	});

	readonly hasText = computed(() => this.paragraphs().some((p) => p.length > 0));

	readonly placeholderLabel = computed(() => {
		const map: Record<string, string> = {
			table: 'Table',
			chart: 'Chart',
			smartArt: 'SmartArt',
			connector: 'Connector',
			group: 'Group',
			media: 'Media',
			ink: 'Ink',
			ole: 'Embedded object',
			model3d: '3D model',
			zoom: 'Zoom',
		};
		return map[this.element().type] ?? this.element().type;
	});

	private segmentStyle(seg: TextSegment): StyleMap {
		const s = seg.style ?? {};
		const style: StyleMap = {};
		if (s.fontFamily) {
			style['font-family'] = s.fontFamily;
		}
		if (typeof s.fontSize === 'number') {
			style['font-size'] = `${s.fontSize}pt`;
		}
		if (s.color) {
			style['color'] = s.color;
		}
		if (s.bold) {
			style['font-weight'] = 'bold';
		}
		if (s.italic) {
			style['font-style'] = 'italic';
		}
		const deco: string[] = [];
		if (s.underline) {
			deco.push('underline');
		}
		if (s.strikethrough) {
			deco.push('line-through');
		}
		if (deco.length > 0) {
			style['text-decoration'] = deco.join(' ');
		}
		return style;
	}
}

@switch (true) {
	@case (isHidden()) {
		<!--
			Hidden via the Selection Pane: draw nothing, exactly as PowerPoint
			does. This is the FIRST case on purpose - @switch takes the first
			match, so one empty branch suppresses every element type at once
			without wrapping (and re-indenting) the whole template. The host
			carries \`display: contents\`, so an empty component collapses.
			Rendering nothing (rather than an invisible box) is what keeps the
			element out of hit-testing, the tab order and the export raster; it
			stays listed in and selectable from the Selection Pane, which reads
			the slide model rather than the DOM.
		-->
	}
	@case (element().type === 'connector') {
		<pptx-connector-renderer
			[element]="element()"
			[zIndex]="zIndex()"
			[obstacles]="obstacles()"
			[canvasWidth]="canvasWidth()"
			[canvasHeight]="canvasHeight()"
			[interactive]="interactive()"
			[marked]="elementMarked()"
			[exposeElementId]="exposeElementId()"
			[animationState]="animationState()"
		/>
	}
	@case (element().type === 'ink') {
		<!--
			This renderer (and zoom / model3d / 3D SmartArt below) positions its
			own root box, so it takes the neutral element marker
			(data-pptx-element) as an input instead of being wrapped in a marked
			box the way chart / table / OLE are: an outer positioned box would
			offset it twice.
		-->
		<pptx-ink-renderer
			[element]="element()"
			[zIndex]="zIndex()"
			[mediaDataUrls]="mediaDataUrls()"
			[replay]="presenting()"
			[markElement]="elementMarked()"
			[exposeElementId]="exposeElementId()"
		/>
	}
	@case (element().type === 'contentPart') {
		<!--
			Real PowerPoint ink. Same positioning contract as pptx-ink-renderer
			above: the renderer's own root is absolutely positioned, so it takes
			the neutral element marker as an input rather than being wrapped.
		-->
		<pptx-content-part-renderer
			[element]="element()"
			[zIndex]="zIndex()"
			[replay]="presenting()"
			[markElement]="elementMarked()"
			[exposeElementId]="exposeElementId()"
		/>
	}
	@case (element().type === 'zoom') {
		<pptx-zoom-renderer
			[element]="element()"
			[zIndex]="zIndex()"
			[mediaDataUrls]="mediaDataUrls()"
			[markElement]="elementMarked()"
		/>
	}
	@case (element().type === 'model3d') {
		<pptx-model3d-renderer
			[element]="element()"
			[zIndex]="zIndex()"
			[mediaDataUrls]="mediaDataUrls()"
			[markElement]="elementMarked()"
			[exposeElementId]="exposeElementId()"
		/>
	}
	@case (element().type === 'smartArt' && smartArt3D()) {
		<pptx-smart-art-3d-renderer
			[element]="element()"
			[zIndex]="zIndex()"
			[canEdit]="interactive() && editable()"
			[markElement]="elementMarked()"
		/>
	}
	@case (element().type === 'smartArt') {
		<div
			class="pptx-ng-element pptx-ng-smartart"
			[ngStyle]="containerStyle()"
			[style.pointer-events]="rootPointerEvents()"
			[attr.data-element-id]="elementIdAttr()"
			[attr.data-pptx-element]="elementMarked() ? 'true' : null"
		>
			<pptx-smart-art-renderer
				[element]="element()"
				[editable]="interactive() && editable()"
				[animationState]="animationState()"
			/>
		</div>
	}
	@case (element().type === 'ole') {
		<div
			class="pptx-ng-element pptx-ng-ole"
			[ngStyle]="containerStyle()"
			[style.pointer-events]="rootPointerEvents()"
			[attr.data-element-id]="elementIdAttr()"
			[attr.data-pptx-element]="elementMarked() ? 'true' : null"
		>
			<pptx-ole-renderer [element]="element()" />
		</div>
	}
	@case (element().type === 'chart') {
		<div
			class="pptx-ng-element pptx-ng-chart"
			[ngStyle]="containerStyle()"
			[style.pointer-events]="rootPointerEvents()"
			[attr.data-element-id]="elementIdAttr()"
			[attr.data-pptx-element]="elementMarked() ? 'true' : null"
		>
			<pptx-chart-element-view
				[element]="element()"
				[editable]="interactive() && editable()"
				[animationState]="animationState()"
			/>
		</div>
	}
	@case (element().type === 'table') {
		<div
			class="pptx-ng-element pptx-ng-table"
			[ngStyle]="containerStyle()"
			[style.pointer-events]="rootPointerEvents()"
			[attr.data-element-id]="elementIdAttr()"
			[attr.data-pptx-element]="elementMarked() ? 'true' : null"
		>
			<pptx-table-renderer
				[element]="element()"
				[editable]="interactive() && editable()"
				(cellCommit)="cellCommit.emit({ id: element().id, commit: $event })"
				(tableChange)="tableChange.emit($event)"
			/>
		</div>
	}
	@case (element().type === 'group') {
		<div
			class="pptx-ng-element pptx-ng-group"
			[ngStyle]="containerStyle()"
			[style.pointer-events]="rootPointerEvents()"
			[attr.data-element-id]="elementIdAttr()"
			[attr.data-pptx-element]="elementMarked() ? 'true' : null"
		>
			@for (child of children(); track child.id) {
				<pptx-element-renderer
					[element]="child"
					[mediaDataUrls]="mediaDataUrls()"
					[zIndex]="$index"
					[interactive]="interactive()"
					[marked]="marked()"
					[exposeElementId]="exposeElementId()"
					[presenting]="presenting()"
					[fieldContext]="fieldContext()"
					[slideElements]="slideElements()"
					[parentGroupFill]="childParentGroupFill()"
					[editingElementId]="editingElementId()"
				/>
			}
		</div>
	}
	@case (isImageLike()) {
		<pptx-image-renderer
			[element]="element()"
			[mediaDataUrls]="mediaDataUrls()"
			[zIndex]="zIndex()"
			[interactive]="interactive()"
			[marked]="elementMarked()"
			[exposeElementId]="exposeElementId()"
		/>
	}
	@case (element().type === 'media') {
		<pptx-media-renderer
			[element]="element()"
			[mediaDataUrls]="mediaDataUrls()"
			[zIndex]="zIndex()"
			[interactive]="interactive()"
			[marked]="elementMarked()"
			[exposeElementId]="exposeElementId()"
			[presenting]="presenting()"
			[placeholderLabel]="placeholderLabel()"
		/>
	}
	@case (isShapeLike()) {
		<div
			class="pptx-ng-element pptx-ng-shape"
			[ngStyle]="shapeContainerStyle()"
			[style.pointer-events]="rootPointerEvents()"
			[attr.data-element-id]="elementIdAttr()"
			[attr.data-pptx-element]="elementMarked() ? 'true' : null"
		>
			<!-- Per-sub-path fill overlay: a multi-sub-path preset (`smileyFace`'s
			     open eyes, `actionButtonBlank`'s darkened bevel well) or custom
			     geometry whose sub-paths cannot share one CSS background-color. -->
			@if (subpathFill(); as sf) {
				<svg
					class="pptx-ng-subpath-fill"
					aria-hidden="true"
					[attr.viewBox]="subpathFillViewBox()"
					preserveAspectRatio="none"
					style="position: absolute; inset: 0; width: 100%; height: 100%"
				>
					@for (paint of sf.paints; track $index) {
						<path [attr.d]="paint.d" [attr.fill]="paint.fill" stroke="none" />
					}
				</svg>
			}
			@if (fillOverlay(); as ov) {
				<div
					class="pptx-ng-fill-overlay"
					aria-hidden="true"
					style="position: absolute; inset: 0; pointer-events: none"
					[style.background]="ov.color"
					[style.mix-blend-mode]="ov.blendMode"
				></div>
			}
			<!-- Mirrored reflection sibling (`a:reflection`): cross-browser, unlike
			     the `-webkit-box-reflect` this replaced (Firefox never implemented
			     that property, so reflections were invisible there entirely). -->
			@if (reflection(); as refl) {
				<div class="pptx-ng-reflection" aria-hidden="true" [ngStyle]="refl.wrapperStyle">
					@if (refl.imgSrc) {
						<img
							[src]="refl.imgSrc"
							alt=""
							draggable="false"
							style="width: 100%; height: 100%"
							[ngStyle]="refl.imgFitStyle"
						/>
					} @else if (refl.fill) {
						<div
							style="width: 100%; height: 100%"
							[style.background-color]="refl.fill.backgroundColor"
							[style.background-image]="refl.fill.backgroundImage"
							[style.background-size]="refl.fill.backgroundSize"
							[style.background-position]="refl.fill.backgroundPosition"
							[style.background-repeat]="refl.fill.backgroundRepeat"
						></div>
					}
				</div>
			}
			<!-- Hollow frame hit target: an unfilled, textless shape is hit-tested
			     on its outline only, so its interior lets clicks through. -->
			@if (hollowHit(); as hit) {
				<svg
					aria-hidden="true"
					[attr.viewBox]="outlineViewBox()"
					preserveAspectRatio="none"
					style="
						position: absolute;
						inset: 0;
						width: 100%;
						height: 100%;
						overflow: visible;
						pointer-events: none;
					"
				>
					<path
						[attr.d]="hit.d"
						fill="none"
						stroke="transparent"
						[attr.stroke-width]="hit.strokeWidth"
						style="pointer-events: stroke"
					/>
				</svg>
			}
			<!-- Stroked outline: a CSS border takes one flat colour, and cannot
			     outline an open preset (`line`, `arc`) at all. -->
			@if (gradientOutline(); as go) {
				<svg
					class="pptx-ng-gradient-outline"
					aria-hidden="true"
					[attr.viewBox]="outlineViewBox()"
					preserveAspectRatio="none"
					style="
						position: absolute;
						inset: 0;
						width: 100%;
						height: 100%;
						overflow: visible;
						pointer-events: none;
					"
				>
					@if (go.paint; as paint) {
						<defs>
							@if (paint.kind === 'pattern') {
								<pattern
									[attr.id]="paint.id"
									[attr.width]="paint.width"
									[attr.height]="paint.height"
									patternUnits="userSpaceOnUse"
								>
									<image
										[attr.href]="paint.href"
										[attr.width]="paint.width"
										[attr.height]="paint.height"
									/>
								</pattern>
							} @else if (paint.kind === 'radial') {
								<radialGradient
									[attr.id]="paint.id"
									[attr.cx]="paint.cx"
									[attr.cy]="paint.cy"
									[attr.r]="paint.r"
								>
									@for (stop of paint.stops; track $index) {
										<stop
											[attr.offset]="stop.offset"
											[attr.stop-color]="stop.color"
											[attr.stop-opacity]="stop.opacity"
										/>
									}
								</radialGradient>
							} @else {
								<linearGradient
									[attr.id]="paint.id"
									[attr.x1]="paint.x1"
									[attr.y1]="paint.y1"
									[attr.x2]="paint.x2"
									[attr.y2]="paint.y2"
								>
									@for (stop of paint.stops; track $index) {
										<stop
											[attr.offset]="stop.offset"
											[attr.stop-color]="stop.color"
											[attr.stop-opacity]="stop.opacity"
										/>
									}
								</linearGradient>
							}
						</defs>
					}
					@for (strand of go.strands; track $index) {
						<path
							[attr.d]="go.d"
							fill="none"
							[attr.stroke]="go.stroke"
							[attr.stroke-width]="strand.strokeWidth"
							[attr.stroke-dasharray]="go.dashArray"
							[attr.stroke-linecap]="go.lineCap"
							[attr.stroke-linejoin]="go.lineJoin"
							[style.transform]="
								strand.offset !== 0 ? 'translate(0, ' + strand.offset + 'px)' : null
							"
						/>
					}
				</svg>
			}
			<!-- While this element is open in the inline text editor, its live text
			     is drawn by that overlay instead (see `isBeingInlineEdited`);
			     rendering it here too produced a duplicate, offset "text shadow"
			     (issue #182). -->
			@if (!isBeingInlineEdited()) {
				@if (pathWarp(); as warp) {
					<svg
						[attr.width]="warp.width"
						[attr.height]="warp.height"
						[attr.viewBox]="'0 0 ' + warp.width + ' ' + warp.height"
						style="position: absolute; inset: 0; overflow: visible; pointer-events: none"
						aria-hidden="true"
					>
						<defs>
							@for (line of warp.pathLines; track line.pathId) {
								<path [attr.id]="line.pathId" [attr.d]="line.d" fill="none" />
							}
						</defs>
						@for (line of warp.pathLines; track line.pathId) {
							<text
								[attr.font-size]="warp.baseFontSize"
								[attr.font-family]="warp.baseFontFamily"
								[attr.fill]="warp.baseColor"
							>
								<textPath
									[attr.href]="'#' + line.pathId"
									[attr.startOffset]="warp.startOffset"
									[attr.text-anchor]="warp.textAnchor"
								>
									@for (seg of line.segments; track $index) {
										<tspan
											[attr.fill]="seg.style?.color ?? warp.baseColor"
											[attr.font-weight]="seg.style?.bold ? 700 : 400"
											[attr.font-style]="seg.style?.italic ? 'italic' : 'normal'"
										>
											{{ seg.text }}
										</tspan>
									}
								</textPath>
							</text>
						}
					</svg>
				} @else if (hasText()) {
					<div class="pptx-ng-text" [ngStyle]="warpedTextStyle()">
						@for (para of paragraphs(); track $index) {
							<p
								class="pptx-ng-para"
								[ngStyle]="para.paragraphStyle ?? null"
								[style.padding-left.px]="para.indentPx"
								[style.text-indent.px]="para.textIndentPx ?? null"
								[style.line-height]="para.lineHeight ?? null"
								[style.margin-top.px]="para.spaceBeforePx ?? null"
								[style.margin-bottom.px]="para.spaceAfterPx ?? null"
								[style.font-size.px]="para.strutFontSizePx ?? null"
							>
								@if (para.bulletPicture?.src) {
									<img
										class="pptx-ng-bullet-image"
										[src]="para.bulletPicture.src"
										[alt]="para.bulletPicture.accessibleLabel"
										[style.width.px]="para.bulletPicture.sizePx"
										[style.height.px]="para.bulletPicture.sizePx"
										style="
											display: inline-block;
											vertical-align: middle;
											margin-inline-end: 4px;
											object-fit: contain;
										"
									/>
								} @else if (para.bulletMarker) {
									<span
										class="pptx-ng-bullet"
										[ngStyle]="para.bulletStyle"
										[attr.aria-label]="para.bulletPicture?.accessibleLabel ?? null"
										>{{ para.bulletMarker }}</span
									>
								}
								@if (textBuildSpecs()[$index]; as spec) {
									<!-- Staged text build: render the split pieces so each one
								     carries its own sub-animation. -->
									@if (spec.granularity === 'paragraph') {
										<span [attr.data-anim-id]="spec.animId" [ngStyle]="buildSpanStyle(spec)">{{
											paragraphText(para)
										}}</span>
									} @else {
										@for (span of spec.spans ?? []; track $index) {
											<span [attr.data-anim-id]="span.animId" [ngStyle]="buildSpanStyle(span)">{{
												span.text
											}}</span>
										}
									}
								} @else {
									@for (run of para.runs; track $index) {
										@if (run.equationXml) {
											<pptx-equation-renderer
												[equationXml]="run.equationXml"
												[equationNumber]="run.equationNumber"
											/>
										} @else if (
											run.text ===
											'
'
										) {
											<br />
										} @else if (run.reflection; as refl) {
											<!-- `a:reflection`: wrapped HERE, around the whole base
										     run (`runBase`), rather than inside its href/ruby/plain
										     branches - a `<ruby>` run's own `display: ruby` (which
										     positions the annotation above its base text) would
										     break if forced to `display: inline-block` to host the
										     mirror. Cross-browser, unlike the `-webkit-box-reflect`
										     this replaced (Firefox never implemented it). -->
											<span style="position: relative; display: inline-block">
												<ng-container *ngTemplateOutlet="runBase; context: { run: run }" />
												<span class="pptx-ng-text-reflection" aria-hidden="true" [ngStyle]="refl"
													><span [ngStyle]="run.style"
														><ng-container
															*ngTemplateOutlet="runContent; context: { run: run }" /></span
												></span>
											</span>
										} @else {
											<ng-container *ngTemplateOutlet="runBase; context: { run: run }" />
										}
									}
								}
								@if (para.isEmpty) {
									<!-- An authored blank line has no runs, so without this the
								     <p> collapses to zero height and the gap a deck puts
								     between a heading and its bullet list disappears. -->
									<br />
								}
							</p>
						}
					</div>
				}
			}
		</div>
	}
	@default {
		<div
			class="pptx-ng-element pptx-ng-unsupported"
			[ngStyle]="containerStyle()"
			[style.pointer-events]="rootPointerEvents()"
			[attr.data-element-id]="elementIdAttr()"
			[attr.data-pptx-element]="elementMarked() ? 'true' : null"
		>
			<div class="pptx-ng-placeholder">{{ placeholderLabel() }}</div>
		</div>
	}
}

<!-- Soft-edge feather <filter> def, referenced via filter: url(#soft-edge-<id>). -->
@if (softEdgeFilter(); as sef) {
	<svg
		width="0"
		height="0"
		aria-hidden="true"
		style="position: absolute; width: 0; height: 0; overflow: hidden"
	>
		<defs>
			<filter
				[attr.id]="sef.id"
				x="-20%"
				y="-20%"
				width="140%"
				height="140%"
				color-interpolation-filters="sRGB"
			>
				<feGaussianBlur in="SourceAlpha" [attr.stdDeviation]="sef.radius" result="softEdgeAlpha" />
				<feComposite in="SourceGraphic" in2="softEdgeAlpha" operator="in" />
			</filter>
		</defs>
	</svg>
}

<!-- Duotone image-effect <filter> def, referenced via filter: url(#id). -->
@if (duotoneFilter(); as df) {
	<svg
		width="0"
		height="0"
		aria-hidden="true"
		style="position: absolute; width: 0; height: 0; overflow: hidden"
	>
		<defs>
			<filter [attr.id]="df.id" color-interpolation-filters="sRGB">
				<feColorMatrix type="matrix" [attr.values]="df.primitives[0].values" />
				<feComponentTransfer>
					<feFuncR
						type="linear"
						[attr.slope]="df.primitives[1].channels[0].slope"
						[attr.intercept]="df.primitives[1].channels[0].intercept"
					/>
					<feFuncG
						type="linear"
						[attr.slope]="df.primitives[1].channels[1].slope"
						[attr.intercept]="df.primitives[1].channels[1].intercept"
					/>
					<feFuncB
						type="linear"
						[attr.slope]="df.primitives[1].channels[2].slope"
						[attr.intercept]="df.primitives[1].channels[2].intercept"
					/>
				</feComponentTransfer>
			</filter>
		</defs>
	</svg>
}

<!--
	One run's base element (hyperlink / ruby / plain span), reused via
	`ngTemplateOutlet` both directly and inside the `a:reflection` wrapper above,
	so the reflection case does not duplicate this three-way branch.
-->
<ng-template #runBase let-run="run">
	@if (run.href) {
		<a
			class="pptx-ng-link"
			[href]="run.href"
			target="_blank"
			rel="noopener noreferrer"
			[attr.title]="run.tooltip ?? null"
			[ngStyle]="run.style"
			><ng-container *ngTemplateOutlet="runContent; context: { run: run }"
		/></a>
	} @else if (run.rubyText) {
		<!-- `a:ruby`: the phonetic guide sits above its base
		     text; the <rp> parentheses are the fallback for a
		     browser without ruby support. -->
		<ruby [ngStyle]="run.style"
			><ng-container *ngTemplateOutlet="runContent; context: { run: run }" /><rp>(</rp
			><rt [ngStyle]="run.rubyStyle">{{ run.rubyText }}</rt
			><rp>)</rp></ruby
		>
	} @else {
		<span [ngStyle]="run.style"
			><ng-container *ngTemplateOutlet="runContent; context: { run: run }"
		/></span>
	}
</ng-template>

<!--
	A run's text content, honouring shared's per-script font split
	(`run.scriptRuns`) and measured tab-stop layout (`run.tabLines`) when
	either is present. Both descriptors come from `pptx-viewer-shared`'s
	`buildParagraphs` (the per-script split was React-only before this
	template existed: CJK, Arabic, Hebrew and Thai text rendered in the wrong
	typeface here; the tab layout was likewise React-only, so a TOC-style row
	lost its leader dots and right-aligned page number). Reused via
	`ngTemplateOutlet` for the run's span / anchor / ruby base text, so all
	three carry the same content logic.
-->
<ng-template #runContent let-run="run">
	@if (run.tabLines) {
		@for (line of run.tabLines; track $index) {
			<span style="display: inline-block; white-space: nowrap">
				@for (piece of line.pieces; track $index) {
					@if (piece.leaderStyle) {
						<span aria-hidden="true" [ngStyle]="piece.leaderStyle">{{ piece.leaderText }}</span>
					}
					<span [ngStyle]="piece.style">{{ piece.text }}</span>
				}
			</span>
			@if (!$last) {
				<br />
			}
		}
	} @else if (run.scriptRuns) {
		<!--
			A bare interpolation as the sole content of an `@if`/`@else` block
			leaks a real leading + trailing whitespace text node: Angular does
			not collapse that whitespace the way it collapses whitespace between
			element TAGS. Worse, oxfmt's Angular-template printer always breaks a
			block's content onto its own indented line, even when the block was
			written as a single line with the braces touching, so writing the
			`{{ x }}` compact ourselves does not survive the next `bun run fmt` /
			pre-commit `lint-staged` pass: it silently re-introduces the leak
			(this happened twice, see `20d4d177`, `18eebb6f`). `<ng-container>`
			does not render any DOM node of its own, so wrapping the
			interpolation in one keeps the no-wrapper-element behaviour of
			React's `<>{piece.text}</>` fragment while making the interpolation
			tag-adjacent, which both Angular AND oxfmt already treat as safely
			collapsible (see the many `<span>{{ x }}</span>` one-liners in this
			file). That was invisible while a paragraph was one run per script
			(two stray spaces at the run's own edges, trimmed visually by the
			browser but still present in `textContent`), but shared's per-word /
			per-gap metric split (`text-run-spacing.ts`, issue #149) re-emits
			every WORD and inter-word GAP as its own sibling run, so the same
			one-space leak lands between every word: "will choose" rendered as
			"will     choose" (five spaces: the word's own trailing leak, the
			gap run's real space plus its OWN two leaks, the next word's leading
			leak). The same leak also showed up one paragraph at a time:
			"Project" / "Atlas" as two separate paragraphs read back as
			"ProjectAtlas" instead of React's "Project Atlas", because the
			plain-run `@else` below had the same bug.
		-->
		@for (piece of run.scriptRuns; track $index) {
			@if (piece.style) {
				<span [ngStyle]="piece.style">{{ piece.text }}</span>
			} @else {
				<ng-container>{{ piece.text }}</ng-container>
			}
		}
	} @else {
		<ng-container>{{ run.text }}</ng-container>
	}
</ng-template>

// packages/svelte/src/viewer/components/ElementRenderer.svelte
<script lang="ts">
	/**
	 * ElementRenderer: a thin dispatcher over the `PptxElement` discriminated
	 * union (Svelte port of Vue's `ElementRenderer`). Real renderers: group
	 * (recursive), image/picture, connector, text/shape, table, chart,
	 * smartArt, media, ink, ole, contentPart, zoom, and model3d. Only
	 * `unknown` still falls through to the typed placeholder.
	 */
	import { hasShapeProperties, hasTextProperties } from 'pptx-viewer-core';
	import { build3DExtrusionData, buildParagraphs, buildTextStyleOverrideCss, getGroupChildParentFill, getOverflowSegments, hasTextWarp, inlineElementPointerEvents, isElementHidden, isEquationOnlyText, isTemplateElement, placeholderPromptDescriptor, shouldRenderHitTarget } from 'pptx-viewer-shared';

	import { getContainerStyle, getElementHitTargetStyle, getShapeBoxStyle, getShapeFillStrokeStyle, getTextBlockStyle, mergeStyles, styleToString } from '../style';
	import { getFieldContextGetter } from '../state/field-context';
	import { getSlideElementsGetter } from '../state/slide-elements';
	import {
		getPresentationElementStatesGetter,
		usePresentationElementState,
	} from '../state/presentation-element-states-context';
	// Self-import: groups recurse into this same component (Svelte 5 pattern).
	// eslint-disable-next-line import/no-self-import
	import ElementRenderer from './ElementRenderer.svelte';
	import ChartView from './ChartView.svelte';
	import ConnectorView from './ConnectorView.svelte';
	import DuotoneFilterDefs from './DuotoneFilterDefs.svelte';
	import ShapeEffectOverlay from './ShapeEffectOverlay.svelte';
	import EquationView from './EquationView.svelte';
	import { useRendering3DFlags } from '../state/rendering-3d-flags-context';
	import Extrusion3D from './Extrusion3D.svelte';
	import ContentPartView from './ContentPartView.svelte';
	import ImageBox from './ImageBox.svelte';
	import InkView from './InkView.svelte';
	import MediaBox from './MediaBox.svelte';
	import Model3dView from './Model3dView.svelte';
	import OleView from './OleView.svelte';
	import PlaceholderElement from './PlaceholderElement.svelte';
	import SmartArt3DView from './SmartArt3DView.svelte';
	import SmartArtView from './SmartArtView.svelte';
	import TableView from './TableView.svelte';
	import TextBlock from './TextBlock.svelte';
	import ZoomView from './ZoomView.svelte';
	import WordArtText from './WordArtText.svelte';
	import type { ElementRendererProps } from './props';

	const { element, mediaDataUrls, zIndex, presenting = false, interactive = false, marked = false, editTemplateMode = false, editingElementId = null, editable = false, selectedElementIds, parentGroupFill, ontablecellcommit, onsmartartnodecommit, onsmartartnodefill, onchartpointcommit, ontableresizecolumns, ontableresizerow }: ElementRendererProps =
		$props();
	/** Whether THIS element is part of the current selection; see `ElementRendererProps.selectedElementIds`. */
	const isSelected = $derived(selectedElementIds?.includes(element.id) ?? false);
	/** This exact element is open in the element-level inline text editor right now. */
	const isBeingInlineEdited = $derived(element.id === editingElementId);
	/**
	 * Whether THIS element takes part in the neutral element contract
	 * (`data-pptx-element="true"`) and in pointer interaction.
	 *
	 * Forwarded to every delegated view, not just the branches that render their
	 * own box here: Svelte has no attribute fallthrough, so a view that is not
	 * handed this flag cannot mark its root, and its element type drops out of
	 * the contract entirely (charts and tables painted correctly while being
	 * invisible to anything that enumerates or hit-tests elements by the marker).
	 */
	const elementInteractive = $derived(interactive && (!isTemplateElement(element) || editTemplateMode));
	/**
	 * The inline pointer-events value for this element's own box, or `undefined`
	 * for "write nothing and let the stylesheet decide".
	 *
	 * Off-stage the inline value is the only thing that tells a locked template
	 * node it is locked. During a show it must stay absent in BOTH directions:
	 * `render/presentation-hit-test` makes the whole stage transparent and then
	 * re-enables only what owns its own click, and an inline value of either
	 * `none` or `auto` outranks that stylesheet. Writing `auto` here (what this
	 * branch used to do, since the show stage renders interactive) left every
	 * piece of scenery clickable, so a shape drawn over an Action Setting could
	 * swallow the click meant for it.
	 */
	const rootPointerEvents = $derived(inlineElementPointerEvents({ interactive: elementInteractive, presenting }));
	/**
	 * The same decision as a style map, so a box can MERGE it instead of spreading
	 * a key over its base map. `getShapeBoxStyle` already writes `none` for an
	 * unfilled, textless FRAME shape (PowerPoint hit-tests one on its outline only,
	 * and `ShapeEffectOverlay` paints the transparent `pointer-events: stroke` band
	 * that opts the outline back in), and `{ ...base, pointerEvents: undefined }`
	 * would drop that declaration rather than leave it alone.
	 */
	const rootPointerEventsStyle = $derived(rootPointerEvents ? { pointerEvents: rootPointerEvents } : undefined);
	/**
	 * Whether THIS element's root carries `data-pptx-element="true"`. Wider than
	 * `elementInteractive`: an interaction-locked template (master/layout)
	 * element on the main canvas keeps the marker (it is still a rendered slide
	 * element carrying the contract), it only loses pointer interactivity.
	 */
	const elementMarked = $derived(interactive || marked);
	/**
	 * The fill handed to this group's `a:grpFill` children (undefined for
	 * non-groups): its own, or the one this group inherited when it has none,
	 * since `a:grpFill` resolves against the nearest ANCESTOR with a fill.
	 */
	const childParentGroupFill = $derived(getGroupChildParentFill(element, parentGroupFill));

	/**
	 * Native-animation playback state for this element (present only during a
	 * running presentation). Drives the staged chart / SmartArt build reveal and
	 * the `p:animClr` fill / stroke relinquish; read from the element-states
	 * context so editor / read-only rendering (context absent) is unaffected.
	 */
	const animationState = $derived(usePresentationElementState(element.id));
	/**
	 * A font-style emphasis effect (Bold Flash, Bold Reveal, Underline, Change
	 * Font Style/Size) overrides the runs' own inline bold/italic/underline/
	 * size, which plain CSS inheritance cannot reach (the runs declare those
	 * unconditionally). See `animation-text-style-css.ts`. NOT gated on
	 * `hasTextProperties`: a table cell, a chart title/label/legend, and a
	 * SmartArt node caption all animate this way too, and shared's selector
	 * already scopes itself to this element's `data-element-id`.
	 */
	const textStyleOverrideCss = $derived(buildTextStyleOverrideCss(element.id, animationState?.textStyle));
	// Captured at init: `getContext` only resolves during component
	// initialisation, so reading it inside the `$derived` below returned nothing
	// and the text-build split never ran.
	const getAllAnimStates = getPresentationElementStatesGetter();
	/** Whole map, so a staged text build can find its `::c` / `::w` sub-states. */
	const allAnimStates = $derived(getAllAnimStates?.());

	/**
	 * The host's resolved 3D flags (provided by PowerPointViewer). Charts
	 * resolve their own `<pptx-three-view>` spec inside `ChartView`; only the
	 * SmartArt branch below is decided here.
	 */
	const getRendering3DFlags = useRendering3DFlags();
	const smartArt3D = $derived(getRendering3DFlags().smartArt3D);

	const isShapeLike = $derived(element.type === 'text' || element.type === 'shape');
	const isImageLike = $derived(element.type === 'picture' || element.type === 'image');

	// Captured at init for the same reason as the animation states above:
	// `getContext` only resolves during component initialisation, so the getter
	// is taken here and invoked inside the `$derived` to stay reactive.
	const getFieldContext = getFieldContextGetter();
	/**
	 * OOXML field-substitution context (slide number, date/time, header/footer,
	 * slide title, document properties), provided by the viewer root and
	 * re-pointed per slide by `SlideStage`. Without it a slide-number run renders
	 * its authored placeholder ("Slide #") instead of the resolved "Slide 1".
	 */
	const fieldContext = $derived(getFieldContext?.());

	// Captured at init for the same reason as the field context above.
	const getSlideElements = getSlideElementsGetter();
	/**
	 * The slice of an `a:linkedTxbx` chain's text this box renders, or
	 * `undefined` when the element is not in a chain (the overwhelmingly common
	 * case, resolved by a single field check inside the shared helper).
	 */
	const linkedSegments = $derived(getOverflowSegments(element, getSlideElements?.()));

	/** Rendered paragraphs (runs + bullet/indent), built by shared logic. */
	const paragraphs = $derived(buildParagraphs(element, fieldContext, linkedSegments));
	const hasText = $derived(
		paragraphs.some((p) => p.runs.length > 0 || p.bulletMarker !== undefined),
	);
	/**
	 * An empty inherited placeholder's greyed-out authoring hint ("Click to add
	 * title"), shown only on the editing canvas (`editable`) and only while the
	 * element carries no real text of its own. `placeholderPromptDescriptor`
	 * (shared) is the one place that decides "edit surface or not" so present
	 * mode, export, and thumbnails never leak the hint (unlike a render surface
	 * that reused the editor's text path unconditionally).
	 */
	const promptDescriptor = $derived(
		editable && !hasText ? placeholderPromptDescriptor(element, 'edit') : null,
	);
	/**
	 * A PURE equation box (OMML and nothing else) delegates wholesale to
	 * `EquationView`, which centres the maths in the shape. A body that mixes
	 * prose with an inline `m:oMath` renders through the paragraph path instead,
	 * where shared emits the equation as a run in its authored position: sending
	 * it here dropped every word around it.
	 */
	const hasEquation = $derived(
		hasTextProperties(element) && isEquationOnlyText(element.textSegments),
	);
	const warpedText = $derived(hasTextWarp(element));
	/** Selection Pane visibility; see the leading branch of the markup below. */
	const isHidden = $derived(isElementHidden(element));
	const extrusion = $derived.by(() => {
		const style = hasShapeProperties(element) ? element.shapeStyle : undefined;
		return build3DExtrusionData(
			style?.shape3d,
			style?.scene3d,
			style?.fillColor,
			element.width,
			element.height,
		);
	});
	/**
	 * Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE) shape:
	 * a bigger, invisible, centred click/drag target, kept separate from the
	 * painted box (`getShapeBoxStyle`, now always the authored size) so a thin
	 * authored line never paints as a thick bar in read-only rendering (issue
	 * #285). Never rendered while presenting: nothing on the show stage is
	 * draggable or selectable. `undefined` on a read-only surface (`editable`
	 * false) and when the authored box already meets the minimum size.
	 */
	const hitTarget = $derived(
		shouldRenderHitTarget(editable, presenting) ? getElementHitTargetStyle(element) : undefined,
	);
</script>

{#if isHidden}
	<!--
		Hidden via the Selection Pane: draw nothing, exactly as PowerPoint does.
		This leads the chain so one empty branch suppresses every element type at
		once. Rendering nothing (rather than an invisible box) is what keeps the
		element out of hit-testing, the tab order and the export raster; it stays
		listed in and selectable from the Selection Pane, which reads the slide
		model rather than the DOM.
	-->
{:else if element.type === 'group'}
	<!-- Group: recurse into children. -->
	<div
		class="pptx-svelte-element pptx-svelte-group"
		style={styleToString(
				mergeStyles(
					getContainerStyle(element, zIndex),
					getShapeFillStrokeStyle(element),
					rootPointerEventsStyle,
				),
			)}
		data-element-id={element.id}
		data-pptx-element={elementMarked ? 'true' : undefined}
	>
		<!-- A group paints no fill/outline of its own, but `p:grpSpPr/a:effectLst`
		     DOES carry a shadow/glow/soft-edge for the group's own composite
		     raster (the `filter`/`overflow` merged into the style above from
		     `getShapeFillStrokeStyle`) and a reflection (parsed onto
		     `groupEffectStyle`) that mirrors the whole group subtree, so this
		     still needs mounting. -->
		<!-- Interaction-only hit target for a degenerate group; see `hitTarget`. -->
		{#if hitTarget}
			<div aria-hidden="true" data-pptx-hit-target="true" style={styleToString(hitTarget)}></div>
		{/if}
		<ShapeEffectOverlay {element} {mediaDataUrls} {zIndex} />
		{#each element.children ?? [] as child, i (child.id)}
			<ElementRenderer element={child} {mediaDataUrls} zIndex={i} {presenting} {interactive} {marked} {editTemplateMode} {editingElementId} {editable} {selectedElementIds} parentGroupFill={childParentGroupFill} {ontablecellcommit} {onsmartartnodecommit} {onsmartartnodefill} {onchartpointcommit} {ontableresizecolumns} {ontableresizerow} />
		{/each}
	</div>
{:else if isImageLike}
	<ImageBox {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if element.type === 'connector'}
	<ConnectorView {element} {mediaDataUrls} {zIndex} {animationState} interactive={elementInteractive} marked={elementMarked} />
{:else if element.type === 'table'}
	<TableView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {ontablecellcommit} {ontableresizecolumns} {ontableresizerow} {editable} {presenting} />
{:else if element.type === 'chart'}
	<ChartView {element} {mediaDataUrls} {zIndex} {animationState} interactive={elementInteractive} marked={elementMarked} selected={isSelected} {onchartpointcommit} {editable} {presenting} />
{:else if element.type === 'smartArt' && smartArt3D}
	<SmartArt3DView {element} {mediaDataUrls} {zIndex} {animationState} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if element.type === 'smartArt'}
	<SmartArtView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {animationState} {onsmartartnodecommit} {onsmartartnodefill} {editable} {presenting} />
{:else if element.type === 'media'}
	<MediaBox {element} {mediaDataUrls} {zIndex} {presenting} interactive={elementInteractive} marked={elementMarked} {editable} />
{:else if element.type === 'ink'}
	<InkView {element} {mediaDataUrls} {zIndex} {presenting} interactive={elementInteractive} marked={elementMarked} {editable} />
{:else if element.type === 'ole'}
	<OleView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if element.type === 'contentPart'}
	<ContentPartView {element} {mediaDataUrls} {zIndex} {presenting} interactive={elementInteractive} marked={elementMarked} {editable} />
{:else if element.type === 'zoom'}
	<ZoomView {element} {mediaDataUrls} {zIndex} {presenting} interactive={elementInteractive} marked={elementMarked} {editable} />
{:else if element.type === 'model3d'}
	<Model3dView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if hasEquation}
	<EquationView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if isShapeLike}
	<!-- Text / shape: shared fill/stroke/effects/geometry + rich text block. -->
	<div
		class="pptx-svelte-element pptx-svelte-shape"
		style={styleToString(mergeStyles(getShapeBoxStyle(element, zIndex, parentGroupFill, animationState?.animatesFill, animationState?.animatesStroke), rootPointerEventsStyle))}
		data-element-id={element.id}
		data-pptx-element={elementMarked ? 'true' : undefined}
	>
		<DuotoneFilterDefs {element} {mediaDataUrls} {zIndex} />
		<!-- Interaction-only hit target for a degenerate shape; see `hitTarget`. -->
		{#if hitTarget}
			<div aria-hidden="true" data-pptx-hit-target="true" style={styleToString(hitTarget)}></div>
		{/if}
		<!-- A font-style emphasis effect (Bold Flash, Bold Reveal, Underline,
		     Change Font Style/Size) overrides the runs' own inline
		     bold/italic/underline/size, which plain CSS inheritance cannot reach
		     (the runs declare those unconditionally). A literal `<style>` tag's
		     content is not reactive to a mustache expression (see `ContentPartView`'s
		     `INK_REPLAY_KEYFRAMES` precedent), so this uses the `svelte:element`
		     escape hatch instead. -->
		{#if textStyleOverrideCss}<svelte:element this={'style'}>{textStyleOverrideCss}</svelte:element>{/if}
		<ShapeEffectOverlay {element} {mediaDataUrls} {zIndex} />
		{#if extrusion.hasExtrusion}<Extrusion3D data={extrusion} />{/if}
		<!-- While this element is open in the inline text editor, its live text is
		     drawn by that overlay instead; rendering it here too duplicates it
		     underneath (issue #182). -->
		{#if !isBeingInlineEdited}
			{#if warpedText}
				<WordArtText {element} {mediaDataUrls} {zIndex} />
			{:else if hasText}
				<TextBlock
					{paragraphs}
					textStyle={styleToString(getTextBlockStyle(element))}
					elementId={element.id}
					subElementAnimStates={allAnimStates}
				/>
			{:else if promptDescriptor}
				<div
					class="pptx-svelte-placeholder-prompt"
					style={styleToString(mergeStyles(getTextBlockStyle(element), promptDescriptor.style))}
				>{promptDescriptor.text}</div>
			{/if}
		{/if}
	</div>
{:else}
	<PlaceholderElement {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{/if}

<!--
	A font-style emphasis effect (Bold Flash, Bold Reveal, Underline, Change
	Font Style/Size) overrides a table cell / chart title-label-legend /
	SmartArt node caption / connector caption's own inline or SVG-attribute
	styling, which plain CSS inheritance cannot reach. Rendered here, as a
	SIBLING of the branch above rather than nested inside it: the selector
	`buildTextStyleOverrideCss` builds (`[data-element-id="<id>"] ...`)
	matches anywhere in the document, and TableView/ConnectorView/
	SmartArtView/ChartView (the last not owned by this change) do not need
	their own copy of this wiring. The plain shape/text case keeps its own
	nested copy above (inside the `isShapeLike` branch) since that predates
	this change and its test asserts the nested position.
-->
{#if !isHidden && textStyleOverrideCss && (element.type === 'table' || element.type === 'chart' || element.type === 'smartArt' || element.type === 'connector')}
	<svelte:element this={'style'}>{textStyleOverrideCss}</svelte:element>
{/if}
