// packages/vue/src/viewer/components/ExportProgressModal.vue
<script setup lang="ts">
import { clampPercent } from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import DialogFooter from './DialogFooter.vue';

/**
 * ExportProgressModal - a centered, non-dismissable overlay shown while a
 * multi-slide export (PDF / GIF / WebM) runs. Vue counterpart of the React
 * `ExportProgressModal`.
 *
 * It deliberately does NOT close on backdrop click or Escape: an export in
 * flight should only end by completing, erroring, or the user pressing Cancel.
 * Cancel emits `cancel`; the parent owns cooperative cancellation (aborting the
 * `AbortController` the export loop checks between slides) and clearing `open`.
 *
 * Presentational only - the parent supplies `open`, `title`, `progress`
 * (0-100), and an optional `statusMessage`.
 */
const props = defineProps<{
	/** Whether the overlay is visible. */
	open: boolean;
	/** Heading shown at the top (e.g. "Export as PDF"). */
	title: string;
	/** Current progress, 0-100. */
	progress: number;
	/** Optional status line (e.g. "Rendering slide 3 of 10..."). */
	statusMessage?: string;
}>();

const emit = defineEmits<{
	(e: 'cancel'): void;
}>();

const { t } = useI18n();

const clampedProgress = computed(() => clampPercent(props.progress));

function onCancel(): void {
	emit('cancel');
}
</script>

<template>
	<Teleport to="body">
		<div
			v-if="open"
			class="pptx-vue-export-progress-backdrop fixed inset-0 z-[1200] flex items-center justify-center bg-black/60 backdrop-blur-sm"
			role="dialog"
			aria-modal="true"
			:aria-label="title"
		>
			<div
				class="pptx-vue-export-progress-panel w-[min(92vw,384px)] rounded-xl border border-border bg-popover p-6 text-foreground shadow-2xl"
			>
				<h3 class="mb-4 text-sm font-semibold">{{ title }}</h3>

				<div class="mb-3 h-2.5 w-full overflow-hidden rounded-full bg-muted">
					<div
						class="h-full rounded-full bg-primary transition-[width] duration-300 ease-out"
						:style="{ width: `${clampedProgress}%` }"
					/>
				</div>

				<div class="mb-4 flex items-center justify-between text-xs text-muted-foreground">
					<span>{{ statusMessage ?? t('pptx.export.processing') }}</span>
					<span class="tabular-nums">{{ clampedProgress }}%</span>
				</div>

				<div class="flex justify-end">
					<DialogFooter
						:actions="[{ id: 'cancel', label: t('pptx.export.cancel') }]"
						@action="onCancel"
					/>
				</div>
			</div>
		</div>
	</Teleport>
</template>

// packages/svelte/src/viewer/components/ExportProgressModal.svelte
<script lang="ts">
	/**
	 * ExportProgressModal: a centered, non-dismissable overlay shown while a
	 * multi-slide export (PDF / GIF / WebM) runs. Svelte port of Vue's
	 * `ExportProgressModal.vue` (same layout and theme tokens, scoped CSS over
	 * the `--pptx-*` variables instead of Tailwind utilities).
	 *
	 * It deliberately does NOT close on backdrop click or Escape: an export in
	 * flight should only end by completing, erroring, or the user pressing
	 * Cancel. `oncancel` aborts cooperatively (the export loops check the
	 * signal between slides).
	 */
	import DialogFooter from './DialogFooter.svelte';
	import { clampPercent } from 'pptx-viewer-shared';

	import { useTranslator } from '../../i18n/context';

	const {
		open,
		title,
		progress,
		statusMessage,
		oncancel,
	}: {
		open: boolean;
		title: string;
		progress: number;
		statusMessage?: string;
		oncancel: () => void;
	} = $props();

	const t = useTranslator();

	const clamped = $derived(clampPercent(progress));
</script>

{#if open}
	<div class="pptx-svelte-export-progress-backdrop" role="dialog" aria-modal="true" aria-label={title}>
		<div class="pptx-svelte-export-progress-panel">
			<h3>{title}</h3>
			<div class="pptx-svelte-export-progress-track">
				<div class="pptx-svelte-export-progress-fill" style={`width: ${clamped}%`}></div>
			</div>
			<div class="pptx-svelte-export-progress-status">
				<span>{statusMessage ?? t('pptx.export.processing')}</span>
				<span class="pptx-svelte-export-progress-pct">{clamped}%</span>
			</div>
			<div class="pptx-svelte-export-progress-actions">
				<DialogFooter actions={[{ id: 'cancel', label: t('pptx.export.cancel') }]} onaction={(id) => oncancel()} />
			</div>
		</div>
	</div>
{/if}

<style>
	.pptx-svelte-export-progress-backdrop {
		position: fixed;
		inset: 0;
		z-index: 1200;
		display: flex;
		align-items: center;
		justify-content: center;
		background: rgba(0, 0, 0, 0.6);
		backdrop-filter: blur(4px);
	}

	.pptx-svelte-export-progress-panel {
		width: min(92vw, 384px);
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: calc(var(--pptx-radius, 6px) + 6px);
		background: var(--pptx-popover, #111827);
		color: var(--pptx-popover-foreground, #f3f4f6);
		padding: 24px;
		box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
		font-family: system-ui, sans-serif;
	}

	.pptx-svelte-export-progress-panel h3 {
		margin: 0 0 16px;
		font-size: 14px;
		font-weight: 600;
	}

	.pptx-svelte-export-progress-track {
		height: 10px;
		width: 100%;
		overflow: hidden;
		border-radius: 9999px;
		background: var(--pptx-muted, #1f2937);
		margin-bottom: 12px;
	}

	.pptx-svelte-export-progress-fill {
		height: 100%;
		border-radius: 9999px;
		background: var(--pptx-primary, #6366f1);
		transition: width 0.3s ease-out;
	}

	.pptx-svelte-export-progress-status {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 16px;
		font-size: 12px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-export-progress-pct {
		font-variant-numeric: tabular-nums;
	}

	.pptx-svelte-export-progress-actions {
		display: flex;
		justify-content: flex-end;
	}
	</style>
