// packages/vue/src/viewer/components/HandoutMasterPanel.vue
<script setup lang="ts">
/**
 * HandoutMasterPanel: settings panel for the handout master.
 *
 * Vue port of the React `HandoutMasterPanel.tsx`. Lets the user pick the
 * slides-per-page layout (1/2/3/4/6/9) and shows the background swatch plus the
 * handout master's placeholders. The selected count is surfaced via an emit
 * (React used an `onSlidesPerPageChange` callback).
 *
 * Props : `{ handoutMaster, slidesPerPage }`
 * Emits : `slides-per-page-change: [count: number]`
 */
import type { PptxHandoutMaster } from 'pptx-viewer-core';
import { useI18n } from 'vue-i18n';

defineProps<{
	handoutMaster: PptxHandoutMaster | undefined;
	slidesPerPage: number;
}>();

const emit = defineEmits<{
	'slides-per-page-change': [count: number];
	'background-change': [color: string];
}>();

const { t } = useI18n();

const SLIDES_PER_PAGE_OPTIONS: readonly number[] = [1, 2, 3, 4, 6, 9];
</script>

<template>
	<div
		v-if="!handoutMaster"
		class="pptx-vue-handout-master-panel__empty"
		data-testid="handout-master-panel-empty"
	>
		{{ t('pptx.master.noHandoutMaster') }}
	</div>

	<div v-else class="pptx-vue-handout-master-panel">
		<section class="pptx-vue-handout-master-panel__card">
			<div class="pptx-vue-handout-master-panel__heading">
				{{ t('pptx.master.handoutSlidesPerPage') }}
			</div>
			<div class="pptx-vue-handout-master-panel__grid">
				<button
					v-for="count in SLIDES_PER_PAGE_OPTIONS"
					:key="count"
					type="button"
					class="pptx-vue-handout-master-panel__option"
					:class="{ 'pptx-vue-handout-master-panel__option--active': slidesPerPage === count }"
					:aria-pressed="slidesPerPage === count"
					:data-testid="`slides-per-page-${count}`"
					@click="emit('slides-per-page-change', count)"
				>
					{{ count }}
				</button>
			</div>
		</section>

		<section class="pptx-vue-handout-master-panel__card">
			<div class="pptx-vue-handout-master-panel__heading">
				{{ t('pptx.master.handoutBackground') }}
			</div>
			<input
				type="color"
				aria-label="Master background color"
				class="pptx-vue-handout-master-panel__swatch"
				data-testid="handout-master-bg-swatch"
				:value="handoutMaster.backgroundColor ?? '#ffffff'"
				@input="emit('background-change', ($event.target as HTMLInputElement).value)"
			/>
		</section>

		<section
			v-if="handoutMaster.placeholders && handoutMaster.placeholders.length > 0"
			class="pptx-vue-handout-master-panel__card"
		>
			<div class="pptx-vue-handout-master-panel__heading">
				{{ t('pptx.master.handoutPlaceholders') }}
			</div>
			<div class="pptx-vue-handout-master-panel__list">
				<div
					v-for="ph in handoutMaster.placeholders"
					:key="`${ph.type}-${ph.idx ?? 'default'}`"
					class="pptx-vue-handout-master-panel__row"
					data-testid="handout-master-placeholder"
				>
					<span class="pptx-vue-handout-master-panel__dot" />
					{{ ph.type }}
				</div>
			</div>
		</section>
	</div>
</template>

<style scoped>
.pptx-vue-handout-master-panel {
	display: flex;
	flex-direction: column;
	gap: 8px;
	padding: 0 4px;
}

.pptx-vue-handout-master-panel__empty {
	padding: 16px 8px;
	text-align: center;
	font-size: 12px;
	color: var(--pptx-vue-muted-foreground, #6b7280);
}

.pptx-vue-handout-master-panel__card {
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 6px;
	padding: 8px;
	background: rgba(0, 0, 0, 0.02);
}

.pptx-vue-handout-master-panel__heading {
	margin-bottom: 6px;
	font-size: 10px;
	color: var(--pptx-vue-muted-foreground, #6b7280);
}

.pptx-vue-handout-master-panel__grid {
	display: grid;
	grid-template-columns: repeat(3, 1fr);
	gap: 4px;
}

.pptx-vue-handout-master-panel__option {
	padding: 6px 8px;
	border: none;
	border-radius: 4px;
	background: rgba(0, 0, 0, 0.05);
	color: var(--pptx-vue-muted-foreground, #6b7280);
	font-size: 11px;
	font-weight: 500;
	cursor: pointer;
	transition:
		background 0.15s ease,
		color 0.15s ease;
}

.pptx-vue-handout-master-panel__option:hover {
	background: rgba(0, 0, 0, 0.08);
	color: var(--pptx-vue-foreground, #111827);
}

.pptx-vue-handout-master-panel__option--active {
	background: var(--pptx-vue-primary, #2563eb);
	color: #ffffff;
}

.pptx-vue-handout-master-panel__swatch {
	width: 100%;
	height: 32px;
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 4px;
}

.pptx-vue-handout-master-panel__list {
	display: flex;
	flex-direction: column;
	gap: 4px;
}

.pptx-vue-handout-master-panel__row {
	display: flex;
	align-items: center;
	gap: 8px;
	padding: 4px 6px;
	border-radius: 4px;
	background: rgba(0, 0, 0, 0.03);
	font-size: 10px;
	color: var(--pptx-vue-foreground, #111827);
}

.pptx-vue-handout-master-panel__dot {
	flex-shrink: 0;
	width: 8px;
	height: 8px;
	border-radius: 9999px;
	background: rgba(168, 85, 247, 0.6);
}
</style>

// packages/svelte/src/viewer/components/HandoutMasterPanel.svelte
<script lang="ts">
	import type { PptxHandoutMaster } from 'pptx-viewer-core';
	import { useTranslator } from '../../i18n/context';

	const { handoutMaster, slidesPerPage, onchange, onbackgroundchange } = $props<{
		handoutMaster: PptxHandoutMaster | undefined;
		slidesPerPage: number;
		onchange: (count: number) => void;
		onbackgroundchange: (color: string) => void;
	}>();
	const t = useTranslator();
	const options = [1, 2, 3, 4, 6, 9];
</script>

{#if handoutMaster}
	<section class="panel" data-testid="handout-master-panel">
		<div class="label">{t('pptx.master.handoutSlidesPerPage')}</div>
		<div class="options">
			{#each options as count}
				<button type="button" class:active={slidesPerPage === count} aria-pressed={slidesPerPage === count} onclick={() => onchange(count)}>{count}</button>
			{/each}
		</div>
		<div class="label">{t('pptx.master.handoutBackground')}</div>
		<input type="color" class="swatch" aria-label="Master background color" value={handoutMaster.backgroundColor ?? '#ffffff'} oninput={(event) => onbackgroundchange(event.currentTarget.value)} />
	</section>
{:else}<p class="empty">{t('pptx.master.noHandoutMaster')}</p>{/if}

<style>
	.panel { display:flex; flex-direction:column; gap:7px; padding:6px; }
	.label { color:var(--pptx-muted-foreground,#a5a5b5); font-size:10px; }
	.options { display:grid; grid-template-columns:repeat(3,1fr); gap:4px; }
	button { padding:5px; border:0; border-radius:4px; background:var(--pptx-accent,#33334d); color:inherit; cursor:pointer; }
	button.active { background:var(--pptx-primary,#6366f1); color:#fff; }
	button:focus-visible { outline:2px solid var(--pptx-ring,#6366f1); outline-offset:1px; }
	.swatch { height:32px; border:1px solid var(--pptx-border,#33334d); border-radius:5px; }
	.empty { padding:12px; color:var(--pptx-muted-foreground,#a5a5b5); font-size:12px; text-align:center; }
</style>
