// packages/vue/src/viewer/components/HeaderFooterPanel.vue
<script setup lang="ts">
import { X } from 'lucide-vue-next';
import type { PptxHeaderFooter } from 'pptx-viewer-core';
/**
 * HeaderFooterPanel: edit the presentation's header/footer placeholders.
 *
 * Vue port of the React `HeaderFooterPanel.tsx`, adapted to the Vue port's
 * data-driven contract: instead of a bundle of separate boolean/text props +
 * `onSetX` callbacks, this panel takes the real core `PptxHeaderFooter` object
 * and, on Apply, emits a fully-formed `update(next)` with the edited copy. The
 * host applies the change (e.g. to `PptxData.headerFooter`).
 *
 * Edits are held in a local draft (matching the Angular port) so toggling a
 * checkbox does not commit and close the dialog; only the Apply buttons do.
 *
 * Covers the visibility flags (date/time, slide number, header, footer) plus the
 * date/footer/header text fields and the date auto/fixed toggle.
 *
 * Props : `{ headerFooter: PptxHeaderFooter | undefined }`
 * Emits : `update: [next: PptxHeaderFooter]`, `close: []`
 */
import {
	cloneHeaderFooterDraft,
	isHeaderFooterDateTextVisible,
	isHeaderFooterFooterTextVisible,
	isHeaderFooterHeaderTextVisible,
	patchHeaderFooterDraft,
} from 'pptx-viewer-shared';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import DialogFooter from './DialogFooter.vue';

const props = defineProps<{
	headerFooter: PptxHeaderFooter | undefined;
}>();

const { t } = useI18n();

const emit = defineEmits<{
	update: [next: PptxHeaderFooter];
	close: [];
}>();

/** Local draft, re-seeded from the incoming prop each time the dialog opens. */
const draft = ref<PptxHeaderFooter>(cloneHeaderFooterDraft(props.headerFooter));
watch(
	() => props.headerFooter,
	(next) => {
		draft.value = cloneHeaderFooterDraft(next);
	},
);

function patch(changes: Partial<PptxHeaderFooter>): void {
	draft.value = patchHeaderFooterDraft(draft.value, changes);
}

function apply(): void {
	emit('update', draft.value);
	emit('close');
}

const showDateTime = computed(() => draft.value.hasDateTime ?? false);
const showSlideNumber = computed(() => draft.value.hasSlideNumber ?? false);
const showHeader = computed(() => draft.value.hasHeader ?? false);
const showFooter = computed(() => draft.value.hasFooter ?? false);
const dateTimeAuto = computed(() => draft.value.dateTimeAuto ?? false);
const showDateText = computed(() => isHeaderFooterDateTextVisible(draft.value));
const showHeaderText = computed(() => isHeaderFooterHeaderTextVisible(draft.value));
const showFooterText = computed(() => isHeaderFooterFooterTextVisible(draft.value));

function onToggleDateTime(event: Event): void {
	patch({ hasDateTime: (event.target as HTMLInputElement).checked });
}
function onToggleSlideNumber(event: Event): void {
	patch({ hasSlideNumber: (event.target as HTMLInputElement).checked });
}
function onToggleHeader(event: Event): void {
	patch({ hasHeader: (event.target as HTMLInputElement).checked });
}
function onToggleFooter(event: Event): void {
	patch({ hasFooter: (event.target as HTMLInputElement).checked });
}
function onToggleDateAuto(event: Event): void {
	patch({ dateTimeAuto: (event.target as HTMLInputElement).checked });
}
function onHeaderText(event: Event): void {
	patch({ headerText: (event.target as HTMLInputElement).value });
}
function onFooterText(event: Event): void {
	patch({ footerText: (event.target as HTMLInputElement).value });
}
function onDateText(event: Event): void {
	patch({ dateTimeText: (event.target as HTMLInputElement).value });
}
</script>

<template>
	<div
		class="pptx-vue-header-footer-panel"
		role="dialog"
		:aria-label="t('pptx.headerFooter.title')"
	>
		<header class="pptx-vue-header-footer-panel__header">
			<h2 class="pptx-vue-header-footer-panel__title">{{ t('pptx.headerFooter.title') }}</h2>
			<button
				type="button"
				class="pptx-vue-header-footer-panel__close"
				:aria-label="t('pptx.headerFooter.close')"
				data-testid="header-footer-close"
				@click="emit('close')"
			>
				<X class="h-4 w-4" aria-hidden="true" />
			</button>
		</header>

		<div class="pptx-vue-header-footer-panel__body">
			<label class="pptx-vue-header-footer-panel__row">
				<pptx-ui-checkbox
					data-testid="hf-date-time"
					:checked="showDateTime"
					@change="onToggleDateTime"
				/>
				<span>{{ t('pptx.headerFooter.dateAndTime') }}</span>
			</label>

			<div v-if="showDateTime" class="pptx-vue-header-footer-panel__sub">
				<label class="pptx-vue-header-footer-panel__row">
					<pptx-ui-checkbox
						data-testid="hf-date-auto"
						:checked="dateTimeAuto"
						@change="onToggleDateAuto"
					/>
					<span>{{ t('pptx.headerFooter.updateAutomatically') }}</span>
				</label>
				<input
					v-if="showDateText"
					type="text"
					class="pptx-vue-header-footer-panel__input"
					:placeholder="t('pptx.headerFooter.fixedDate')"
					data-testid="hf-date-text"
					:value="draft.dateTimeText ?? ''"
					@input="onDateText"
				/>
			</div>

			<label class="pptx-vue-header-footer-panel__row">
				<pptx-ui-checkbox
					data-testid="hf-slide-number"
					:checked="showSlideNumber"
					@change="onToggleSlideNumber"
				/>
				<span>{{ t('pptx.headerFooter.slideNumber') }}</span>
			</label>

			<label class="pptx-vue-header-footer-panel__row">
				<pptx-ui-checkbox data-testid="hf-header" :checked="showHeader" @change="onToggleHeader" />
				<span>{{ t('pptx.field.header') }}</span>
			</label>

			<div v-if="showHeaderText" class="pptx-vue-header-footer-panel__sub">
				<input
					type="text"
					class="pptx-vue-header-footer-panel__input"
					:placeholder="t('pptx.headerFooter.headerText')"
					data-testid="hf-header-text"
					:value="draft.headerText ?? ''"
					@input="onHeaderText"
				/>
			</div>

			<label class="pptx-vue-header-footer-panel__row">
				<pptx-ui-checkbox data-testid="hf-footer" :checked="showFooter" @change="onToggleFooter" />
				<span>{{ t('pptx.headerFooter.footer') }}</span>
			</label>

			<div v-if="showFooterText" class="pptx-vue-header-footer-panel__sub">
				<input
					type="text"
					class="pptx-vue-header-footer-panel__input"
					:placeholder="t('pptx.headerFooter.footerPlaceholder')"
					data-testid="hf-footer-text"
					:value="draft.footerText ?? ''"
					@input="onFooterText"
				/>
			</div>
		</div>

		<footer class="pptx-vue-header-footer-panel__footer">
			<DialogFooter
				:actions="[
					{ id: 'applyAll', label: t('pptx.headerFooter.applyToAll'), testId: 'hf-apply-all' },
					{
						id: 'applyCurrent',
						label: t('pptx.headerFooter.applyToCurrent'),
						variant: 'primary',
						testId: 'hf-apply-current',
					},
				]"
				@action="apply"
			/>
		</footer>
	</div>
</template>

<style scoped>
.pptx-vue-header-footer-panel {
	display: flex;
	flex-direction: column;
	width: 100%;
	max-width: 360px;
	background: var(--pptx-vue-background, #ffffff);
	color: var(--pptx-vue-foreground, #111827);
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: var(--pptx-vue-radius, 8px);
}

.pptx-vue-header-footer-panel__header {
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 12px 16px;
	border-bottom: 1px solid var(--pptx-vue-border, #e5e7eb);
}

.pptx-vue-header-footer-panel__title {
	margin: 0;
	font-size: 14px;
	font-weight: 600;
}

.pptx-vue-header-footer-panel__close {
	width: 24px;
	height: 24px;
	padding: 0;
	border: none;
	border-radius: 4px;
	background: transparent;
	color: var(--pptx-vue-muted-foreground, #6b7280);
	font-size: 18px;
	line-height: 1;
	cursor: pointer;
}

.pptx-vue-header-footer-panel__close:hover {
	background: var(--pptx-vue-muted, #f3f4f6);
	color: var(--pptx-vue-foreground, #111827);
}

.pptx-vue-header-footer-panel__body {
	display: flex;
	flex-direction: column;
	gap: 14px;
	padding: 16px;
}

.pptx-vue-header-footer-panel__row {
	display: flex;
	align-items: center;
	gap: 10px;
	font-size: 12px;
	cursor: pointer;
	user-select: none;
}

.pptx-vue-header-footer-panel__sub {
	display: flex;
	flex-direction: column;
	gap: 8px;
	padding-left: 24px;
}

.pptx-vue-header-footer-panel__input {
	width: 100%;
	padding: 6px 10px;
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 4px;
	background: var(--pptx-vue-muted, #f9fafb);
	color: var(--pptx-vue-foreground, #111827);
	font-size: 12px;
	box-sizing: border-box;
}

.pptx-vue-header-footer-panel__input:focus {
	outline: none;
	border-color: var(--pptx-vue-primary, #2563eb);
}

.pptx-vue-header-footer-panel__footer {
	display: flex;
	align-items: center;
	justify-content: flex-end;
	gap: 8px;
	padding: 12px 16px;
	border-top: 1px solid var(--pptx-vue-border, #e5e7eb);
}
</style>

// packages/svelte/src/viewer/components/HeaderFooterPanel.svelte
<script lang="ts">
	import DialogFooter from './DialogFooter.svelte';
	import CalendarDays from '@lucide/svelte/icons/calendar-days';
	import Hash from '@lucide/svelte/icons/hash';
	import Text from '@lucide/svelte/icons/text';
	import X from '@lucide/svelte/icons/x';
	import type { PptxHeaderFooter } from 'pptx-viewer-core';
	import { cloneHeaderFooterDraft, patchHeaderFooterDraft } from 'pptx-viewer-shared';
	import { untrack } from 'svelte';
	import { useTranslator } from '../../i18n/context';

	const { value, onclose, onapply }: { value: PptxHeaderFooter; onclose: () => void; onapply: (next: PptxHeaderFooter) => void } = $props();
	const t = useTranslator();
	let draft = $state<PptxHeaderFooter>(cloneHeaderFooterDraft(untrack(() => value)));
	const toggle = (key: keyof PptxHeaderFooter, checked: boolean) => { draft = patchHeaderFooterDraft(draft, { [key]: checked }); };
</script>
<div class="backdrop"><button class="scrim" type="button" aria-label={t('pptx.headerFooter.close')} onclick={onclose}></button>
	<!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
	<section role="dialog" tabindex="-1" aria-modal="true" aria-labelledby="hf-title"><header><h2 id="hf-title">{t('pptx.headerFooter.title')}</h2><button type="button" aria-label={t('pptx.headerFooter.close')} onclick={onclose}><X size={16} aria-hidden="true" /></button></header>
		<div class="body"><label><pptx-ui-checkbox checked={draft.hasDateTime ?? false} onchange={(event) => toggle('hasDateTime', event.currentTarget.checked)}></pptx-ui-checkbox><CalendarDays size={14} aria-hidden="true" /> {t('pptx.headerFooter.dateAndTime')}</label><label><pptx-ui-checkbox checked={draft.hasSlideNumber ?? false} onchange={(event) => toggle('hasSlideNumber', event.currentTarget.checked)}></pptx-ui-checkbox><Hash size={14} aria-hidden="true" /> {t('pptx.headerFooter.slideNumber')}</label><label><pptx-ui-checkbox checked={draft.hasFooter ?? false} onchange={(event) => toggle('hasFooter', event.currentTarget.checked)}></pptx-ui-checkbox><Text size={14} aria-hidden="true" /> {t('pptx.headerFooter.footer')}</label>{#if draft.hasFooter}<input type="text" aria-label={t('pptx.headerFooter.footer')} placeholder={t('pptx.headerFooter.footerPlaceholder')} value={draft.footerText ?? ''} oninput={(event) => (draft = patchHeaderFooterDraft(draft, { footerText: event.currentTarget.value }))} />{/if}</div>
		<footer><DialogFooter actions={[{ id: 'applyAll', label: t('pptx.headerFooter.applyToAll') }, { id: 'applyCurrent', label: t('pptx.headerFooter.applyToCurrent'), variant: 'primary' }]} onaction={() => { onapply(draft); onclose(); }} /></footer>
	</section>
</div>
<style>
	.backdrop{position:fixed;inset:0;z-index:1200;display:grid;place-items:center;background:#0007}.scrim{position:absolute;inset:0;border:0;background:transparent}section{position:relative;width:min(390px,calc(100vw - 32px));border:1px solid var(--pptx-border,#3f3f52);border-radius:11px;background:var(--pptx-card,#1e1e2e);box-shadow:0 24px 70px #0009}header,footer{display:flex;align-items:center;justify-content:space-between;padding:13px 16px;border-bottom:1px solid var(--pptx-border,#3f3f52)}h2{margin:0;font-size:14px}.body{display:grid;gap:14px;padding:18px}.body label{display:flex;align-items:center;gap:7px;font-size:12px}.body input[type=checkbox]{accent-color:var(--pptx-primary,#c43b32)}.body input[type=text]{margin-left:24px;border:1px solid var(--pptx-border,#3f3f52);border-radius:6px;padding:8px;background:var(--pptx-muted,#2a2a3d);color:inherit}button{border:1px solid var(--pptx-border,#3f3f52);border-radius:6px;padding:6px 10px;background:var(--pptx-muted,#2a2a3d);color:inherit}header button{display:inline-flex;align-items:center;justify-content:center;border:0;background:transparent}footer{justify-content:flex-end;gap:8px;border-top:1px solid var(--pptx-border,#3f3f52);border-bottom:0}@media(max-width:600px){section{position:fixed;inset:auto 0 0;width:100%;border-radius:16px 16px 0 0}}
</style>
