// packages/vue/src/viewer/components/PresentationTouchControls.vue
<script setup lang="ts">
/**
 * PresentationTouchControls: always-visible, touch-friendly controls for
 * presentation (slide-show) mode.
 *
 * The auto-hiding mouse `PresentationToolbar` only reveals itself on pointer
 * movement, so on a touch device there is no way to exit the slideshow or step
 * between slides (a phone has no Escape key). This overlay fills that gap: a
 * persistent close button plus large prev / next navigation buttons, each at
 * least 44px and offset by the device safe-area insets so they clear notches
 * and rounded corners.
 *
 * Rendered only on touch-capable devices so it never clutters the desktop UI
 * (which keeps the auto-hiding mouse toolbar). Every control stops event
 * propagation so a tap on it never falls through to the slide tap-advance.
 *
 * Mirrors the React `PresentationTouchControls`
 * (`packages/react/src/viewer/components/PresentationTouchControls.tsx`).
 */
import { ChevronLeft, ChevronRight, X } from 'lucide-vue-next';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { useIsMobile } from '../composables/useIsMobile';

const { t } = useI18n();

const props = defineProps<{
	/** Zero-based index of the current presentation slide. */
	currentSlideIndex: number;
	/** Total number of slides. */
	totalSlides: number;
}>();

const emit = defineEmits<{
	/** Navigate next (1) / previous (-1). */
	(e: 'move', direction: 1 | -1): void;
	/** Exit the slideshow. */
	(e: 'end'): void;
}>();

const { isTouchDevice } = useIsMobile();

const atFirst = computed(() => props.currentSlideIndex <= 0);
const atLast = computed(() => props.currentSlideIndex >= props.totalSlides - 1);
const counterLabel = computed(() =>
	props.totalSlides === 0 ? '0 / 0' : `${props.currentSlideIndex + 1} / ${props.totalSlides}`,
);
</script>

<template>
	<template v-if="isTouchDevice">
		<!-- Close (top-right, safe-area aware) -->
		<button
			type="button"
			class="pptx-vue-pt-btn pptx-vue-pt-close"
			:aria-label="t('pptx.presenter.endPresentation')"
			@click.stop="emit('end')"
			@touchend.stop.prevent="emit('end')"
		>
			<X :size="22" aria-hidden="true" />
		</button>

		<!-- Previous (left edge) -->
		<button
			type="button"
			class="pptx-vue-pt-btn pptx-vue-pt-prev"
			:aria-label="t('pptx.mobileBar.previousSlide')"
			:disabled="atFirst"
			@click.stop="emit('move', -1)"
			@touchend.stop.prevent="emit('move', -1)"
		>
			<ChevronLeft :size="26" aria-hidden="true" />
		</button>

		<!-- Next (right edge) -->
		<button
			type="button"
			class="pptx-vue-pt-btn pptx-vue-pt-next"
			:aria-label="t('pptx.mobileBar.nextSlide')"
			:disabled="atLast"
			@click.stop="emit('move', 1)"
			@touchend.stop.prevent="emit('move', 1)"
		>
			<ChevronRight :size="26" aria-hidden="true" />
		</button>

		<!-- Slide counter (bottom-centre, safe-area aware) -->
		<span class="pptx-vue-pt-counter">{{ counterLabel }}</span>
	</template>
</template>

<style scoped>
.pptx-vue-pt-btn {
	position: fixed;
	z-index: 2147483002;
	display: flex;
	align-items: center;
	justify-content: center;
	width: 44px;
	height: 44px;
	min-width: 44px;
	min-height: 44px;
	border: none;
	border-radius: 50%;
	background-color: rgba(0, 0, 0, 0.55);
	color: #ffffff;
	line-height: 1;
	cursor: pointer;
	pointer-events: auto;
	touch-action: manipulation;
	box-shadow: 0 2px 8px rgba(0, 0, 0, 0.35);
}

.pptx-vue-pt-btn:active {
	background-color: rgba(0, 0, 0, 0.75);
}

.pptx-vue-pt-btn:disabled {
	opacity: 0.3;
	cursor: not-allowed;
}

.pptx-vue-pt-close {
	top: calc(env(safe-area-inset-top, 0px) + 0.5rem);
	right: calc(env(safe-area-inset-right, 0px) + 0.5rem);
}

.pptx-vue-pt-prev,
.pptx-vue-pt-next {
	top: 50%;
	transform: translateY(-50%);
}

.pptx-vue-pt-prev {
	left: calc(env(safe-area-inset-left, 0px) + 0.5rem);
}

.pptx-vue-pt-next {
	right: calc(env(safe-area-inset-right, 0px) + 0.5rem);
}

.pptx-vue-pt-counter {
	position: fixed;
	z-index: 2147483002;
	bottom: calc(env(safe-area-inset-bottom, 0px) + 0.5rem);
	left: 50%;
	transform: translateX(-50%);
	padding: 4px 12px;
	border-radius: 999px;
	background-color: rgba(0, 0, 0, 0.55);
	color: #ffffff;
	font-size: 12px;
	font-variant-numeric: tabular-nums;
	pointer-events: none;
	user-select: none;
}
</style>

// packages/svelte/src/viewer/components/PresentationTouchControls.svelte
<script lang="ts">
	/** Persistent safe-area-aware controls for touch presentation mode. */
	import { buildPresentationTouchControlState } from 'pptx-viewer-shared';

	import { useTranslator } from '../../i18n/context';

	const { current, total, onprev, onnext, onexit }: {
		current: number;
		total: number;
		onprev: () => void;
		onnext: () => void;
		onexit: () => void;
	} = $props();

	const t = useTranslator();
	const state = $derived(buildPresentationTouchControlState(current, total));

	function stop(event: Event): void {
		event.stopPropagation();
	}
</script>

<div class="pptx-svelte-presentation-touch-controls" aria-label={t('pptx.statusBar.slideShow')}>
	<button
		type="button"
		class="pptx-svelte-presentation-touch-exit"
		aria-label={t('pptx.presenter.endPresentation')}
		onpointerdown={stop}
		onclick={(event) => { stop(event); onexit(); }}
	>×</button>
	<button
		type="button"
		class="pptx-svelte-presentation-touch-prev"
		aria-label={t('pptx.presenter.previousSlide')}
		disabled={state.previousDisabled}
		onpointerdown={stop}
		onclick={(event) => { stop(event); onprev(); }}
	><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M10.5 3 5.5 8l5 5" /></svg></button>
	<button
		type="button"
		class="pptx-svelte-presentation-touch-next"
		aria-label={t('pptx.presenter.nextSlide')}
		disabled={state.nextDisabled}
		onpointerdown={stop}
		onclick={(event) => { stop(event); onnext(); }}
	><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M5.5 3 10.5 8l-5 5" /></svg></button>
	<span class="pptx-svelte-presentation-touch-counter" aria-live="polite">
		{state.counterLabel}
	</span>
</div>

<style>
	.pptx-svelte-presentation-touch-controls { display: none; }
	@media (any-pointer: coarse) {
		.pptx-svelte-presentation-touch-controls { display: contents; }
		.pptx-svelte-presentation-touch-controls button { position: fixed; z-index: 90; display: flex; align-items: center; justify-content: center; width: 44px; height: 44px; padding: 0; border: 0; border-radius: 999px; background: rgb(0 0 0 / 55%); box-shadow: 0 4px 14px rgb(0 0 0 / 30%); color: #fff; font: 28px/1 system-ui, sans-serif; touch-action: manipulation; }
		.pptx-svelte-presentation-touch-controls button:active { background: rgb(0 0 0 / 75%); }
		.pptx-svelte-presentation-touch-controls button:disabled { opacity: .3; }
		.pptx-svelte-presentation-touch-controls svg { width: 26px; height: 26px; fill: none; stroke: currentColor; stroke-width: 1.7; stroke-linecap: round; stroke-linejoin: round; }
		.pptx-svelte-presentation-touch-exit { top: calc(env(safe-area-inset-top, 0px) + 8px); right: calc(env(safe-area-inset-right, 0px) + 8px); }
		.pptx-svelte-presentation-touch-prev { top: 50%; left: calc(env(safe-area-inset-left, 0px) + 8px); transform: translateY(-50%); }
		.pptx-svelte-presentation-touch-next { top: 50%; right: calc(env(safe-area-inset-right, 0px) + 8px); transform: translateY(-50%); }
		.pptx-svelte-presentation-touch-counter { position: fixed; z-index: 90; bottom: calc(env(safe-area-inset-bottom, 0px) + 8px); left: 50%; padding: 4px 12px; border-radius: 999px; background: rgb(0 0 0 / 55%); color: #fff; font: 12px ui-monospace, monospace; font-variant-numeric: tabular-nums; pointer-events: none; transform: translateX(-50%); }
	}
</style>
