// packages/vue/src/viewer/components/SelectionPane.vue
<script setup lang="ts">
import { Eye, EyeOff, GripVertical } from 'lucide-vue-next';
import { hasTextProperties } from 'pptx-viewer-core';
import type { PptxElement } from 'pptx-viewer-core';
import { restoreEditorKeyboardFocus } from 'pptx-viewer-shared';
import { computed, nextTick, ref } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * SelectionPane: lists every element on the active slide with visibility
 * toggles, drag-to-reorder (z-order), and double-click-to-rename. Vue port of
 * the React `SelectionPane.tsx`. The pane is presentational: it emits
 * `select`, `toggle-visibility`, `reorder`, and `rename`; the host routes
 * those through the history-tracked editor operations so they undo/redo like
 * any other edit.
 */
const props = defineProps<{
	elements: PptxElement[];
	selectedIds: string[];
	canEdit: boolean;
}>();

const emit = defineEmits<{
	select: [id: string];
	'toggle-visibility': [id: string];
	reorder: [payload: { from: number; to: number }];
	rename: [payload: { id: string; name: string | undefined }];
	close: [];
}>();

const { t } = useI18n();

const TYPE_LABEL_KEYS: Record<string, string> = {
	text: 'pptx.elementType.textBox',
	shape: 'pptx.elementType.shape',
	connector: 'pptx.elementType.connector',
	image: 'pptx.elementType.image',
	picture: 'pptx.elementType.picture',
	chart: 'pptx.elementType.chart',
	table: 'pptx.elementType.table',
	smartArt: 'pptx.elementType.smartArt',
	media: 'pptx.elementType.media',
	group: 'pptx.elementType.group',
	ink: 'pptx.elementType.ink',
	ole: 'pptx.elementType.object',
	unknown: 'pptx.elementType.object',
};

function displayName(element: PptxElement, index: number): string {
	if (element.name && element.name.trim().length > 0) {
		return element.name.trim();
	}
	if (hasTextProperties(element) && element.text && element.text.trim().length > 0) {
		return element.text.trim().slice(0, 32);
	}
	const typeKey = TYPE_LABEL_KEYS[element.type] ?? 'pptx.elementType.object';
	return t('pptx.selectionPane.elementLabel', { type: t(typeKey), number: index + 1 });
}

// -- Inline rename (double-click the row label, like React) ------------------
const editingId = ref<string | null>(null);
const editDraft = ref('');
const renameInputRef = ref<HTMLInputElement | null>(null);
/** Function ref: a string ref inside `v-for` would collect into an array. */
function setRenameInput(el: unknown): void {
	renameInputRef.value = el instanceof HTMLInputElement ? el : null;
}
// The display name the rename input was seeded with: an unedited commit (blur
// or Enter without typing) must not write that fallback label into the element
// as its name. Mirrors React's `editSeedRef`.
let editSeed = '';

function startRename(element: PptxElement, index: number): void {
	if (!props.canEdit) {
		return;
	}
	editingId.value = element.id;
	editDraft.value = displayName(element, index);
	editSeed = editDraft.value;
	void nextTick(() => {
		renameInputRef.value?.focus();
		renameInputRef.value?.select();
	});
}

/**
 * Give the keyboard back to the viewer root before the input unmounts.
 *
 * Without this, focus lands on `document.body` when the input goes away and
 * the viewer (which listens for `keydown` on its own root) never sees the
 * Ctrl+Z that undoes the rename. Shared, because three bindings had it.
 */
function releaseRenameFocus(): void {
	restoreEditorKeyboardFocus(renameInputRef.value);
}

/** Commit the trimmed draft: non-empty renames, empty clears the name. */
function commitRename(element: PptxElement): void {
	if (editingId.value !== element.id) {
		return;
	}
	// Clear first: focusing the root blurs the input, and the `blur` handler
	// re-enters here. With `editingId` already null that re-entry is a no-op.
	editingId.value = null;
	releaseRenameFocus();
	const trimmed = editDraft.value.trim();
	// Unedited commit: keep whatever the element had (in particular, do not
	// persist a "Shape 3"-style fallback label as a real name).
	if (trimmed === editSeed.trim()) {
		return;
	}
	emit('rename', { id: element.id, name: trimmed.length > 0 ? trimmed : undefined });
}

/** Escape: drop the draft without emitting (clearing first disarms blur). */
function cancelRename(): void {
	editingId.value = null;
	releaseRenameFocus();
}

// Top-most element first (reverse of paint order), matching PowerPoint.
const rows = computed(() =>
	props.elements
		.map((element, index) => ({ element, index }))
		.slice()
		.reverse(),
);

const dragIndex = ref<number | null>(null);
const dragOverIndex = ref<number | null>(null);

function onDragStart(index: number): void {
	dragIndex.value = index;
}

function onDragOver(event: DragEvent, index: number): void {
	event.preventDefault();
	if (dragIndex.value !== null && dragIndex.value !== index) {
		dragOverIndex.value = index;
	}
}

function onDrop(targetIndex: number): void {
	const from = dragIndex.value;
	dragIndex.value = null;
	dragOverIndex.value = null;
	if (from === null || from === targetIndex) {
		return;
	}
	emit('reorder', { from, to: targetIndex });
}
</script>

<template>
	<div class="flex h-full w-56 flex-col border-l border-border bg-popover" data-pptx-selection-pane>
		<div class="flex items-center justify-between border-b border-border px-3 py-2">
			<span class="text-xs font-medium text-foreground">{{ t('pptx.selectionPane.heading') }}</span>
			<button
				type="button"
				class="text-xs text-muted-foreground hover:text-foreground"
				:title="t('pptx.selectionPane.close')"
				@click="emit('close')"
			>
				&times;
			</button>
		</div>
		<div class="flex-1 overflow-y-auto py-1">
			<div v-if="rows.length === 0" class="px-3 py-4 text-xs italic text-muted-foreground">
				{{ t('pptx.selectionPane.noObjects') }}
			</div>
			<div
				v-for="{ element, index } in rows"
				v-else
				:key="element.id"
				:draggable="props.canEdit && editingId !== element.id"
				class="flex cursor-pointer items-center gap-1.5 px-2 py-1 text-xs transition-colors"
				:class="[
					props.selectedIds.includes(element.id)
						? 'bg-primary/30 text-primary'
						: 'text-foreground hover:bg-muted',
					dragOverIndex === index ? 'border-t-2 border-primary' : '',
				]"
				@click="emit('select', element.id)"
				@dragstart="onDragStart(index)"
				@dragover="onDragOver($event, index)"
				@drop="onDrop(index)"
				@dragend="
					dragIndex = null;
					dragOverIndex = null;
				"
			>
				<GripVertical
					v-if="props.canEdit"
					class="h-3 w-3 flex-shrink-0 cursor-grab text-muted-foreground"
				/>
				<span
					class="flex-1 truncate"
					data-pptx-selection-name
					@dblclick.stop="startRename(element, index)"
				>
					<input
						v-if="editingId === element.id"
						:ref="setRenameInput"
						type="text"
						:aria-label="t('pptx.selectionPane.renameElement')"
						:value="editDraft"
						class="w-full rounded border border-border bg-muted px-1 py-0.5 text-xs outline-none"
						@input="editDraft = ($event.target as HTMLInputElement).value"
						@blur="commitRename(element)"
						@keydown.enter="commitRename(element)"
						@keydown.escape="cancelRename"
						@click.stop
					/>
					<template v-else>{{ displayName(element, index) }}</template>
				</span>
				<button
					type="button"
					class="flex-shrink-0 text-muted-foreground hover:text-foreground"
					:title="element.hidden ? t('pptx.selectionPane.show') : t('pptx.selectionPane.hide')"
					@click.stop="emit('toggle-visibility', element.id)"
				>
					<EyeOff v-if="element.hidden" class="h-3.5 w-3.5" />
					<Eye v-else class="h-3.5 w-3.5 opacity-50" />
				</button>
			</div>
		</div>
	</div>
</template>

// packages/svelte/src/viewer/components/SelectionPane.svelte
<script lang="ts">
	import BringToFront from '@lucide/svelte/icons/bring-to-front';
	import Eye from '@lucide/svelte/icons/eye';
	import EyeOff from '@lucide/svelte/icons/eye-off';
	import SendToBack from '@lucide/svelte/icons/send-to-back';
	import X from '@lucide/svelte/icons/x';
	import type { PptxElement } from 'pptx-viewer-core';
	import { isElementHidden, restoreEditorKeyboardFocus } from 'pptx-viewer-shared';
	import type { EditorState } from '../editor/editor-state.svelte'; import { useTranslator } from '../../i18n/context';

	const { editor, onclose }: { editor: EditorState; onclose: () => void } = $props(); const t = useTranslator();
	const elements = $derived(editor.activeElements);

	/**
	 * Flip an element's Selection Pane visibility. Svelte was the only binding
	 * whose pane listed objects without the eye toggle the other four ship, so
	 * hiding a shape was simply unreachable here.
	 */
	function toggleHidden(id: string, hidden: boolean): void {
		editor.applyElementPatch(id, { hidden: !hidden });
	}

	// ── Inline rename (double-click a row's name label, as in React) ────────
	let renamingId = $state<string | null>(null);
	let renameValue = $state('');
	let renameInput = $state<HTMLInputElement | null>(null);

	function beginRename(element: PptxElement): void {
		renamingId = element.id;
		renameValue = element.name ?? '';
	}
	/**
	 * Give the keyboard back to the viewer root before the input goes away.
	 * Focus would otherwise fall to `document.body`, which is outside the root
	 * this binding listens on, and the Ctrl+Z that undoes the rename would be
	 * swallowed. Shared (`restoreEditorKeyboardFocus`), because three bindings
	 * shipped the same hole.
	 */
	function releaseRenameFocus(): void {
		restoreEditorKeyboardFocus(renameInput);
	}
	/** Commit the trimmed name through the history-integrated patch channel. */
	function commitRename(): void {
		if (renamingId === null) { return; }
		const id = renamingId;
		// Clear first: focusing the root blurs the input, which re-enters this
		// handler through `onblur`; a null `renamingId` makes that a no-op.
		renamingId = null;
		releaseRenameFocus();
		const name = renameValue.trim();
		editor.applyElementPatch(id, { name: name.length > 0 ? name : undefined });
	}
	function cancelRename(): void {
		renamingId = null;
		releaseRenameFocus();
	}
	function renameKeydown(event: KeyboardEvent): void {
		if (event.key === 'Enter') { event.preventDefault(); commitRename(); }
		else if (event.key === 'Escape') { event.stopPropagation(); cancelRename(); }
	}
	/** Svelte action: focus + select the rename input the moment it mounts. */
	function autofocus(node: HTMLInputElement): void {
		renameInput = node;
		node.focus();
		node.select();
	}
</script>
<aside class="pane" data-pptx-selection-pane aria-label={t('pptx.ribbon.selectionPane')}><header><h2>{t('pptx.ribbon.selectionPane')}</h2><button aria-label={t('pptx.common.close')} onclick={onclose}><X size={16} aria-hidden="true" /></button></header><div>{#each [...elements].reverse() as element, index}<div class="row" class:selected={editor.selection.ids.includes(element.id)}>{#if renamingId === element.id}<input class="rename" type="text" bind:value={renameValue} aria-label={t('pptx.selectionPane.renameElement')} use:autofocus onkeydown={renameKeydown} onblur={commitRename} />{:else}<button class="name" onclick={() => editor.select(element.id)} ondblclick={() => beginRename(element)}><span data-pptx-selection-name>{element.name || `${element.type} ${elements.length - index}`}</span><i>{element.type}</i></button>{/if}<button class="eye" title={isElementHidden(element) ? t('pptx.selectionPane.showElement') : t('pptx.selectionPane.hideElement')} aria-label={isElementHidden(element) ? t('pptx.selectionPane.showElement') : t('pptx.selectionPane.hideElement')} aria-pressed={isElementHidden(element)} onclick={() => toggleHidden(element.id, isElementHidden(element))}>{#if isElementHidden(element)}<EyeOff size={14} aria-hidden="true" />{:else}<Eye size={14} aria-hidden="true" />{/if}</button></div>{:else}<p>{t('pptx.statusBar.noSlides')}</p>{/each}</div><footer><button title={t('pptx.arrange.bringToFront')} aria-label={t('pptx.arrange.bringToFront')} disabled={!editor.selectedElementId} onclick={() => editor.reorderSelected('front')}><BringToFront size={14} aria-hidden="true" /></button><button title={t('pptx.arrange.sendToBack')} aria-label={t('pptx.arrange.sendToBack')} disabled={!editor.selectedElementId} onclick={() => editor.reorderSelected('back')}><SendToBack size={14} aria-hidden="true" /></button></footer></aside>
<style>.pane{position:absolute;z-index:45;top:0;right:0;bottom:0;width:260px;border-left:1px solid var(--pptx-border,#3f3f52);background:var(--pptx-card,#1e1e2e);box-shadow:-12px 0 35px #0006}header,footer{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;border-bottom:1px solid var(--pptx-border,#3f3f52)}h2{margin:0;font-size:12px}header button{display:inline-flex;align-items:center;justify-content:center;border:0;background:transparent;color:inherit}.pane>div{display:grid;gap:4px;overflow:auto;padding:8px}.row{display:flex;align-items:stretch;gap:4px;border:1px solid transparent;border-radius:5px;background:var(--pptx-muted,#2a2a3d)}.row.selected{border-color:var(--pptx-primary,#c43b32)}.row button{border:0;background:transparent;color:inherit;font-size:11px}.row .name{display:flex;flex:1;justify-content:space-between;gap:8px;min-width:0;padding:8px;text-align:left}.row .name span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row .rename{flex:1;min-width:0;margin:4px;padding:3px 5px;border:1px solid var(--pptx-primary,#c43b32);border-radius:4px;background:var(--pptx-background,#11111b);color:inherit;font:inherit;font-size:11px}.row .eye{display:inline-flex;flex-shrink:0;align-items:center;justify-content:center;padding:0 8px}.row .eye[aria-pressed='false']{opacity:.5}i{color:var(--pptx-muted-foreground,#94a3b8);font-style:normal}footer{justify-content:flex-end;gap:5px;border-top:1px solid var(--pptx-border,#3f3f52);border-bottom:0}footer button{display:inline-flex;align-items:center;justify-content:center;border:1px solid var(--pptx-border,#3f3f52);border-radius:5px;background:var(--pptx-muted,#2a2a3d);color:inherit}footer button:disabled{opacity:.4}</style>
