// packages/angular/src/viewer/shortcut-panel.component.ts
/**
 * shortcut-panel.component.ts: Floating keyboard-shortcut cheat sheet.
 *
 * Selector: `pptx-shortcut-panel`
 *
 * Angular port of the React `ShortcutPanel` component
 * (`packages/react/src/viewer/components/ShortcutPanel.tsx`). Unlike the
 * dialogs, this is NOT a modal: it is a small floating popover anchored to the
 * top-right of the viewer that lists the keyboard shortcuts from
 * {@link SHORTCUT_REFERENCE_ITEMS}. The host owns the `open` flag; the component
 * only renders and emits `close`.
 */

import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';

import { SHORTCUT_REFERENCE_ITEMS } from './shortcut-reference';

@Component({
	selector: 'pptx-shortcut-panel',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		@if (open()) {
			<div class="pptx-ng-shortcuts" data-pptx-shortcuts-panel="true">
				<div class="pptx-ng-shortcuts-header">
					<span class="pptx-ng-shortcuts-title">Keyboard shortcuts</span>
					<button type="button" class="pptx-ng-shortcuts-close" (click)="close.emit()">
						Close
					</button>
				</div>
				<div class="pptx-ng-shortcuts-list">
					@for (item of items; track item.action) {
						<div class="pptx-ng-shortcuts-row">
							<span class="pptx-ng-shortcuts-action">{{ item.action }}</span>
							<span class="pptx-ng-shortcuts-keys">{{ item.shortcut }}</span>
						</div>
					}
				</div>
			</div>
		}
	`,
	styles: [
		`
			.pptx-ng-shortcuts {
				position: absolute;
				top: 3.5rem;
				right: 0.75rem;
				z-index: 40;
				width: min(24rem, calc(100% - 1.5rem));
				border: 1px solid var(--pptx-border, #374151);
				border-radius: 0.25rem;
				background: var(--pptx-popover, #111827);
				color: var(--pptx-foreground, #f3f4f6);
				box-shadow: 0 10px 40px rgba(0, 0, 0, 0.35);
			}

			.pptx-ng-shortcuts-header {
				display: flex;
				align-items: center;
				justify-content: space-between;
				gap: 0.5rem;
				padding: 0.5rem 0.75rem;
				border-bottom: 1px solid var(--pptx-border, #374151);
			}

			.pptx-ng-shortcuts-title {
				font-size: 0.75rem;
				text-transform: uppercase;
				letter-spacing: 0.05em;
				color: var(--pptx-foreground, #f3f4f6);
			}

			.pptx-ng-shortcuts-close {
				padding: 0.25rem 0.5rem;
				font-size: 0.6875rem;
				color: var(--pptx-foreground, #f3f4f6);
				background: transparent;
				border: none;
				border-radius: 0.25rem;
				cursor: pointer;
			}

			.pptx-ng-shortcuts-close:hover {
				background: var(--pptx-muted, #1f2937);
			}

			.pptx-ng-shortcuts-list {
				max-height: 16rem;
				overflow-y: auto;
				padding: 0.5rem;
				display: flex;
				flex-direction: column;
				gap: 0.25rem;
			}

			.pptx-ng-shortcuts-row {
				display: flex;
				align-items: center;
				justify-content: space-between;
				gap: 0.75rem;
				padding: 0.375rem 0.5rem;
				border-radius: 0.25rem;
				background: var(--pptx-muted, rgba(31, 41, 55, 0.8));
			}

			.pptx-ng-shortcuts-action {
				font-size: 0.75rem;
				color: var(--pptx-foreground, #f3f4f6);
			}

			.pptx-ng-shortcuts-keys {
				font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
				font-size: 0.6875rem;
				white-space: nowrap;
				color: var(--pptx-foreground, #f3f4f6);
			}
		`,
	],
})
export class ShortcutPanelComponent {
	/** Whether the popover is visible. */
	readonly open = input<boolean>(false);

	/** Fired when the Close button is clicked. */
	readonly close = output<void>();

	/** Static shortcut reference rows. */
	protected readonly items = SHORTCUT_REFERENCE_ITEMS;
}

// packages/svelte/src/viewer/components/ShortcutPanel.svelte
<script lang="ts">
	import { VIEWER_SHORTCUT_REFERENCE } from 'pptx-viewer-shared';
	import { useTranslator } from '../../i18n/context';
	const { onclose }: { onclose: () => void } = $props();
	const t = useTranslator();
</script>
<!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
<aside class="panel" role="dialog" tabindex="-1" aria-labelledby="shortcuts-title">
	<header><h2 id="shortcuts-title">{t('pptx.shortcuts.title')}</h2><button type="button" onclick={onclose}>{t('pptx.shortcuts.close')}</button></header>
	<div>{#each VIEWER_SHORTCUT_REFERENCE as shortcut, index}<p class:stripe={index % 2 === 0}><span>{t(shortcut.actionKey)}</span><kbd>{shortcut.shortcut}</kbd></p>{/each}</div>
</aside>
<style>
	.panel{position:absolute;z-index:80;top:56px;right:12px;width:min(384px,calc(100% - 24px));overflow:hidden;border:1px solid var(--pptx-border,#3f3f52);border-radius:8px;background:var(--pptx-card,#1e1e2e);box-shadow:0 18px 50px #0008}header{display:flex;align-items:center;justify-content:space-between;padding:9px 12px;border-bottom:1px solid var(--pptx-border,#3f3f52)}h2{margin:0;font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase}button{border:0;border-radius:5px;padding:5px 8px;background:transparent;color:inherit;font-size:11px}button:hover{background:var(--pptx-muted,#2a2a3d)}div{max-height:280px;overflow:auto;padding:8px}p{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:0;padding:7px 9px;border-radius:5px;font-size:12px}.stripe{background:var(--pptx-muted,#2a2a3d)}kbd{color:var(--pptx-muted-foreground,#94a3b8);font:11px ui-monospace,monospace;white-space:nowrap}
</style>
