// packages/react/src/viewer/components/StatusBar.tsx
import { resolveStatusBarSave, statusBarViewMode } from 'pptx-viewer-shared';
import type { PptxUiStatusBarElement, StatusBarRequestEvent } from 'pptx-viewer-shared';
import React, { useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';

import type { AutosaveStatus } from '../hooks/useAutosave';

export interface StatusBarProps {
	slideCount: number;
	activeSlideIndex: number;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	/** Current zoom scale (0-1+ range, e.g. 1.0 = 100%). */
	scale?: number;
	/** Callback to zoom in. */
	onZoomIn?: () => void;
	/** Callback to zoom out. */
	onZoomOut?: () => void;
	/** Callback to zoom to fit. */
	onZoomToFit?: () => void;
	/** Whether the notes panel is expanded. */
	isNotesExpanded?: boolean;
	/** Toggle the notes panel. */
	onToggleNotes?: () => void;
	/** Current viewer mode. */
	mode?: string;
	/** Callback to switch viewer mode. */
	onSetMode?: (mode: 'edit' | 'present') => void;
	/** Callback to toggle slide sorter view. */
	onToggleSlideSorter?: () => void;
	/** Optional collaboration status indicator rendered inline. */
	collaborationSlot?: React.ReactNode;
	/** Hides the zoom in/out/to-fit control cluster. Maps to `hiddenActions: ['zoom']`. */
	hideZoomControls?: boolean;
	/** Hides the notes-panel toggle button. Maps to `hiddenActions: ['notes']`. */
	hideNotesToggle?: boolean;
	/** Hides the quick "Slide Show" (fullscreen present) toggle button. Maps to `hiddenActions: ['fullscreen']`. */
	hideFullscreenToggle?: boolean;
}

/**
 * Thin adapter around the shared `pptx-ui-status-bar`: it maps viewer state to the
 * element's controlled state and routes `status-request` intents to the handlers.
 */
export function StatusBar(p: StatusBarProps): React.ReactElement {
	const { t } = useTranslation();
	const ref = useRef<PptxUiStatusBarElement>(null);
	const save = resolveStatusBarSave(t, p.autosaveStatus, p.isDirty);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		host.state = {
			slideCount: p.slideCount,
			activeSlideIndex: p.activeSlideIndex,
			saveText: save.text,
			saveKind: save.kind,
			zoomPercent: p.scale !== undefined && !p.hideZoomControls ? (p.scale ?? 1) * 100 : undefined,
			showNotes: Boolean(p.onToggleNotes) && !p.hideNotesToggle,
			notesExpanded: p.isNotesExpanded === true,
			showViewModes: Boolean(p.onSetMode),
			showSorter: Boolean(p.onToggleSlideSorter),
			showSlideShow: !p.hideFullscreenToggle,
			viewMode: statusBarViewMode(p.mode),
			translate: t,
		};
	}, [p, save.text, save.kind, t]);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		const request = (event: Event) => {
			switch ((event as StatusBarRequestEvent).detail.id) {
				case 'notes':
					p.onToggleNotes?.();
					break;
				case 'normal':
					p.onSetMode?.('edit');
					break;
				case 'sorter':
					p.onToggleSlideSorter?.();
					break;
				case 'slideShow':
					p.onSetMode?.('present');
					break;
				case 'zoomOut':
					p.onZoomOut?.();
					break;
				case 'zoomFit':
					p.onZoomToFit?.();
					break;
				case 'zoomIn':
					p.onZoomIn?.();
			}
		};
		host.addEventListener('status-request', request);
		return () => host.removeEventListener('status-request', request);
	}, [p]);
	return (
		<pptx-ui-status-bar ref={ref}>
			{p.collaborationSlot ? (
				<div slot='collaboration' style={{ display: 'contents' }}>
					{p.collaborationSlot}
				</div>
			) : null}
		</pptx-ui-status-bar>
	);
}

// packages/svelte/src/viewer/components/StatusBar.svelte
<script lang="ts">
	/**
	 * Desktop status bar, docked beneath the slide/notes area. A thin adapter around
	 * the shared `pptx-ui-status-bar`: it maps viewer state onto the element and routes
	 * typed intents to the callbacks. Kept independent from the top toolbar so
	 * read-only viewers retain PowerPoint's navigation and zoom chrome.
	 */
	import { resolveStatusBarSave } from 'pptx-viewer-shared';
	import type { StatusBarRequestEvent, StatusBarViewState } from 'pptx-viewer-shared';
	import type { Snippet } from 'svelte';
	import { useTranslator } from '../../i18n/context';
	import type { AutosaveStatus } from '../state/autosave.svelte';

	const {
		current,
		total,
		zoomPercent,
		isDirty,
		autosaveStatus,
		showNotes = false,
		notesExpanded = false,
		isFullscreen = false,
		slideSorterActive = false,
		onzoomin,
		onzoomout,
		onzoomfit,
		onfullscreen,
		onnotestoggle,
		onnormal,
		onslidesorter,
		collaborationSlot,
		hideZoom = false,
		hideFullscreen = false,
	}: {
		current: number;
		total: number;
		zoomPercent: number;
		isDirty: boolean;
		autosaveStatus?: AutosaveStatus;
		showNotes?: boolean;
		notesExpanded?: boolean;
		isFullscreen?: boolean;
		slideSorterActive?: boolean;
		onzoomin: () => void;
		onzoomout: () => void;
		onzoomfit: () => void;
		onfullscreen: () => void;
		onnotestoggle?: () => void;
		onnormal?: () => void;
		onslidesorter?: () => void;
		collaborationSlot?: Snippet;
		/** Hide the zoom cluster (`hiddenActions: ['zoom']`). */
		hideZoom?: boolean;
		/** Hide the Slide Show toggle (`hiddenActions: ['fullscreen']`). */
		hideFullscreen?: boolean;
	} = $props();

	const t = useTranslator();
	const save = $derived(
		resolveStatusBarSave(t, autosaveStatus ? { state: autosaveStatus } : undefined, isDirty),
	);
	// "Normal" is active whenever neither the slide sorter nor the slideshow is up.
	const state = $derived<StatusBarViewState>({
		slideCount: total,
		activeSlideIndex: current,
		saveText: save.text,
		saveKind: save.kind,
		zoomPercent: hideZoom ? undefined : zoomPercent,
		showNotes,
		notesExpanded,
		showSorter: Boolean(onslidesorter),
		showSlideShow: !hideFullscreen,
		viewMode: isFullscreen ? 'slideShow' : slideSorterActive ? 'sorter' : 'normal',
		translate: t,
	});
	function request(event: StatusBarRequestEvent): void {
		const handlers = {
			notes: onnotestoggle,
			normal: onnormal,
			sorter: onslidesorter,
			slideShow: onfullscreen,
			zoomOut: onzoomout,
			zoomFit: onzoomfit,
			zoomIn: onzoomin,
		};
		handlers[event.detail.id]?.();
	}
</script>

<!--
	No landmark role here, matching the other four bindings: the row is a mixed
	region of live readouts and controls, not a toolbar. The class lets the viewer
	hide the bar on phones, where the mobile bottom bar replaces it.
-->
<pptx-ui-status-bar class="pptx-svelte-statusbar" {state} onstatus-request={request}>
	{#if collaborationSlot}
		<div slot="collaboration" style="display:contents">{@render collaborationSlot()}</div>
	{/if}
</pptx-ui-status-bar>
