// packages/vue/src/viewer/components/inspector/ActionSettingsPanel.vue
<script setup lang="ts">
import type { ElementAction, ElementActionType, PptxElement } from 'pptx-viewer-core';
import { elementActionToPptxAction, pptxActionToElementAction } from 'pptx-viewer-core';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

const props = withDefaults(
	defineProps<{ element: PptxElement; slideCount?: number; canEdit?: boolean }>(),
	{ slideCount: 0, canEdit: true },
);
const emit = defineEmits<{ update: [patch: Partial<PptxElement>] }>();
const { t } = useI18n();

const OPTIONS: ReadonlyArray<{ value: ElementActionType; key: string }> = [
	{ value: 'none', key: 'pptx.hyperlink.actionNone' },
	{ value: 'url', key: 'pptx.action.gotoUrl' },
	{ value: 'slide', key: 'pptx.action.gotoSlide' },
	{ value: 'firstSlide', key: 'pptx.hyperlink.actionFirstSlide' },
	{ value: 'lastSlide', key: 'pptx.hyperlink.actionLastSlide' },
	{ value: 'prevSlide', key: 'pptx.hyperlink.actionPrevSlide' },
	{ value: 'nextSlide', key: 'pptx.hyperlink.actionNextSlide' },
	{ value: 'endShow', key: 'pptx.hyperlink.actionEndShow' },
];

const clickAction = computed(() =>
	props.element.actionClick
		? pptxActionToElementAction(props.element.actionClick, 'click')
		: undefined,
);
const hoverAction = computed(() =>
	props.element.actionHover
		? pptxActionToElementAction(props.element.actionHover, 'hover')
		: undefined,
);

function actionFor(trigger: 'click' | 'hover'): ElementAction | undefined {
	return trigger === 'click' ? clickAction.value : hoverAction.value;
}

function update(
	trigger: 'click' | 'hover',
	type: ElementActionType,
	url?: string,
	slideIndex?: number,
): void {
	const action = elementActionToPptxAction({ trigger, type, url, slideIndex });
	emit(
		'update',
		(trigger === 'click'
			? { actionClick: action }
			: { actionHover: action }) as Partial<PptxElement>,
	);
}

function onType(event: Event, trigger: 'click' | 'hover'): void {
	const current = actionFor(trigger);
	update(
		trigger,
		(event.target as HTMLSelectElement).value as ElementActionType,
		current?.url,
		current?.slideIndex,
	);
}

function onUrl(event: Event, trigger: 'click' | 'hover'): void {
	update(trigger, 'url', (event.target as HTMLInputElement).value);
}

function onSlide(event: Event, trigger: 'click' | 'hover'): void {
	const value = Number((event.target as HTMLInputElement).value);
	if (Number.isFinite(value)) {
		update(trigger, 'slide', undefined, Math.max(0, value - 1));
	}
}
</script>

<template>
	<div class="pptx-vue-action-settings rounded border border-border bg-card p-2 space-y-2">
		<div class="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.action.title') }}
		</div>
		<div v-for="trigger in ['click', 'hover'] as const" :key="trigger" class="space-y-1.5">
			<label class="block text-[11px] font-medium text-muted-foreground">
				{{ t(trigger === 'click' ? 'pptx.action.onClick' : 'pptx.action.onHover') }}
			</label>
			<select
				class="w-full rounded border border-border bg-muted px-1.5 py-1 text-[11px]"
				:disabled="!canEdit"
				:value="actionFor(trigger)?.type ?? 'none'"
				@change="onType($event, trigger)"
			>
				<option v-for="option in OPTIONS" :key="option.value" :value="option.value">
					{{ t(option.key) }}
				</option>
			</select>
			<input
				v-if="actionFor(trigger)?.type === 'url'"
				type="url"
				class="w-full rounded border border-border bg-muted px-1.5 py-1 text-[11px]"
				:disabled="!canEdit"
				:value="actionFor(trigger)?.url ?? ''"
				placeholder="https://..."
				@input="onUrl($event, trigger)"
			/>
			<input
				v-if="actionFor(trigger)?.type === 'slide'"
				type="number"
				class="w-full rounded border border-border bg-muted px-1.5 py-1 text-[11px]"
				:disabled="!canEdit"
				:min="1"
				:max="slideCount"
				:value="(actionFor(trigger)?.slideIndex ?? 0) + 1"
				@change="onSlide($event, trigger)"
			/>
		</div>
	</div>
</template>

// src/viewer/components/inspector/ActionSettingsPanel.tsx
import React from "react";
import { useTranslation } from "react-i18next";

import { cn } from "../../utils";
import type {
  PptxElement,
  PptxSlide,
  ElementAction,
  ElementActionType,
} from "../../../core";
import {
  pptxActionToElementAction,
  elementActionToPptxAction,
} from "../../../core";
import { CARD, HEADING, INPUT } from "./inspector-pane-constants";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface ActionSettingsPanelProps {
  selectedElement: PptxElement;
  slides: PptxSlide[];
  canEdit: boolean;
  onUpdateElement: (updates: Partial<PptxElement>) => void;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const ACTION_TYPE_OPTIONS: Array<{ value: ElementActionType; label: string }> =
  [
    { value: "none", label: "None" },
    { value: "url", label: "Go to URL" },
    { value: "slide", label: "Go to Slide" },
    { value: "firstSlide", label: "First Slide" },
    { value: "lastSlide", label: "Last Slide" },
    { value: "prevSlide", label: "Previous Slide" },
    { value: "nextSlide", label: "Next Slide" },
    { value: "endShow", label: "End Show" },
  ];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ActionSettingsPanel({
  selectedElement,
  slides,
  canEdit,
  onUpdateElement,
}: ActionSettingsPanelProps): React.ReactElement {
  const { t } = useTranslation();

  const clickAction: ElementAction | undefined = selectedElement.actionClick
    ? pptxActionToElementAction(selectedElement.actionClick, "click")
    : undefined;

  const hoverAction: ElementAction | undefined = selectedElement.actionHover
    ? pptxActionToElementAction(selectedElement.actionHover, "hover")
    : undefined;

  const activeClickType: ElementActionType = clickAction?.type ?? "none";
  const activeHoverType: ElementActionType = hoverAction?.type ?? "none";

  const updateAction = (
    trigger: "click" | "hover",
    type: ElementActionType,
    url?: string,
    slideIndex?: number,
  ) => {
    const ea: ElementAction = { trigger, type, url, slideIndex };
    const pa = elementActionToPptxAction(ea);
    if (trigger === "click") {
      onUpdateElement({ actionClick: pa } as Partial<PptxElement>);
    } else {
      onUpdateElement({ actionHover: pa } as Partial<PptxElement>);
    }
  };

  return (
    <div className={CARD}>
      <div className={HEADING}>{t("pptx.action.title", "Action")}</div>
      <div className="space-y-2 text-[11px]">
        {/* On Click */}
        <ActionTriggerSection
          label={t("pptx.action.onClick", "On Click")}
          trigger="click"
          activeType={activeClickType}
          action={clickAction}
          fallbackUrl={selectedElement.actionClick?.url}
          fallbackSlideIndex={selectedElement.actionClick?.targetSlideIndex}
          canEdit={canEdit}
          slideCount={slides.length}
          onChangeType={(type) =>
            updateAction(
              "click",
              type,
              clickAction?.url,
              clickAction?.slideIndex,
            )
          }
          onChangeUrl={(url) => updateAction("click", "url", url)}
          onChangeSlide={(idx) =>
            updateAction("click", "slide", undefined, idx)
          }
        />

        {/* On Hover */}
        <ActionTriggerSection
          label={t("pptx.action.onHover", "On Hover")}
          trigger="hover"
          activeType={activeHoverType}
          action={hoverAction}
          fallbackUrl={selectedElement.actionHover?.url}
          fallbackSlideIndex={selectedElement.actionHover?.targetSlideIndex}
          canEdit={canEdit}
          slideCount={slides.length}
          onChangeType={(type) =>
            updateAction(
              "hover",
              type,
              hoverAction?.url,
              hoverAction?.slideIndex,
            )
          }
          onChangeUrl={(url) => updateAction("hover", "url", url)}
          onChangeSlide={(idx) =>
            updateAction("hover", "slide", undefined, idx)
          }
        />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sub-component: a single trigger block (Click or Hover)
// ---------------------------------------------------------------------------

interface ActionTriggerSectionProps {
  label: string;
  trigger: "click" | "hover";
  activeType: ElementActionType;
  action: ElementAction | undefined;
  fallbackUrl: string | undefined;
  fallbackSlideIndex: number | undefined;
  canEdit: boolean;
  slideCount: number;
  onChangeType: (type: ElementActionType) => void;
  onChangeUrl: (url: string) => void;
  onChangeSlide: (idx: number) => void;
}

function ActionTriggerSection({
  label,
  activeType,
  action,
  fallbackUrl,
  fallbackSlideIndex,
  canEdit,
  slideCount,
  onChangeType,
  onChangeUrl,
  onChangeSlide,
}: ActionTriggerSectionProps): React.ReactElement {
  return (
    <div className="space-y-1.5">
      <span className="text-muted-foreground font-medium">{label}</span>
      <select
        disabled={!canEdit}
        className={cn(INPUT, "w-full")}
        value={activeType}
        onChange={(e) => onChangeType(e.target.value as ElementActionType)}
      >
        {ACTION_TYPE_OPTIONS.map((o) => (
          <option key={o.value} value={o.value}>
            {o.label}
          </option>
        ))}
      </select>

      {activeType === "url" && (
        <input
          type="text"
          disabled={!canEdit}
          className={cn(INPUT, "w-full")}
          placeholder="https://..."
          value={action?.url ?? fallbackUrl ?? ""}
          onChange={(e) => onChangeUrl(e.target.value)}
        />
      )}

      {activeType === "slide" && (
        <input
          type="number"
          disabled={!canEdit}
          className={cn(INPUT, "w-full")}
          placeholder="Slide number (1-based)"
          min={1}
          max={slideCount}
          value={(action?.slideIndex ?? fallbackSlideIndex ?? 0) + 1}
          onChange={(e) => {
            const n = Number(e.target.value);
            if (Number.isFinite(n)) onChangeSlide(Math.max(0, n - 1));
          }}
        />
      )}
    </div>
  );
}
