// packages/vue/src/viewer/components/inspector/DuotonePanel.vue
<script setup lang="ts">
import type { PptxElement, PptxImageEffects } from 'pptx-viewer-core';
import { DUOTONE_PRESETS, normalizeHexColor } from 'pptx-viewer-shared';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import {
	DEFAULT_DUOTONE,
	humanizeEffectLabel,
	mergeEffectsPatch,
} from '../../composables/useImageEditing';
import DebouncedColorInput from './DebouncedColorInput.vue';

/**
 * DuotonePanel: the duotone image effect (`a:duotone`) - a shadow + highlight
 * colour pair plus quick-apply presets from the shared DUOTONE_PRESETS
 * catalogue. Emits the FULL merged `imageEffects` sub-object per change.
 */
const props = defineProps<{
	fx: PptxImageEffects | undefined;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxElement>];
}>();

const { t } = useI18n();

const duotone = computed(() => props.fx?.duotone);
const shadow = computed<string>(() =>
	normalizeHexColor(duotone.value?.color1, DEFAULT_DUOTONE.color1),
);
const highlight = computed<string>(() =>
	normalizeHexColor(duotone.value?.color2, DEFAULT_DUOTONE.color2),
);

function commit(color1: string, color2: string): void {
	emit('update', mergeEffectsPatch(props.fx, { duotone: { color1, color2 } }));
}

function clear(): void {
	emit('update', mergeEffectsPatch(props.fx, { duotone: undefined }));
}

function onShadow(hex: string): void {
	commit(hex, highlight.value);
}

function onHighlight(hex: string): void {
	commit(shadow.value, hex);
}
</script>

<template>
	<div class="pptx-vue-duotone flex flex-col gap-2 text-[11px]">
		<span class="font-semibold text-muted-foreground">{{ t('pptx.image.duotone') }}</span>

		<div class="flex items-center gap-3">
			<label class="flex items-center gap-1.5">
				<span class="text-muted-foreground">{{ t('pptx.image.duotoneShadows') }}</span>
				<DebouncedColorInput
					:value="shadow"
					:aria-label="t('pptx.image.duotoneShadowsAria')"
					@commit="onShadow"
				/>
			</label>
			<label class="flex items-center gap-1.5">
				<span class="text-muted-foreground">{{ t('pptx.image.duotoneHighlights') }}</span>
				<DebouncedColorInput
					:value="highlight"
					:aria-label="t('pptx.image.duotoneHighlightsAria')"
					@commit="onHighlight"
				/>
			</label>
		</div>

		<div class="flex flex-col gap-1">
			<span class="text-[10px] text-muted-foreground">{{ t('pptx.image.duotonePresets') }}</span>
			<div class="pptx-vue-duotone__grid grid grid-cols-4 gap-1">
				<button
					v-for="preset in DUOTONE_PRESETS"
					:key="preset.labelKey"
					type="button"
					class="pptx-vue-duotone__cell flex flex-col items-center gap-0.5 rounded border border-border hover:bg-accent p-1 transition-colors"
					:title="humanizeEffectLabel(preset.labelKey)"
					@click="commit(preset.shadow, preset.highlight)"
				>
					<div class="flex h-4 w-full overflow-hidden rounded">
						<div class="flex-1" :style="{ backgroundColor: preset.shadow }" />
						<div class="flex-1" :style="{ backgroundColor: preset.highlight }" />
					</div>
					<span class="w-full truncate text-center text-[8px] text-muted-foreground">
						{{ humanizeEffectLabel(preset.labelKey) }}
					</span>
				</button>
			</div>
		</div>

		<button
			v-if="duotone"
			type="button"
			class="pptx-vue-duotone__clear w-full rounded border border-border bg-muted px-2 py-1 hover:bg-accent transition-colors"
			@click="clear"
		>
			{{ t('pptx.image.duotoneClear') }}
		</button>
	</div>
</template>

// src/viewer/components/inspector/DuotonePanel.tsx
/**
 * Inspector panel for the duotone image effect — two colour pickers
 * (shadow + highlight) plus quick-apply presets.
 */
import React, { useCallback, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";

import type { PptxElement } from "../../../core";
import { normalizeHexColor } from "../../utils";
import { DUOTONE_PRESETS } from "../../utils/duotone-effects";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface DuotonePanelProps {
  selectedElement: PptxElement;
  canEdit: boolean;
  onUpdateElement: (updates: Partial<PptxElement>) => void;
}

// ---------------------------------------------------------------------------
// Debounced colour input (matches InspectorPane's pattern)
// ---------------------------------------------------------------------------

function DebouncedColorInput({
  value,
  disabled,
  className,
  onCommit,
}: {
  value: string;
  disabled?: boolean;
  className?: string;
  onCommit: (hex: string) => void;
}) {
  const [local, setLocal] = useState(value);
  const commitRef = useRef(onCommit);
  commitRef.current = onCommit;

  useEffect(() => {
    setLocal(value);
  }, [value]);

  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    setLocal(e.target.value);
  }, []);

  const handleBlur = useCallback(() => {
    commitRef.current(local);
  }, [local]);

  const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    const el = inputRef.current;
    if (!el) return;
    const handler = () => {
      commitRef.current(el.value);
    };
    el.addEventListener("change", handler);
    return () => el.removeEventListener("change", handler);
  }, []);

  return (
    <input
      ref={inputRef}
      type="color"
      disabled={disabled}
      className={className}
      value={local}
      onChange={handleChange}
      onBlur={handleBlur}
    />
  );
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function DuotonePanel({
  selectedElement,
  canEdit,
  onUpdateElement,
}: DuotonePanelProps): React.ReactElement {
  const { t } = useTranslation();
  const effects =
    "imageEffects" in selectedElement
      ? (
          selectedElement as unknown as {
            imageEffects?: { duotone?: { color1: string; color2: string } };
          }
        ).imageEffects
      : undefined;

  const commitDuotone = useCallback(
    (color1: string, color2: string) => {
      onUpdateElement({
        imageEffects: {
          ...(effects ?? {}),
          duotone: { color1, color2 },
        },
      } as Partial<PptxElement>);
    },
    [effects, onUpdateElement],
  );

  const clearDuotone = useCallback(() => {
    onUpdateElement({
      imageEffects: {
        ...(effects ?? {}),
        duotone: undefined,
      },
    } as Partial<PptxElement>);
  }, [effects, onUpdateElement]);

  const shadowColor = normalizeHexColor(effects?.duotone?.color1, "#000000");
  const highlightColor = normalizeHexColor(effects?.duotone?.color2, "#ffffff");

  return (
    <div className="space-y-2 text-[11px]">
      <div className="text-muted-foreground font-medium">
        {t("pptx.image.duotone")}
      </div>

      {/* Colour pickers */}
      <div className="flex items-center gap-3">
        <label className="flex items-center gap-1.5">
          <span className="text-muted-foreground">
            {t("pptx.image.duotoneShadows")}
          </span>
          <DebouncedColorInput
            disabled={!canEdit}
            value={shadowColor}
            className="h-6 w-8 rounded border border-border bg-transparent cursor-pointer"
            onCommit={(hex) => commitDuotone(hex, highlightColor)}
          />
        </label>
        <label className="flex items-center gap-1.5">
          <span className="text-muted-foreground">
            {t("pptx.image.duotoneHighlights")}
          </span>
          <DebouncedColorInput
            disabled={!canEdit}
            value={highlightColor}
            className="h-6 w-8 rounded border border-border bg-transparent cursor-pointer"
            onCommit={(hex) => commitDuotone(shadowColor, hex)}
          />
        </label>
      </div>

      {/* Presets grid */}
      <div className="space-y-1">
        <div className="text-muted-foreground text-[10px]">
          {t("pptx.image.duotonePresets")}
        </div>
        <div className="grid grid-cols-4 gap-1">
          {DUOTONE_PRESETS.map((preset) => (
            <button
              key={preset.labelKey}
              type="button"
              disabled={!canEdit}
              className="flex flex-col items-center gap-0.5 rounded border border-border hover:bg-accent p-1 transition-colors"
              title={t(preset.labelKey)}
              onClick={() => commitDuotone(preset.shadow, preset.highlight)}
            >
              <div className="flex h-4 w-full rounded overflow-hidden">
                <div
                  className="flex-1"
                  style={{ backgroundColor: preset.shadow }}
                />
                <div
                  className="flex-1"
                  style={{ backgroundColor: preset.highlight }}
                />
              </div>
              <span className="text-[8px] text-muted-foreground truncate w-full text-center">
                {t(preset.labelKey)}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* Clear button */}
      {effects?.duotone && (
        <button
          type="button"
          disabled={!canEdit}
          className="w-full rounded bg-muted hover:bg-accent border border-border px-2 py-1 text-foreground transition-colors"
          onClick={clearDuotone}
        >
          {t("pptx.image.duotoneClear")}
        </button>
      )}
    </div>
  );
}
