// packages/angular/src/viewer/comments-panel.component.ts
/**
 * comments-panel.component.ts: Side panel listing the active slide's comments.
 *
 * Selector: `pptx-comments-panel`
 *
 * Presentational only: it renders the supplied `comments` (already filtered to
 * the active slide by the host) and surfaces add / remove / resolve intents via
 * outputs. The host owns state and commits history-aware comment-array writes.
 *
 * Timestamps are formatted with the core `formatCommentTimestamp` helper so the
 * Angular binding matches the React/Vue formatting exactly.
 *
 * Usage:
 * ```html
 * <pptx-comments-panel
 *   [comments]="slideComments()"
 *   [authorName]="userName()"
 *   (add)="onAddComment($event)"
 *   (remove)="onRemoveComment($event)"
 *   (resolve)="onResolveComment($event)"
 * />
 * ```
 */

import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import type { PptxComment } from 'pptx-viewer-core';
import { formatCommentTimestamp } from 'pptx-viewer-core';

@Component({
	selector: 'pptx-comments-panel',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<aside class="pptx-ng-comments" aria-label="Slide comments">
			<header class="pptx-ng-comments__header">
				<h2 class="pptx-ng-comments__title">Comments</h2>
				<span class="pptx-ng-comments__count" data-testid="comment-count">
					{{ comments().length }}
				</span>
			</header>

			@if (comments().length > 0) {
				<ul class="pptx-ng-comments__list">
					@for (comment of comments(); track comment.id) {
						<li
							class="pptx-ng-comments__item"
							[class.pptx-ng-comments__item--resolved]="comment.resolved"
							[attr.data-comment-id]="comment.id"
						>
							<div class="pptx-ng-comments__meta">
								<span class="pptx-ng-comments__author">{{ comment.author || 'Unknown' }}</span>
								@if (formatTimestamp(comment.createdAt); as ts) {
									<time class="pptx-ng-comments__time">{{ ts }}</time>
								}
							</div>
							<p class="pptx-ng-comments__text">{{ comment.text }}</p>
							<div class="pptx-ng-comments__actions">
								<button
									type="button"
									class="pptx-ng-comments__action"
									[attr.data-comment-id]="comment.id"
									[attr.aria-pressed]="comment.resolved ? 'true' : 'false'"
									(click)="resolve.emit(comment.id)"
								>
									{{ comment.resolved ? 'Reopen' : 'Resolve' }}
								</button>
								<button
									type="button"
									class="pptx-ng-comments__action pptx-ng-comments__action--danger"
									[attr.data-comment-id]="comment.id"
									aria-label="Remove comment"
									(click)="remove.emit(comment.id)"
								>
									Remove
								</button>
							</div>
						</li>
					}
				</ul>
			} @else {
				<p class="pptx-ng-comments__empty" data-testid="comments-empty">
					No comments on this slide yet.
				</p>
			}

			<form class="pptx-ng-comments__compose" (submit)="submit($event)">
				<label class="pptx-ng-comments__compose-label" [title]="'Commenting as ' + authorName()">
					Add comment
				</label>
				<textarea
					class="pptx-ng-comments__textarea"
					rows="3"
					placeholder="Write a comment…"
					aria-label="Add comment"
					[value]="draft()"
					(input)="onDraftInput($event)"
				></textarea>
				<button
					type="submit"
					class="pptx-ng-comments__submit"
					[disabled]="!canAdd()"
					data-testid="add-comment"
				>
					Add comment
				</button>
			</form>
		</aside>
	`,
	styles: [
		`
			:host {
				display: block;
				height: 100%;
				width: 100%;
			}

			.pptx-ng-comments {
				display: flex;
				flex-direction: column;
				min-height: 0;
				height: 100%;
				width: 100%;
				background: var(--pptx-card, #111827);
				color: var(--pptx-foreground, #f3f4f6);
				border-left: 1px solid var(--pptx-border, #374151);
				font-family: system-ui, sans-serif;
			}

			.pptx-ng-comments__header {
				display: flex;
				align-items: center;
				justify-content: space-between;
				padding: 12px 16px;
				border-bottom: 1px solid var(--pptx-border, #374151);
			}

			.pptx-ng-comments__title {
				margin: 0;
				font-size: 14px;
				font-weight: 600;
			}

			.pptx-ng-comments__count {
				font-size: 12px;
				color: var(--pptx-muted-foreground, #9ca3af);
			}

			.pptx-ng-comments__list {
				list-style: none;
				margin: 0;
				padding: 8px;
				overflow-y: auto;
				flex: 1 1 auto;
				min-height: 0;
			}

			.pptx-ng-comments__item {
				padding: 10px 12px;
				border: 1px solid var(--pptx-border, #374151);
				border-radius: 8px;
				margin-bottom: 8px;
			}

			.pptx-ng-comments__item--resolved {
				opacity: 0.6;
			}

			.pptx-ng-comments__meta {
				display: flex;
				align-items: baseline;
				justify-content: space-between;
				gap: 8px;
				margin-bottom: 4px;
			}

			.pptx-ng-comments__author {
				font-size: 13px;
				font-weight: 600;
			}

			.pptx-ng-comments__time {
				font-size: 11px;
				color: var(--pptx-muted-foreground, #9ca3af);
			}

			.pptx-ng-comments__text {
				margin: 0 0 8px;
				font-size: 13px;
				white-space: pre-wrap;
				word-break: break-word;
			}

			.pptx-ng-comments__actions {
				display: flex;
				gap: 8px;
			}

			.pptx-ng-comments__action {
				font-size: 12px;
				padding: 4px 8px;
				border-radius: 6px;
				border: 1px solid var(--pptx-border, #374151);
				background: transparent;
				color: inherit;
				cursor: pointer;
			}

			.pptx-ng-comments__action--danger {
				color: #f87171;
			}

			.pptx-ng-comments__empty {
				padding: 16px;
				font-size: 13px;
				color: var(--pptx-muted-foreground, #9ca3af);
				flex: 1 1 auto;
			}

			.pptx-ng-comments__compose {
				display: flex;
				flex-direction: column;
				gap: 8px;
				padding: 12px 16px;
				border-top: 1px solid var(--pptx-border, #374151);
			}

			.pptx-ng-comments__compose-label {
				font-size: 12px;
				font-weight: 600;
			}

			.pptx-ng-comments__textarea {
				resize: vertical;
				width: 100%;
				padding: 8px;
				border-radius: 6px;
				border: 1px solid var(--pptx-border, #374151);
				background: var(--pptx-background, #030712);
				color: inherit;
				font: inherit;
				font-size: 13px;
			}

			.pptx-ng-comments__submit {
				align-self: flex-end;
				font-size: 13px;
				padding: 6px 14px;
				border-radius: 6px;
				border: none;
				background: var(--pptx-primary, #6366f1);
				color: #fff;
				cursor: pointer;
			}

			.pptx-ng-comments__submit:disabled {
				opacity: 0.5;
				cursor: not-allowed;
			}
		`,
	],
})
export class CommentsPanelComponent {
	// -------------------------------------------------------------------------
	// Inputs / outputs
	// -------------------------------------------------------------------------

	/** The active slide's comments (already filtered to the active slide). */
	readonly comments = input<PptxComment[]>([]);

	/** Display name shown in the compose label ("Commenting as …"). */
	readonly authorName = input<string>('You');

	/** Emits the trimmed comment text the user wants to add. */
	readonly add = output<string>();

	/** Emits the id of a comment the user wants to remove. */
	readonly remove = output<string>();

	/** Emits the id of a comment whose resolved flag should toggle. */
	readonly resolve = output<string>();

	// -------------------------------------------------------------------------
	// Draft state
	// -------------------------------------------------------------------------

	/** Current text typed into the compose textarea. */
	readonly draft = signal('');

	/** Whether the draft has non-whitespace content (enables the submit button). */
	readonly canAdd = computed<boolean>(() => this.draft().trim().length > 0);

	// -------------------------------------------------------------------------
	// Event handlers
	// -------------------------------------------------------------------------

	onDraftInput(event: Event): void {
		const target = event.target as HTMLTextAreaElement;
		this.draft.set(target.value);
	}

	submit(event: Event): void {
		event.preventDefault();
		const text = this.draft().trim();
		if (text.length === 0) {
			return;
		}
		this.add.emit(text);
		this.draft.set('');
	}

	formatTimestamp(value: string | undefined): string {
		return formatCommentTimestamp(value);
	}
}

<aside class="pptx-ng-comments" [attr.aria-label]="'pptx.comments.slideComments' | translate">
	<header class="pptx-ng-comments__header">
		<h2 class="pptx-ng-comments__title">{{ 'pptx.toolbar.comments' | translate }}</h2>
		<span class="pptx-ng-comments__count" data-testid="comment-count">
			{{ comments().length }}
		</span>
	</header>

	@if (comments().length > 0) {
		<ul class="pptx-ng-comments__list">
			@for (comment of comments(); track comment.id) {
				<li
					class="pptx-ng-comments__item"
					[class.pptx-ng-comments__item--resolved]="comment.resolved"
					[attr.data-comment-id]="comment.id"
				>
					<div class="pptx-ng-comments__meta">
						<span class="pptx-ng-comments__author">{{
							comment.author || ('pptx.comments.unknownAuthor' | translate)
						}}</span>
						@if (formatTimestamp(comment.createdAt); as ts) {
							<time class="pptx-ng-comments__time">{{ ts }}</time>
						}
					</div>
					<p class="pptx-ng-comments__text">
						<pptx-comment-body [text]="comment.text" [mentions]="comment.mentions" />
					</p>

					<!-- Threaded replies, nested inside the parent card -->
					@if (comment.replies && comment.replies.length > 0) {
						<ul class="pptx-ng-comments__replies">
							@for (replyItem of comment.replies; track replyItem.id) {
								<li class="pptx-ng-comments__reply" [attr.data-comment-id]="replyItem.id">
									<div class="pptx-ng-comments__meta">
										<span class="pptx-ng-comments__reply-author">{{
											replyItem.author || ('pptx.comments.unknownAuthor' | translate)
										}}</span>
										@if (formatTimestamp(replyItem.createdAt); as replyTs) {
											<time class="pptx-ng-comments__time">{{ replyTs }}</time>
										}
									</div>
									<p class="pptx-ng-comments__reply-text">
										<pptx-comment-body [text]="replyItem.text" [mentions]="replyItem.mentions" />
									</p>
								</li>
							}
						</ul>
					}

					<div class="pptx-ng-comments__actions">
						<button
							type="button"
							class="pptx-ng-comments__action"
							[attr.data-comment-id]="comment.id"
							[attr.aria-pressed]="comment.resolved ? 'true' : 'false'"
							(click)="resolve.emit(comment.id)"
						>
							{{
								(comment.resolved ? 'pptx.comments.reopen' : 'pptx.comments.resolve') | translate
							}}
						</button>
						<button
							type="button"
							class="pptx-ng-comments__action"
							[attr.data-comment-id]="comment.id"
							(click)="startReply(comment.id)"
						>
							{{ 'pptx.comments.reply' | translate }}
						</button>
						<button
							type="button"
							class="pptx-ng-comments__action pptx-ng-comments__action--danger"
							[attr.data-comment-id]="comment.id"
							[attr.aria-label]="'pptx.comments.removeComment' | translate"
							(click)="remove.emit(comment.id)"
						>
							{{ 'pptx.comments.remove' | translate }}
						</button>
					</div>

					<!-- Reply composer -->
					@if (replyingTo() === comment.id) {
						<div class="pptx-ng-comments__reply-compose">
							<textarea
								class="pptx-ng-comments__reply-textarea"
								rows="2"
								[placeholder]="replyPlaceholder(comment)"
								[attr.aria-label]="'pptx.comments.reply' | translate"
								[value]="replyDraft()"
								(input)="onReplyInput($event)"
							></textarea>
							<div class="pptx-ng-comments__reply-actions">
								<button type="button" class="pptx-ng-comments__action" (click)="cancelReply()">
									{{ 'pptx.comments.cancel' | translate }}
								</button>
								<button
									type="button"
									class="pptx-ng-comments__reply-submit"
									[disabled]="!canReply()"
									(click)="submitReply(comment.id)"
								>
									{{ 'pptx.comments.reply' | translate }}
								</button>
							</div>
						</div>
					}
				</li>
			}
		</ul>
	} @else {
		<p class="pptx-ng-comments__empty" data-testid="comments-empty">
			{{ 'pptx.comments.noneOnSlide' | translate }}
		</p>
	}

	<form class="pptx-ng-comments__compose" (submit)="submit($event)">
		<label
			class="pptx-ng-comments__compose-label"
			[title]="'pptx.comments.commentingAs' | translate: { name: authorName() }"
		>
			{{ 'pptx.comments.addComment' | translate }}
		</label>
		<textarea
			class="pptx-ng-comments__textarea"
			rows="3"
			[placeholder]="'pptx.comments.writePlaceholder' | translate"
			[attr.aria-label]="'pptx.comments.addComment' | translate"
			[value]="draft()"
			(input)="onDraftInput($event)"
		></textarea>
		<button
			type="submit"
			class="pptx-ng-comments__submit"
			[disabled]="!canAdd()"
			data-testid="add-comment"
		>
			{{ 'pptx.comments.addComment' | translate }}
		</button>
	</form>
</aside>

// packages/vue/src/viewer/components/CommentsPanel.vue
<script setup lang="ts">
import type { PptxComment } from 'pptx-viewer-core';
import { formatCommentTimestamp } from 'pptx-viewer-core';
import { computed, ref } from 'vue';

/**
 * CommentsPanel — side panel listing the active slide's comments.
 *
 * Presentational only: it renders the supplied `comments` (already filtered to
 * the active slide by the host) and surfaces add / remove / resolve intents via
 * emits. The host owns state and commits history-aware comment-array writes.
 *
 * Timestamps are formatted with the core `formatCommentTimestamp` helper so the
 * Vue binding matches the React/Angular formatting exactly.
 */
const props = defineProps<{
	comments: PptxComment[];
	authorName: string;
}>();

const emit = defineEmits<{
	add: [text: string];
	remove: [id: string];
	resolve: [id: string];
}>();

const draft = ref('');

const canAdd = computed<boolean>(() => draft.value.trim().length > 0);

const submit = (): void => {
	const text = draft.value.trim();
	if (text.length === 0) {
		return;
	}
	emit('add', text);
	draft.value = '';
};

const formatTimestamp = (value: string | undefined): string => formatCommentTimestamp(value);
</script>

<template>
	<aside class="pptx-comments-panel" aria-label="Slide comments">
		<header class="pptx-comments-panel__header">
			<h2 class="pptx-comments-panel__title">Comments</h2>
			<span class="pptx-comments-panel__count" data-testid="comment-count">
				{{ props.comments.length }}
			</span>
		</header>

		<ul v-if="props.comments.length > 0" class="pptx-comments-panel__list">
			<li
				v-for="comment in props.comments"
				:key="comment.id"
				class="pptx-comments-panel__item"
				:class="{ 'pptx-comments-panel__item--resolved': comment.resolved }"
				:data-comment-id="comment.id"
			>
				<div class="pptx-comments-panel__meta">
					<span class="pptx-comments-panel__author">{{ comment.author || 'Unknown' }}</span>
					<time v-if="formatTimestamp(comment.createdAt)" class="pptx-comments-panel__time">
						{{ formatTimestamp(comment.createdAt) }}
					</time>
				</div>
				<p class="pptx-comments-panel__text">{{ comment.text }}</p>
				<div class="pptx-comments-panel__actions">
					<button
						type="button"
						class="pptx-comments-panel__action"
						:data-comment-id="comment.id"
						:aria-pressed="comment.resolved ? 'true' : 'false'"
						@click="emit('resolve', comment.id)"
					>
						{{ comment.resolved ? 'Reopen' : 'Resolve' }}
					</button>
					<button
						type="button"
						class="pptx-comments-panel__action pptx-comments-panel__action--danger"
						:data-comment-id="comment.id"
						aria-label="Remove comment"
						@click="emit('remove', comment.id)"
					>
						Remove
					</button>
				</div>
			</li>
		</ul>

		<p v-else class="pptx-comments-panel__empty" data-testid="comments-empty">
			No comments on this slide yet.
		</p>

		<form class="pptx-comments-panel__compose" @submit.prevent="submit">
			<label
				class="pptx-comments-panel__compose-label"
				:title="`Commenting as ${props.authorName}`"
			>
				Add comment
			</label>
			<textarea
				v-model="draft"
				class="pptx-comments-panel__textarea"
				rows="3"
				placeholder="Write a comment…"
				aria-label="Add comment"
			></textarea>
			<button
				type="submit"
				class="pptx-comments-panel__submit"
				:disabled="!canAdd"
				data-testid="add-comment"
			>
				Add comment
			</button>
		</form>
	</aside>
</template>

<style scoped>
.pptx-comments-panel {
	display: flex;
	flex-direction: column;
	min-height: 0;
	height: 100%;
	width: 100%;
	background: var(--pptx-card, #111827);
	color: var(--pptx-foreground, #f3f4f6);
	border-left: 1px solid var(--pptx-border, #374151);
	font-family: system-ui, sans-serif;
}

.pptx-comments-panel__header {
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 12px 16px;
	border-bottom: 1px solid var(--pptx-border, #374151);
}

.pptx-comments-panel__title {
	margin: 0;
	font-size: 14px;
	font-weight: 600;
}

.pptx-comments-panel__count {
	font-size: 12px;
	color: var(--pptx-muted-foreground, #9ca3af);
}

.pptx-comments-panel__list {
	list-style: none;
	margin: 0;
	padding: 8px;
	overflow-y: auto;
	flex: 1 1 auto;
	min-height: 0;
}

.pptx-comments-panel__item {
	padding: 10px 12px;
	border: 1px solid var(--pptx-border, #374151);
	border-radius: 8px;
	margin-bottom: 8px;
}

.pptx-comments-panel__item--resolved {
	opacity: 0.6;
}

.pptx-comments-panel__meta {
	display: flex;
	align-items: baseline;
	justify-content: space-between;
	gap: 8px;
	margin-bottom: 4px;
}

.pptx-comments-panel__author {
	font-size: 13px;
	font-weight: 600;
}

.pptx-comments-panel__time {
	font-size: 11px;
	color: var(--pptx-muted-foreground, #9ca3af);
}

.pptx-comments-panel__text {
	margin: 0 0 8px;
	font-size: 13px;
	white-space: pre-wrap;
	word-break: break-word;
}

.pptx-comments-panel__actions {
	display: flex;
	gap: 8px;
}

.pptx-comments-panel__action {
	font-size: 12px;
	padding: 4px 8px;
	border-radius: 6px;
	border: 1px solid var(--pptx-border, #374151);
	background: transparent;
	color: inherit;
	cursor: pointer;
}

.pptx-comments-panel__action--danger {
	color: #f87171;
}

.pptx-comments-panel__empty {
	padding: 16px;
	font-size: 13px;
	color: var(--pptx-muted-foreground, #9ca3af);
	flex: 1 1 auto;
}

.pptx-comments-panel__compose {
	display: flex;
	flex-direction: column;
	gap: 8px;
	padding: 12px 16px;
	border-top: 1px solid var(--pptx-border, #374151);
}

.pptx-comments-panel__compose-label {
	font-size: 12px;
	font-weight: 600;
}

.pptx-comments-panel__textarea {
	resize: vertical;
	width: 100%;
	padding: 8px;
	border-radius: 6px;
	border: 1px solid var(--pptx-border, #374151);
	background: var(--pptx-background, #030712);
	color: inherit;
	font: inherit;
	font-size: 13px;
}

.pptx-comments-panel__submit {
	align-self: flex-end;
	font-size: 13px;
	padding: 6px 14px;
	border-radius: 6px;
	border: none;
	background: var(--pptx-primary, #6366f1);
	color: #fff;
	cursor: pointer;
}

.pptx-comments-panel__submit:disabled {
	opacity: 0.5;
	cursor: not-allowed;
}
</style>
