// packages/react/src/viewer/components/ComparePanel.tsx
import React, { useState, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { LuCheck, LuX } from "react-icons/lu";

import type { CanvasSize } from "../types";
import type { CompareResult } from "../utils/compare";
import { SlideDiffRow } from "./SlideDiffRow";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

/**
 * Props for the {@link ComparePanel} component.
 */
export interface ComparePanelProps {
  /** Whether the panel is visible. */
  isOpen: boolean;
  /** The comparison result containing slide diffs, or `null` if none. */
  compareResult: CompareResult | null;
  /** Current canvas dimensions used to render diff thumbnails. */
  canvasSize: CanvasSize;
  /** Callback to close the panel. */
  onClose: () => void;
  /** Callback to accept a single diff by its index. */
  onAcceptSlide: (diffIndex: number) => void;
  /** Callback to reject a single diff by its index. */
  onRejectSlide: (diffIndex: number) => void;
  /** Callback to accept all non-trivial diffs at once. */
  onAcceptAll: () => void;
}

// ---------------------------------------------------------------------------
// Main panel
// ---------------------------------------------------------------------------

/**
 * Side panel that displays slide-level diffs between two presentations.
 *
 * Users can accept or reject individual slide changes, or accept all
 * at once. Accepted / rejected states are tracked locally via `useState`
 * and propagated to the parent through the `onAcceptSlide` / `onRejectSlide`
 * callbacks.
 *
 * @param props - {@link ComparePanelProps}
 * @returns The rendered panel, or `null` when hidden or no result is available.
 */
export function ComparePanel({
  isOpen,
  compareResult,
  canvasSize,
  onClose,
  onAcceptSlide,
  onRejectSlide,
  onAcceptAll,
}: ComparePanelProps): React.ReactElement | null {
  const { t } = useTranslation();
  /** Map of diff indices the user has accepted. */
  const [accepted, setAccepted] = useState<Record<number, boolean>>({});
  /** Map of diff indices the user has rejected. */
  const [rejected, setRejected] = useState<Record<number, boolean>>({});

  /** Accept a diff: mark it accepted, un-reject if previously rejected, then notify parent. */
  const handleAccept = useCallback(
    (index: number) => {
      setAccepted((p) => ({ ...p, [index]: true }));
      setRejected((p) => {
        const next = { ...p };
        delete next[index];
        return next;
      });
      onAcceptSlide(index);
    },
    [onAcceptSlide],
  );

  /** Reject a diff: mark it rejected, un-accept if previously accepted, then notify parent. */
  const handleReject = useCallback(
    (index: number) => {
      setRejected((p) => ({ ...p, [index]: true }));
      setAccepted((p) => {
        const next = { ...p };
        delete next[index];
        return next;
      });
      onRejectSlide(index);
    },
    [onRejectSlide],
  );

  /** Accept every non-unchanged diff in a single action. */
  const handleAcceptAll = useCallback(() => {
    if (!compareResult) return;
    const acc: Record<number, boolean> = {};
    compareResult.diffs.forEach((d, i) => {
      if (d.status !== "unchanged") acc[i] = true;
    });
    setAccepted(acc);
    setRejected({});
    onAcceptAll();
  }, [compareResult, onAcceptAll]);

  if (!isOpen || !compareResult) return null;

  const nonTrivialDiffs = compareResult.diffs.filter(
    (d) => d.status !== "unchanged",
  );

  return (
    <div className="fixed inset-y-0 right-0 z-50 flex flex-col w-[440px] border-l border-border bg-popover backdrop-blur-lg shadow-2xl">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border">
        <div>
          <h3 className="text-sm font-medium text-foreground">
            {t("pptx.compare.title")}
          </h3>
          <p className="text-[11px] text-muted-foreground mt-0.5">
            {t("pptx.compare.summary", {
              added: compareResult.addedCount,
              removed: compareResult.removedCount,
              changed: compareResult.changedCount,
            })}
          </p>
        </div>
        <button
          type="button"
          className="rounded p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
          onClick={onClose}
          title={t("pptx.compare.close")}
        >
          <LuX className="w-4 h-4" />
        </button>
      </div>

      {/* Accept All button */}
      {nonTrivialDiffs.length > 0 && (
        <div className="px-4 py-2 border-b border-border/60">
          <button
            type="button"
            className="inline-flex items-center gap-1.5 rounded bg-green-700/80 px-3 py-1.5 text-xs text-green-50 hover:bg-green-600 transition-colors"
            onClick={handleAcceptAll}
          >
            <LuCheck className="w-3.5 h-3.5" />
            {t("pptx.compare.acceptAll")}
          </button>
        </div>
      )}

      {/* Diff list */}
      <div className="flex-1 overflow-y-auto px-3 py-3 space-y-2">
        {nonTrivialDiffs.length === 0 ? (
          <div className="text-center py-8 text-xs text-muted-foreground">
            {t("pptx.compare.noDifferences")}
          </div>
        ) : (
          compareResult.diffs.map((diff, i) => (
            <SlideDiffRow
              key={`diff-${i}-${diff.status}`}
              diff={diff}
              diffIndex={i}
              canvasSize={canvasSize}
              accepted={Boolean(accepted[i])}
              rejected={Boolean(rejected[i])}
              onAccept={handleAccept}
              onReject={handleReject}
            />
          ))
        )}
      </div>
    </div>
  );
}

// packages/vue/src/viewer/components/ComparePanel.vue
<script setup lang="ts">
import { X } from 'lucide-vue-next';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import type { CompareResult } from '../composables/slide-compare';
import type { CanvasSize } from '../types';
import SlideDiffRow from './SlideDiffRow.vue';

/**
 * ComparePanel: side panel showing slide-level diffs between two versions.
 *
 * Vue port of the React `ComparePanel.tsx`. Lists each non-trivial
 * {@link SlideDiff} as a {@link SlideDiffRow}; the user can accept/reject
 * individual diffs or accept all at once. Accepted/rejected state is tracked
 * locally and propagated to the host via emits, which carry the diff index.
 */
const props = defineProps<{
	/** Whether the panel is visible. */
	open: boolean;
	/** The comparison result, or `null` when nothing to compare. */
	compareResult: CompareResult | null;
	/** Canvas dimensions used to render diff thumbnails. */
	canvasSize: CanvasSize;
	/** Resolved media data URLs for thumbnail rendering. */
	mediaDataUrls: Map<string, string>;
}>();

const emit = defineEmits<{
	(e: 'close' | 'accept-all'): void;
	(e: 'accept-slide' | 'reject-slide', diffIndex: number): void;
}>();

const { t } = useI18n();

const accepted = ref<Record<number, boolean>>({});
const rejected = ref<Record<number, boolean>>({});

const nonTrivialCount = computed(
	() => props.compareResult?.diffs.filter((d) => d.status !== 'unchanged').length ?? 0,
);

function handleAccept(index: number): void {
	accepted.value = { ...accepted.value, [index]: true };
	const next = { ...rejected.value };
	delete next[index];
	rejected.value = next;
	emit('accept-slide', index);
}

function handleReject(index: number): void {
	rejected.value = { ...rejected.value, [index]: true };
	const next = { ...accepted.value };
	delete next[index];
	accepted.value = next;
	emit('reject-slide', index);
}

function handleAcceptAll(): void {
	if (!props.compareResult) {
		return;
	}
	const acc: Record<number, boolean> = {};
	props.compareResult.diffs.forEach((d, i) => {
		if (d.status !== 'unchanged') {
			acc[i] = true;
		}
	});
	accepted.value = acc;
	rejected.value = {};
	emit('accept-all');
}
</script>

<template>
	<aside
		v-if="open && compareResult"
		class="pptx-vue-compare-panel fixed inset-y-0 right-0 z-50 flex w-[440px] max-w-[100vw] flex-col border-l border-border bg-popover text-foreground shadow-2xl backdrop-blur-lg"
	>
		<header
			class="pptx-vue-compare-header flex items-start justify-between gap-3 border-b border-border px-4 py-3"
		>
			<div>
				<h3 class="pptx-vue-compare-title m-0 text-sm font-medium text-foreground">
					{{ t('pptx.compare.title') }}
				</h3>
				<p class="pptx-vue-compare-summary mt-0.5 text-[11px] text-muted-foreground">
					{{
						t('pptx.compare.summary', {
							added: compareResult.addedCount,
							removed: compareResult.removedCount,
							changed: compareResult.changedCount,
						})
					}}
				</p>
			</div>
			<button
				type="button"
				class="pptx-vue-compare-close inline-flex h-6 w-6 items-center justify-center rounded p-0 text-lg leading-none text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
				:aria-label="t('pptx.compare.close')"
				@click="emit('close')"
			>
				<X class="h-4 w-4" aria-hidden="true" />
			</button>
		</header>

		<div
			v-if="nonTrivialCount > 0"
			class="pptx-vue-compare-actions border-b border-border/60 px-4 py-2"
		>
			<button
				type="button"
				class="pptx-vue-compare-accept-all inline-flex cursor-pointer items-center gap-1.5 rounded bg-green-700/80 px-3 py-1.5 text-xs text-green-50 transition-colors hover:bg-green-600"
				@click="handleAcceptAll"
			>
				{{ t('pptx.compare.acceptAll') }}
			</button>
		</div>

		<div class="pptx-vue-compare-list flex flex-1 flex-col gap-2 overflow-y-auto p-3">
			<p
				v-if="nonTrivialCount === 0"
				class="pptx-vue-compare-empty m-0 py-8 text-center text-xs text-muted-foreground"
			>
				{{ t('pptx.compare.noDifferences') }}
			</p>
			<template v-else>
				<SlideDiffRow
					v-for="(diff, i) in compareResult.diffs"
					:key="`diff-${i}-${diff.status}`"
					:diff="diff"
					:diff-index="i"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:accepted="Boolean(accepted[i])"
					:rejected="Boolean(rejected[i])"
					@accept="handleAccept"
					@reject="handleReject"
				/>
			</template>
		</div>
	</aside>
</template>
