// packages/react/src/viewer/components/DocumentPropertiesDialog.tsx
import React, { useState, useCallback, useMemo } from "react";
import { LuFileText, LuX } from "react-icons/lu";
import { useTranslation } from "react-i18next";

import type {
  PptxAppProperties,
  PptxCoreProperties,
  PptxCustomProperty,
} from "pptx-viewer-core";
import { DocumentPropertiesCustomTab } from "./DocumentPropertiesCustomTab";
import { DocumentPropertiesStatisticsTab } from "./DocumentPropertiesStatisticsTab";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Props for the {@link DocumentPropertiesDialog} component.
 */
export interface DocumentPropertiesDialogProps {
  /** Whether the dialog is visible. */
  isOpen: boolean;
  /** Core document metadata (title, author, keywords, etc.). */
  coreProperties: PptxCoreProperties;
  /** User-defined custom properties attached to the presentation. */
  customProperties: PptxCustomProperty[];
  /** Application-level metadata (company, version, etc.). */
  appProperties?: PptxAppProperties;
  /** Callback invoked when the dialog is dismissed without saving. */
  onClose: () => void;
  /** Callback invoked with updated property values when the user saves. */
  onSave: (
    core: PptxCoreProperties,
    custom: PptxCustomProperty[],
    app?: Partial<PptxAppProperties>,
  ) => void;
}

/** Identifies the active tab inside the Document Properties dialog. */
type TabId = "summary" | "custom" | "statistics";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Field definitions for the Summary tab — maps core property keys to i18n labels. */
const SUMMARY_FIELDS: Array<{
  key: keyof PptxCoreProperties;
  labelKey: string;
  multiline?: boolean;
}> = [
  { key: "title", labelKey: "pptx.documentProperties.summary.title" },
  { key: "subject", labelKey: "pptx.documentProperties.summary.subject" },
  { key: "creator", labelKey: "pptx.documentProperties.summary.author" },
  { key: "keywords", labelKey: "pptx.documentProperties.summary.keywords" },
  {
    key: "description",
    labelKey: "pptx.documentProperties.summary.description",
    multiline: true,
  },
  { key: "category", labelKey: "pptx.documentProperties.summary.category" },
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * Tabbed modal dialog for viewing and editing document properties.
 *
 * Contains three tabs:
 * - **Summary** -- core metadata fields (title, author, keywords, etc.)
 * - **Custom** -- user-defined key/value properties
 * - **Statistics** -- read-only app metadata plus editable company/manager
 *
 * Draft state is maintained locally and only committed via `onSave` when
 * the user clicks Save. A dirty-check prevents no-op saves.
 *
 * @param props - {@link DocumentPropertiesDialogProps}
 * @returns The dialog element, or `null` when `isOpen` is `false`.
 */
export function DocumentPropertiesDialog({
  isOpen,
  coreProperties,
  customProperties,
  appProperties,
  onClose,
  onSave,
}: DocumentPropertiesDialogProps): React.ReactElement | null {
  const { t } = useTranslation();

  const [activeTab, setActiveTab] = useState<TabId>("summary");
  const [draftCore, setDraftCore] = useState<PptxCoreProperties>({});
  const [draftCustom, setDraftCustom] = useState<PptxCustomProperty[]>([]);
  const [draftApp, setDraftApp] = useState<Partial<PptxAppProperties>>({});

  // Sync draft state when dialog opens
  const [prevOpen, setPrevOpen] = useState(false);
  if (isOpen && !prevOpen) {
    setDraftCore({ ...coreProperties });
    setDraftCustom(customProperties.map((p) => ({ ...p })));
    setDraftApp({
      company: appProperties?.company,
      manager: appProperties?.manager,
    });
    setActiveTab("summary");
  }
  if (isOpen !== prevOpen) {
    setPrevOpen(isOpen);
  }

  const handleCoreFieldChange = useCallback(
    (key: keyof PptxCoreProperties, value: string) => {
      setDraftCore((prev) => ({ ...prev, [key]: value }));
    },
    [],
  );

  const isDirty = useMemo(() => {
    const coreChanged = SUMMARY_FIELDS.some(
      ({ key }) => (draftCore[key] ?? "") !== (coreProperties[key] ?? ""),
    );
    if (coreChanged) return true;
    const appCompanyChanged =
      (draftApp.company ?? "") !== (appProperties?.company ?? "");
    const appManagerChanged =
      (draftApp.manager ?? "") !== (appProperties?.manager ?? "");
    if (appCompanyChanged || appManagerChanged) return true;
    if (draftCustom.length !== customProperties.length) return true;
    return draftCustom.some(
      (p, i) =>
        p.name !== customProperties[i]?.name ||
        p.value !== customProperties[i]?.value ||
        p.type !== customProperties[i]?.type,
    );
  }, [
    draftCore,
    draftCustom,
    draftApp,
    coreProperties,
    customProperties,
    appProperties,
  ]);

  const handleUpdateDraftApp = useCallback(
    (updates: Partial<PptxAppProperties>) => {
      setDraftApp((prev) => ({ ...prev, ...updates }));
    },
    [],
  );

  const handleSave = useCallback(() => {
    const appChanged =
      (draftApp.company ?? "") !== (appProperties?.company ?? "") ||
      (draftApp.manager ?? "") !== (appProperties?.manager ?? "");
    onSave(draftCore, draftCustom, appChanged ? draftApp : undefined);
    onClose();
  }, [draftCore, draftCustom, draftApp, appProperties, onSave, onClose]);

  const handleClose = useCallback(() => {
    onClose();
  }, [onClose]);

  if (!isOpen) return null;

  const TABS: Array<{ id: TabId; labelKey: string }> = [
    { id: "summary", labelKey: "pptx.documentProperties.tabs.summary" },
    { id: "custom", labelKey: "pptx.documentProperties.tabs.custom" },
    { id: "statistics", labelKey: "pptx.documentProperties.tabs.statistics" },
  ];

  return (
    <>
      {/* Backdrop */}
      <button
        type="button"
        className="fixed inset-0 z-50 bg-black/60"
        aria-label={t("common.close")}
        onClick={handleClose}
      />
      {/* Dialog */}
      <div className="fixed inset-0 z-50 flex items-center justify-center pointer-events-none">
        <div className="pointer-events-auto w-[520px] rounded-xl border border-border bg-popover backdrop-blur-xl shadow-2xl">
          {/* Header */}
          <div className="flex items-center justify-between px-5 py-4 border-b border-border/60">
            <div className="flex items-center gap-2">
              <LuFileText className="w-5 h-5 text-primary" />
              <h2 className="text-sm font-semibold text-foreground">
                {t("pptx.documentProperties.dialogTitle")}
              </h2>
            </div>
            <button
              type="button"
              onClick={handleClose}
              className="p-1 rounded hover:bg-accent transition-colors"
              aria-label={t("common.close")}
            >
              <LuX className="w-4 h-4 text-muted-foreground" />
            </button>
          </div>

          {/* Tabs */}
          <div className="flex border-b border-border/60">
            {TABS.map((tab) => (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id)}
                className={`px-4 py-2 text-xs font-medium transition-colors ${
                  activeTab === tab.id
                    ? "text-primary border-b-2 border-primary"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                {t(tab.labelKey)}
              </button>
            ))}
          </div>

          {/* Body */}
          <div className="px-5 py-4 min-h-[280px]">
            {activeTab === "summary" && (
              <div className="space-y-3">
                {SUMMARY_FIELDS.map(({ key, labelKey, multiline }) => (
                  <div key={key}>
                    <label className="block text-xs text-foreground mb-1">
                      {t(labelKey)}
                    </label>
                    {multiline ? (
                      <textarea
                        className="w-full rounded-lg border border-border bg-muted px-3 py-2 text-sm text-foreground placeholder-muted-foreground focus:border-primary focus:ring-1 focus:ring-primary outline-none resize-none"
                        rows={3}
                        value={draftCore[key] ?? ""}
                        onChange={(e) =>
                          handleCoreFieldChange(key, e.target.value)
                        }
                      />
                    ) : (
                      <input
                        type="text"
                        className="w-full rounded-lg border border-border bg-muted px-3 py-2 text-sm text-foreground placeholder-muted-foreground focus:border-primary focus:ring-1 focus:ring-primary outline-none"
                        value={draftCore[key] ?? ""}
                        onChange={(e) =>
                          handleCoreFieldChange(key, e.target.value)
                        }
                      />
                    )}
                  </div>
                ))}
              </div>
            )}

            {activeTab === "custom" && (
              <DocumentPropertiesCustomTab
                customProperties={draftCustom}
                onUpdate={setDraftCustom}
              />
            )}

            {activeTab === "statistics" && (
              <DocumentPropertiesStatisticsTab
                appProperties={{
                  ...(appProperties ?? {}),
                  company: draftApp.company,
                  manager: draftApp.manager,
                }}
                onUpdateAppProperties={handleUpdateDraftApp}
                canEdit={true}
              />
            )}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-end gap-2 px-5 py-3 border-t border-border/60">
            <button
              type="button"
              onClick={handleClose}
              className="px-3 py-1.5 text-xs rounded-lg border border-border text-foreground hover:bg-muted transition-colors"
            >
              {t("common.cancel")}
            </button>
            <button
              type="button"
              onClick={handleSave}
              disabled={!isDirty}
              className="px-3 py-1.5 text-xs rounded-lg bg-primary text-white hover:bg-primary/80 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
            >
              {t("common.save")}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

// packages/vue/src/viewer/components/DocumentPropertiesDialog.vue
<script setup lang="ts">
import type {
	PptxAppProperties,
	PptxCoreProperties,
	PptxCustomProperty,
	PptxSlide,
} from 'pptx-viewer-core';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { computeDocumentStatistics } from '../composables/useDocumentStatistics';
import type { DocumentStatistics } from '../composables/useDocumentStatistics';
import DocumentPropertiesCustomTab from './DocumentPropertiesCustomTab.vue';
import DocumentPropertiesGeneralTab from './DocumentPropertiesGeneralTab.vue';
import type { GeneralCoreKey } from './DocumentPropertiesGeneralTab.vue';
import DocumentPropertiesStatisticsTab from './DocumentPropertiesStatisticsTab.vue';
import ModalDialog from './ModalDialog.vue';

type TabId = 'general' | 'statistics' | 'custom';

/**
 * Payload emitted on save. Mirrors the React `onSave(core, custom, app?)`
 * signature, collapsed into a single patch object so the host can apply it in
 * one call. `app` is only present when manager/company changed.
 */
export interface DocumentPropertiesSavePatch {
	/** Full edited core-properties draft. */
	core: PptxCoreProperties;
	/** Full edited custom-properties list. */
	custom: PptxCustomProperty[];
	/** Edited app properties (manager/company); omitted when unchanged. */
	app?: Pick<PptxAppProperties, 'manager' | 'company'>;
}

/**
 * DocumentPropertiesDialog: the full tabbed Document Properties dialog.
 *
 * Vue port of React's `DocumentPropertiesDialog`, built on `ModalDialog`. Three
 * tabs:
 *  - **General**: editable core metadata (title/subject/author/keywords/
 *    comments/category) plus app-level manager/company.
 *  - **Statistics**: read-only counts computed live from the slide model
 *    (`computeDocumentStatistics`) + timestamps/revision from core properties.
 *  - **Custom**: add/remove/edit user-defined custom properties.
 *
 * Draft state is held locally and re-seeded each time the dialog opens; nothing
 * is committed until the user clicks Save, which emits a single
 * {@link DocumentPropertiesSavePatch}. A dirty check disables no-op saves.
 */
const props = defineProps<{
	/** Whether the dialog is visible. */
	open: boolean;
	/** Parsed document core properties. */
	coreProperties: PptxCoreProperties | undefined;
	/** Parsed custom properties (defaults to empty). */
	customProperties?: PptxCustomProperty[];
	/** Parsed app properties; only manager/company are editable here. */
	appProperties?: PptxAppProperties;
	/** Live slide model, used to compute the Statistics tab. */
	slides: PptxSlide[];
}>();

const emit = defineEmits<{
	/** Fired with the edited properties when the user saves. */
	(e: 'save', patch: DocumentPropertiesSavePatch): void;
	/** Fired when the dialog is dismissed without saving. */
	(e: 'close'): void;
}>();

const { t } = useI18n();

const TABS: Array<{ id: TabId; labelKey: string }> = [
	{ id: 'general', labelKey: 'pptx.documentProperties.tabs.general' },
	{ id: 'statistics', labelKey: 'pptx.documentProperties.tabs.statistics' },
	{ id: 'custom', labelKey: 'pptx.documentProperties.tabs.custom' },
];

const activeTab = ref<TabId>('general');
const draftCore = ref<PptxCoreProperties>({});
const draftCustom = ref<PptxCustomProperty[]>([]);
const draftManager = ref('');
const draftCompany = ref('');

function seedDraft(): void {
	draftCore.value = { ...(props.coreProperties ?? {}) };
	draftCustom.value = (props.customProperties ?? []).map((p) => ({ ...p }));
	draftManager.value = props.appProperties?.manager ?? '';
	draftCompany.value = props.appProperties?.company ?? '';
	activeTab.value = 'general';
}

watch(
	() => props.open,
	(isOpen) => {
		if (isOpen) {
			seedDraft();
		}
	},
	{ immediate: true },
);

const statistics = computed<DocumentStatistics>(() =>
	computeDocumentStatistics(props.slides, props.coreProperties),
);

function updateCore(key: GeneralCoreKey, value: string): void {
	draftCore.value = { ...draftCore.value, [key]: value };
}

function updateCustom(next: PptxCustomProperty[]): void {
	draftCustom.value = next;
}

const isDirty = computed<boolean>(() => {
	const core = props.coreProperties ?? {};
	const coreKeys: GeneralCoreKey[] = [
		'title',
		'subject',
		'creator',
		'keywords',
		'description',
		'category',
	];
	const coreChanged = coreKeys.some((key) => (draftCore.value[key] ?? '') !== (core[key] ?? ''));
	if (coreChanged) {
		return true;
	}

	if (draftManager.value !== (props.appProperties?.manager ?? '')) {
		return true;
	}
	if (draftCompany.value !== (props.appProperties?.company ?? '')) {
		return true;
	}

	const original = props.customProperties ?? [];
	if (draftCustom.value.length !== original.length) {
		return true;
	}
	return draftCustom.value.some(
		(p, i) =>
			p.name !== original[i]?.name ||
			p.value !== original[i]?.value ||
			p.type !== original[i]?.type,
	);
});

function handleSave(): void {
	const appChanged =
		draftManager.value !== (props.appProperties?.manager ?? '') ||
		draftCompany.value !== (props.appProperties?.company ?? '');

	const patch: DocumentPropertiesSavePatch = {
		core: { ...draftCore.value },
		custom: draftCustom.value.map((p) => ({ ...p })),
	};
	if (appChanged) {
		patch.app = { manager: draftManager.value, company: draftCompany.value };
	}
	emit('save', patch);
	emit('close');
}
</script>

<template>
	<ModalDialog
		:open="open"
		:title="t('pptx.documentProperties.dialogTitle')"
		@close="emit('close')"
	>
		<div class="pptx-vue-docprops flex min-w-[360px] flex-col gap-3 max-md:min-w-0">
			<div class="pptx-vue-docprops-tabs flex border-b border-border/60" role="tablist">
				<button
					v-for="tab in TABS"
					:key="tab.id"
					type="button"
					role="tab"
					:aria-selected="activeTab === tab.id"
					class="pptx-vue-docprops-tab px-4 py-2 text-xs font-medium transition-colors"
					:class="
						activeTab === tab.id
							? 'pptx-vue-docprops-tab-active border-b-2 border-primary text-primary'
							: 'text-muted-foreground hover:text-foreground'
					"
					@click="activeTab = tab.id"
				>
					{{ t(tab.labelKey) }}
				</button>
			</div>

			<div class="pptx-vue-docprops-body min-h-[280px]">
				<DocumentPropertiesGeneralTab
					v-if="activeTab === 'general'"
					:core="draftCore"
					:manager="draftManager"
					:company="draftCompany"
					@update-core="updateCore"
					@update-manager="draftManager = $event"
					@update-company="draftCompany = $event"
				/>
				<DocumentPropertiesStatisticsTab
					v-else-if="activeTab === 'statistics'"
					:statistics="statistics"
				/>
				<DocumentPropertiesCustomTab
					v-else
					:custom-properties="draftCustom"
					@update="updateCustom"
				/>
			</div>
		</div>

		<template #footer>
			<button
				type="button"
				class="pptx-vue-docprops-btn rounded-md border border-border px-3 py-1.5 text-xs text-foreground transition-colors hover:bg-muted"
				@click="emit('close')"
			>
				{{ t('pptx.comments.cancel') }}
			</button>
			<button
				type="button"
				class="pptx-vue-docprops-btn pptx-vue-docprops-btn-primary rounded-md border border-transparent bg-primary px-3 py-1.5 text-xs text-primary-foreground transition-colors hover:bg-primary/80 disabled:cursor-not-allowed disabled:opacity-40"
				:disabled="!isDirty"
				@click="handleSave"
			>
				{{ t('pptx.comments.save') }}
			</button>
		</template>
	</ModalDialog>
</template>
