// packages/react/src/viewer/components/HeaderFooterPanel.tsx
import type { PptxHeaderFooter } from 'pptx-viewer-core';
import {
	isHeaderFooterDateTextVisible,
	isHeaderFooterHeaderTextVisible,
	isHeaderFooterFooterTextVisible,
} from 'pptx-viewer-shared';
import React, { useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { LuCalendarDays, LuClock, LuFileText, LuHash, LuText, LuX } from 'react-icons/lu';

import { WebCheckbox } from './WebControls';

import { DialogFooter } from './DialogFooter';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface HeaderFooterPanelProps {
	headerFooter: PptxHeaderFooter;
	onUpdate: (patch: Partial<PptxHeaderFooter>) => void;
	onApplyToAll: () => void;
	onApplyToCurrent: () => void;
	onClose: () => void;
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

interface ToggleRowProps {
	checked: boolean;
	onChange: (checked: boolean) => void;
	icon: React.ReactNode;
	label: string;
	testId?: string;
}

function ToggleRow({ checked, onChange, icon, label, testId }: ToggleRowProps): React.ReactElement {
	return (
		<label className='flex items-center gap-2.5 cursor-pointer group select-none'>
			<WebCheckbox
				checked={checked}
				onChange={(e) => onChange(e.target.checked)}
				data-testid={testId}
			/>
			<span className='flex items-center gap-1.5 text-xs text-foreground group-hover:text-foreground transition-colors'>
				{icon}
				{label}
			</span>
		</label>
	);
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

/**
 * Header & Footer dialog. Covers the same `PptxHeaderFooter` fields Vue and
 * Angular's ports cover (this used to be React-only booleans for date/time,
 * slide number and footer with no header field and no auto/fixed date
 * distinction; Vue/Angular's ports already carried both).
 */
export function HeaderFooterPanel({
	headerFooter,
	onUpdate,
	onApplyToAll,
	onApplyToCurrent,
	onClose,
}: HeaderFooterPanelProps): React.ReactElement {
	const { t } = useTranslation();

	const showDateTime = headerFooter.hasDateTime ?? false;
	const dateTimeAuto = headerFooter.dateTimeAuto ?? false;
	const showDateText = isHeaderFooterDateTextVisible(headerFooter);
	const showSlideNumber = headerFooter.hasSlideNumber ?? false;
	const showHeader = headerFooter.hasHeader ?? false;
	const showHeaderText = isHeaderFooterHeaderTextVisible(headerFooter);
	const showFooter = headerFooter.hasFooter ?? false;
	const showFooterText = isHeaderFooterFooterTextVisible(headerFooter);

	const handleDateTextChange = useCallback(
		(e: React.ChangeEvent<HTMLInputElement>) => onUpdate({ dateTimeText: e.target.value }),
		[onUpdate],
	);
	const handleHeaderTextChange = useCallback(
		(e: React.ChangeEvent<HTMLInputElement>) => onUpdate({ headerText: e.target.value }),
		[onUpdate],
	);
	const handleFooterTextChange = useCallback(
		(e: React.ChangeEvent<HTMLInputElement>) => onUpdate({ footerText: e.target.value }),
		[onUpdate],
	);

	return (
		<div className='absolute inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm'>
			<div className='w-full max-w-sm rounded-lg border border-border bg-background shadow-2xl'>
				{/* ── Header ── */}
				<div className='flex items-center justify-between border-b border-border px-4 py-3'>
					<h2 className='text-sm font-semibold text-foreground'>{t('pptx.headerFooter.title')}</h2>
					<button
						type='button'
						onClick={onClose}
						className='rounded p-1 text-muted-foreground hover:bg-muted hover:text-foreground transition-colors'
						aria-label={t('pptx.headerFooter.close')}
						data-testid='header-footer-close'
					>
						<LuX className='w-4 h-4' />
					</button>
				</div>

				{/* ── Body ── */}
				<div className='space-y-4 px-4 py-4'>
					{/* Toggle: Date/Time */}
					<ToggleRow
						checked={showDateTime}
						onChange={(hasDateTime) => onUpdate({ hasDateTime })}
						icon={<LuCalendarDays className='w-3.5 h-3.5' />}
						label={t('pptx.headerFooter.dateAndTime')}
						testId='hf-date-time'
					/>

					{showDateTime && (
						<div className='pl-6 space-y-2'>
							<ToggleRow
								checked={dateTimeAuto}
								onChange={(auto) => onUpdate({ dateTimeAuto: auto })}
								icon={<LuClock className='w-3.5 h-3.5' />}
								label={t('pptx.headerFooter.updateAutomatically')}
								testId='hf-date-auto'
							/>
							{showDateText && (
								<input
									type='text'
									value={headerFooter.dateTimeText ?? ''}
									onChange={handleDateTextChange}
									placeholder={t('pptx.headerFooter.fixedDate')}
									data-testid='hf-date-text'
									className='w-full rounded border border-border bg-muted px-2.5 py-1.5 text-xs text-foreground placeholder-muted-foreground outline-none transition-colors focus:border-primary focus:ring-1 focus:ring-primary/30'
								/>
							)}
						</div>
					)}

					{/* Toggle: Slide number */}
					<ToggleRow
						checked={showSlideNumber}
						onChange={(hasSlideNumber) => onUpdate({ hasSlideNumber })}
						icon={<LuHash className='w-3.5 h-3.5' />}
						label={t('pptx.headerFooter.slideNumber')}
						testId='hf-slide-number'
					/>

					{/* Toggle: Header */}
					<ToggleRow
						checked={showHeader}
						onChange={(hasHeader) => onUpdate({ hasHeader })}
						icon={<LuFileText className='w-3.5 h-3.5' />}
						label={t('pptx.field.header')}
						testId='hf-header'
					/>

					{showHeaderText && (
						<div className='pl-6'>
							<input
								type='text'
								value={headerFooter.headerText ?? ''}
								onChange={handleHeaderTextChange}
								placeholder={t('pptx.headerFooter.headerText')}
								data-testid='hf-header-text'
								className='w-full rounded border border-border bg-muted px-2.5 py-1.5 text-xs text-foreground placeholder-muted-foreground outline-none transition-colors focus:border-primary focus:ring-1 focus:ring-primary/30'
							/>
						</div>
					)}

					{/* Toggle: Footer */}
					<ToggleRow
						checked={showFooter}
						onChange={(hasFooter) => onUpdate({ hasFooter })}
						icon={<LuText className='w-3.5 h-3.5' />}
						label={t('pptx.headerFooter.footer')}
						testId='hf-footer'
					/>

					{/* Footer text input: only visible when footer is enabled */}
					{showFooterText && (
						<div className='pl-6'>
							<input
								type='text'
								value={headerFooter.footerText ?? ''}
								onChange={handleFooterTextChange}
								placeholder={t('pptx.headerFooter.footerPlaceholder')}
								data-testid='hf-footer-text'
								className='w-full rounded border border-border bg-muted px-2.5 py-1.5 text-xs text-foreground placeholder-muted-foreground outline-none transition-colors focus:border-primary focus:ring-1 focus:ring-primary/30'
							/>
						</div>
					)}
				</div>

				{/* ── Footer actions ── */}
				<div className='flex items-center justify-end gap-2 border-t border-border px-4 py-3'>
					<DialogFooter
						actions={[
							{ id: 'applyAll', label: t('pptx.headerFooter.applyToAll'), testId: 'hf-apply-all' },
							{
								id: 'applyCurrent',
								label: t('pptx.headerFooter.applyToCurrent'),
								variant: 'primary',
								testId: 'hf-apply-current',
							},
						]}
						onAction={(id) => (id === 'applyAll' ? onApplyToAll() : onApplyToCurrent())}
					/>
				</div>
			</div>
		</div>
	);
}

// packages/vue/src/viewer/components/HeaderFooterPanel.vue
<script setup lang="ts">
import { X } from 'lucide-vue-next';
import type { PptxHeaderFooter } from 'pptx-viewer-core';
/**
 * HeaderFooterPanel: edit the presentation's header/footer placeholders.
 *
 * Vue port of the React `HeaderFooterPanel.tsx`, adapted to the Vue port's
 * data-driven contract: instead of a bundle of separate boolean/text props +
 * `onSetX` callbacks, this panel takes the real core `PptxHeaderFooter` object
 * and, on Apply, emits a fully-formed `update(next)` with the edited copy. The
 * host applies the change (e.g. to `PptxData.headerFooter`).
 *
 * Edits are held in a local draft (matching the Angular port) so toggling a
 * checkbox does not commit and close the dialog; only the Apply buttons do.
 *
 * Covers the visibility flags (date/time, slide number, header, footer) plus the
 * date/footer/header text fields and the date auto/fixed toggle.
 *
 * Props : `{ headerFooter: PptxHeaderFooter | undefined }`
 * Emits : `update: [next: PptxHeaderFooter]`, `close: []`
 */
import {
	cloneHeaderFooterDraft,
	isHeaderFooterDateTextVisible,
	isHeaderFooterFooterTextVisible,
	isHeaderFooterHeaderTextVisible,
	patchHeaderFooterDraft,
} from 'pptx-viewer-shared';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import DialogFooter from './DialogFooter.vue';

const props = defineProps<{
	headerFooter: PptxHeaderFooter | undefined;
}>();

const { t } = useI18n();

const emit = defineEmits<{
	update: [next: PptxHeaderFooter];
	close: [];
}>();

/** Local draft, re-seeded from the incoming prop each time the dialog opens. */
const draft = ref<PptxHeaderFooter>(cloneHeaderFooterDraft(props.headerFooter));
watch(
	() => props.headerFooter,
	(next) => {
		draft.value = cloneHeaderFooterDraft(next);
	},
);

function patch(changes: Partial<PptxHeaderFooter>): void {
	draft.value = patchHeaderFooterDraft(draft.value, changes);
}

function apply(): void {
	emit('update', draft.value);
	emit('close');
}

const showDateTime = computed(() => draft.value.hasDateTime ?? false);
const showSlideNumber = computed(() => draft.value.hasSlideNumber ?? false);
const showHeader = computed(() => draft.value.hasHeader ?? false);
const showFooter = computed(() => draft.value.hasFooter ?? false);
const dateTimeAuto = computed(() => draft.value.dateTimeAuto ?? false);
const showDateText = computed(() => isHeaderFooterDateTextVisible(draft.value));
const showHeaderText = computed(() => isHeaderFooterHeaderTextVisible(draft.value));
const showFooterText = computed(() => isHeaderFooterFooterTextVisible(draft.value));

function onToggleDateTime(event: Event): void {
	patch({ hasDateTime: (event.target as HTMLInputElement).checked });
}
function onToggleSlideNumber(event: Event): void {
	patch({ hasSlideNumber: (event.target as HTMLInputElement).checked });
}
function onToggleHeader(event: Event): void {
	patch({ hasHeader: (event.target as HTMLInputElement).checked });
}
function onToggleFooter(event: Event): void {
	patch({ hasFooter: (event.target as HTMLInputElement).checked });
}
function onToggleDateAuto(event: Event): void {
	patch({ dateTimeAuto: (event.target as HTMLInputElement).checked });
}
function onHeaderText(event: Event): void {
	patch({ headerText: (event.target as HTMLInputElement).value });
}
function onFooterText(event: Event): void {
	patch({ footerText: (event.target as HTMLInputElement).value });
}
function onDateText(event: Event): void {
	patch({ dateTimeText: (event.target as HTMLInputElement).value });
}
</script>

<template>
	<div
		class="pptx-vue-header-footer-panel"
		role="dialog"
		:aria-label="t('pptx.headerFooter.title')"
	>
		<header class="pptx-vue-header-footer-panel__header">
			<h2 class="pptx-vue-header-footer-panel__title">{{ t('pptx.headerFooter.title') }}</h2>
			<button
				type="button"
				class="pptx-vue-header-footer-panel__close"
				:aria-label="t('pptx.headerFooter.close')"
				data-testid="header-footer-close"
				@click="emit('close')"
			>
				<X class="h-4 w-4" aria-hidden="true" />
			</button>
		</header>

		<div class="pptx-vue-header-footer-panel__body">
			<label class="pptx-vue-header-footer-panel__row">
				<pptx-ui-checkbox
					data-testid="hf-date-time"
					:checked="showDateTime"
					@change="onToggleDateTime"
				/>
				<span>{{ t('pptx.headerFooter.dateAndTime') }}</span>
			</label>

			<div v-if="showDateTime" class="pptx-vue-header-footer-panel__sub">
				<label class="pptx-vue-header-footer-panel__row">
					<pptx-ui-checkbox
						data-testid="hf-date-auto"
						:checked="dateTimeAuto"
						@change="onToggleDateAuto"
					/>
					<span>{{ t('pptx.headerFooter.updateAutomatically') }}</span>
				</label>
				<input
					v-if="showDateText"
					type="text"
					class="pptx-vue-header-footer-panel__input"
					:placeholder="t('pptx.headerFooter.fixedDate')"
					data-testid="hf-date-text"
					:value="draft.dateTimeText ?? ''"
					@input="onDateText"
				/>
			</div>

			<label class="pptx-vue-header-footer-panel__row">
				<pptx-ui-checkbox
					data-testid="hf-slide-number"
					:checked="showSlideNumber"
					@change="onToggleSlideNumber"
				/>
				<span>{{ t('pptx.headerFooter.slideNumber') }}</span>
			</label>

			<label class="pptx-vue-header-footer-panel__row">
				<pptx-ui-checkbox data-testid="hf-header" :checked="showHeader" @change="onToggleHeader" />
				<span>{{ t('pptx.field.header') }}</span>
			</label>

			<div v-if="showHeaderText" class="pptx-vue-header-footer-panel__sub">
				<input
					type="text"
					class="pptx-vue-header-footer-panel__input"
					:placeholder="t('pptx.headerFooter.headerText')"
					data-testid="hf-header-text"
					:value="draft.headerText ?? ''"
					@input="onHeaderText"
				/>
			</div>

			<label class="pptx-vue-header-footer-panel__row">
				<pptx-ui-checkbox data-testid="hf-footer" :checked="showFooter" @change="onToggleFooter" />
				<span>{{ t('pptx.headerFooter.footer') }}</span>
			</label>

			<div v-if="showFooterText" class="pptx-vue-header-footer-panel__sub">
				<input
					type="text"
					class="pptx-vue-header-footer-panel__input"
					:placeholder="t('pptx.headerFooter.footerPlaceholder')"
					data-testid="hf-footer-text"
					:value="draft.footerText ?? ''"
					@input="onFooterText"
				/>
			</div>
		</div>

		<footer class="pptx-vue-header-footer-panel__footer">
			<DialogFooter
				:actions="[
					{ id: 'applyAll', label: t('pptx.headerFooter.applyToAll'), testId: 'hf-apply-all' },
					{
						id: 'applyCurrent',
						label: t('pptx.headerFooter.applyToCurrent'),
						variant: 'primary',
						testId: 'hf-apply-current',
					},
				]"
				@action="apply"
			/>
		</footer>
	</div>
</template>

<style scoped>
.pptx-vue-header-footer-panel {
	display: flex;
	flex-direction: column;
	width: 100%;
	max-width: 360px;
	background: var(--pptx-vue-background, #ffffff);
	color: var(--pptx-vue-foreground, #111827);
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: var(--pptx-vue-radius, 8px);
}

.pptx-vue-header-footer-panel__header {
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 12px 16px;
	border-bottom: 1px solid var(--pptx-vue-border, #e5e7eb);
}

.pptx-vue-header-footer-panel__title {
	margin: 0;
	font-size: 14px;
	font-weight: 600;
}

.pptx-vue-header-footer-panel__close {
	width: 24px;
	height: 24px;
	padding: 0;
	border: none;
	border-radius: 4px;
	background: transparent;
	color: var(--pptx-vue-muted-foreground, #6b7280);
	font-size: 18px;
	line-height: 1;
	cursor: pointer;
}

.pptx-vue-header-footer-panel__close:hover {
	background: var(--pptx-vue-muted, #f3f4f6);
	color: var(--pptx-vue-foreground, #111827);
}

.pptx-vue-header-footer-panel__body {
	display: flex;
	flex-direction: column;
	gap: 14px;
	padding: 16px;
}

.pptx-vue-header-footer-panel__row {
	display: flex;
	align-items: center;
	gap: 10px;
	font-size: 12px;
	cursor: pointer;
	user-select: none;
}

.pptx-vue-header-footer-panel__sub {
	display: flex;
	flex-direction: column;
	gap: 8px;
	padding-left: 24px;
}

.pptx-vue-header-footer-panel__input {
	width: 100%;
	padding: 6px 10px;
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 4px;
	background: var(--pptx-vue-muted, #f9fafb);
	color: var(--pptx-vue-foreground, #111827);
	font-size: 12px;
	box-sizing: border-box;
}

.pptx-vue-header-footer-panel__input:focus {
	outline: none;
	border-color: var(--pptx-vue-primary, #2563eb);
}

.pptx-vue-header-footer-panel__footer {
	display: flex;
	align-items: center;
	justify-content: flex-end;
	gap: 8px;
	padding: 12px 16px;
	border-top: 1px solid var(--pptx-vue-border, #e5e7eb);
}
</style>
