// packages/react/src/viewer/components/mobile/MobileBottomBar.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { LuLayers, LuMessageSquare, LuPlus, LuSettings2, LuStickyNote } from 'react-icons/lu';

import { cn } from '../../utils';

export interface MobileBottomBarProps {
	/** Open the slides panel sheet. */
	onOpenSlides: () => void;
	/** Open the insert sheet (also reachable from menu). */
	onOpenInsert: () => void;
	/** Open the inspector / properties sheet. */
	onOpenInspector: () => void;
	/** Open the comments / review sheet. */
	onOpenComments: () => void;
	/** Toggle the notes drawer. */
	onToggleNotes: () => void;
	/** Currently-active sheet, for highlighting the bar button. */
	activeSheet: 'slides' | 'insert' | 'inspector' | 'comments' | 'notes' | null;
	/** Number of comments on the active slide (for the badge). */
	commentCount?: number;
}

interface Action {
	key: NonNullable<MobileBottomBarProps['activeSheet']>;
	label: string;
	icon: React.ComponentType<{ className?: string }>;
	onClick: () => void;
	badge?: number;
}

/**
 * Persistent mobile bottom action bar: five primary navigation targets that
 * each open a bottom sheet (slides / inspector / comments / notes) or trigger
 * an action (insert). Mirrors the navigation pattern of Office Mobile and
 * Google Slides on small screens.
 */
export function MobileBottomBar({
	onOpenSlides,
	onOpenInsert,
	onOpenInspector,
	onOpenComments,
	onToggleNotes,
	activeSheet,
	commentCount,
}: MobileBottomBarProps): React.ReactElement {
	const { t } = useTranslation();
	const actions: Action[] = [
		{
			key: 'slides',
			label: 'pptx.sections.slides',
			icon: LuLayers,
			onClick: onOpenSlides,
		},
		{
			key: 'insert',
			label: 'pptx.mobileBar.insert',
			icon: LuPlus,
			onClick: onOpenInsert,
		},
		{
			key: 'inspector',
			label: 'pptx.field.format',
			icon: LuSettings2,
			onClick: onOpenInspector,
		},
		{
			key: 'comments',
			label: 'pptx.toolbar.comments',
			icon: LuMessageSquare,
			onClick: onOpenComments,
			badge: commentCount,
		},
		{
			key: 'notes',
			label: 'pptx.notes.title',
			icon: LuStickyNote,
			onClick: onToggleNotes,
		},
	];

	return (
		<nav
			aria-label={t('pptx.mobileBar.ariaLabel')}
			// Visibility is owned by the parent (rendered only when `isMobile`), so
			// no width-based `md:hidden` here; that would wrongly hide the bar on a
			// wide-but-short landscape phone, which is still mobile.
			className='flex items-stretch justify-around border-t border-border bg-secondary/80 backdrop-blur supports-[backdrop-filter]:bg-secondary/60 pb-[max(env(safe-area-inset-bottom),0px)]'
		>
			{actions.map(({ key, label, icon: Icon, onClick, badge }) => {
				const active = activeSheet === key;
				return (
					<button
						key={key}
						type='button'
						onClick={onClick}
						className={cn(
							'relative flex flex-col items-center justify-center gap-0.5 flex-1 min-h-[56px] py-1.5 text-[10px] font-medium transition-colors active:scale-95',
							active ? 'text-primary' : 'text-muted-foreground hover:text-foreground',
						)}
						aria-pressed={active}
					>
						<Icon className='w-5 h-5' />
						<span>{t(label)}</span>
						{badge !== undefined && badge > 0 && (
							<span className='absolute top-1 right-1/4 flex items-center justify-center min-w-[16px] h-4 px-1 rounded-full bg-primary text-[9px] font-semibold text-white'>
								{badge > 99 ? '99+' : badge}
							</span>
						)}
						{active && (
							<span className='absolute top-0 left-1/2 -translate-x-1/2 w-8 h-0.5 rounded-full bg-primary' />
						)}
					</button>
				);
			})}
		</nav>
	);
}

// packages/vue/src/viewer/components/MobileBottomBar.vue
<script setup lang="ts">
/**
 * MobileBottomBar - the Vue port of React's mobile bottom navigation
 * (`packages/react/src/viewer/components/mobile/MobileBottomBar.tsx`).
 *
 * Five labelled destination tabs - Slides / Insert / Format / Comments / Notes -
 * each opening a bottom sheet (or, for Insert, quick-inserting a text box),
 * matching the navigation pattern of Office Mobile and Google Slides. The active
 * tab is tinted and carries a top pill indicator.
 *
 * Slide navigation is a horizontal swipe and zoom is a pinch (both handled on the
 * canvas), so this bar carries no prev/next or zoom controls; Present, Save and
 * the section menu live in the top `MobileToolbar`. That division mirrors React,
 * whose mobile StatusBar is hidden and whose bottom bar is purely these five
 * targets.
 *
 * Conventions vs. React: function-prop callbacks become emits. The Vue package
 * has a Tailwind build (see `src/styles/pptx-vue-viewer.css`), so the utility
 * classes are used directly, like React, rather than hand-written scoped CSS.
 */
import { Layers, MessageSquare, Plus, Settings2, StickyNote } from 'lucide-vue-next';
import type { FunctionalComponent } from 'vue';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import type { MobileActiveSheet } from '../composables/useMobileChrome';

const { t } = useI18n();

const props = defineProps<{
	/** The currently-open sheet, so its tab renders active. */
	activeSheet?: MobileActiveSheet;
	/** Number of comments on the active slide (renders a badge, capped at 99+). */
	commentCount?: number;
	/**
	 * CSS pixels the on-screen keyboard covers. When > 0 the fixed bar lifts by
	 * this amount so it stays above the keyboard instead of under it.
	 */
	keyboardInset?: number;
}>();

const emit = defineEmits<{
	slides: [];
	insert: [];
	format: [];
	comments: [];
	notes: [];
}>();

type TabKey = 'slides' | 'insert' | 'format' | 'comments' | 'notes';

interface Tab {
	/** Sheet key; `insert` is a fire action and never renders active. */
	key: TabKey;
	labelKey: string;
	icon: FunctionalComponent;
	/** Overrides the visible label as the accessible name (React does this for Notes). */
	ariaLabelKey?: string;
	badge?: number;
}

const tabs = computed<Tab[]>(() => [
	{ key: 'slides', labelKey: 'pptx.sections.slides', icon: Layers },
	{ key: 'insert', labelKey: 'pptx.mobileBar.insert', icon: Plus },
	{ key: 'format', labelKey: 'pptx.field.format', icon: Settings2 },
	{
		key: 'comments',
		labelKey: 'pptx.toolbar.comments',
		icon: MessageSquare,
		badge: props.commentCount,
	},
	{
		key: 'notes',
		labelKey: 'pptx.notes.title',
		icon: StickyNote,
		ariaLabelKey: 'pptx.statusBar.toggleNotes',
	},
]);

/**
 * Fire the emit for a tapped tab. Vue's typed `emit` is an overload set that
 * rejects a union argument, so dispatch each event name as a literal.
 */
function onTab(key: TabKey): void {
	switch (key) {
		case 'slides':
			emit('slides');
			break;
		case 'insert':
			emit('insert');
			break;
		case 'format':
			emit('format');
			break;
		case 'comments':
			emit('comments');
			break;
		case 'notes':
			emit('notes');
			break;
	}
}

/** Comment-count badge text, capped at "99+" like the React mobile bar. */
function badgeText(count: number | undefined): string | null {
	if (count === undefined || count <= 0) {
		return null;
	}
	return count > 99 ? '99+' : String(count);
}

/** Translate the fixed bar up above the on-screen keyboard, if one is open. */
const barStyle = computed(() => {
	const inset = props.keyboardInset ?? 0;
	if (inset <= 0) {
		return undefined;
	}
	return {
		transform: `translateY(-${inset}px)`,
		transition: 'transform 150ms ease-out',
		willChange: 'transform',
	};
});
</script>

<template>
	<nav
		class="pptx-vue-mobile-bar fixed bottom-0 left-0 right-0 z-40 flex items-stretch justify-around border-t border-border bg-secondary/80 backdrop-blur supports-[backdrop-filter]:bg-secondary/60 pb-[max(env(safe-area-inset-bottom),0px)]"
		:style="barStyle"
		:aria-label="t('pptx.mobileBar.ariaLabel')"
	>
		<button
			v-for="tab in tabs"
			:key="tab.key"
			type="button"
			class="pptx-vue-mobile-tab relative flex flex-col items-center justify-center gap-0.5 flex-1 min-h-[56px] py-1.5 text-[10px] font-medium transition-colors active:scale-95"
			:class="
				activeSheet === tab.key ? 'text-primary' : 'text-muted-foreground hover:text-foreground'
			"
			:aria-pressed="activeSheet === tab.key"
			:aria-label="tab.ariaLabelKey ? t(tab.ariaLabelKey) : undefined"
			@click="onTab(tab.key)"
		>
			<component :is="tab.icon" class="w-5 h-5" aria-hidden="true" />
			<span>{{ t(tab.labelKey) }}</span>
			<span
				v-if="badgeText(tab.badge)"
				class="pptx-vue-mobile-badge absolute top-1 right-1/4 flex items-center justify-center min-w-[16px] h-4 px-1 rounded-full bg-primary text-[9px] font-semibold text-white"
				aria-hidden="true"
				>{{ badgeText(tab.badge) }}</span
			>
			<span
				v-if="activeSheet === tab.key"
				class="absolute top-0 left-1/2 -translate-x-1/2 w-8 h-0.5 rounded-full bg-primary"
				aria-hidden="true"
			/>
		</button>
	</nav>
</template>
