// packages/react/src/viewer/components/PresentationTransitionOverlay.tsx
import type { PptxElement, PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
/**
 * Overlay rendered during slide transitions in presentation mode.
 *
 * Displays the *outgoing* (previous) slide as an absolutely-positioned layer
 * with CSS exit animation. The *incoming* (new) slide is rendered by the
 * main SlideCanvas underneath (or on top, depending on `outgoingOnTop`).
 */
import type { MorphTransitionPlan } from 'pptx-viewer-shared';
import { MORPH_CROSSFADE_GROUP_STYLE, MORPH_CROSSFADE_HALF_STYLE } from 'pptx-viewer-shared';
import React, { useEffect, useRef, useMemo, useState } from 'react';

import type { CanvasSize } from '../types';
import { normalizeHexColor } from '../utils';
import {
	getSlideTransitionAnimations,
	SLIDE_TRANSITION_KEYFRAMES,
} from '../utils/slide-transitions';
import type { SlideTransitionAnimations } from '../utils/slide-transitions';
import { StaticElementRenderer } from './StaticElementRenderer';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface PresentationTransitionOverlayProps {
	/** The outgoing (old) slide to render in the overlay layer. */
	outgoingSlide: PptxSlide;
	/** Template/master elements that belong to the outgoing slide. */
	templateElements: PptxElement[];
	/** Canvas dimensions (slide width × height in EMU-derived px). */
	canvasSize: CanvasSize;
	/** Transition definition from the incoming slide. */
	transition: PptxSlideTransition;
	/** Resolved transition duration in ms. */
	durationMs: number;
	/**
	 * The live stage scale (slide box scale) supplied by `PresentationStage`.
	 *
	 * Passing it is what keeps the outgoing slide the same size as the incoming
	 * one on the very first painted frame. Without it the overlay has to measure
	 * itself after mount, and the first frame paints the outgoing slide at its
	 * intrinsic (unscaled) size over a full-screen incoming slide - a one-frame
	 * flash right after the transition starts.
	 */
	scale?: number;
	/**
	 * Active Morph plan, when the incoming slide's transition is `morph`.
	 *
	 * Morph is not a whole-slide effect, so the overlay changes shape when this
	 * is present: instead of animating the entire outgoing slide as one block, it
	 * paints each outgoing shape separately and glides it onto its counterpart -
	 * dissolving into it when its appearance changed, fading out in place when it
	 * has none. The incoming halves animate on the live stage underneath (their
	 * `incomingAnimations` are already merged into the stage's element states by
	 * `usePresentationMode`).
	 */
	morphPlan?: MorphTransitionPlan;
	/**
	 * The arriving slide, needed only as the render context for the few of its
	 * own shapes a morph has to paint above the ghosts (see
	 * {@link MorphTransitionPlan.overlayIncomingElements}). Every other
	 * transition ignores it.
	 */
	incomingSlide?: PptxSlide;
	/** Called when the transition animation completes. */
	onComplete: () => void;
}

// ---------------------------------------------------------------------------
// Slide layer renderer (simplified non-interactive slide, like SlideThumbnail)
// ---------------------------------------------------------------------------

interface SlideLayerProps {
	slide: PptxSlide;
	templateElements: PptxElement[];
	canvasSize: CanvasSize;
}

function SlideLayer({ slide, templateElements, canvasSize }: SlideLayerProps): React.ReactElement {
	const safeWidth = Math.max(canvasSize.width, 1);
	const safeHeight = Math.max(canvasSize.height, 1);
	const elements = [...templateElements, ...slide.elements];

	return (
		<div
			className='relative overflow-hidden'
			style={{
				width: safeWidth,
				height: safeHeight,
				backgroundColor: slide.backgroundColor
					? normalizeHexColor(slide.backgroundColor, '#ffffff')
					: '#ffffff',
				backgroundImage: slide.backgroundImage
					? `url(${slide.backgroundImage})`
					: slide.backgroundGradient
						? slide.backgroundGradient
						: undefined,
				backgroundSize: slide.backgroundImage ? 'cover' : undefined,
				backgroundPosition: slide.backgroundImage ? 'center' : undefined,
			}}
		>
			{elements.map((element, index) => (
				<StaticElementRenderer
					key={element.id}
					element={element}
					activeSlide={slide}
					allSlides={[slide]}
					zIndex={index}
				/>
			))}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function PresentationTransitionOverlay({
	outgoingSlide,
	templateElements,
	canvasSize,
	transition,
	durationMs,
	scale: stageScale,
	morphPlan,
	incomingSlide,
	onComplete,
}: PresentationTransitionOverlayProps): React.ReactElement | null {
	const containerRef = useRef<HTMLDivElement>(null);
	const [containerSize, setContainerSize] = useState<{
		width: number;
		height: number;
	} | null>(null);
	const resolvedStageScale =
		typeof stageScale === 'number' && Number.isFinite(stageScale) && stageScale > 0
			? stageScale
			: null;

	// Fallback measurement for hosts that mount the overlay without a stage
	// scale. Skipped entirely when the stage supplied one, since measuring only
	// ever reproduces the value we were already handed - one frame later.
	useEffect(() => {
		if (resolvedStageScale !== null) {
			return;
		}
		const el = containerRef.current;
		if (!el) {
			return;
		}
		const rect = el.getBoundingClientRect();
		setContainerSize({ width: rect.width, height: rect.height });
	}, [resolvedStageScale]);

	// Fire completion callback after duration
	useEffect(() => {
		const timer = window.setTimeout(onComplete, durationMs + 50);
		return () => {
			window.clearTimeout(timer);
		};
	}, [durationMs, onComplete]);

	// Compute transition animations
	const animations: SlideTransitionAnimations = useMemo(
		() =>
			getSlideTransitionAnimations(
				transition.type,
				durationMs,
				transition.direction,
				transition.orient,
				transition.spokes,
			),
		[transition.type, transition.direction, transition.orient, transition.spokes, durationMs],
	);

	// Scale for the slide layer. Prefer the stage's own scale: it is already
	// correct on the first render, so the outgoing slide never paints unscaled.
	const scale = useMemo(() => {
		if (resolvedStageScale !== null) {
			return resolvedStageScale;
		}
		if (!containerSize) {
			return 1;
		}
		const scaleX = containerSize.width / Math.max(canvasSize.width, 1);
		const scaleY = containerSize.height / Math.max(canvasSize.height, 1);
		return Math.min(scaleX, scaleY);
	}, [resolvedStageScale, containerSize, canvasSize]);

	const outgoingZIndex = animations.outgoingOnTop ? 40 : 20;

	// Morph: paint only the departing shapes, unanimated as a layer, each
	// carrying its own fade-out. The persisting shapes are already gliding on
	// the live stage below, so covering them with a copy of the whole outgoing
	// slide would hide the effect entirely.
	if (morphPlan) {
		return (
			<div
				ref={containerRef}
				data-pptx-transition-overlay
				data-pptx-transition-morph='true'
				className='pptx-react-transition-overlay absolute inset-0 pointer-events-none overflow-hidden'
				style={{ zIndex: 40 }}
			>
				<style>{morphPlan.keyframesCss}</style>
				<div className='absolute inset-0 flex items-center justify-center'>
					<div
						style={{
							width: canvasSize.width,
							height: canvasSize.height,
							// The slide box is a flex ITEM, so it shrinks to the container
							// unless told not to. A show surface narrower than the deck's own
							// canvas (a windowed show, or a display scaled past 100%) squeezed
							// the unscaled 1280px box down to the container width and only
							// then scaled it, landing the whole outgoing slide up to ~77px to
							// the right of the live one for the length of the morph (issue
							// #161). The stage below positions its slide box absolutely and is
							// unaffected, so the two layers disagreed.
							flexShrink: 0,
							transform: `scale(${scale})`,
							transformOrigin: 'center',
							position: 'relative',
						}}
					>
						{morphPlan.outgoingElements.map((element, index) => (
							<div
								key={element.id}
								data-pptx-morph-outgoing={element.id}
								style={{ position: 'absolute', inset: 0 }}
							>
								{/* The animation rides the element's own positioned container:
								    ghost keyframes are element-local (they restate the static
								    rotation/flips and pivot on the element centre), so a
								    slide-sized wrapper would pivot them around the slide
								    centre and double-apply the static transform. */}
								<StaticElementRenderer
									element={element}
									activeSlide={outgoingSlide}
									allSlides={[outgoingSlide]}
									zIndex={index}
									animation={morphPlan.outgoingAnimations.get(element.id)}
									imageAnimation={morphPlan.outgoingImageAnimations.get(element.id)}
								/>
							</div>
						))}
						{/* The arriving shapes a ghost above them would otherwise hide for
						    the whole morph, painted here instead so they dissolve in where
						    a viewer can see them (issue #146). Their copy on the live stage
						    is held invisible by the plan, so nothing composites twice. */}
						{incomingSlide &&
							morphPlan.overlayIncomingElements.map((element, index) => (
								<div
									key={element.id}
									data-pptx-morph-lifted={element.id}
									style={{ position: 'absolute', inset: 0 }}
								>
									<StaticElementRenderer
										element={element}
										activeSlide={incomingSlide}
										allSlides={[incomingSlide]}
										zIndex={morphPlan.outgoingElements.length + index}
										animation={morphPlan.overlayIncomingAnimations.get(element.id)}
									/>
								</div>
							))}
						{/* Pairs the overlay paints both halves of, summed inside their own
						    isolated group instead of stacked: two source-over fades dip the
						    ink they share toward the backdrop, which bites chunks out of
						    glyphs that cross during a text dissolve (issue #161). The group
						    carries an explicit z-index because `isolation` makes it a
						    stacking context, so the halves' own z-indexes no longer place
						    it against the ghosts. */}
						{incomingSlide &&
							morphPlan.crossfadeGroups.map((group, index) => (
								<div
									key={group.incoming.id}
									data-pptx-morph-crossfade={group.incoming.id}
									style={{
										...MORPH_CROSSFADE_GROUP_STYLE,
										zIndex:
											morphPlan.outgoingElements.length +
											morphPlan.overlayIncomingElements.length +
											index,
									}}
								>
									<div
										data-pptx-morph-outgoing={group.outgoing.id}
										style={MORPH_CROSSFADE_HALF_STYLE}
									>
										<StaticElementRenderer
											element={group.outgoing}
											activeSlide={outgoingSlide}
											allSlides={[outgoingSlide]}
											zIndex={0}
											animation={morphPlan.outgoingAnimations.get(group.outgoing.id)}
											imageAnimation={morphPlan.outgoingImageAnimations.get(group.outgoing.id)}
										/>
									</div>
									<div
										data-pptx-morph-lifted={group.incoming.id}
										style={MORPH_CROSSFADE_HALF_STYLE}
									>
										<StaticElementRenderer
											element={group.incoming}
											activeSlide={incomingSlide}
											allSlides={[incomingSlide]}
											zIndex={0}
											animation={morphPlan.overlayIncomingAnimations.get(group.incoming.id)}
										/>
									</div>
								</div>
							))}
					</div>
				</div>
			</div>
		);
	}

	return (
		<div
			ref={containerRef}
			data-pptx-transition-overlay
			className='pptx-react-transition-overlay absolute inset-0 pointer-events-none overflow-hidden'
			style={{ zIndex: outgoingZIndex }}
		>
			{/* Inject the transition @keyframes so the `animation` shorthands resolve. */}
			<style>{SLIDE_TRANSITION_KEYFRAMES}</style>
			<div
				data-pptx-transition-layer='outgoing'
				className='pptx-react-transition-layer absolute inset-0 flex items-center justify-center'
				style={{
					animation: animations.outgoing !== 'none' ? animations.outgoing : undefined,
				}}
			>
				<div
					style={{
						width: canvasSize.width,
						height: canvasSize.height,
						// See the morph layer above: a flex item shrinks to its container,
						// which offsets the whole outgoing slide on a show surface narrower
						// than the deck's canvas.
						flexShrink: 0,
						transform: `scale(${scale})`,
						transformOrigin: 'center',
					}}
				>
					<SlideLayer
						slide={outgoingSlide}
						templateElements={templateElements}
						canvasSize={canvasSize}
					/>
				</div>
			</div>
		</div>
	);
}

// packages/vue/src/viewer/components/PresentationTransitionOverlay.vue
<script setup lang="ts">
import type { PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
import {
	buildMorphScopedCss,
	buildMorphTransitionPlan,
	MORPH_CROSSFADE_GROUP_STYLE,
	MORPH_CROSSFADE_HALF_BLEND_MODE,
	morphOptionToMode,
} from 'pptx-viewer-shared';
import type { CSSProperties } from 'vue';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';

import {
	resolveSlideTransition,
	resolveTransitionDurationMs,
	SLIDE_TRANSITION_KEYFRAMES_CSS,
} from '../composables/slide-transition-css';
import type { CanvasSize } from '../types';
import SlideStage from './SlideStage.vue';

/**
 * PresentationTransitionOverlay - animates a slide change in presentation mode.
 *
 * It stacks two {@link SlideStage} layers, both scaled-to-fit identically to the
 * underlying presentation frame:
 *   - the **outgoing** (old) slide as a snapshot layer, and
 *   - the **incoming** (new) slide.
 *
 * The active slide's {@link PptxSlideTransition} is mapped to CSS `animation`
 * shorthands (via {@link resolveSlideTransition}); each layer's `z-index` is set
 * from `outgoingOnTop`. When the configured duration elapses the overlay emits
 * `done`, at which point the host should drop the overlay and leave the static
 * incoming slide rendered by its main stage.
 *
 * `PresentationMode` is expected to mount this **only while a transition is
 * playing** (between the outgoing and incoming slides), render nothing of its
 * own animated stage during that window, and remove it on `@done`.
 */
const props = withDefaults(
	defineProps<{
		/** The outgoing (previous) slide rendered in the exit layer. */
		outgoingSlide: PptxSlide | undefined;
		/** The incoming (new) slide rendered in the entrance layer. */
		incomingSlide: PptxSlide | undefined;
		/** Slide surface dimensions (px). */
		canvasSize: CanvasSize;
		/** Resolved media data URLs, threaded to each {@link SlideStage}. */
		mediaDataUrls: Map<string, string>;
		/** Fit-to-viewport scale (same value the host applies to its main stage). */
		scale?: number;
		/** The transition definition from the incoming slide. */
		transition: PptxSlideTransition | undefined;
	}>(),
	{ scale: 1 },
);

const emit = defineEmits<{
	(e: 'done'): void;
}>();

// ---------------------------------------------------------------------------
// Resolved animation pieces
// ---------------------------------------------------------------------------

const animations = computed(() => resolveSlideTransition(props.transition));

/** Effective duration (ms); `0` for instant (none/cut). */
const durationMs = computed(() => resolveTransitionDurationMs(props.transition));

// ---------------------------------------------------------------------------
// Morph
// ---------------------------------------------------------------------------

/**
 * Morph is not a whole-slide wipe: individual shapes travel from where they sat
 * on the outgoing slide to where they sit on the incoming one. So when the
 * transition is `morph` the two stacked layers are re-purposed - the incoming
 * layer plays per-element keyframes (scoped by `data-pptx-morph-incoming`), and
 * the outgoing layer paints a moving copy of the outgoing slide, each shape
 * gliding onto its counterpart (dissolving into it when its appearance changed)
 * or fading out in place when it has none.
 */
const morphPlan = computed(() =>
	props.transition?.type === 'morph'
		? buildMorphTransitionPlan(
				props.outgoingSlide,
				props.incomingSlide,
				durationMs.value,
				morphOptionToMode(props.transition.morphOption),
			)
		: undefined,
);

/** The outgoing slide's shapes, rendered as the morph's departing layer. */
const morphOutgoingSlide = computed<PptxSlide | undefined>(() => {
	const plan = morphPlan.value;
	if (!plan || !props.outgoingSlide) {
		return undefined;
	}
	return { ...props.outgoingSlide, elements: plan.outgoingElements };
});

/**
 * The arriving shapes a ghost above them would otherwise hide for the whole
 * morph, painted in their own layer over the departing one (issue #146). Their
 * copy on the incoming layer is held invisible by the plan, so the two never
 * composite with each other.
 */
const morphLiftedSlide = computed<PptxSlide | undefined>(() => {
	const plan = morphPlan.value;
	if (!plan || !props.incomingSlide || plan.overlayIncomingElements.length === 0) {
		return undefined;
	}
	return { ...props.incomingSlide, elements: plan.overlayIncomingElements };
});

/** Both halves of a grouped pair blend additively, and only with each other. */
const crossfadeHalfStyle: CSSProperties = { mixBlendMode: MORPH_CROSSFADE_HALF_BLEND_MODE };

/**
 * The pairs whose two halves the overlay paints itself, as one isolated group
 * each so they can be SUMMED rather than stacked.
 *
 * Two source-over fades leave the ink the halves share dipped toward the
 * backdrop (0.75 of full strength at the midpoint), which bites chunks out of
 * glyphs crossing during a text dissolve; PowerPoint's own render holds the two
 * coefficients at a sum of 1.0 throughout (issue #161).
 */
const morphCrossfadeGroups = computed(() => {
	const plan = morphPlan.value;
	if (!plan || !props.outgoingSlide || !props.incomingSlide) {
		return [];
	}
	const outgoing = props.outgoingSlide;
	const incoming = props.incomingSlide;
	return plan.crossfadeGroups.map((group, index) => ({
		key: group.incoming.id,
		// `isolation` makes the group a stacking context, so it needs its own
		// z-index to stay above the ghosts its halves used to sit among.
		style: { ...MORPH_CROSSFADE_GROUP_STYLE, zIndex: 4 + index } as CSSProperties,
		// The dissolve rides these WRAPPERS, not the elements: a pair dissolving
		// in place never moves, and an animation on the small element box gives it
		// a compositing layer whose raster snaps to whole device pixels, painting
		// the wording a fraction of a pixel off the live stage (issue #161).
		outgoingStyle: { ...crossfadeHalfStyle, animation: group.outgoingAnimation } as CSSProperties,
		incomingStyle: { ...crossfadeHalfStyle, animation: group.incomingAnimation } as CSSProperties,
		outgoingSlide: { ...outgoing, elements: [group.outgoing] },
		incomingSlide: { ...incoming, elements: [group.incoming] },
	}));
});

const morphCss = computed(() => {
	const plan = morphPlan.value;
	if (!plan) {
		return '';
	}
	return [
		buildMorphScopedCss(plan, 'data-pptx-morph-incoming', 'incoming'),
		buildMorphScopedCss(plan, 'data-pptx-morph-outgoing', 'outgoing'),
		buildMorphScopedCss(plan, 'data-pptx-morph-lifted', 'lifted'),
	].join('\n');
});

const outgoingZIndex = computed(() => (animations.value.outgoingOnTop ? 2 : 1));
const incomingZIndex = computed(() => (animations.value.outgoingOnTop ? 1 : 2));

const outgoingLayerStyle = computed<CSSProperties>(() => ({
	zIndex: morphPlan.value ? 2 : outgoingZIndex.value,
	// Morph animates each shape individually; a layer-wide animation on top of
	// that would drag the whole slide and cancel the effect.
	animation: morphPlan.value
		? undefined
		: animations.value.outgoing !== 'none'
			? animations.value.outgoing
			: undefined,
}));

const liftedLayerStyle = computed<CSSProperties>(() => ({ zIndex: 3 }));

const incomingLayerStyle = computed<CSSProperties>(() => ({
	zIndex: morphPlan.value ? 1 : incomingZIndex.value,
	animation: morphPlan.value
		? undefined
		: animations.value.incoming !== 'none'
			? animations.value.incoming
			: undefined,
}));

// ---------------------------------------------------------------------------
// Completion timer
// ---------------------------------------------------------------------------

let timer: ReturnType<typeof setTimeout> | null = null;

function clearTimer(): void {
	if (timer !== null) {
		clearTimeout(timer);
		timer = null;
	}
}

onMounted(() => {
	// A small buffer past the animation duration ensures the CSS `forwards`
	// fill has settled before the host swaps to the static slide.
	const wait = Math.max(0, durationMs.value) + 50;
	timer = setTimeout(() => {
		timer = null;
		emit('done');
	}, wait);
});

onBeforeUnmount(clearTimer);
</script>

<template>
	<div class="pptx-vue-transition-overlay" data-pptx-transition-overlay>
		<!-- Inject the transition @keyframes once for this overlay. -->
		<component :is="'style'">{{ SLIDE_TRANSITION_KEYFRAMES_CSS }}</component>
		<component :is="'style'" v-if="morphPlan">{{ morphCss }}</component>

		<!-- Outgoing (old) slide snapshot. During a morph this carries only the
		     shapes with no incoming counterpart, so the ones that persist stay
		     visible on the incoming layer while they travel - and it must stay
		     BACKGROUND-FREE, or the departing layer's opaque slide fill covers the
		     morph underneath it for the whole transition. -->
		<div
			class="pptx-vue-transition-layer"
			data-pptx-transition-layer="outgoing"
			:data-pptx-morph-outgoing="morphPlan ? 'true' : undefined"
			:style="outgoingLayerStyle"
		>
			<SlideStage
				:slide="morphPlan ? morphOutgoingSlide : outgoingSlide"
				:canvas-size="canvasSize"
				:media-data-urls="mediaDataUrls"
				:scale="scale"
				:preserve-element-ids="Boolean(morphPlan)"
				:transparent-background="Boolean(morphPlan)"
			/>
		</div>

		<!-- Incoming (new) slide. -->
		<div
			class="pptx-vue-transition-layer"
			data-pptx-transition-layer="incoming"
			:data-pptx-morph-incoming="morphPlan ? 'true' : undefined"
			:style="incomingLayerStyle"
		>
			<SlideStage
				:slide="incomingSlide"
				:canvas-size="canvasSize"
				:media-data-urls="mediaDataUrls"
				:scale="scale"
				:preserve-element-ids="Boolean(morphPlan)"
			/>
		</div>

		<!-- The arriving shapes that dissolve in ABOVE a departing one. They live
		     on the incoming slide, so the layer below draws them under the
		     departing layer, where nobody would see them. -->
		<div
			v-if="morphLiftedSlide"
			class="pptx-vue-transition-layer"
			data-pptx-transition-layer="lifted"
			data-pptx-morph-lifted="true"
			:style="liftedLayerStyle"
		>
			<SlideStage
				:slide="morphLiftedSlide"
				:canvas-size="canvasSize"
				:media-data-urls="mediaDataUrls"
				:scale="scale"
				preserve-element-ids
				transparent-background
			/>
		</div>

		<!-- A pair dissolving in place, painted as ONE isolated group whose two
		     halves sum instead of stacking (issue #161). -->
		<div
			v-for="group in morphCrossfadeGroups"
			:key="group.key"
			:data-pptx-morph-crossfade="group.key"
			:style="group.style"
		>
			<div
				class="pptx-vue-transition-layer"
				data-pptx-transition-layer="outgoing"
				data-pptx-morph-outgoing="true"
				:style="group.outgoingStyle"
			>
				<SlideStage
					:slide="group.outgoingSlide"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:scale="scale"
					preserve-element-ids
					transparent-background
				/>
			</div>
			<div
				class="pptx-vue-transition-layer"
				data-pptx-transition-layer="lifted"
				data-pptx-morph-lifted="true"
				:style="group.incomingStyle"
			>
				<SlideStage
					:slide="group.incomingSlide"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:scale="scale"
					preserve-element-ids
					transparent-background
				/>
			</div>
		</div>
	</div>
</template>

<style scoped>
.pptx-vue-transition-overlay {
	position: absolute;
	inset: 0;
	overflow: hidden;
	pointer-events: none;
}

/*
 * The layer must FILL the overlay, not shrink-wrap its child.
 *
 * `SlideStage` scales with `transform`, which never changes its laid-out box, so
 * an auto-sized absolute layer measures the deck's NATIVE size (e.g. 1280x720)
 * while the stage paints at `canvasSize * scale`. Combined with `overflow:
 * hidden` that cropped every transition to the top-left native-size corner of
 * the show whenever the display was bigger than the deck: on a 1920x1080 screen
 * a 1280x720 deck lost the outer third of the animation and the morph read as a
 * hard-edged slab rather than a transition. `inset: 0` pins the layer to the
 * overlay (itself the frame's scaled footprint), so the clip lands exactly on
 * the slide edge, as intended.
 */
.pptx-vue-transition-layer {
	position: absolute;
	inset: 0;
	overflow: hidden;
	will-change: transform, opacity, clip-path, filter;
}
</style>
