// packages/svelte/src/viewer/components/PresentationAnnotationOverlay.svelte
<script lang="ts">
	/**
	 * The ink canvas a show draws annotations onto. It is DRAWING SURFACE ONLY:
	 * the tool palette that used to sit in its bottom-right corner (five buttons
	 * whose accessible names were the raw tool ids, plus a colour input) has
	 * moved into `PresentationToolbar.svelte`, so the show has one toolbar with
	 * translated labels instead of a second, competing strip.
	 */
	import { annotationOverlayZIndex, pointsToSvgPathD } from 'pptx-viewer-shared';
	import type { CanvasSize, PresentationBlackout } from 'pptx-viewer-shared';
	import type { PresentationAnnotations } from '../presentation/presentation-annotations.svelte';

	const { annotations, current, canvasSize, blackout = 'none' }: { annotations: PresentationAnnotations; current: number; canvasSize: CanvasSize; blackout?: PresentationBlackout } = $props();
	function point(event: PointerEvent): { x: number; y: number } { const rect = (event.currentTarget as SVGSVGElement).getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvasSize.width / rect.width, y: (event.clientY - rect.top) * canvasSize.height / rect.height }; }
</script>
<!-- The z-index comes from shared `annotationOverlayZIndex` as an inline style
     (a scoped style block cannot read a TS value): 60 during a normal show,
     raised above the blackout sheet (z 75) while the screen is blanked so
     "blackboard" ink stays visible. -->
<div class="overlay" class:interactive={annotations.tool !== 'none'} data-pptx-annotation-overlay style={`z-index:${annotationOverlayZIndex(blackout)}`}>
	<svg role="application" aria-label="Slide annotations" viewBox={`0 0 ${canvasSize.width} ${canvasSize.height}`} preserveAspectRatio="none" onpointerdown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); annotations.pointerDown(current, point(event)); }} onpointermove={(event) => annotations.pointerMove(current, point(event))} onpointerup={() => annotations.pointerUp(current)} onpointerleave={() => (annotations.laser = null)}>
		{#each annotations.strokes(current) as stroke}<path d={pointsToSvgPathD(stroke.points)} stroke={stroke.color} stroke-width={stroke.width} stroke-opacity={stroke.tool === 'highlighter' ? .4 : 1} />{/each}
		{#if annotations.current}<path d={pointsToSvgPathD(annotations.current.points)} stroke={annotations.current.color} stroke-width={annotations.current.width} stroke-opacity={annotations.current.tool === 'highlighter' ? .4 : 1} />{/if}
		{#if annotations.laser}<circle cx={annotations.laser.x} cy={annotations.laser.y} r="7" class="laser" />{/if}
	</svg>
</div>
<style>
	.overlay{position:absolute;inset:0;pointer-events:none}.overlay svg{width:100%;height:100%;touch-action:none}.overlay.interactive svg{pointer-events:auto}.overlay path{fill:none;stroke-linecap:round;stroke-linejoin:round}.laser{fill:#ef4444;filter:drop-shadow(0 0 8px #ef4444)}
</style>

// packages/vue/src/viewer/components/PresentationAnnotationOverlay.vue
<script setup lang="ts">
import { annotationOverlayZIndex } from 'pptx-viewer-shared';
import type { PresentationBlackout } from 'pptx-viewer-shared';
import type { CSSProperties } from 'vue';
import { computed, ref } from 'vue';

import type {
	AnnotationStroke,
	LaserPosition,
	PresentationTool,
} from '../composables/usePresentationAnnotations';
import { buildStrokePathD } from '../composables/usePresentationAnnotations';
import type { CanvasSize } from '../types';

/**
 * PresentationAnnotationOverlay - transparent SVG overlay drawn on top of the
 * slide during presentation mode. Captures pointer events for the
 * pen/highlighter/eraser tools and renders the laser-pointer dot. Vue port of
 * the React `PresentationAnnotationOverlay`.
 *
 * Coordinate conversion divides client coordinates by `editorScale` so emitted
 * points are in the slide's unscaled coordinate space (matching
 * `usePresentationAnnotations`). Renders `null` (nothing) when the tool is
 * `'none'`.
 */
const props = withDefaults(
	defineProps<{
		canvasSize: CanvasSize;
		editorScale: number;
		presentationTool: PresentationTool;
		annotationStrokes: AnnotationStroke[];
		currentStroke: AnnotationStroke | null;
		laserPosition: LaserPosition | null;
		/**
		 * Presenter-snapshot blackout state. During a blackout the overlay is
		 * raised ABOVE the blackout sheet (shared `annotationOverlayZIndex`) so
		 * "blackboard" ink stays visible on the blank screen.
		 */
		blackout?: PresentationBlackout;
	}>(),
	{ blackout: 'none' },
);

const emit = defineEmits<{
	(e: 'pointer-down' | 'pointer-move' | 'laser-move' | 'erase', x: number, y: number): void;
	(e: 'pointer-up' | 'laser-leave'): void;
}>();

const svgRef = ref<SVGSVGElement | null>(null);
let isErasing = false;

function toSlideCoords(clientX: number, clientY: number): { x: number; y: number } | null {
	const svg = svgRef.value;
	if (!svg) {
		return null;
	}
	const rect = svg.getBoundingClientRect();
	return {
		x: (clientX - rect.left) / props.editorScale,
		y: (clientY - rect.top) / props.editorScale,
	};
}

function onPointerDown(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	event.preventDefault();
	event.stopPropagation();
	const coords = toSlideCoords(event.clientX, event.clientY);
	if (!coords) {
		return;
	}
	if (props.presentationTool === 'eraser') {
		isErasing = true;
		emit('erase', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'pen' || props.presentationTool === 'highlighter') {
		emit('pointer-down', coords.x, coords.y);
	}
}

function onPointerMove(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	const coords = toSlideCoords(event.clientX, event.clientY);
	if (!coords) {
		return;
	}
	if (props.presentationTool === 'laser') {
		emit('laser-move', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'eraser' && isErasing) {
		emit('erase', coords.x, coords.y);
		return;
	}
	if (props.presentationTool === 'pen' || props.presentationTool === 'highlighter') {
		emit('pointer-move', coords.x, coords.y);
	}
}

function onPointerUp(event: PointerEvent): void {
	if (props.presentationTool === 'none') {
		return;
	}
	event.preventDefault();
	if (props.presentationTool === 'eraser') {
		isErasing = false;
		return;
	}
	emit('pointer-up');
}

function onPointerLeave(): void {
	if (props.presentationTool === 'laser') {
		emit('laser-leave');
	}
	if (props.presentationTool === 'eraser') {
		isErasing = false;
	}
	emit('pointer-up');
}

const cursor = computed<string>(() => {
	switch (props.presentationTool) {
		case 'laser':
			return 'none';
		case 'pen':
		case 'highlighter':
		case 'eraser':
			return 'crosshair';
		default:
			return 'default';
	}
});

const allStrokes = computed<AnnotationStroke[]>(() =>
	props.currentStroke ? [...props.annotationStrokes, props.currentStroke] : props.annotationStrokes,
);

/**
 * Cursor + stacking level. The z-index is bound inline (scoped CSS is static):
 * 60 during a normal show, raised above the z-75 blackout sheet while the
 * screen is blanked, per the shared blackboard layering rules.
 */
const overlayStyle = computed<CSSProperties>(() => ({
	cursor: cursor.value,
	zIndex: annotationOverlayZIndex(props.blackout),
}));

const svgStyle = computed<CSSProperties>(() => ({
	position: 'absolute',
	width: `${props.canvasSize.width}px`,
	height: `${props.canvasSize.height}px`,
	transformOrigin: 'top left',
	transform: `scale(${props.editorScale})`,
}));

const laserStyle = computed<CSSProperties | undefined>(() => {
	if (props.presentationTool !== 'laser' || !props.laserPosition) {
		return undefined;
	}
	return {
		position: 'absolute',
		width: '24px',
		height: '24px',
		left: `${props.laserPosition.x * props.editorScale - 12}px`,
		top: `${props.laserPosition.y * props.editorScale - 12}px`,
		backgroundColor: 'rgba(255, 0, 0, 0.85)',
		boxShadow: '0 0 12px 6px rgba(255, 0, 0, 0.5), 0 0 24px 12px rgba(255, 0, 0, 0.25)',
		filter: 'drop-shadow(0 0 8px rgba(255, 0, 0, 0.7))',
		borderRadius: '50%',
		pointerEvents: 'none',
		zIndex: 70,
	};
});
</script>

<template>
	<div
		v-if="presentationTool !== 'none'"
		class="pptx-vue-annotation-overlay"
		data-pptx-annotation-overlay
		:style="overlayStyle"
	>
		<svg
			ref="svgRef"
			:style="svgStyle"
			:viewBox="`0 0 ${canvasSize.width} ${canvasSize.height}`"
			@pointerdown="onPointerDown"
			@pointermove="onPointerMove"
			@pointerup="onPointerUp"
			@pointerleave="onPointerLeave"
		>
			<path
				v-for="stroke in allStrokes"
				:key="stroke.id"
				:d="buildStrokePathD(stroke.points)"
				fill="none"
				:stroke="stroke.color"
				:stroke-width="stroke.width"
				:opacity="stroke.opacity"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</svg>
		<div v-if="laserStyle" class="pptx-vue-annotation-laser" :style="laserStyle" />
	</div>
</template>

<style scoped>
/* The z-index is bound inline (`overlayStyle`): it comes from the shared
   `annotationOverlayZIndex(blackout)` rule and a scoped stylesheet cannot see
   the blackout state. */
.pptx-vue-annotation-overlay {
	position: absolute;
	inset: 0;
	pointer-events: auto;
}
</style>
