// packages/angular/src/viewer/presenter-view.component.ts
import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	computed,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import type { PptxElement, PptxSlide } from 'pptx-viewer-core';

import type { CanvasSize } from '../internal/shared';
import type { StyleMap } from './element-style';
import {
	NOTES_FONT_SIZE_DEFAULT,
	NOTES_FONT_SIZE_MAX,
	NOTES_FONT_SIZE_MIN,
	NOTES_FONT_SIZE_STEP,
	clampNotesFontSize,
	computeTimerProgress,
	currentSlideAt,
	elapsedSince,
	formatElapsed,
	formatTime,
	nextSlideAfter,
	resolvePresenterNotes,
	slideCounter,
	slideLabel,
} from './presenter-view-helpers';
import { SlideCanvasComponent } from './slide-canvas.component';

/** Clock tick interval (ms) for the current-time / elapsed display. */
const CLOCK_TICK_MS = 1000;

/**
 * PresenterViewComponent: split-screen presenter layout with the current
 * slide, a next-slide preview, speaker notes (rich or plain), a live clock +
 * elapsed timer, font-size controls, and navigation controls.
 *
 * Angular port of the React `PresenterView.tsx`. Keyboard navigation is owned
 * by the orchestrator (mirroring React, where `usePresentationKeyboard` handles
 * keys); this component registers no document keydown listener. Slide previews
 * reuse `pptx-slide-canvas` (the master/layout elements are prepended to each
 * slide's own elements, like the React `templateElements` merge).
 *
 * Selector: `pptx-presenter-view`
 *
 * Inputs:
 *   - `slides`                (required): all slides in the deck
 *   - `currentSlideIndex`     (required): zero-based active slide index
 *   - `canvasSize`            (required): logical slide dimensions (px)
 *   - `templateElements`     : master/layout elements behind every slide
 *   - `mediaDataUrls`        : data-URL map for media assets
 *   - `presentationStartTime`: epoch ms when the presentation began (or null)
 *   - `isAudienceWindowOpen` : whether a separate audience window is open
 *
 * Outputs:
 *   - `movePresentationSlide`: emits +1 / -1 to step the active slide
 *   - `exit`                 : emits void to end the presentation
 *   - `openAudienceWindow`   : request opening the audience display window
 *   - `closeAudienceWindow`  : request closing the audience display window
 */
@Component({
	selector: 'pptx-presenter-view',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, SlideCanvasComponent],
	styles: `
		:host {
			position: absolute;
			inset: 0;
			z-index: 50;
			display: flex;
			flex-direction: column;
			background: #0b0b0c;
			color: #f5f5f5;
			font-family: system-ui, sans-serif;
		}

		.pptx-ng-presenter-body {
			display: flex;
			flex: 1 1 auto;
			min-height: 0;
		}

		.pptx-ng-presenter-current {
			flex: 7 1 0;
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			background: #000;
			padding: 1rem;
			min-width: 0;
		}

		.pptx-ng-presenter-preview-stage {
			width: 100%;
			max-width: 100%;
			min-height: 0;
		}

		.pptx-ng-presenter-slide-badge {
			margin-top: 0.5rem;
			font-family: ui-monospace, monospace;
			font-variant-numeric: tabular-nums;
			font-size: 0.75rem;
			color: rgba(255, 255, 255, 0.5);
			user-select: none;
		}

		.pptx-ng-presenter-side {
			flex: 3 1 0;
			display: flex;
			flex-direction: column;
			background: #18181b;
			border-left: 1px solid rgba(255, 255, 255, 0.12);
			min-width: 260px;
			max-width: 440px;
		}

		.pptx-ng-presenter-header,
		.pptx-ng-presenter-nav,
		.pptx-ng-presenter-next {
			padding: 0.5rem 1rem;
			border-bottom: 1px solid rgba(255, 255, 255, 0.08);
		}

		.pptx-ng-presenter-header {
			display: flex;
			align-items: center;
			justify-content: space-between;
			gap: 0.5rem;
		}

		.pptx-ng-presenter-label {
			font-size: 0.625rem;
			text-transform: uppercase;
			letter-spacing: 0.06em;
			color: rgba(255, 255, 255, 0.55);
		}

		.pptx-ng-presenter-clock {
			font-family: ui-monospace, monospace;
			font-variant-numeric: tabular-nums;
			font-size: 1.125rem;
		}

		.pptx-ng-presenter-elapsed {
			color: #6ea8fe;
		}

		.pptx-ng-presenter-iconbtn {
			display: inline-flex;
			align-items: center;
			justify-content: center;
			width: 32px;
			height: 32px;
			border: none;
			border-radius: 6px;
			background: transparent;
			color: rgba(255, 255, 255, 0.7);
			cursor: pointer;
			font-size: 1rem;
			line-height: 1;
		}

		.pptx-ng-presenter-iconbtn:hover {
			background: rgba(255, 255, 255, 0.1);
			color: #fff;
		}

		.pptx-ng-presenter-iconbtn:disabled {
			opacity: 0.3;
			cursor: not-allowed;
		}

		.pptx-ng-presenter-nav {
			display: flex;
			align-items: center;
			justify-content: space-between;
		}

		.pptx-ng-presenter-navbtn {
			display: inline-flex;
			align-items: center;
			gap: 0.375rem;
			padding: 0.375rem 0.75rem;
			border: none;
			border-radius: 6px;
			background: rgba(255, 255, 255, 0.08);
			color: #f5f5f5;
			cursor: pointer;
			font-size: 0.75rem;
		}

		.pptx-ng-presenter-navbtn:hover:not(:disabled) {
			background: rgba(255, 255, 255, 0.16);
		}

		.pptx-ng-presenter-navbtn:disabled {
			opacity: 0.4;
			cursor: not-allowed;
		}

		.pptx-ng-presenter-counter {
			font-family: ui-monospace, monospace;
			font-variant-numeric: tabular-nums;
			font-size: 0.875rem;
		}

		.pptx-ng-presenter-next-empty {
			display: flex;
			align-items: center;
			justify-content: center;
			height: 4rem;
			border: 1px solid rgba(255, 255, 255, 0.15);
			border-radius: 6px;
			background: rgba(255, 255, 255, 0.04);
			font-size: 0.75rem;
			font-style: italic;
			color: rgba(255, 255, 255, 0.5);
		}

		.pptx-ng-presenter-notes {
			flex: 1 1 auto;
			display: flex;
			flex-direction: column;
			min-height: 0;
			padding: 0.75rem 1rem;
		}

		.pptx-ng-presenter-notes-head {
			display: flex;
			align-items: center;
			justify-content: space-between;
			margin-bottom: 0.5rem;
		}

		.pptx-ng-presenter-notes-size {
			display: flex;
			align-items: center;
			gap: 0.25rem;
		}

		.pptx-ng-presenter-notes-size-value {
			min-width: 28px;
			text-align: center;
			font-family: ui-monospace, monospace;
			font-variant-numeric: tabular-nums;
			font-size: 0.625rem;
			color: rgba(255, 255, 255, 0.55);
			user-select: none;
		}

		.pptx-ng-presenter-notes-body {
			flex: 1 1 auto;
			overflow-y: auto;
			border: 1px solid rgba(255, 255, 255, 0.15);
			border-radius: 6px;
			background: rgba(255, 255, 255, 0.04);
			padding: 0.5rem 0.75rem;
			white-space: pre-wrap;
			line-height: 1.5;
		}

		.pptx-ng-presenter-notes-empty {
			font-style: italic;
			color: rgba(255, 255, 255, 0.5);
		}

		.pptx-ng-presenter-progress {
			height: 6px;
			width: 100%;
			background: rgba(255, 255, 255, 0.12);
			flex: 0 0 auto;
		}

		.pptx-ng-presenter-progress-fill {
			height: 100%;
			background: #6ea8fe;
			transition: width 1s linear;
		}

		.pptx-ng-presenter-empty {
			position: absolute;
			inset: 0;
			display: flex;
			align-items: center;
			justify-content: center;
			color: rgba(255, 255, 255, 0.6);
		}
	`,
	template: `
		@if (currentSlide(); as current) {
			<div class="pptx-ng-presenter-body">
				<!-- Current slide (≈70%) -->
				<div class="pptx-ng-presenter-current">
					<div class="pptx-ng-presenter-preview-stage">
						<pptx-slide-canvas
							[slide]="currentPreviewSlide()"
							[canvasSize]="canvasSize()"
							[mediaDataUrls]="mediaDataUrls()"
							[zoom]="1"
							[interactive]="false"
						/>
					</div>
					<div class="pptx-ng-presenter-slide-badge">{{ slideBadge() }}</div>
				</div>

				<!-- Controls (≈30%) -->
				<div class="pptx-ng-presenter-side">
					<!-- Header: clock + elapsed + window/exit -->
					<div class="pptx-ng-presenter-header">
						<div>
							<div class="pptx-ng-presenter-label">Current time</div>
							<div class="pptx-ng-presenter-clock">{{ clockLabel() }}</div>
						</div>
						<div>
							<div class="pptx-ng-presenter-label">Elapsed</div>
							<div class="pptx-ng-presenter-clock pptx-ng-presenter-elapsed">
								{{ elapsedLabel() }}
							</div>
						</div>
						<div style="display:flex;align-items:center;gap:0.25rem;">
							<button
								type="button"
								class="pptx-ng-presenter-iconbtn"
								(click)="onToggleAudienceWindow()"
								[attr.aria-label]="
									isAudienceWindowOpen() ? 'Close audience window' : 'Open audience window'
								"
								[title]="isAudienceWindowOpen() ? 'Close audience window' : 'Open audience window'"
							>
								{{ isAudienceWindowOpen() ? '▣' : '□' }}
							</button>
							<button
								type="button"
								class="pptx-ng-presenter-iconbtn"
								(click)="exit.emit()"
								aria-label="End presentation"
								title="End presentation"
							>
								&#x2715;
							</button>
						</div>
					</div>

					<!-- Navigation -->
					<div class="pptx-ng-presenter-nav">
						<button
							type="button"
							class="pptx-ng-presenter-navbtn"
							(click)="movePresentationSlide.emit(-1)"
							[disabled]="currentSlideIndex() === 0"
							title="Previous slide"
						>
							&#x2039; Prev
						</button>
						<span class="pptx-ng-presenter-counter">{{ counterLabel() }}</span>
						<button
							type="button"
							class="pptx-ng-presenter-navbtn"
							(click)="movePresentationSlide.emit(1)"
							[disabled]="currentSlideIndex() >= slides().length - 1"
							title="Next slide"
						>
							Next &#x203A;
						</button>
					</div>

					<!-- Next slide preview -->
					<div class="pptx-ng-presenter-next">
						<div class="pptx-ng-presenter-label" style="margin-bottom:0.5rem;">Next slide</div>
						@if (nextPreviewSlide(); as next) {
							<pptx-slide-canvas
								[slide]="next"
								[canvasSize]="canvasSize()"
								[mediaDataUrls]="mediaDataUrls()"
								[zoom]="1"
								[interactive]="false"
							/>
						} @else {
							<div class="pptx-ng-presenter-next-empty">End of presentation</div>
						}
					</div>

					<!-- Speaker notes -->
					<div class="pptx-ng-presenter-notes">
						<div class="pptx-ng-presenter-notes-head">
							<div class="pptx-ng-presenter-label">Speaker notes</div>
							<div class="pptx-ng-presenter-notes-size">
								<button
									type="button"
									class="pptx-ng-presenter-iconbtn"
									(click)="decreaseNotesFontSize()"
									[disabled]="notesFontSize() <= NOTES_FONT_SIZE_MIN"
									aria-label="Decrease font size"
									title="Decrease font size"
								>
									&#x2212;
								</button>
								<span class="pptx-ng-presenter-notes-size-value">{{ notesFontSize() }}px</span>
								<button
									type="button"
									class="pptx-ng-presenter-iconbtn"
									(click)="increaseNotesFontSize()"
									[disabled]="notesFontSize() >= NOTES_FONT_SIZE_MAX"
									aria-label="Increase font size"
									title="Increase font size"
								>
									&#x2b;
								</button>
							</div>
						</div>
						<div class="pptx-ng-presenter-notes-body" [ngStyle]="notesBodyStyle()">
							@if (notes().hasRichNotes) {
								@for (seg of notes().segments; track seg.key) {
									@if (seg.isBreak) {
										<br />
									} @else {
										<span [ngStyle]="seg.style">{{ seg.text }}</span>
									}
								}
							} @else if (notes().hasAnyNotes) {
								{{ notes().plainText }}
							} @else {
								<span class="pptx-ng-presenter-notes-empty">No notes for this slide.</span>
							}
						</div>
					</div>
				</div>
			</div>

			<!-- Timer progress bar -->
			<div
				class="pptx-ng-presenter-progress"
				role="progressbar"
				[attr.aria-valuenow]="progressValue()"
				aria-valuemin="0"
				aria-valuemax="100"
				aria-label="Presentation timer"
			>
				<div class="pptx-ng-presenter-progress-fill" [style.width.%]="timerPercent()"></div>
			</div>
		} @else {
			<div class="pptx-ng-presenter-empty">No slides to present.</div>
		}
	`,
})
export class PresenterViewComponent {
	// Template-exposed constants.
	protected readonly NOTES_FONT_SIZE_MIN = NOTES_FONT_SIZE_MIN;
	protected readonly NOTES_FONT_SIZE_MAX = NOTES_FONT_SIZE_MAX;

	// ------------------------------------------------------------------
	// Inputs
	// ------------------------------------------------------------------

	readonly slides = input.required<PptxSlide[]>();
	readonly currentSlideIndex = input.required<number>();
	readonly canvasSize = input.required<CanvasSize>();
	readonly templateElements = input<readonly PptxElement[]>([]);
	readonly mediaDataUrls = input<Map<string, string>>(new Map());
	readonly presentationStartTime = input<number | null>(null);
	readonly isAudienceWindowOpen = input<boolean>(false);

	// ------------------------------------------------------------------
	// Outputs
	// ------------------------------------------------------------------

	readonly movePresentationSlide = output<1 | -1>();
	readonly exit = output<void>();
	readonly openAudienceWindow = output<void>();
	readonly closeAudienceWindow = output<void>();

	// ------------------------------------------------------------------
	// Internal state
	// ------------------------------------------------------------------

	/** Live wall-clock (epoch ms), advanced once per second. */
	private readonly now = signal(Date.now());

	/** Speaker-notes font size (px), clamped to the allowed range. */
	protected readonly notesFontSize = signal(NOTES_FONT_SIZE_DEFAULT);

	constructor() {
		// 1 Hz tick for the clock + elapsed timer + progress bar.
		if (typeof setInterval !== 'undefined') {
			const handle = setInterval(() => this.now.set(Date.now()), CLOCK_TICK_MS);
			inject(DestroyRef).onDestroy(() => clearInterval(handle));
		}
	}

	// ------------------------------------------------------------------
	// Derived signals
	// ------------------------------------------------------------------

	protected readonly currentSlide = computed<PptxSlide | undefined>(() =>
		currentSlideAt(this.slides(), this.currentSlideIndex()),
	);

	protected readonly nextSlide = computed<PptxSlide | undefined>(() =>
		nextSlideAfter(this.slides(), this.currentSlideIndex()),
	);

	/** Current slide with master/layout elements prepended for preview. */
	protected readonly currentPreviewSlide = computed<PptxSlide | undefined>(() =>
		this.withTemplate(this.currentSlide()),
	);

	/** Next slide with master/layout elements prepended for preview. */
	protected readonly nextPreviewSlide = computed<PptxSlide | undefined>(() =>
		this.withTemplate(this.nextSlide()),
	);

	protected readonly notes = computed(() => resolvePresenterNotes(this.currentSlide()));

	protected readonly clockLabel = computed<string>(() => formatTime(new Date(this.now())));

	protected readonly elapsedMs = computed<number>(() =>
		elapsedSince(this.presentationStartTime(), this.now()),
	);

	protected readonly elapsedLabel = computed<string>(() => formatElapsed(this.elapsedMs()));

	private readonly timerProgress = computed(() => computeTimerProgress(this.elapsedMs()));

	protected readonly timerPercent = computed<number>(() => this.timerProgress().percent);

	protected readonly progressValue = computed<number>(() =>
		Math.round(this.timerProgress().percent),
	);

	protected readonly slideBadge = computed<string>(() =>
		slideLabel(this.currentSlideIndex(), this.slides().length),
	);

	protected readonly counterLabel = computed<string>(() =>
		slideCounter(this.currentSlideIndex(), this.slides().length),
	);

	protected readonly notesBodyStyle = computed<StyleMap>(() => ({
		'font-size': `${this.notesFontSize()}px`,
	}));

	// ------------------------------------------------------------------
	// Actions
	// ------------------------------------------------------------------

	protected increaseNotesFontSize(): void {
		this.notesFontSize.set(clampNotesFontSize(this.notesFontSize() + NOTES_FONT_SIZE_STEP));
	}

	protected decreaseNotesFontSize(): void {
		this.notesFontSize.set(clampNotesFontSize(this.notesFontSize() - NOTES_FONT_SIZE_STEP));
	}

	protected onToggleAudienceWindow(): void {
		if (this.isAudienceWindowOpen()) {
			this.closeAudienceWindow.emit();
		} else {
			this.openAudienceWindow.emit();
		}
	}

	// ------------------------------------------------------------------
	// Helpers
	// ------------------------------------------------------------------

	private withTemplate(slide: PptxSlide | undefined): PptxSlide | undefined {
		if (!slide) {
			return undefined;
		}
		const template = this.templateElements();
		if (template.length === 0) {
			return slide;
		}
		return { ...slide, elements: [...template, ...slide.elements] };
	}
}

@if (currentSlide(); as current) {
	<pptx-presenter-controls
		[snapshot]="presenterWindow.snapshot()"
		[audienceOpen]="isAudienceWindowOpen()"
		[slides]="slides()"
		[current]="currentSlideIndex()"
		[canvasSize]="canvasSize()"
		[mediaDataUrls]="mediaDataUrls()"
		(patch)="presenterWindow.updateSnapshot($event)"
		(navigate)="navigateToSlide.emit($event)"
		(audience)="onToggleAudienceWindow()"
		(end)="exit.emit()"
	/>
	<div class="pptx-ng-presenter-body">
		<!-- Current slide (≈70%) -->
		<div
			class="pptx-ng-presenter-current"
			[class.pptx-ng-presenter-current--advances]="paneAdvancesOnClick()"
			role="presentation"
			data-pptx-presenter-slide
			(click)="onSlidePaneClick()"
		>
			<div class="pptx-ng-presenter-preview-stage">
				<pptx-slide-canvas
					[slide]="currentPreviewSlide()"
					[canvasSize]="canvasSize()"
					[mediaDataUrls]="mediaDataUrls()"
					[zoom]="1"
					[interactive]="false"
				/>
			</div>
			<div class="pptx-ng-presenter-slide-badge">{{ slideBadge() }}</div>
		</div>

		<!-- Controls (≈30%) -->
		<div class="pptx-ng-presenter-side">
			<!-- Header: clock + elapsed + window/exit -->
			<div class="pptx-ng-presenter-header">
				<div>
					<div class="pptx-ng-presenter-label">
						{{ 'pptx.presenter.currentTime' | translate }}
					</div>
					<div class="pptx-ng-presenter-clock">{{ clockLabel() }}</div>
				</div>
				<div>
					<div class="pptx-ng-presenter-label">{{ 'pptx.presenter.elapsed' | translate }}</div>
					<div class="pptx-ng-presenter-clock pptx-ng-presenter-elapsed">
						{{ elapsedLabel() }}
					</div>
				</div>
				<div style="display: flex; align-items: center; gap: 0.25rem">
					<button
						type="button"
						class="pptx-ng-presenter-iconbtn"
						(click)="onToggleAudienceWindow()"
						[attr.aria-label]="
							(isAudienceWindowOpen()
								? 'pptx.presenter.closeAudienceWindow'
								: 'pptx.presenter.openAudienceWindow'
							) | translate
						"
						[title]="
							(isAudienceWindowOpen()
								? 'pptx.presenter.closeAudienceWindow'
								: 'pptx.presenter.openAudienceWindow'
							) | translate
						"
					>
						{{ isAudienceWindowOpen() ? '▣' : '□' }}
					</button>
					<button
						type="button"
						class="pptx-ng-presenter-iconbtn"
						(click)="exit.emit()"
						[attr.aria-label]="'pptx.presenter.endPresentation' | translate"
						[title]="'pptx.presenter.endPresentation' | translate"
					>
						&#x2715;
					</button>
				</div>
			</div>

			<!-- Navigation -->
			<div class="pptx-ng-presenter-nav">
				<button
					type="button"
					class="pptx-ng-presenter-navbtn"
					(click)="movePresentationSlide.emit(-1)"
					[disabled]="currentSlideIndex() === 0"
					[title]="'pptx.presenter.previousSlide' | translate"
				>
					&#x2039; {{ 'pptx.presenter.prev' | translate }}
				</button>
				<span class="pptx-ng-presenter-counter">{{ counterLabel() }}</span>
				<button
					type="button"
					class="pptx-ng-presenter-navbtn"
					(click)="movePresentationSlide.emit(1)"
					[disabled]="currentSlideIndex() >= slides().length - 1"
					[title]="'pptx.presenter.nextSlide' | translate"
				>
					{{ 'pptx.presenter.next' | translate }} &#x203A;
				</button>
			</div>

			<!-- Next slide preview -->
			<div class="pptx-ng-presenter-next">
				<div class="pptx-ng-presenter-label" style="margin-bottom: 0.5rem">
					{{ 'pptx.presenter.nextSlidePreview' | translate }}
				</div>
				@if (nextPreviewSlide(); as next) {
					<pptx-slide-canvas
						[slide]="next"
						[canvasSize]="canvasSize()"
						[mediaDataUrls]="mediaDataUrls()"
						[zoom]="1"
						[interactive]="false"
					/>
				} @else {
					<div class="pptx-ng-presenter-next-empty">
						{{ 'pptx.presenter.endOfPresentation' | translate }}
					</div>
				}
			</div>

			<!-- Speaker notes -->
			<div class="pptx-ng-presenter-notes">
				<div class="pptx-ng-presenter-notes-head">
					<div class="pptx-ng-presenter-label">
						{{ 'pptx.presenter.speakerNotes' | translate }}
					</div>
					<div class="pptx-ng-presenter-notes-size">
						<button
							type="button"
							class="pptx-ng-presenter-iconbtn"
							(click)="decreaseNotesFontSize()"
							[disabled]="notesFontSize() <= NOTES_FONT_SIZE_MIN"
							[attr.aria-label]="'pptx.presenter.decreaseFontSize' | translate"
							[title]="'pptx.presenter.decreaseFontSize' | translate"
						>
							&#x2212;
						</button>
						<span class="pptx-ng-presenter-notes-size-value">{{ notesFontSize() }}px</span>
						<button
							type="button"
							class="pptx-ng-presenter-iconbtn"
							(click)="increaseNotesFontSize()"
							[disabled]="notesFontSize() >= NOTES_FONT_SIZE_MAX"
							[attr.aria-label]="'pptx.presenter.increaseFontSize' | translate"
							[title]="'pptx.presenter.increaseFontSize' | translate"
						>
							&#x2b;
						</button>
					</div>
				</div>
				<div class="pptx-ng-presenter-notes-body" [ngStyle]="notesBodyStyle()">
					@if (notes().hasRichNotes) {
						@for (seg of notes().segments; track seg.key) {
							@if (seg.isBreak) {
								<br />
							} @else {
								<span [ngStyle]="seg.style">{{ seg.text }}</span>
							}
						}
					} @else if (notes().hasAnyNotes) {
						{{ notes().plainText }}
					} @else {
						<span class="pptx-ng-presenter-notes-empty">
							{{ 'pptx.presenter.noNotes' | translate }}
						</span>
					}
				</div>
			</div>
		</div>
	</div>

	<!-- Timer progress bar -->
	<div
		class="pptx-ng-presenter-progress"
		role="progressbar"
		[attr.aria-valuenow]="progressValue()"
		aria-valuemin="0"
		aria-valuemax="100"
		[attr.aria-label]="'pptx.presenter.timerProgress' | translate"
	>
		<div class="pptx-ng-presenter-progress-fill" [style.width.%]="timerPercent()"></div>
	</div>
} @else {
	<div class="pptx-ng-presenter-empty">{{ 'pptx.presenter.noSlides' | translate }}</div>
}

// packages/vue/src/viewer/components/PresenterView.vue
<script setup lang="ts">
import type { PptxSlide } from 'pptx-viewer-core';
import { createInitialPresentationSnapshot, stepPresenterZoom } from 'pptx-viewer-shared';
import type { PresentationPointerTool, PresentationSnapshot } from 'pptx-viewer-shared';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import {
	clampNotesFontSize,
	formatElapsed,
	formatTime,
	notesSegmentsToSpans,
	NOTES_FONT_SIZE_DEFAULT,
	NOTES_FONT_SIZE_MAX,
	NOTES_FONT_SIZE_MIN,
	NOTES_FONT_SIZE_STEP,
} from '../composables/presenter-view-utils';
import type { CanvasSize } from '../types';
import PresenterControlStrip from './PresenterControlStrip.vue';
import PresenterSlideGrid from './PresenterSlideGrid.vue';
import SlideStage from './SlideStage.vue';

/**
 * PresenterView - split-screen presenter layout: current slide (left, 70%) plus
 * a control rail (right, 30%) with the wall-clock time, elapsed timer, prev/next
 * navigation, a next-slide preview, scalable speaker notes, and a 5-minute
 * timer progress bar. Vue port of the React `PresenterView`.
 *
 * Rendered as an absolute overlay by the host (`PresentationMode`). Keyboard
 * navigation is owned by the host; this component only emits navigation /
 * exit intents.
 */
const props = withDefaults(
	defineProps<{
		slides: PptxSlide[];
		currentSlideIndex: number;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		/** Timestamp (ms) the presentation started, or `null`. */
		presentationStartTime: number | null;
		audienceOpen?: boolean;
		snapshot?: PresentationSnapshot;
	}>(),
	{
		snapshot: () => createInitialPresentationSnapshot(),
	},
);

const emit = defineEmits<{
	(e: 'move', direction: 1 | -1): void;
	(e: 'exit' | 'open-audience' | 'close-audience'): void;
	(e: 'navigate', index: number): void;
	(e: 'update-snapshot', patch: Partial<PresentationSnapshot>): void;
}>();

const { t } = useI18n();
const showSlides = ref(false);
function update(patch: Partial<PresentationSnapshot>): void {
	emit('update-snapshot', patch);
}
function setTool(tool: PresentationPointerTool): void {
	update({
		pointer: { ...(props.snapshot.pointer ?? { x: 0.5, y: 0.5, color: '#ef4444' }), tool },
	});
}
function zoom(direction: -1 | 1): void {
	update({
		zoom: stepPresenterZoom(
			props.snapshot.zoom ?? { scale: 1, originX: 0.5, originY: 0.5 },
			direction,
		),
	});
}

// -- Live clock -------------------------------------------------------------
const now = ref(Date.now());
let clockId: ReturnType<typeof setInterval> | null = null;

onMounted(() => {
	clockId = setInterval(() => {
		now.value = Date.now();
	}, 1000);
});

onBeforeUnmount(() => {
	if (clockId !== null) {
		clearInterval(clockId);
		clockId = null;
	}
});

const elapsed = computed(() =>
	props.presentationStartTime ? now.value - props.presentationStartTime : 0,
);

const clockText = computed(() => formatTime(new Date(now.value)));
const elapsedText = computed(() => formatElapsed(elapsed.value));

// -- Timer progress (5-minute segments) ------------------------------------
const TIMER_SEGMENT_MS = 5 * 60 * 1000;
const timerProgress = computed(() =>
	Math.min(100, ((elapsed.value % TIMER_SEGMENT_MS) / TIMER_SEGMENT_MS) * 100),
);
const timerSegment = computed(() => Math.floor(elapsed.value / TIMER_SEGMENT_MS));

// -- Notes font size --------------------------------------------------------
const notesFontSize = ref(NOTES_FONT_SIZE_DEFAULT);

function increaseNotesFontSize(): void {
	notesFontSize.value = clampNotesFontSize(notesFontSize.value + NOTES_FONT_SIZE_STEP);
}

function decreaseNotesFontSize(): void {
	notesFontSize.value = clampNotesFontSize(notesFontSize.value - NOTES_FONT_SIZE_STEP);
}

function toggleAudience(): void {
	if (props.audienceOpen) {
		emit('close-audience');
	} else {
		emit('open-audience');
	}
}

// -- Slide data -------------------------------------------------------------
const currentSlide = computed<PptxSlide | undefined>(() => props.slides[props.currentSlideIndex]);
const nextSlide = computed<PptxSlide | undefined>(() =>
	props.slides.slice(props.currentSlideIndex + 1).find((slide) => !slide.hidden),
);

const notesText = computed(() => currentSlide.value?.notes ?? '');
const notesSpans = computed(() => {
	const segments = currentSlide.value?.notesSegments;
	return segments && segments.length > 0 ? notesSegmentsToSpans(segments) : null;
});
const hasPlainNotes = computed(() => notesText.value.trim().length > 0);

const atFirst = computed(() => props.currentSlideIndex === 0);
const atLast = computed(() => props.currentSlideIndex >= props.slides.length - 1);

// -- Preview scaling (fit into a ~260px-wide rail panel) --------------------
const PREVIEW_WIDTH = 240;
const previewScale = computed(() =>
	props.canvasSize.width > 0 ? PREVIEW_WIDTH / props.canvasSize.width : 1,
);
const previewFrameStyle = computed(() => ({
	width: `${props.canvasSize.width * previewScale.value}px`,
	height: `${props.canvasSize.height * previewScale.value}px`,
}));

// -- Main-stage scaling: fit the slide into a notional area; the flex layout
// (70% width) plus overflow clipping handles the rest.
const MAIN_FIT_WIDTH = 760;
const MAIN_FIT_HEIGHT = 460;
const mainScale = computed(() => {
	const { width, height } = props.canvasSize;
	if (width <= 0 || height <= 0) {
		return 1;
	}
	return Math.min(MAIN_FIT_WIDTH / width, MAIN_FIT_HEIGHT / height);
});
const previewMainFrameStyle = computed(() => ({
	width: `${props.canvasSize.width * mainScale.value}px`,
	height: `${props.canvasSize.height * mainScale.value}px`,
	transform: `scale(${props.snapshot.zoom?.scale ?? 1})`,
	transformOrigin: `${(props.snapshot.zoom?.originX ?? 0.5) * 100}% ${(props.snapshot.zoom?.originY ?? 0.5) * 100}%`,
}));
</script>

<template>
	<div
		v-if="!currentSlide"
		class="pptx-vue-presenter pptx-vue-presenter--empty absolute inset-0 z-50 flex items-center justify-center bg-card text-muted-foreground"
	>
		<PresenterControlStrip
			:snapshot="snapshot"
			:audience-open="Boolean(audienceOpen)"
			@timer="update({ paused: !snapshot.paused })"
			@reset-timer="update({ paused: false, elapsedMs: 0 })"
			@slides="showSlides = true"
			@zoom="zoom"
			@reset-zoom="update({ zoom: { scale: 1, originX: 0.5, originY: 0.5 } })"
			@blackout="(value) => update({ blackout: value })"
			@tool="setTool"
			@subtitles="update({ subtitlesVisible: !snapshot.subtitlesVisible })"
			@audience="toggleAudience"
			@exit="emit('exit')"
		/>
		{{ t('pptx.mpresenter.noSlides') }}
	</div>
	<div
		v-else
		class="pptx-vue-presenter absolute inset-0 z-50 flex flex-col bg-card text-foreground"
	>
		<div class="pptx-vue-presenter-body flex flex-1 min-h-0">
			<!-- Left: current slide -->
			<div
				class="pptx-vue-presenter-main flex flex-[7] min-w-0 flex-col items-center justify-center overflow-hidden bg-black p-6"
			>
				<div
					class="pptx-vue-presenter-stage relative overflow-hidden"
					:style="previewMainFrameStyle"
				>
					<SlideStage
						:slide="currentSlide"
						:canvas-size="canvasSize"
						:media-data-urls="mediaDataUrls"
						:scale="mainScale"
					/>
				</div>
				<div
					class="pptx-vue-presenter-slide-label mt-3 select-none font-mono text-xs tabular-nums text-white/50"
				>
					{{
						t('pptx.statusBar.slideOf', { current: currentSlideIndex + 1, total: slides.length })
					}}
				</div>
			</div>

			<!-- Right: controls -->
			<div
				class="pptx-vue-presenter-rail flex flex-[3] min-w-[260px] max-w-[440px] flex-col border-l border-border bg-background"
			>
				<!-- Header: clock + elapsed + exit -->
				<div
					class="pptx-vue-presenter-header flex items-center justify-between gap-2 border-b border-border/60 px-4 py-3"
				>
					<div class="pptx-vue-presenter-time flex flex-col">
						<span
							class="pptx-vue-presenter-label text-[10px] uppercase tracking-wider text-muted-foreground"
							>{{ t('pptx.presenterView.currentTime') }}</span
						>
						<span class="pptx-vue-presenter-clock font-mono text-lg tabular-nums text-foreground">{{
							clockText
						}}</span>
					</div>
					<div
						class="pptx-vue-presenter-time pptx-vue-presenter-time--right flex flex-col items-end"
					>
						<span
							class="pptx-vue-presenter-label text-[10px] uppercase tracking-wider text-muted-foreground"
							>{{ t('pptx.mpresenter.elapsed') }}</span
						>
						<span class="pptx-vue-presenter-elapsed font-mono text-lg tabular-nums text-primary">{{
							elapsedText
						}}</span>
					</div>
					<div class="flex items-center gap-1">
						<button
							type="button"
							class="pptx-vue-presenter-audience-btn flex h-7 items-center justify-center rounded px-2 text-xs text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
							:title="
								audienceOpen
									? t('pptx.presenter.closeAudienceWindow')
									: t('pptx.presenter.openAudienceWindow')
							"
							@click="toggleAudience"
						>
							{{ audienceOpen ? 'Disconnect display' : 'Audience display' }}
						</button>
						<button
							type="button"
							class="pptx-vue-presenter-icon-btn flex h-7 w-7 items-center justify-center rounded text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
							:title="t('pptx.presenter.endPresentation')"
							:aria-label="t('pptx.presenter.endPresentation')"
							@click="emit('exit')"
						>
							&times;
						</button>
					</div>
				</div>

				<!-- Navigation -->
				<div
					class="pptx-vue-presenter-nav flex items-center justify-between border-b border-border/60 px-4 py-2"
				>
					<button
						type="button"
						class="pptx-vue-presenter-nav-btn inline-flex items-center gap-1.5 rounded bg-muted px-3 py-1.5 text-xs transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
						:disabled="atFirst"
						:title="t('pptx.mobileBar.previousSlide')"
						@click="emit('move', -1)"
					>
						‹ {{ t('pptx.mpresenter.prev') }}
					</button>
					<span class="pptx-vue-presenter-counter font-mono text-sm tabular-nums text-foreground">
						{{ currentSlideIndex + 1 }} / {{ slides.length }}
					</span>
					<button
						type="button"
						class="pptx-vue-presenter-nav-btn inline-flex items-center gap-1.5 rounded bg-muted px-3 py-1.5 text-xs transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
						:disabled="atLast"
						:title="t('pptx.mobileBar.nextSlide')"
						@click="emit('move', 1)"
					>
						{{ t('pptx.mpresenter.next') }} ›
					</button>
				</div>

				<!-- Next slide preview -->
				<div class="pptx-vue-presenter-section border-b border-border/60 px-4 py-3">
					<div
						class="pptx-vue-presenter-label mb-2 text-[10px] uppercase tracking-wider text-muted-foreground"
					>
						{{ t('pptx.mobileBar.nextSlide') }}
					</div>
					<div
						v-if="nextSlide"
						class="pptx-vue-presenter-preview-frame relative mt-2 overflow-hidden rounded border border-border/30"
						:style="previewFrameStyle"
					>
						<SlideStage
							:slide="nextSlide"
							:canvas-size="canvasSize"
							:media-data-urls="mediaDataUrls"
							:scale="previewScale"
						/>
					</div>
					<div
						v-else
						class="pptx-vue-presenter-preview-empty mt-2 flex h-16 items-center justify-center rounded border border-border/30 bg-muted/40 text-xs italic text-muted-foreground"
					>
						{{ t('pptx.mpresenter.endOfPresentation') }}
					</div>
				</div>

				<!-- Speaker notes -->
				<div class="pptx-vue-presenter-notes-section flex flex-1 min-h-0 flex-col px-4 py-3">
					<div class="pptx-vue-presenter-notes-head mb-2 flex items-center justify-between">
						<div
							class="pptx-vue-presenter-label text-[10px] uppercase tracking-wider text-muted-foreground"
						>
							{{ t('pptx.presenter.speakerNotes') }}
						</div>
						<div class="pptx-vue-presenter-font-ctl flex items-center gap-1">
							<button
								type="button"
								class="pptx-vue-presenter-font-btn rounded p-0.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground disabled:cursor-not-allowed disabled:opacity-30"
								:disabled="notesFontSize <= NOTES_FONT_SIZE_MIN"
								:title="t('pptx.presenterView.decreaseFontSize')"
								:aria-label="t('pptx.presenterView.decreaseFontSize')"
								@click="decreaseNotesFontSize"
							>
								−
							</button>
							<span
								class="pptx-vue-presenter-font-val min-w-[28px] select-none text-center font-mono text-[10px] tabular-nums text-muted-foreground"
								>{{ notesFontSize }}px</span
							>
							<button
								type="button"
								class="pptx-vue-presenter-font-btn rounded p-0.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground disabled:cursor-not-allowed disabled:opacity-30"
								:disabled="notesFontSize >= NOTES_FONT_SIZE_MAX"
								:title="t('pptx.presenterView.increaseFontSize')"
								:aria-label="t('pptx.presenterView.increaseFontSize')"
								@click="increaseNotesFontSize"
							>
								+
							</button>
						</div>
					</div>
					<div
						class="pptx-vue-presenter-notes flex-1 overflow-y-auto whitespace-pre-wrap rounded border border-border/30 bg-muted/40 px-3 py-2 leading-relaxed text-foreground"
						:style="{ fontSize: `${notesFontSize}px` }"
					>
						<template v-if="notesSpans">
							<template v-for="span in notesSpans" :key="span.key">
								<br v-if="span.kind === 'break'" />
								<span v-else :style="span.style">{{ span.text }}</span>
							</template>
						</template>
						<template v-else-if="hasPlainNotes">{{ notesText }}</template>
						<span v-else class="pptx-vue-presenter-notes-empty italic text-muted-foreground">{{
							t('pptx.mpresenter.noNotes')
						}}</span>
					</div>
				</div>
			</div>
		</div>
		<PresenterSlideGrid
			v-if="showSlides"
			:slides="slides"
			:current="currentSlideIndex"
			:canvas-size="canvasSize"
			:media-data-urls="mediaDataUrls"
			@select="
				(index) => {
					emit('navigate', index);
					showSlides = false;
				}
			"
			@close="showSlides = false"
		/>

		<!-- Timer progress bar -->
		<div
			class="pptx-vue-presenter-progress h-1.5 w-full flex-shrink-0 bg-muted/60"
			role="progressbar"
			:aria-valuenow="Math.round(timerProgress)"
			:aria-valuemin="0"
			:aria-valuemax="100"
			:aria-label="t('pptx.presenterView.timerProgress')"
			:title="
				t('pptx.presenterView.timerTitle', { elapsed: elapsedText, segment: timerSegment + 1 })
			"
		>
			<div
				class="pptx-vue-presenter-progress-fill h-full bg-primary transition-[width] duration-1000 ease-linear"
				:style="{ width: `${timerProgress}%` }"
			/>
		</div>
	</div>
</template>
