// packages/react/src/viewer/components/PrintSettingsPanel.tsx
/** PrintSettingsPanel: Settings form for the print dialog. */
import React from 'react';
import { useTranslation } from 'react-i18next';
import { LuFileText, LuGrid2X2, LuStickyNote, LuList } from 'react-icons/lu';

import type {
	PrintWhat,
	PrintOrientation,
	PrintColorMode,
	HandoutSlidesPerPage,
	PrintSlideRange,
} from './print-dialog-types';
import { HANDOUT_OPTIONS, radioClass } from './print-dialog-types';
import { WebCheckbox } from './WebControls';

export interface PrintSettingsPanelProps {
	printWhat: PrintWhat;
	onPrintWhatChange: (value: PrintWhat) => void;
	orientation: PrintOrientation;
	onOrientationChange: (value: PrintOrientation) => void;
	colorMode: PrintColorMode;
	onColorModeChange: (value: PrintColorMode) => void;
	frameSlides: boolean;
	onFrameSlidesChange: (value: boolean) => void;
	slidesPerPage: HandoutSlidesPerPage;
	onSlidesPerPageChange: (value: HandoutSlidesPerPage) => void;
	slideRange: PrintSlideRange;
	onSlideRangeChange: (value: PrintSlideRange) => void;
	customFrom: number;
	onCustomFromChange: (value: number) => void;
	customTo: number;
	onCustomToChange: (value: number) => void;
	totalSlides: number;
	activeSlideIndex: number;
}

export function PrintSettingsPanel({
	printWhat,
	onPrintWhatChange,
	orientation,
	onOrientationChange,
	colorMode,
	onColorModeChange,
	frameSlides,
	onFrameSlidesChange,
	slidesPerPage,
	onSlidesPerPageChange,
	slideRange,
	onSlideRangeChange,
	customFrom,
	onCustomFromChange,
	customTo,
	onCustomToChange,
	totalSlides,
	activeSlideIndex,
}: PrintSettingsPanelProps): React.ReactElement {
	const { t } = useTranslation();

	return (
		<div className='flex-1 space-y-5 min-w-0'>
			{/* Print What */}
			<fieldset>
				<legend className='text-xs font-medium text-muted-foreground mb-2 uppercase tracking-wide'>
					{t('pptx.print.printWhat')}
				</legend>
				<div className='grid grid-cols-2 gap-2'>
					<label className={radioClass(printWhat === 'slides')}>
						<input
							type='radio'
							name='printWhat'
							className='sr-only'
							checked={printWhat === 'slides'}
							onChange={() => onPrintWhatChange('slides')}
						/>
						<LuFileText className='w-4 h-4 shrink-0' />
						{t('pptx.print.fullPageSlides')}
					</label>
					<label className={radioClass(printWhat === 'handouts')}>
						<input
							type='radio'
							name='printWhat'
							className='sr-only'
							checked={printWhat === 'handouts'}
							onChange={() => onPrintWhatChange('handouts')}
						/>
						<LuGrid2X2 className='w-4 h-4 shrink-0' />
						{t('pptx.print.handouts')}
					</label>
					<label className={radioClass(printWhat === 'notes')}>
						<input
							type='radio'
							name='printWhat'
							className='sr-only'
							checked={printWhat === 'notes'}
							onChange={() => onPrintWhatChange('notes')}
						/>
						<LuStickyNote className='w-4 h-4 shrink-0' />
						{t('pptx.print.notesPages')}
					</label>
					<label className={radioClass(printWhat === 'outline')}>
						<input
							type='radio'
							name='printWhat'
							className='sr-only'
							checked={printWhat === 'outline'}
							onChange={() => onPrintWhatChange('outline')}
						/>
						<LuList className='w-4 h-4 shrink-0' />
						{t('pptx.print.outline')}
					</label>
				</div>
			</fieldset>

			{/* Handout options */}
			{printWhat === 'handouts' && (
				<fieldset>
					<legend className='text-xs font-medium text-muted-foreground mb-2 uppercase tracking-wide'>
						{t('pptx.print.slidesPerPage')}
					</legend>
					<div className='flex gap-1.5 flex-wrap'>
						{HANDOUT_OPTIONS.map((n) => (
							<button
								key={n}
								type='button'
								onClick={() => onSlidesPerPageChange(n)}
								className={`px-3 py-1.5 rounded-md text-sm font-medium border transition-colors ${
									slidesPerPage === n
										? 'border-primary bg-primary/10 text-foreground'
										: 'border-border bg-background text-muted-foreground hover:border-primary/40'
								}`}
							>
								{n}
							</button>
						))}
					</div>
				</fieldset>
			)}

			{/* Slide Range */}
			<fieldset>
				<legend className='text-xs font-medium text-muted-foreground mb-2 uppercase tracking-wide'>
					{t('pptx.print.slideRange')}
				</legend>
				<div className='space-y-2'>
					<label className={radioClass(slideRange === 'all')}>
						<input
							type='radio'
							name='slideRange'
							className='sr-only'
							checked={slideRange === 'all'}
							onChange={() => onSlideRangeChange('all')}
						/>
						{t('pptx.print.allSlides')} ({totalSlides})
					</label>
					<label className={radioClass(slideRange === 'current')}>
						<input
							type='radio'
							name='slideRange'
							className='sr-only'
							checked={slideRange === 'current'}
							onChange={() => onSlideRangeChange('current')}
						/>
						{t('pptx.print.currentSlide')} ({activeSlideIndex + 1})
					</label>
					<label className={radioClass(slideRange === 'custom')}>
						<input
							type='radio'
							name='slideRange'
							className='sr-only'
							checked={slideRange === 'custom'}
							onChange={() => onSlideRangeChange('custom')}
						/>
						{t('pptx.print.customRange')}
					</label>
					{slideRange === 'custom' && (
						<div className='flex items-center gap-2 pl-6'>
							<span className='text-xs text-muted-foreground'>{t('pptx.print.from')}</span>
							<input
								type='number'
								min={1}
								max={totalSlides}
								value={customFrom}
								onChange={(e) => onCustomFromChange(Math.max(1, parseInt(e.target.value, 10) || 1))}
								className='w-16 px-2 py-1 text-sm border border-border rounded bg-background text-foreground'
							/>
							<span className='text-xs text-muted-foreground'>{t('pptx.print.to')}</span>
							<input
								type='number'
								min={1}
								max={totalSlides}
								value={customTo}
								onChange={(e) => onCustomToChange(Math.max(1, parseInt(e.target.value, 10) || 1))}
								className='w-16 px-2 py-1 text-sm border border-border rounded bg-background text-foreground'
							/>
						</div>
					)}
				</div>
			</fieldset>

			{/* Orientation: only for full-page slides */}
			{printWhat === 'slides' && (
				<fieldset>
					<legend className='text-xs font-medium text-muted-foreground mb-2 uppercase tracking-wide'>
						{t('pptx.print.orientation')}
					</legend>
					<div className='flex gap-2'>
						<label className={radioClass(orientation === 'landscape')}>
							<input
								type='radio'
								name='orientation'
								className='sr-only'
								checked={orientation === 'landscape'}
								onChange={() => onOrientationChange('landscape')}
							/>
							{t('pptx.print.landscape')}
						</label>
						<label className={radioClass(orientation === 'portrait')}>
							<input
								type='radio'
								name='orientation'
								className='sr-only'
								checked={orientation === 'portrait'}
								onChange={() => onOrientationChange('portrait')}
							/>
							{t('pptx.print.portrait')}
						</label>
					</div>
				</fieldset>
			)}

			{/* Colour Mode */}
			<fieldset>
				<legend className='text-xs font-medium text-muted-foreground mb-2 uppercase tracking-wide'>
					{t('pptx.print.colorMode')}
				</legend>
				<div className='flex gap-2 flex-wrap'>
					<label className={radioClass(colorMode === 'color')}>
						<input
							type='radio'
							name='colorMode'
							className='sr-only'
							checked={colorMode === 'color'}
							onChange={() => onColorModeChange('color')}
						/>
						{t('pptx.print.color')}
					</label>
					<label className={radioClass(colorMode === 'grayscale')}>
						<input
							type='radio'
							name='colorMode'
							className='sr-only'
							checked={colorMode === 'grayscale'}
							onChange={() => onColorModeChange('grayscale')}
						/>
						{t('pptx.print.grayscale')}
					</label>
					<label className={radioClass(colorMode === 'blackAndWhite')}>
						<input
							type='radio'
							name='colorMode'
							className='sr-only'
							checked={colorMode === 'blackAndWhite'}
							onChange={() => onColorModeChange('blackAndWhite')}
						/>
						{t('pptx.print.blackAndWhite')}
					</label>
				</div>
			</fieldset>

			{/* Frame Slides */}
			<label className='flex items-center gap-2 cursor-pointer'>
				<WebCheckbox
					checked={frameSlides}
					onChange={(e) => onFrameSlidesChange(e.target.checked)}
				/>
				<span className='text-sm text-foreground'>{t('pptx.print.frameSlides')}</span>
			</label>
		</div>
	);
}

// packages/vue/src/viewer/components/PrintSettingsPanel.vue
<script setup lang="ts">
/**
 * PrintSettingsPanel — the settings fieldset shown inside {@link PrintDialog}.
 *
 * Vue port of the React `PrintSettingsPanel.tsx`. Presentational: the parent
 * (`PrintDialog`) owns all state via `v-model`-style props + `update:*` emits.
 * Hand-written scoped CSS (no Tailwind), class names prefixed `pptx-vue-`.
 */
import { HANDOUT_OPTIONS } from './print-dialog-types';
import type {
	HandoutSlidesPerPage,
	PrintColorMode,
	PrintOrientation,
	PrintSlideRange,
	PrintWhat,
} from './print-dialog-types';

const props = defineProps<{
	printWhat: PrintWhat;
	orientation: PrintOrientation;
	colorMode: PrintColorMode;
	frameSlides: boolean;
	slidesPerPage: HandoutSlidesPerPage;
	slideRange: PrintSlideRange;
	customFrom: number;
	customTo: number;
	totalSlides: number;
	activeSlideIndex: number;
}>();

const emit = defineEmits<{
	'update:printWhat': [value: PrintWhat];
	'update:orientation': [value: PrintOrientation];
	'update:colorMode': [value: PrintColorMode];
	'update:frameSlides': [value: boolean];
	'update:slidesPerPage': [value: HandoutSlidesPerPage];
	'update:slideRange': [value: PrintSlideRange];
	'update:customFrom': [value: number];
	'update:customTo': [value: number];
}>();

const PRINT_WHAT_OPTIONS: { value: PrintWhat; label: string }[] = [
	{ value: 'slides', label: 'Full-page slides' },
	{ value: 'handouts', label: 'Handouts' },
	{ value: 'notes', label: 'Notes pages' },
	{ value: 'outline', label: 'Outline' },
];

const COLOR_OPTIONS: { value: PrintColorMode; label: string }[] = [
	{ value: 'color', label: 'Color' },
	{ value: 'grayscale', label: 'Grayscale' },
	{ value: 'blackAndWhite', label: 'Black & white' },
];

function parseRangeInput(raw: string): number {
	return Math.max(1, Number.parseInt(raw, 10) || 1);
}

function onCustomFromInput(event: Event): void {
	emit('update:customFrom', parseRangeInput((event.target as HTMLInputElement).value));
}

function onCustomToInput(event: Event): void {
	emit('update:customTo', parseRangeInput((event.target as HTMLInputElement).value));
}
</script>

<template>
	<div class="pptx-vue-print-settings flex min-w-0 flex-1 flex-col gap-5">
		<!-- Print What -->
		<fieldset class="pptx-vue-print-fieldset m-0 border-none p-0">
			<legend
				class="pptx-vue-print-legend mb-2 p-0 text-xs font-medium uppercase tracking-wide text-muted-foreground"
			>
				Print what
			</legend>
			<div class="pptx-vue-print-grid grid grid-cols-2 gap-2">
				<label
					v-for="opt in PRINT_WHAT_OPTIONS"
					:key="opt.value"
					class="pptx-vue-print-card flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
					:class="
						props.printWhat === opt.value
							? 'pptx-vue-print-card--active border-primary bg-primary/10 text-foreground'
							: 'border-border bg-background text-muted-foreground hover:border-primary/40'
					"
				>
					<input
						type="radio"
						name="printWhat"
						class="pptx-vue-print-sr-only sr-only"
						:checked="props.printWhat === opt.value"
						@change="emit('update:printWhat', opt.value)"
					/>
					{{ opt.label }}
				</label>
			</div>
		</fieldset>

		<!-- Handout options -->
		<fieldset
			v-if="props.printWhat === 'handouts'"
			class="pptx-vue-print-fieldset m-0 border-none p-0"
		>
			<legend
				class="pptx-vue-print-legend mb-2 p-0 text-xs font-medium uppercase tracking-wide text-muted-foreground"
			>
				Slides per page
			</legend>
			<div class="pptx-vue-print-chips flex flex-wrap gap-1.5">
				<button
					v-for="n in HANDOUT_OPTIONS"
					:key="n"
					type="button"
					class="pptx-vue-print-chip rounded-md border px-3 py-1.5 text-sm font-medium transition-colors"
					:class="
						props.slidesPerPage === n
							? 'pptx-vue-print-chip--active border-primary bg-primary/10 text-foreground'
							: 'border-border bg-background text-muted-foreground hover:border-primary/40'
					"
					@click="emit('update:slidesPerPage', n)"
				>
					{{ n }}
				</button>
			</div>
		</fieldset>

		<!-- Slide Range -->
		<fieldset class="pptx-vue-print-fieldset m-0 border-none p-0">
			<legend
				class="pptx-vue-print-legend mb-2 p-0 text-xs font-medium uppercase tracking-wide text-muted-foreground"
			>
				Slide range
			</legend>
			<div class="pptx-vue-print-stack flex flex-col gap-2">
				<label
					class="pptx-vue-print-card flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
					:class="
						props.slideRange === 'all'
							? 'pptx-vue-print-card--active border-primary bg-primary/10 text-foreground'
							: 'border-border bg-background text-muted-foreground hover:border-primary/40'
					"
				>
					<input
						type="radio"
						name="slideRange"
						class="pptx-vue-print-sr-only sr-only"
						:checked="props.slideRange === 'all'"
						@change="emit('update:slideRange', 'all')"
					/>
					All slides ({{ props.totalSlides }})
				</label>
				<label
					class="pptx-vue-print-card flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
					:class="
						props.slideRange === 'current'
							? 'pptx-vue-print-card--active border-primary bg-primary/10 text-foreground'
							: 'border-border bg-background text-muted-foreground hover:border-primary/40'
					"
				>
					<input
						type="radio"
						name="slideRange"
						class="pptx-vue-print-sr-only sr-only"
						:checked="props.slideRange === 'current'"
						@change="emit('update:slideRange', 'current')"
					/>
					Current slide ({{ props.activeSlideIndex + 1 }})
				</label>
				<label
					class="pptx-vue-print-card flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
					:class="
						props.slideRange === 'custom'
							? 'pptx-vue-print-card--active border-primary bg-primary/10 text-foreground'
							: 'border-border bg-background text-muted-foreground hover:border-primary/40'
					"
				>
					<input
						type="radio"
						name="slideRange"
						class="pptx-vue-print-sr-only sr-only"
						:checked="props.slideRange === 'custom'"
						@change="emit('update:slideRange', 'custom')"
					/>
					Custom range
				</label>
				<div
					v-if="props.slideRange === 'custom'"
					class="pptx-vue-print-range flex items-center gap-2 pl-6"
				>
					<span class="pptx-vue-print-range-label text-xs text-muted-foreground">From</span>
					<input
						type="number"
						:min="1"
						:max="props.totalSlides"
						:value="props.customFrom"
						class="pptx-vue-print-number w-16 rounded border border-border bg-background px-2 py-1 text-sm text-foreground"
						@input="onCustomFromInput"
					/>
					<span class="pptx-vue-print-range-label text-xs text-muted-foreground">To</span>
					<input
						type="number"
						:min="1"
						:max="props.totalSlides"
						:value="props.customTo"
						class="pptx-vue-print-number w-16 rounded border border-border bg-background px-2 py-1 text-sm text-foreground"
						@input="onCustomToInput"
					/>
				</div>
			</div>
		</fieldset>

		<!-- Orientation — only for full-page slides -->
		<fieldset
			v-if="props.printWhat === 'slides'"
			class="pptx-vue-print-fieldset m-0 border-none p-0"
		>
			<legend
				class="pptx-vue-print-legend mb-2 p-0 text-xs font-medium uppercase tracking-wide text-muted-foreground"
			>
				Orientation
			</legend>
			<div class="pptx-vue-print-row flex flex-wrap gap-2">
				<label
					class="pptx-vue-print-card flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
					:class="
						props.orientation === 'landscape'
							? 'pptx-vue-print-card--active border-primary bg-primary/10 text-foreground'
							: 'border-border bg-background text-muted-foreground hover:border-primary/40'
					"
				>
					<input
						type="radio"
						name="orientation"
						class="pptx-vue-print-sr-only sr-only"
						:checked="props.orientation === 'landscape'"
						@change="emit('update:orientation', 'landscape')"
					/>
					Landscape
				</label>
				<label
					class="pptx-vue-print-card flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
					:class="
						props.orientation === 'portrait'
							? 'pptx-vue-print-card--active border-primary bg-primary/10 text-foreground'
							: 'border-border bg-background text-muted-foreground hover:border-primary/40'
					"
				>
					<input
						type="radio"
						name="orientation"
						class="pptx-vue-print-sr-only sr-only"
						:checked="props.orientation === 'portrait'"
						@change="emit('update:orientation', 'portrait')"
					/>
					Portrait
				</label>
			</div>
		</fieldset>

		<!-- Colour Mode -->
		<fieldset class="pptx-vue-print-fieldset m-0 border-none p-0">
			<legend
				class="pptx-vue-print-legend mb-2 p-0 text-xs font-medium uppercase tracking-wide text-muted-foreground"
			>
				Color mode
			</legend>
			<div class="pptx-vue-print-row flex flex-wrap gap-2">
				<label
					v-for="opt in COLOR_OPTIONS"
					:key="opt.value"
					class="pptx-vue-print-card flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
					:class="
						props.colorMode === opt.value
							? 'pptx-vue-print-card--active border-primary bg-primary/10 text-foreground'
							: 'border-border bg-background text-muted-foreground hover:border-primary/40'
					"
				>
					<input
						type="radio"
						name="colorMode"
						class="pptx-vue-print-sr-only sr-only"
						:checked="props.colorMode === opt.value"
						@change="emit('update:colorMode', opt.value)"
					/>
					{{ opt.label }}
				</label>
			</div>
		</fieldset>

		<!-- Frame Slides -->
		<label
			class="pptx-vue-print-checkbox flex cursor-pointer items-center gap-2 text-sm text-foreground"
		>
			<input
				type="checkbox"
				class="rounded border-border"
				:checked="props.frameSlides"
				@change="emit('update:frameSlides', ($event.target as HTMLInputElement).checked)"
			/>
			<span>Frame slides</span>
		</label>
	</div>
</template>
