// packages/angular/src/viewer/show-options-fieldset.component.ts
/**
 * show-options-fieldset.component.ts: Slide-show option checkboxes.
 *
 * Selector: `pptx-show-options-fieldset`
 *
 * Angular port of the React `ShowOptionsFieldset`. Renders the "Show options"
 * fieldset with the loop / narration / animation / subtitles toggles. Reads the
 * current values from the `draft` presentation-properties input and emits a
 * partial `patch` for the host dialog to merge.
 */

import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import type { PptxPresentationProperties } from 'pptx-viewer-core';

@Component({
	selector: 'pptx-show-options-fieldset',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<fieldset class="pptx-ng-sss-fieldset">
			<legend class="pptx-ng-sss-legend">Show options</legend>

			<label class="pptx-ng-sss-option">
				<input
					type="checkbox"
					class="pptx-ng-sss-radio"
					[checked]="!!draft().loopContinuously"
					(change)="patch.emit({ loopContinuously: isChecked($event) })"
				/>
				<span>Loop continuously until Esc</span>
			</label>

			<label class="pptx-ng-sss-option">
				<input
					type="checkbox"
					class="pptx-ng-sss-radio"
					[checked]="draft().showWithNarration === false"
					(change)="patch.emit({ showWithNarration: !isChecked($event) })"
				/>
				<span>Show without narration</span>
			</label>

			<label class="pptx-ng-sss-option">
				<input
					type="checkbox"
					class="pptx-ng-sss-radio"
					[checked]="draft().showWithAnimation === false"
					(change)="patch.emit({ showWithAnimation: !isChecked($event) })"
				/>
				<span>Show without animation</span>
			</label>

			<label class="pptx-ng-sss-option">
				<input
					type="checkbox"
					class="pptx-ng-sss-radio"
					[checked]="!!draft().showSubtitles"
					(change)="patch.emit({ showSubtitles: isChecked($event) })"
				/>
				<span>Show subtitles</span>
			</label>
		</fieldset>
	`,
	styles: [
		`
			.pptx-ng-sss-fieldset {
				display: flex;
				flex-direction: column;
				gap: 0.375rem;
				margin: 0;
				padding: 0;
				border: none;
			}

			.pptx-ng-sss-legend {
				margin-bottom: 0.25rem;
				padding: 0;
				font-size: 0.6875rem;
				font-weight: 500;
				text-transform: uppercase;
				letter-spacing: 0.03em;
				color: var(--pptx-muted-foreground, #9ca3af);
			}

			.pptx-ng-sss-option {
				display: flex;
				align-items: center;
				gap: 0.5rem;
				font-size: 0.75rem;
				color: var(--pptx-foreground, #f3f4f6);
				cursor: pointer;
			}

			.pptx-ng-sss-radio {
				accent-color: var(--pptx-primary, #6366f1);
			}
		`,
	],
})
export class ShowOptionsFieldsetComponent {
	/** Current slide-show properties draft (source of the checkbox states). */
	readonly draft = input<PptxPresentationProperties>({});

	/** Emits a partial patch to merge into the host draft. */
	readonly patch = output<Partial<PptxPresentationProperties>>();

	protected isChecked(event: Event): boolean {
		return (event.target as HTMLInputElement).checked;
	}
}

// packages/vue/src/viewer/components/ShowOptionsFieldset.vue
<script setup lang="ts">
import type { PptxPresentationProperties } from 'pptx-viewer-core';

/**
 * ShowOptionsFieldset: slide-show option toggles (loop, narration, animation,
 * subtitles) plus the annotation pen colour. Vue port of the React
 * `ShowOptionsFieldset.tsx`, extended with the pen-colour control the React
 * dialog stores on `penColor`.
 */
const props = defineProps<{
	draft: PptxPresentationProperties;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxPresentationProperties>];
}>();

function checked(e: Event): boolean {
	return (e.target as HTMLInputElement).checked;
}
</script>

<template>
	<fieldset class="space-y-1.5">
		<legend class="mb-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
			Show options
		</legend>
		<label class="flex cursor-pointer items-center gap-2">
			<input
				type="checkbox"
				class="accent-primary"
				:checked="Boolean(draft.loopContinuously)"
				@change="emit('update', { loopContinuously: checked($event) })"
			/>
			<span>Loop continuously until 'Esc'</span>
		</label>
		<label class="flex cursor-pointer items-center gap-2">
			<input
				type="checkbox"
				class="accent-primary"
				:checked="draft.showWithNarration === false"
				@change="emit('update', { showWithNarration: !checked($event) })"
			/>
			<span>Show without narration</span>
		</label>
		<label class="flex cursor-pointer items-center gap-2">
			<input
				type="checkbox"
				class="accent-primary"
				:checked="draft.showWithAnimation === false"
				@change="emit('update', { showWithAnimation: !checked($event) })"
			/>
			<span>Show without animation</span>
		</label>
		<label class="flex cursor-pointer items-center gap-2">
			<input
				type="checkbox"
				class="accent-primary"
				:checked="Boolean(draft.showSubtitles)"
				@change="emit('update', { showSubtitles: checked($event) })"
			/>
			<span>Show subtitles / captions</span>
		</label>
		<label class="flex cursor-pointer items-center gap-2 pt-1">
			<span class="text-muted-foreground">Pen color</span>
			<input
				type="color"
				class="h-6 w-8 cursor-pointer rounded border border-border bg-muted"
				:value="draft.penColor ?? '#ff0000'"
				@input="emit('update', { penColor: ($event.target as HTMLInputElement).value })"
			/>
		</label>
	</fieldset>
</template>
