// packages/angular/src/viewer/slide-template-gallery-dialog.component.ts
/**
 * slide-template-gallery-dialog.component.ts: the Slide Templates gallery.
 *
 * Selector: `pptx-slide-template-gallery-dialog`
 *
 * Angular port of the React `SlideTemplateGalleryDialog.tsx`. Presents the
 * shared slide-template catalogue as a grid of live-rendered previews (one
 * `pptx-slide-template-preview` each). Single click selects, double click or
 * the Insert button emits an `insert` event carrying the chosen template id;
 * the host (the viewer) inserts the slide after the active one via
 * `EditorStateService.insertSlideFromTemplate` (one history entry).
 *
 * @module angular-viewer/slide-template-gallery-dialog
 */

import {
	ChangeDetectionStrategy,
	Component,
	effect,
	input,
	output,
	signal,
	computed,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { SLIDE_TEMPLATES } from '../internal/shared';
import type { SlideTemplateId } from '../internal/shared';
import type { DialogFooterActionSpec } from './dialog-footer.component';
import { DialogFooterComponent } from './dialog-footer.component';
import { ModalDialogComponent } from './modal-dialog.component';
import { SlideTemplatePreviewComponent } from './slide-template-preview.component';

@Component({
	selector: 'pptx-slide-template-gallery-dialog',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [
		DialogFooterComponent,
		ModalDialogComponent,
		SlideTemplatePreviewComponent,
		TranslatePipe,
	],
	template: `
		<pptx-modal-dialog
			[open]="open()"
			[title]="'pptx.slideTemplates.galleryTitle' | translate"
			(close)="close.emit()"
		>
			<div class="pptx-tpl-gallery">
				<p class="pptx-tpl-gallery__desc">
					{{ 'pptx.slideTemplates.galleryDescription' | translate }}
				</p>
				<div
					class="pptx-tpl-gallery__grid"
					role="listbox"
					[attr.aria-label]="'pptx.slideTemplates.gallery' | translate"
				>
					@for (spec of templates; track spec.id) {
						<button
							type="button"
							role="option"
							class="pptx-tpl-gallery__cell"
							[class.is-selected]="selected() === spec.id"
							[attr.aria-selected]="selected() === spec.id"
							[attr.aria-label]="spec.nameKey | translate"
							[title]="spec.descriptionKey | translate"
							(click)="select(spec.id)"
							(dblclick)="confirmTemplate(spec.id)"
						>
							<span class="pptx-tpl-gallery__thumb">
								<pptx-slide-template-preview [templateId]="spec.id" [scheme]="scheme()" />
							</span>
							<span class="pptx-tpl-gallery__cell-label">{{ spec.nameKey | translate }}</span>
						</button>
					}
				</div>
			</div>

			<div footer class="pptx-tpl-gallery__footer">
				<pptx-dialog-footer [actions]="footerActions()" (action)="onFooterAction($event)" />
			</div>
		</pptx-modal-dialog>
	`,
	styles: `
		.pptx-tpl-gallery {
			display: flex;
			flex-direction: column;
			gap: 0.5rem;
			min-width: min(86vw, 560px);
		}

		.pptx-tpl-gallery__desc {
			margin: 0;
			font-size: 11px;
			color: var(--pptx-muted-foreground, #6b7280);
		}

		.pptx-tpl-gallery__grid {
			display: grid;
			grid-template-columns: repeat(3, 1fr);
			gap: 0.5rem;
			max-height: 20rem;
			overflow-y: auto;
		}

		.pptx-tpl-gallery__cell {
			display: flex;
			flex-direction: column;
			align-items: center;
			gap: 0.25rem;
			padding: 0.4rem;
			border: 1px solid var(--pptx-border, #e5e7eb);
			border-radius: 4px;
			background: transparent;
			color: inherit;
			cursor: pointer;
		}

		.pptx-tpl-gallery__cell:hover {
			background: var(--pptx-accent, #f1f5f9);
		}

		.pptx-tpl-gallery__cell.is-selected {
			border-color: var(--pptx-primary, #2563eb);
			background: color-mix(in srgb, var(--pptx-primary, #2563eb) 18%, transparent);
		}

		.pptx-tpl-gallery__thumb {
			display: flex;
			align-items: center;
			justify-content: center;
			background: var(--pptx-muted, #f1f5f9);
			border-radius: 4px;
		}

		.pptx-tpl-gallery__cell-label {
			font-size: 10px;
			text-align: center;
			line-height: 1.15;
		}

		.pptx-tpl-gallery__footer {
			display: flex;
			gap: 0.5rem;
			justify-content: flex-end;
		}
	`,
})
export class SlideTemplateGalleryDialogComponent {
	/** Footer actions for the shared `pptx-ui-dialog-footer`. */
	protected readonly footerActions = computed<DialogFooterActionSpec[]>(() => [
		{ id: 'cancel', labelKey: 'pptx.slideTemplates.cancel' },
		{
			id: 'insert',
			labelKey: 'pptx.slideTemplates.insert',
			variant: 'primary' as const,
			disabled: this.selected() === null,
		},
	]);

	protected onFooterAction(id: string): void {
		if (id === 'insert') {
			this.confirm();
		} else {
			this.close.emit();
		}
	}

	/** Whether the dialog is visible. */
	readonly open = input<boolean>(false);

	/** Optional deck scheme map so previews show the deck's theme colours. */
	readonly scheme = input<Record<string, string> | undefined>(undefined);

	/** Emitted when the dialog should close (cancel / backdrop / Escape). */
	readonly close = output<void>();

	/** Emitted with the chosen template id when the user confirms. */
	readonly insert = output<SlideTemplateId>();

	/** The shared catalogue (12 templates). */
	protected readonly templates = SLIDE_TEMPLATES;

	protected readonly selected = signal<SlideTemplateId | null>(null);

	constructor() {
		// Reset the selection each time the dialog opens, so it starts fresh.
		effect(() => {
			if (this.open()) {
				this.selected.set(null);
			}
		});
	}

	/** Select a template tile (single click). */
	protected select(id: SlideTemplateId): void {
		this.selected.set(id);
	}

	/** Insert a template immediately (double-click shortcut). */
	protected confirmTemplate(id: SlideTemplateId): void {
		this.selected.set(id);
		this.confirm();
	}

	/** Emit the insert payload for the current selection, then close. */
	protected confirm(): void {
		const id = this.selected();
		if (id === null) {
			return;
		}
		this.insert.emit(id);
		this.close.emit();
	}
}

// packages/vue/src/viewer/components/SlideTemplateGalleryDialog.vue
<script setup lang="ts">
import { SLIDE_TEMPLATES } from 'pptx-viewer-shared';
import type { SlideTemplateId } from 'pptx-viewer-shared';
import { ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import DialogFooter from './DialogFooter.vue';
import ModalDialog from './ModalDialog.vue';
import SlideTemplatePreview from './SlideTemplatePreview.vue';

/**
 * SlideTemplateGalleryDialog - the New Slide template gallery.
 *
 * Vue port of React's `SlideTemplateGalleryDialog.tsx`, built on
 * {@link ModalDialog}. Presents the shared slide-template catalogue as a grid
 * of live-rendered previews (`SlideTemplatePreview.vue`). Single click
 * selects, double click or the Insert button emits `insert` with the chosen
 * template id; the host routes the payload to its history-integrated insert
 * path.
 */
const props = defineProps<{
	/** Whether the dialog is open. */
	open: boolean;
	/** Optional deck scheme so previews show the deck's theme colours. */
	scheme?: Record<string, string>;
}>();

const emit = defineEmits<{
	/** Emitted with the chosen template id. */
	(e: 'insert', templateId: SlideTemplateId): void;
	/** Emitted when the dialog should close without inserting. */
	(e: 'close'): void;
}>();

const { t } = useI18n();

const selected = ref<SlideTemplateId | null>(null);

/** Re-seed the selection whenever the dialog (re)opens. */
watch(
	() => props.open,
	(isOpen) => {
		if (isOpen) {
			selected.value = null;
		}
	},
	{ immediate: true },
);

function select(id: SlideTemplateId): void {
	selected.value = id;
}

function insertTemplate(id: SlideTemplateId): void {
	emit('insert', id);
	emit('close');
}

function handleInsert(): void {
	if (selected.value) {
		insertTemplate(selected.value);
	}
}

function close(): void {
	emit('close');
}
</script>

<template>
	<ModalDialog :open="open" :title="t('pptx.slideTemplates.galleryTitle')" @close="close">
		<div class="pptx-vue-template-dialog flex max-h-[min(64vh,480px)] flex-col gap-2.5">
			<p class="pptx-vue-template-description text-[11px] text-muted-foreground">
				{{ t('pptx.slideTemplates.galleryDescription') }}
			</p>
			<div
				class="pptx-vue-template-gallery grid flex-1 grid-cols-3 gap-1 overflow-y-auto"
				role="listbox"
				:aria-label="t('pptx.slideTemplates.gallery')"
			>
				<button
					v-for="spec in SLIDE_TEMPLATES"
					:key="spec.id"
					type="button"
					role="option"
					:aria-selected="selected === spec.id"
					:aria-label="t(spec.nameKey)"
					:title="t(spec.descriptionKey)"
					class="pptx-vue-template-tile flex flex-col items-center gap-1 rounded border py-1 transition-colors"
					:class="
						selected === spec.id
							? 'pptx-vue-template-tile--active border-primary bg-primary/20'
							: 'border-border hover:border-border hover:bg-muted/50'
					"
					@click="select(spec.id)"
					@dblclick="insertTemplate(spec.id)"
				>
					<span class="pptx-vue-template-thumb flex items-center justify-center rounded bg-muted">
						<SlideTemplatePreview :template-id="spec.id" :scheme="props.scheme" />
					</span>
					<span
						class="pptx-vue-template-tile-label text-center text-[10px] leading-tight text-foreground"
					>
						{{ t(spec.nameKey) }}
					</span>
				</button>
			</div>
		</div>

		<template #footer>
			<DialogFooter
				:actions="[
					{ id: 'cancel', label: t('pptx.slideTemplates.cancel') },
					{
						id: 'insert',
						label: t('pptx.slideTemplates.insert'),
						variant: 'primary',
						disabled: !selected,
					},
				]"
				@action="(id) => (id === 'insert' ? handleInsert() : close())"
			/>
		</template>
	</ModalDialog>
</template>
